### ISSUE TITLE
🐛 Bug Report: Function is considered "Failed" if http response code is not 200, and no response is logged 

### ISSUE THREAD

**Issue by maikeriva** [appwrite/appwrite#3933] opened 2022-09-27 12:09 UTC
### 👟 Reproduction steps

When I complete a function execution with `res.json(400)` the web console marks the execution as "failed". This is not true, as the function execution completed correctly and no error prevented it from doing so. After a [brief discussion on Discord](https://discord.com/channels/564160730845151244/812714347298160690/1023639381489242262), I was recommended to open an issue here.

This behaviour also prevents the full JSON response returned by the function from being available in the RESPONSE field of the function's log page in the web console, which would be extremely useful for troubleshooting what went wrong (client error? server error? 3rd party service error?)

### 👍 Expected behavior

The function should be marked as "completed" regardless of the returned http code. "Failed" should only apply if an error/exception got thrown preventing the function from completing.
The RESPONSE field should contain the full response even in case of non-200 http code.

### 👎 Actual Behavior

Function is marked as "Failed" and no response is registered in the RESPONSE log field.

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite: 1.0.1
OS: Fedora 36

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-01-08 15:54
Closing as a duplicate of https://github.com/appwrite/appwrite/issues/4594. Please 👍 the other issue 🙏

**Closed by stnguyen90** 2023-01-08 15:54 UTC
Labels: bug
