### ISSUE TITLE
🐛 Bug Report: Console won't show more than 6 projects 

### ISSUE THREAD

**Issue by sonicviz** [appwrite/appwrite#7356] opened 2023-12-29 08:48 UTC
### 👟 Reproduction steps

Reported on Discord at https://discord.com/channels/564160730845151244/1190121841797378110 and reproduced. 
Opened issue upon request of core dev who reproduced (Steven).

Issue:
Website project listing lets you list 6, 12, 24 etc projects per page. 
I have 9 simple test projects at the moment (quick starts, tutorials, demos for learning/testing) and if I have 6 projects per page selected I get 6 shown with a page 2 to see the next block. 
If I select 12 or more per page it will still say there are 9 projects but it will still only show 6 and the pagination has now dissappeared (correctly) but you cannot access the other three (or more) projects anymore. 
This is on latest Chrome. Tried clearing cache, relogging but it still seems broken.

This image shows 6 projects out of 9 when set to 12 projects per page, and correctly shows 1 page (as 9 is less than 12) but only shows the first 6 with no scroll action. 
![image](https://github.com/appwrite/website/assets/200370/bc08ffa1-b000-4921-a4d4-6cdaeb443f36)

This is set to 6 per page, shows there are total 9 projects and you can page to the next 3. Showing page 2 here, which are not being shown in the above example with 12 per page (bottom right says page 1 but you can see the next/prev links are disabled as all projects are now supposed to be on page 1). 
![image](https://github.com/appwrite/website/assets/200370/fbd3e170-14a8-4eae-9f1a-ffcca060812b)

### 👍 Expected behavior

Setting per page amount to 12 or more should show all 9 projects 

### 👎 Actual Behavior

Pagination was correctly set to show 9 projects on 1 page ie: prev/next disabled, but it only shows page 1 amount of projects from previous setting of 6

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-12-29 17:27
@sonicviz, thanks for creating this issue! 🙏 The problem is probably due to an incorrect limit being passed [here](https://github.com/appwrite/console/blob/bf2969614de0e46eedf4057b82212785fdc8770b/src/routes/console/organization-%5Borganization%5D/%2Bpage.ts#L20).

**Comment by kanugurajesh** [comment] 2023-12-29 18:44
@stnguyen90 I would like to work on this issue can you assign it to me.

**Comment by sourabpramanik** [comment] 2023-12-30 09:06
@kanugurajesh are working on this bug? If not can I raise a PR?

**Comment by MadhuSaini22** [comment] 2023-12-30 17:24
Is someone working on this issue? Or else I can take it.

**Closed** 2024-01-02 14:13 UTC
Labels: bug, good first issue, console
