### ISSUE TITLE
🐛 Bug Report: In dark mode, the "Sign In" button is not visible on the website.

### ISSUE THREAD

**Issue by Itsamanjain** [appwrite/appwrite#6330] opened 2023-09-26 06:15 UTC
### 👟 Reproduction steps

Go to https://appwrite.io/. 
On the homepage, as a new user in dark mode, the 'Sign In' button is not visible.
![Screenshot from 2023-09-26 11-40-00](https://github.com/appwrite/appwrite/assets/112370476/64974d14-c439-4e10-8fd6-45bfb9aac3da)

### 👍 Expected behavior

sign in button should be clearly visible.

### 👎 Actual Behavior

its color merge with background color

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by baroiSubhra** [comment] 2023-09-26 06:22
Unable to reproduce it in chrome & firefox @Itsamanjain, could you please give some more details ??

**Comment by ItzNotABug** [comment] 2023-09-26 07:42
Same as @baroiSubhra said, cannot reproduce on Chrome, Safari, DuckDuckGo (Desktop & Mobile).
@Itsamanjain Maybe try in an incognito window & see if it works?

**Comment by Itsamanjain** [comment] 2023-09-26 12:34
@ItzNotABug @baroiSubhra , you're absolutely right. It works perfectly fine in incognito mode. So, what should I do next? Should I close the issue?

**Comment by ItzNotABug** [comment] 2023-09-26 14:19
@Itsamanjain If the provide solution works then sure, go ahead and close the issue.

**Closed** 2023-09-27 00:18 UTC
Labels: bug
