### ISSUE TITLE
🐛 Bug Report: `accounts` event not being sent to function

### ISSUE THREAD

**Issue by arnu515** [appwrite/appwrite#3114] opened 2022-04-19 10:45 UTC
### 👟 Reproduction steps

I have added a function to automatically verify the user and create an entry in the profiles collection whenever a user gets created, and I've selected these events: `users.create`, `accounts.create`, `users.delete`, `accounts.delete`, but the function only gets called on users.create and users.delete events, and not the account events.

I've added `role:all` to the executors list thinking it's a permission issue, but that didn't fix anything.

Basically, it calls the function when I create a user from the console, but NOT when I create it using `appwrite.accounts.create`.

I've also checked that the events are executing, by adding a webhook with the same events as the function, and it looks like the webhook is working fine.
![image](https://user-images.githubusercontent.com/52203828/163987085-4994a6e9-1386-49ae-b0fc-32318fcd3031.png)

Screenshot of function settings:

![image](https://user-images.githubusercontent.com/52203828/163985328-9846d31e-54ad-421b-852e-7810e7d86419.png)
![image](https://user-images.githubusercontent.com/52203828/163985368-f2b68cf4-f7ef-43ed-aeb8-10aedcff7ad6.png)
![image](https://user-images.githubusercontent.com/52203828/163985389-2addb857-ff15-451c-9210-1dd3eec90198.png)

I asked this on discord originally, but I was asked to create an issue. [Here's the message on discord](https://discord.com/channels/564160730845151244/812714347298160690/965865956100427796)

### 👍 Expected behavior

It should execute the function when I create a user using the Appwrite account SDK.

### 👎 Actual Behavior

It does not execute the function.

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I'm using my old laptop to host appwrite. This laptop is running fedora server 35.

I'm accessing appwrite from another computer on the same network, so my requests aren't going to `localhost`, but they are going to `192.168.1.7` which is my laptop's ip.

I've also changed the port to `8000` because there's an NGINX server running on port `80`

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by arnu515** [comment] 2022-04-19 10:46
Function's code: https://www.toptal.com/developers/hastebin/ojilukuhid.js

**Comment by arnu515** [comment] 2022-04-21 06:17
It seems that both the `users` and `accounts` events aren't getting called for some reason from my frontend. The `users.create` event is being called when I create a user from the appwrite console itself, but when I do it from the frontend, it isn't working.

This is the code for the `account` SDK which runs on the frontend,

```typescript
try {
  await appwrite.account.create("unique()", body.email, body.password, body.username)
  alert("Account created successfully. Please log in.")
  mode = 'login'
} catch(e) {
  alert(e.message)
}
```

And here's the code for the `users` SDK, which is running on a [backend endpoint](https://kit.svelte.dev/docs/routing#endpoints)

```typescript
import type { RequestHandler } from '@sveltejs/kit'
import * as yup from 'yup'
import appwrite from '$lib/appwriteSdk'

export const post: RequestHandler = async ({ request }) => {
	try {
		const body = await yup
			.object({
				email: yup.string().email().required().trim(),
				username: yup.string().required().trim(),
				password: yup.string().required().min(8)
			})
			.validate(await request.json())

		const { email, username, password } = body

		// create the account with appwrite
		await appwrite.users.create('unique()', email, password, username)
		// the user's profile is created automatically by appwrite's functions.

		return {
			status: 200,
			body: {
				message: 'Account created successfully'
			}
		}
	} catch (e) {
		if (e instanceof yup.ValidationError) {
			return {
				status: 400,
				body: {
					error: 'Invalid body',
					error_description: e.message
				}
			}
		} else {
			console.error(e)
			return {
				status: 500,
				body: {
					error: 'Server error',
					error_description: e.message
				}
			}
		}
	}
}
```

I am using SvelteKit, and the appwrite server is **not** running on localhost, but it is running on another computer in my local network.

@Meldiron I'll test this on localhost a bit later.

**Comment by elvisduru** [comment] 2022-04-21 18:47
I have a similar issue when creating new users via the Magic Url feature. The users are created and show up in the console but the function doesn't get triggered by the event.

**Comment by arnu515** [comment] 2022-04-23 06:12
@Meldiron I just noticed that the function **works** when **there are NO collections in the database**, but it doesn't when a collection is added.

Can you please test this?

**Comment by Meldiron** [comment] 2022-06-09 10:24
Event functionality was refactored (improved by A LOT) in Appwrite 0.14. Can you please try our new system and see if the problem still persists?

**Comment by stnguyen90** [comment] 2022-07-28 13:59
I'll close this now since we've made a lot of changes since this issue was first opened. @arnu515, if the issue is still occurring, I can reopen

**Closed by stnguyen90** 2022-07-28 13:59 UTC
Labels: bug, auth/users
