### ISSUE TITLE
🐛 Bug Report: Default value for bool attribute is not set properly if added later to document

### ISSUE THREAD

**Issue by ivenprillwitz** [appwrite/appwrite#2768] opened 2022-02-09 16:42 UTC
### 👟 Reproduction steps

1. Create new Collection
2. Create text attribute 'name', requiered
3. Create  a sample data 
4. Create bool attribute 'isActive', default value
5. Create index on 'isActive'
6. Read List with query isActive= false

### 👍 Expected behavior

Should return data with 'isActive = false'

### 👎 Actual Behavior

Returns nothing

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

local docker instance on my mac

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2022-11-15 21:02
@ivenprillwitz thanks for creating this issue! 🙏🏼 This is probably happening because the older values are `null` instead of what you set for the default value. Appwrite doesn't go back and update older documents. The default value is only applied to new documents.

**Comment by abnegate** [comment] 2023-04-13 04:22
Closing as expected behavior

**Closed by abnegate** 2023-04-13 04:22 UTC
Labels: bug, database
