### ISSUE TITLE
🐛 Bug Report: Misleading Duplicate User Error

### ISSUE THREAD

**Issue by Omar8345** [appwrite/appwrite#5554] opened 2023-05-17 12:40 UTC
### 👟 Reproduction steps

When I create a user with the a already used User ID, in this way:

```py
users.create(user_id=username, password=password, name=name)
```

You get a exception back because the `User ID` is already used.

### 👍 Expected behavior

The exception's message should be replaced to something else, like:

```py
appwrite.exception.AppwriteException: A user with the same ID already exists in your project.
```

### 👎 Actual Behavior

The exception's message currently is:

```py
appwrite.exception.AppwriteException: A user with the same email already exists in your project.
```

![image](https://github.com/appwrite/sdk-for-python/assets/68811721/08870064-c371-4665-ab13-de375ae1dbe0)

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Windows

### 🧱 Your Environment

I use Flask to build a API which I will use in my frontend.

I am using Version `2.0.0` of Appwrite Python SDK and I use Appwrite cloud.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-05-18 14:35
@Omar8345, thanks for creating this issue! 🙏🏼 This looks like a duplicate of https://github.com/appwrite/appwrite/issues/5147 and should be fixed in Appwrite version 1.3.2.

**Closed by stnguyen90** 2023-05-18 14:35 UTC
Labels: bug, authentication
