### ISSUE TITLE
🐛 Bug Report: failed migration from v1.3.8 to v1.4.0

### ISSUE THREAD

**Issue by usamashafiqs** [appwrite/appwrite#6075] opened 2023-08-30 20:55 UTC
### 👟 Reproduction steps

Failed migration from v1.3.8 to v1.4.0
### **Console Output**
The _APP_CONNECTIONS_MAX variable is not set. Defaulting to a blank string
Failed to create connection: php_network_getaddresses: getaddrinfo failed: Name does not resolve

### 👍 Expected behavior

It should migrate to v1.4.0.

### 👎 Actual Behavior

Failed migration from v1.3.8 to v1.4.0.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by patrickhilker** [comment] 2023-08-30 21:02
I added the env var to my `.env` and appwrite started up - I set the value to 10 (not knowing what I am doing). It is also missing in https://appwrite.io/install/env

**Comment by teknotut** [comment] 2023-08-30 21:13
Same with me, I try to upgrade and get error

> [Error] URL: /v1/vcs/installations
[Error] Type: Appwrite\Extend\Exception
[Error] Message: away@7ion.co.id (role: owner) missing scope (none)
[Error] File: /usr/src/code/app/controllers/general.php
[Error] Line: 475

Then I try to install fresh in other machine, I get same error.

Error when click in Function, and Project Setting (Error 500)

**Comment by RyousukeUchino** [comment] 2023-08-30 21:42
I also upgraded from 1.3.8, and I'm encountering a 500 error when clicking on [Function] and [Project Settings].
All environment variables have already been migrated, and the necessary commands have been executed, but my migration to 1.4.0 is currently failing and breaking.

To begin with, I think migration documentation should be prepared (for Docker environments, etc.) before making a fuss about it in newsletters.

**Comment by akaco** [comment] 2023-08-31 00:16
I think this batch is not ready. I'm getting server errors on my new machine when I try to read data from the database and I see error on service-worker calls.


![Screen Shot 2023-08-31 at 10 10 47 am](https://github.com/appwrite/appwrite/assets/1654273/7b8c1ec8-ccd0-4071-9c39-127bf1b478a8)

**Comment by rmpietro** [comment] 2023-08-31 00:22
Same error here. It seems this version definitely needs adjustments. Or maybe some docs on how to configure new params like functions domains, since it's now a new feature, in the case the errors come from misconfiguration.
 
First, the _APP_CONNECTIONS_MAX that is by default a blank String and locks the db connection pool to a number of 1 that needs to be changed, then the error:

2023-08-30 21:16:28 [Error] Timestamp: 2023-08-31T00:16:28+00:00
2023-08-30 21:16:28 [Error] Method: GET
2023-08-30 21:16:28 [Error] URL: /v1/vcs/installations
2023-08-30 21:16:28 [Error] Type: Appwrite\Extend\Exception
2023-08-30 21:16:28 [Error] Message: rmpietro@gmail.com (role: owner) missing scope (none)
2023-08-30 21:16:28 [Error] File: /usr/src/code/app/controllers/general.php
2023-08-30 21:16:28 [Error] Line: 475

This gets thrown every time hovering over or clicking on "Functions" or "Settings" inside a created project.

**Comment by LDY681** [comment] 2023-08-31 03:01
Same 500 Server Error. I just downgraded back to 1.3.8. Hope this will get fixed soon.

**Comment by bourvill** [comment] 2023-08-31 11:26
same, error 500, no response from my backend.

```
[Error] Type: Utopia\Exception
[Error] Message: Error handler had an error: Failed to create connection: SQLSTATE[HY000] [1040] Too many connections
[Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
[Error] Line: 551
```

**Comment by 13mralex** [comment] 2023-08-31 16:24
> I added the env var to my `.env` and appwrite started up - I set the value to 20 (not knowing what I am doing). It is also missing in https://appwrite.io/install/env

I can confirm this works. Adding `_APP_CONNECTIONS_MAX = 20` to `.env` let me run the migration from 1.3.0 to 1.4.1 - after restarting.

**Comment by joeyouss** [comment] 2023-08-31 18:32
Hi, please try migrating to 1.4.1 @usamashafiqs

**Comment by lucasctd** [comment] 2023-08-31 19:59
> > I added the env var to my `.env` and appwrite started up - I set the value to 20 (not knowing what I am doing). It is also missing in https://appwrite.io/install/env
> 
> I can confirm this works. Adding `_APP_CONNECTIONS_MAX=20` to `.env` let me run the migration from 1.3.0 to 1.4.1 - after restarting.

gonna give it a try.

**Comment by lucasctd** [comment] 2023-09-01 00:50
No success. I am getting a 500 error now

```
Error 500
Domain environment variables not configured. Please configure domain environment variables before using Appwrite outside of localhost.

Type

router_domain_not_configured
```

**Comment by lucasctd** [comment] 2023-09-01 01:26
I guess I just gonna wait for the next release. I was not able to manage it to work.
I dunno if it matters but by appwrite app is behind a proxy.

![image](https://github.com/appwrite/appwrite/assets/5876679/123b1492-46b5-427c-82f6-dcb5b982f82f)

**Comment by poble-pos** [comment] 2023-09-01 03:20
> > I added the env var to my `.env` and appwrite started up - I set the value to 20 (not knowing what I am doing). It is also missing in https://appwrite.io/install/env
> 
> I can confirm this works. Adding `_APP_CONNECTIONS_MAX=20` to `.env` let me run the migration from 1.3.0 to 1.4.1 - after restarting.

Thanks this worked for me.
After update .env and version
docker compose up -d --remove-orphans
worked for me.

**Comment by lucasctd** [comment] 2023-09-01 04:14
> No success. I am getting a 500 error now
> 
> ```
> Error 500
> Domain environment variables not configured. Please configure domain environment variables before using Appwrite outside of localhost.
> 
> Type
> 
> router_domain_not_configured
> ```

To fix this I had to update my _APP_DOMAIN env variable to the domain I use in the proxy, It used to have localhost set there xD bu according to line #64 of [app/controllers/general.php](https://github.com/appwrite/appwrite/blob/891099c7c3dc1fe86c4e64467f9249651991b603/app/controllers/general.php), it will throw the error I was seeing =)

Now my function is throwing a 500 error with no clear description

```json
{
    "message": "Server Error",
    "code": 500,
    "type": "general_unknown",
    "version": "1.4.1"
}
```

I gonna update it according to the [upgrade guide](https://appwrite.io/docs/functions-develop#upgrade) and see if it fixed the issue.

**Comment by stnguyen90** [comment] 2023-09-01 17:08
@usamashafiqs, are you still getting the error about `_APP_CONNECTIONS_MAX` after upgrading to 1.4.1 and running the migrate command?

**Comment by usamashafiqs** [comment] 2023-09-02 12:46
> 

No, but I have to manually set the ```_APP_DOMAIN_FUNCTIONS=``` in order to migrate.

**Comment by stnguyen90** [comment] 2023-09-02 23:22
@usamashafiqs that's weird...you shouldn't need to set that in order to migrate...do you get an error?

**Comment by usamashafiqs** [comment] 2023-09-03 03:24
@stnguyen90  I was getting a database connection timed out error, so I checked that the containers were restarting after the crash when I set ```_APP_DOMAIN_FUNCTIONS=``` to domain containers running fine, then I ran migrate commend.

**Comment by stnguyen90** [comment] 2023-09-04 04:42
@usamashafiqs other people have gotten things working by restarting containers. That's probably what got things working for you rather than changing the environment variable.

I'm going to close this now since your original problem is resolved.

**Closed by stnguyen90** 2023-09-04 04:42 UTC
Labels: bug, Migration

**Comment by AleXoTroN** [comment] 2023-09-21 23:01
> > > I added the env var to my `.env` and appwrite started up - I set the value to 20 (not knowing what I am doing). It is also missing in https://appwrite.io/install/env
> > 
> > I can confirm this works. Adding `_APP_CONNECTIONS_MAX=20` to `.env` let me run the migration from 1.3.0 to 1.4.1 - after restarting.
> 
> Thanks this worked for me.
> After update .env and version
> docker compose up -d --remove-orphans
> worked for me.

This actually worked for me. After upgrading the version and setting the env variable I just stopped the containers and then used the command
```
docker compose up -d --remove-orphans
```

**Comment by GrimGaiden** [comment] 2023-10-05 18:01
I'm encountering the same issue. Can't upgrade from 1.3.8 to any version of 1.4.X with database migration. Why is this issue closed? Is there a fix?
