### ISSUE TITLE
🚀 Feature: Foreign keys as an attribute type for a document

### ISSUE THREAD

**Issue by MananShah9** [appwrite/appwrite#4897] opened 2022-12-22 08:55 UTC
### 🔖 Feature description

A new attribute type that refers to another 'DOCUMENT ID' from same or different collection/db.

### 🎤 Pitch

Foreign keys will establish and enforce a link between the related data.
There are various use cases, to name a few, 
1. Mongo has the method '.populate()' in its select query that populates actual data from the other doc instead of returning just the id.
2. Safe deletion of data. Let's say a user is deleted but a document refers to the id of that user. Currently, we have references to nowhere.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by AisukoWasTaken** [comment] 2022-12-22 09:21
Somewhat duplicate of #2735

**Comment by MananShah9** [comment] 2022-12-22 09:27
I still think this feature deserves it's own issue!

**Comment by stnguyen90** [comment] 2022-12-22 17:48
@MananShah9 it would be much better to use the existing issue as having a separate issue splits demand (there's low demand for this issue because there are no upvotes on it) and can cause confusion with different ideas being in different places.

**Closed** 2022-12-22 18:31 UTC
