### ISSUE TITLE
🐛 Bug Report: Make Server Side Attributes Nullable in SDK Models

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#8252] opened 2024-06-10 06:11 UTC
### 👟 Reproduction steps

**Query.select** isn't really helpful on all platforms.

Example: Excluding the server side attributes (`$*`) will basically crash the app as the passed `Map` would not contain `$databaseId`, `$collectionId`, etc due to the variables being marked as `NonNull`. 

---
Ref - https://discord.com/channels/564160730845151244/636852860709240842/1249264735501684746

### 👍 Expected behavior

Not crash the app.

### 👎 Actual Behavior

App is crashed.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2024-06-10 15:41
Closing as a duplicate of https://github.com/appwrite/appwrite/issues/6158

**Closed by stnguyen90** 2024-06-10 15:41 UTC
Labels: bug
