### ISSUE TITLE
🐛 Bug Report: Cannot create Flutter Web Platform on Appwrite Cloud Console version 1.1.2

### ISSUE THREAD

**Issue by teoprayoga** [appwrite/appwrite#6025] opened 2023-08-22 07:28 UTC
### 👟 Reproduction steps

When I wanted to create new Flutter platform from Appwrite Cloud (v1.1.2). but after i fill 
1. Flutter web (options)
2. name 
3. hostname. 
I get this in screenshot
<img width="452" alt="Screenshot 2023-08-22 at 15 23 45" src="https://github.com/appwrite/appwrite/assets/19910443/2a756c01-5129-4ca6-9a96-ca1e69b8ea40">

### 👍 Expected behavior

It should allow me to create new Flutter Web Platform

### 👎 Actual Behavior

I running Appwrite (v1.3.4) in local works fine. But cannot create new Flutter Web Platform in Appwrite Cloud Console (v1.1.2)

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

I run local Appwrite version. 1.3.4
the issue is Appwrite Cloud Console version 1.1.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment] 2023-08-22 07:42
Hi @teoprayoga I just recreated the steps, and it works for me. You will have to choose if your app is Android, iOS,  Linux, macOS, Windows or Web. Are you doing that?

**Comment by eldadfux** [comment] 2023-08-24 04:29
I can confirm this is a bug. A workaround would be to use the regular web platform instead. A core member has been assigned to apply a fix. Closing in favor of #6004

**Closed by eldadfux** 2023-08-24 04:29 UTC
Labels: bug
