### ISSUE TITLE
🐛 Bug Report: Function deployment always fails after 10 minutes

### ISSUE THREAD

**Issue by fawkeswei** [appwrite/appwrite#7318] opened 2023-12-22 07:19 UTC
### 👟 Reproduction steps

0. Ensure `_APP_FUNCTIONS_BUILD_TIMEOUT` is set to 900 (seconds)
1. Create a starter function
2. Update the build command to `sleep 720`
3. Create a deployment

### 👍 Expected behavior

`_APP_FUNCTIONS_BUILD_TIMEOUT` is respected during function deployment 

### 👎 Actual Behavior

Value of `_APP_FUNCTIONS_BUILD_TIMEOUT` is not being using and deployment always fails after 10 minutes.

More info in discord thread https://discord.com/channels/564160730845151244/1179694661300932628

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

https://marketplace.digitalocean.com/apps/appwrite

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-12-22 07:53
@fawkeswei, thanks for creating this issue! 🙏🏼 I think the problem is the executor's "Create a new runtime server" API exposes a [timeout that defaults to 10 minutes](https://github.com/open-runtimes/executor/blob/a72f0d5b8f77235e179f8c45dd981b85a20993a3/app/http.php#L383), but Appwrite isn't passing `_APP_FUNCTIONS_BUILD_TIMEOUT` for the parameter:

https://github.com/appwrite/appwrite/blob/5cd94041dc1037f53f62d6afb78528021ece3fa1/src/Executor/Executor.php#L75-L87

Instead, it's passed as a request timeout:

https://github.com/appwrite/appwrite/blob/5cd94041dc1037f53f62d6afb78528021ece3fa1/src/Executor/Executor.php#L89-L91

**Comment by adityaoberai** [comment] 2024-01-19 13:41
Closing this issue since it was fixed by #7350

**Closed by adityaoberai** 2024-01-19 13:41 UTC
Labels: bug, functions
