### ISSUE TITLE
🐛 Bug Report: Unable to close the details page after open

### ISSUE THREAD

**Issue by centopw** [appwrite/appwrite#7935] opened 2024-04-08 04:06 UTC
### 👟 Reproduction steps

On local host click migrate to cloud. Then on appwrite cloud project setting, in the Migrations tab click the details button and try to close it

### 👍 Expected behavior

When click close icon it should close

### 👎 Actual Behavior

doens't close

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 🧱 Your Environment

No customised been done 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2024-04-16 04:18
Closing as a duplicate of https://github.com/appwrite/console/issues/1025

**Closed by stnguyen90** 2024-04-16 04:18 UTC
Labels: bug, product / console
