### ISSUE TITLE
Help Translate Appwrite Locale and Email templates

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#25] opened 2019-09-23 18:26 UTC
Currently, Appwrite locale and email templates support 44 locales. We need help supporting more languages and improving current translations.

Translating is as easy as adding a few PHP file with new locale as prefix in file names.

## Update (#Hacktoberfest 20)
Please submit any PRs against branch `0.7.x` with the updated file structure, as shown below ⬇️

## Structure
List of file required for new locale are:

**Email Templates**
app/config/locale/translations/templates/en.email.auth.confirm.tpl
app/config/locale/translations/templates/en.email.auth.invitation.tpl
app/config/locale/translations/templates/en.email.auth.recovery.tpl

**Locale Lists and Settings**
app/config/locale/translations/en.php
app/config/locale/translations/en.continents.php
app/config/locale/translations/en.countries.php

**Configuration and Loading**
Add the new language to Appwrite config file: `/app/config/locale/codes.php` (order by ABC)
Load the new translation here: `./app/init.php (line: 224)` (order by ABC)

Make sure to keep PHP array keys exactly the same.

## Template Status

✅ = Updated - You can still submit PRs with fixes or improvements
⛔️ = Outdated - Update to match languages that are marked as updated
🆘 = Missing - No translation has yet been contributed (fallback to english)

New locales are always welcomed.

| Locale  | Phrases | Countries | Continents | Template - confirm | Template - invite | Template - recovery
|--|--|--|--|--|--|--|
| af | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| ar | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| bn | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| cat | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| cz | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| de | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| en | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| es | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| fi | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| fo | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| fr | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| gr | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| he | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| hi | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| hu | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| hy | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| id | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| is | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| it | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| ja | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| jv | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| km | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| ko | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| lt | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| ml | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| mr | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| ms | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| nl | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| no | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| np | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| ph | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| pl | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| pt-br | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| pt-pt | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| ro | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| ru | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| si | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| sl | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| sq | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| sv | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| ta | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| th | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| tr | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| ua | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| vi | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| zh-cn | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| zh-tw | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |

**Comment by daniloff200** [comment] 2019-09-25 18:43
I can help with Ukrainian and Russian localizations :) gonna create a PRs with that

**Comment by eldadfux** [comment] 2019-09-25 18:45
@daniloff200 Amazing! let me know if you have any question. Feel free to join our Gitter community for live support and discussions.

https://gitter.im/appwrite/community

**Comment by jessescn** [comment] 2019-09-26 00:01
Hello, i can help in translate locale and email templates into Brazilian Portuguese (ptbr).

**Comment by cho0o0** [comment] 2019-09-26 00:14
I can pick up Japanese and Chinese. Do I need to create the PRs during October since it seems that the issue is labeled by hacktoberfest?

**Comment by eldadfux** [comment] 2019-09-26 05:55
@jessescn, @cho0o0 That will be an amazing addition to the project! Thank you both! If you need any help, just let me know.

Also, feel free to join our Gitter community for live help and discussions.

@cho0o0 if you want your pull request to get counted for a DigitalOcean T-Shirt you probably better wait for October 1st before submitting.

**Comment by Chaaarles** [comment] 2019-09-26 11:47
I can help with a Norwegian translation <3<3

**Comment by eldadfux** [comment] 2019-09-26 13:05
@Chaaarles that will be amazing. Feel free to join us on Gitter:
https://gitter.im/appwrite/community

**Comment by Soundug** [comment] 2019-09-26 19:27
@cho0o0 I can help with Japanese translation. Do let me know if you need any help.

**Comment by eldadfux** [comment] 2019-09-26 22:07
@Chaaarles @Soundug @cho0o0 @jessescn @daniloff200 Please notice I have updated the list above and added this file for translation:

https://github.com/appwrite/appwrite/blob/master/app/config/locale/en.php

It had a lot of junk in it so I had to clean it to make sure it has only what we need for translation.

**Comment by cho0o0** [comment] 2019-09-26 23:30
@Soundug Sure. I think we can cooperate like you do the email templates and I translate others. How do you like it?

**Comment by cho0o0** [comment] 2019-09-26 23:36
@eldadfux I see. Though I think I can still win a T-Shirt without this count, why not make it a hacktoberfest PR😄

**Comment by hexmind** [comment] 2019-09-27 19:22
I can make Polish localization. I will create a PRs with that.

**Comment by Kiy4h** [comment] 2019-09-28 12:25
Hi, I can help by translating to Indonesia. I'll make a pull request soon.

**Comment by eldadfux** [comment] 2019-09-28 12:39
@hexmind , @Kiy4h thats great, waiting for your PRs. If you have any questions you can ask here or join our Gitter community

**Comment by EstherAF** [comment] 2019-09-28 18:48
I can translate into spanish. Will prepare a PR 😄

**Comment by alistairholmes** [comment] 2019-09-28 19:14
Hi there :wave:, I would like to translate the email templates for now into French :fr: for now, if i have more time i can try the rest of the files :smile:

**Comment by eldadfux** [comment] 2019-09-28 20:08
We have a new PT-BR and ES locale 🇧🇷🇪🇸! If anyone has more Spanish locales please send a pull request...

**Comment by pessip** [comment] 2019-09-29 13:32
I can help with Finnish locales. I'll send a PR when they are ready!

**Comment by Kolkies** [comment] 2019-09-29 20:09
I can help translating it in Dutch 🇳🇱. I will create a pr when done!

**Comment by eldadfux** [comment] 2019-09-29 20:11
Hey @Kolkies thats great, send a PR when you're ready.

**Comment by tanmaymohan** [comment] 2019-09-30 09:56
Hi, I can try translating it to hindi

**Comment by eldadfux** [comment] 2019-09-30 10:05
@tanmaymohan that will be great. let me know if you need any help.

**Comment by 1qk1** [comment] 2019-09-30 11:39
I can translate it to Greek!

**Comment by tacoelho** [comment] 2019-09-30 20:19
I can translate do Portuguese-Brazil :)

**Comment by tacoelho** [comment] 2019-09-30 20:54
#40

**Comment by tacoelho** [comment] 2019-09-30 20:55
**#40 Add IT locale**

**Comment by lacexd** [comment] 2019-09-30 21:34
I'd love to do the Hungarian translation!

**Comment by eldadfux** [comment] 2019-09-30 21:46
> I'd love to do the Hungarian translation!

That will be great. 🥳🇭🇺

**Comment by Taminoful** [comment] 2019-09-30 21:59
I'd love to help you out with the German translation. 🎉

**Comment by eldadfux** [comment] 2019-09-30 22:40
@Taminoful 👌🏻send a PR when you're ready

**Comment by VMadalin** [comment] 2019-10-01 05:42
I can help with translation to Catalan and Romanian

**Comment by eldadfux** [comment] 2019-10-01 05:44
@VMadalin we already have the Catalan (#36) and the Romanian (#57) translations but you can take a look and see if there is any room for improvements.

**Comment by MasterKN48** [comment] 2019-10-01 08:00
If required to add Czech (CZ) language translation i can add.

**Comment by LiTO773** [comment] 2019-10-01 08:35
Hi, I can do the European Portuguese translation (pt-PT). It has a few differences from pt-BR in some of its words and grammar rules.

**Comment by eldadfux** [comment] 2019-10-01 10:36
@MasterKN48 @LiTO773 Hey guys CZ, HI and pt-PT will be great additions. Send a PR when you're ready ✌🏻

**Comment by RizkyRajitha** [comment] 2019-10-01 13:57
can i help  with sinhala version  si_lk locale

**Comment by Pedrocssg** [comment] 2019-10-01 14:20
Fixed some PT-PT Translations, as referred in the issue above

**Comment by Carike** [comment] 2019-10-01 15:21
I have created and updated the relevant language files for the Afrikaans language (af_ZA) from South Africa for the issue:

#25 Help Translate Appwrite Locale and Email templates (See pull request #75)

Hacktoberfest 2019 is in full swing!

**Comment by the-bose** [comment] 2019-10-01 15:26
I can help with Tamil (TAM) translations

**Comment by Orozco93** [comment] 2019-10-01 15:57
I can help with Spanish version translations

**Comment by taniaReyesM** [comment] 2019-10-01 19:05
> I can translate into spanish. Will prepare a PR 😄

I send a PR to solve some issues in the spanish traslation

**Comment by jarvisdev** [comment] 2019-10-02 08:33
Hi @eldadfux can we do the translation for other Indian regional languages? i.e. Gujarati, Tamil etc.

**Comment by utkarsh-raj** [comment] 2019-10-03 23:00
Hi, I have updated the data for Hindi and added more translations in #116

**Comment by hillarysousa** [comment] 2019-10-04 04:07
Hello! I've edited some translations for country names on PT-BR and translated the inspiration quote. Creating a PR right now :)

**Comment by tanmaymohan** [comment] 2019-10-04 04:23
> @tanmaymohan that will be great. let me know if you need any help.

#110

**Comment by lucianosz7** [comment] 2019-10-05 12:21
Hello @eldadfux , I may be helping with the translation for javanes.

**Comment by CAT-ID** [comment] 2019-10-05 12:49
i can help with japanese

**Comment by SevenIndirecto** [comment] 2019-10-05 17:43
Hey @eldadfux I opened a localization PR https://github.com/appwrite/appwrite/pull/133 if that's fine.

**Comment by ahmedkrmn** [comment] 2019-10-05 20:22
I will start working on Arabic (AR) locals and will submit a PR when I'm done.

**Comment by stvmachine** [comment] 2019-10-06 03:59
Updated typo errors in spanish translations:
- https://github.com/appwrite/appwrite/pull/140
- https://github.com/appwrite/appwrite/pull/139
- https://github.com/appwrite/appwrite/pull/138

**Comment by Nishtha3512** [comment] 2019-10-06 07:41
How can i work on this.can u please help me??

**Comment by Jain-Sanchit** [comment] 2019-10-06 11:41
Can i help you by translating templates in Indian Regional languages ?

**Comment by eldadfux** [comment] 2019-10-06 12:12
@Jain-Sanchit Thank you but no need for regional translations. At this point, we are trying to focus on significant locales only. We'll open a separate issue for regional languages in case we decide to work on them in the future.

**Comment by ayan-b** [comment] 2019-10-07 12:12
I would like to add translations in [Bengali](https://en.wikipedia.org/wiki/Bengali_language).

**Comment by eldadfux** [comment] 2019-10-07 12:45
@ayan-b that will be great!

**Comment by vhgn** [comment] 2019-10-07 18:00
Hey! I can translate it to Armenian (HY) if you need. Russian is done already so I am able to help only with Armenian.

**Comment by sesam** [comment] 2019-10-08 22:34
Just for the record, a Swedish translation was added and merged in https://github.com/appwrite/appwrite/pull/155 -- so if anyone from Finland wants to add `se_FI` translation I hope the `sv` translation is useful as a start :). Have a nice day!

**Comment by sesam** [comment] 2019-10-08 23:08
@RizkyRajitha I think app/config/locale/templates/si.email.auth.invitation.tpl has a space too much in the base Sinhalese translation, can't comment on anything else in that translation though!
I had a look there just to make sure sl (Slovenian = sl_SI) and Sinhalese aren't confused anywhere :) since it tends to happen elsewhere. Have a great day!

**Comment by OnkarAgnihotri** [comment] 2019-10-09 10:18
I can help to translate in Hindi.

**Comment by RizkyRajitha** [comment] 2019-10-09 13:25
@sesam , is there anything i can do to solve that sir
thank you

**Comment by sesam** [comment] 2019-10-09 13:35
@RizkyRajitha yes if you have time -- and you know Sinhalese, correct? Please can you look specifically at line 14 here: https://github.com/appwrite/appwrite/blob/master/app/config/locale/templates/si.email.auth.invitation.tpl#L14 -- is that a space too much? Or if it's something with my browser/system not showing Sinhalese fonts correctly -- I'm unsure. Thanks for your attention :) and have a great day!

**Comment by RizkyRajitha** [comment] 2019-10-09 13:47
@sesam 
if you are see like this , then its correct , that sentence have 17 words in total 

![appwrite](https://user-images.githubusercontent.com/38534289/66487070-58c2d380-eac9-11e9-861d-ed6d63e9669a.PNG)

**Comment by YMsyaraf** [comment] 2019-10-13 12:58
do you need any help for malaysia localize?

**Comment by Vinatk** [comment] 2019-10-13 15:53
are you be needing Thai language localize?

**Comment by eldadfux** [comment] 2019-10-13 16:18
@YMsyaraf , @Vinatk that will be great, we could use both Thai and Malaysian locales! 🇹🇭🇲🇾

**Comment by noobyogi0010** [comment] 2019-10-13 16:59
@eldadfux Hi, I can help with translating in हिन्दी ‍‍‍

**Comment by jollypuppet** [comment] 2019-10-13 18:48
I can help with the Italian translation :)

**Comment by eldadfux** [comment] 2019-10-13 19:36
@jollypuppet hey, we already have it locale but you can review it for improvements if needed.

**Comment by MustafaNoorani** [comment] 2019-10-13 20:04
Hello I am available to translate into Urdu

**Comment by MIP2000** [comment] 2019-10-13 20:35
Hello, i can translate to Albanian.

**Comment by JohannaHillebrand** [comment] 2019-10-15 13:49
Do you need a Translation into German? I could help with that :)

**Comment by eldadfux** [comment] 2019-10-15 15:14
This is our updated list of currently supported locales:

```php
const APP_LOCALES = [
    'af', // Afrikaans
    'ar', // Arabic
    'bn', // Bengali
    'cat', // Catalan
    'cz', // Czech
    'de', // German
    'en', // English
    'es', // Spanish
    'fi', // Finnish
    'fr', // French
    'gr', // Greek
    'he', // Hebrew
    'hi', // Hindi
    'hu', // Hungarian
    'hy', // Armenian
    'id', // Indonesian
    'it', // Italian
    'ja', // Japanese
    'jv', // Javanese
    'lt', // Lithuanian
    'nl', // Dutch
    'no', // Norwegian
    'pl', // Polish
    'pt-br', // Portuguese - Brazil	
    'pt-pt', // Portuguese - Portugal
    'ro', // Romanian
    'ru', // Russian
    'si', // Sinhala
    'sl', // Slovenian
    'sv', // Swedish
    'ta', // Tamil
    'tr', // Turkish
    'ua', // Ukrainian
    'vi', // Vietnamese
    'zh-cn', // Chinese - China
    'zh-tw', // Chinese - Taiwan
];
```

**Comment by 24sharkS** [comment] 2019-10-20 14:32
If there is a requirement for Danish or Icelandic translation @eldadfux ? I am willing to contribute. :-)

**Comment by eldadfux** [comment] 2019-10-20 17:26
@24sharkS Danish and Icelandic translation will be awesome!

**Comment by sagarvd01** [comment] 2019-10-20 18:35
Hi, I added Malayalam Language Support in the PR #212

**Comment by karandixit10** [comment] 2019-10-20 20:30
I can help to translate in Hindi.

**Comment by jayehernandez** [comment] 2019-10-26 17:33
I can help translate to Filipino! 🇵🇭

**Comment by eldadfux** [comment] 2019-10-26 17:54
Hey @jayehernandez that will be great! If you need any help, you can contact me or any of the other maintainers in our new & cool Discord server:

https://discord.gg/GSeTUeA

**Comment by Nishtha3512** [comment] 2019-10-28 05:35
Can i help to translate in Guarani?

**Comment by eldadfux** [comment] 2019-11-01 07:17
@Nishtha3512 that will be great, if you need any help or just want to chat, join our Discord server:
https://discord.gg/GSeTUeA

**Comment by spielers** [comment] 2020-09-19 14:50
Hi @eldadfux I can help to translate in Marathi and Hindi and Gujarati and Punjabi

**Comment by spielers** [comment] 2020-09-20 08:11
Hey @eldadfux  translated into the Marathi language please have a look and merge it PR[#542](https://github.com/appwrite/appwrite/pull/542)

**Comment by prasanjit15** [comment] 2020-10-01 07:17
Hii @eldadfux I can help to translate in Odia

**Comment by prasanjit15** [comment] 2020-10-01 10:09
Hii @eldadfux. I have done the required changes and translated into the Odia language please have a look and merge it PR#598

**Comment by navneetsn18** [comment] 2020-10-01 10:54
Hiii @eldadfux  I can help to translate in Urdu.

**Comment by Unviray** [comment] 2020-10-01 12:39
Hi @eldadfux, I can help to translate in French but I don't know how to push in specific branch. How to do that ?

**Comment by Unviray** [comment] 2020-10-01 12:41
Can I translate in Malagasy language mg-MG ?

**Comment by spielers** [comment] 2020-10-01 12:41
@eldadfux I request you to update the list with the latest merges.
1] Marathi (mr) => all done
2] Gujrati(gu) => PR done #604 
3] Urdu => PR done #605

**Comment by spielers** [comment] 2020-10-01 13:03
> Hi @eldadfux, I can help to translate in French but I don't know how to push in specific branch. How to do that ?

@Unviray you can select the specific branch in our case i.e (0.7.x) and then translate or add your stuff there and make a PR from that branch if its any error there DM me ill help you out.

**Comment by adithyaakrishna** [comment] 2020-10-01 14:42
Hi @eldadfux , Would love to add a new language i.e in Kannada and I can work on that :)

**Comment by naman360** [comment] 2020-10-01 16:31
Would love to add Punjabi and hindi locales.

**Comment by spielers** [comment] 2020-10-01 16:37
@naman360 Thanks for your interest. You can go with Punjabi locales Hindi is already done.

**Comment by eldadfux** [comment] 2020-10-02 08:36
**Please Note** - We have add another step for adding a new translation. This is for the tests to run properly. I have also updated the original post.

**Configuration and Loading**
Add the new language to Appwrite config file: `/app/config/locale/codes.php` (order by ABC)
Load the new translation here: `./app/init.php (line: 224)` (order by ABC)

**Comment by spielers** [comment] 2020-10-02 08:36
Hello Guys we have a new update to the issue. please read the description of the issue before making any new PR

best,
spielers

**Comment by spielers** [comment] 2020-10-02 09:27
Hey guys, I suggest have a look at the list of translated languages before making any new PR, it has been observed that some of the languages are getting repeated.

Best,
spielers

**Comment by AshishMhrzn10** [comment] 2020-10-02 12:20
Hey @spielers and @eldadfux , Please check PR #623 where i have updated everything for Nepali language including files codes.php as well as init.php. Please, Do check

> **Please Note** - We have add another step for adding a new translation. This is for the tests to run properly. I have also updated the original post.
> 
> **Configuration and Loading**
> Add the new language to Appwrite config file: `/app/config/locale/codes.php` (order by ABC)
> Load the new translation here: `./app/init.php (line: 224)` (order by ABC)

Hey @spielers and @eldadfux , Please check PR #623 where i have updated everything for Nepali language including files codes.php as well as init.php. Please, Do check

**Comment by AshishMhrzn10** [comment] 2020-10-02 12:21
Hey @spielers and @eldadfux , Please check PR #623 where i have updated everything for Nepali language including files codes.php as well as init.php. Please, Do check

**Comment by spielers** [comment] 2020-10-03 06:11
Hey, guys, I would suggest reading the description of the issues first before making a new PR. it has been observed that contributors  are splitting the issue into multiple PRs for increasing the PR count for hactoberfest, That's not an appropriate way 
I would suggest you can have a look at issues there are plenty of them for newcomers 

best,
spielers

**Comment by abhaypawar** [comment] 2020-10-03 16:09
Hey @eldadfux and @spielers. I would love to translate into Sanskrit locale - (sa).

**Comment by spielers** [comment] 2020-10-05 08:04
@abhaypawar Go for it, I am assigning you for Sanskrit (sr)

**Comment by syshcndr** [comment] 2020-10-05 08:44
Hey! @spielers , I am interested in translating to Kannada (ka).

**Comment by spielers** [comment] 2020-10-05 08:47
hey, @syshcndr  that would be helpful, go ahead! 

best,
spielers

**Comment by saidau** [comment] 2020-10-06 20:56
I'd love to add Bosnian! If possible?

**Comment by shivaylamba** [comment] 2020-10-06 21:33
Hi @spielers I can work on Azerbaijani. if Possible

**Comment by midopooler** [comment] 2020-10-06 21:47
Hi @spielers I can work on Nicobarese. if Possible

**Comment by GriffinMLN** [comment] 2020-10-06 23:30
@spielers @eldadfux I'll add Bulgarian translations :)

**Comment by spielers** [comment] 2020-10-07 03:46
> Hi @spielers I can work on Azerbaijani. if Possible

Go ahead @shivaylamba

**Comment by spielers** [comment] 2020-10-07 03:46
> I'd love to add Bosnian! If possible?

Go ahead @saidau

**Comment by spielers** [comment] 2020-10-07 03:47
> Hi @spielers I can work on Nicobarese. if Possible

Gi ahead @midopooler

**Comment by spielers** [comment] 2020-10-07 03:48
> @spielers @eldadfux I'll add Bulgarian translations :)

Sure you can @GriffinMLN

**Comment by vj-codes** [comment] 2020-10-09 09:38
@spielers @eldadfux if I find any typos or corrections , can I create a PR for that ?Not necessarily for hacktoberfest as I have completed my first 4 PRs but as a improvement in general

**Comment by spielers** [comment] 2020-10-09 09:47
@vj-codes Yeah for sure you can. but just mention in the description of the PR That you are not aiming for hacktoberfest. will get you merged.

**Comment by vj-codes** [comment] 2020-10-09 10:01
@spielers also can I add marathi lang , code : mr
I see it is mentioned in languages.php but no translations , this as a part of hacktoberfest

**Comment by spielers** [comment] 2020-10-09 10:51
Hey, @vj-codes I guess you are checking with the master branch right ?? because I am the one who added Marathi Mr in 0.7.x branch. our current working directory for Locale translation is 0.7.x. if you found any fixes for that surely send a PR.


best,
spielers

**Comment by SandeepGamot** [comment] 2020-10-11 11:00
Hey I'd like to help with Gujarati (lang code : gu).

**Comment by spielers** [comment] 2020-10-11 11:11
> Hey I'd like to help with Gujarati (lang code : gu).
> Hey also I noticed that this issue has path like `app/config/locale/` but the actual app has `app/config/locales/`, just heads up so that you can edit the issue.

Hey, @SandeepGamot  The Gujrati gu translation is already done.You can proceed with any other language if you want

best,
spielers

**Comment by spielers** [comment] 2020-10-11 11:14
And the correct path is `app/config/locale/`. We are currently working on **0.7.x** branch So you can proceed with This is you want

Best,
spielers

**Comment by antoine29** [comment] 2020-10-25 05:26
Hey @eldadfux 
As a Spanish speaker, I noticed some minor errors in the Spanish translations. I opened a [PR](https://github.com/appwrite/appwrite/pull/703) to fix them.

**Comment by thesmartrenovation** [comment] 2021-02-12 16:21
How can I change the locale to change the language of the E-Mail templates?

**Comment by eldadfux** [comment] 2021-02-12 18:38
> How can I change the locale to change the language of the E-Mail templates?

By passing the `X-Appwrite-Locale` header or using the `setLocale` method in your SDK client object

**Comment by PayResto** [comment] 2021-06-26 16:39
I can make arabic localization.

**Comment by KaminskiDaniell** [comment] 2021-10-01 14:35
Can I help with Polish translations? :D

**Comment by adsingh14** [comment] 2021-10-04 19:02
Just a reminder, I'll be available for Punjabi language.

**Comment by idivyanshbansal** [comment] 2021-10-06 11:00
Please assign me for india(in) language

**Closed** 2021-10-16 20:32 UTC
Labels: enhancement, help wanted, good first issue, hacktoberfest, dwoc
