### ISSUE TITLE
🐛 Bug Report: The build of the project does not stop

### ISSUE THREAD

**Issue by voodee** [appwrite/appwrite#3067] opened 2022-04-07 18:50 UTC
### 👟 Reproduction steps

Create a simple script in NodeJS 16 or 17.
```
module.exports = async (req, res) => {
  res.json({
    message: "Hello Open Runtimes 👋",
  });
};
```
Add one dependency (`puppeteer-extra`):
```
{
  "name": "code",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "puppeteer-extra": "^3.2.3"
  }
}
```
Deploy the code.

-------------------------------------------------------

This is an extremely simplified example. In my case, the project was built with `esbuild` and deploded without `package.json`. I got an error: "File Not Found".

I debugged the error for a long time. At the end I realized that the project when installing certain packages the script will not start. At least I found two such packages: "puppeteer-extra" and "puppeteer-extra-plugin-recaptcha".

### 👍 Expected behavior

Successful project build.

### 👎 Actual Behavior

The project build becomes perpetual.

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment] 2022-04-11 10:17
Hey :)

have you been able to see any logs from that build?

**Comment by voodee** [comment] 2022-04-11 16:21
> Hey :)
> 
> have you been able to see any logs from that build?

No.. I found a docker process running, but it has no logs.

**Comment by christyjacob4** [comment] 2022-04-12 10:41
@voodee Thats seems unlikely, did you try 
`docker logs -f <container_id>` ?

**Comment by christyjacob4** [comment] 2022-04-12 10:42
@Meldiron  please take a look here

**Comment by Meldiron** [comment] 2022-04-12 12:10
I managed to find an error message:

```
12:00:56 0|server  | Error: Failed to launch the browser process! spawn /usr/code-start/node_modules/puppeteer/.local-chromium/linux-970485/chrome-linux/chrome ENOENT
```

Looks like the puppeteer requires an os-library setup before working - install Chromium. Our Node runtime runs on Alpine, and to keep it small&simple&fast, there is no way I could add chromium installation in there. I would recommend doing research around where puppeteer looks for chromium executable binary, and if you can provide it custom path. If so, you could ship puppeteer Linux Alpine binary with your function, and the puppeteer should be able to use it.

You can also try to look for alternatives that do not require an os-library setup; I am not experienced enough in this sector to give advance.

The last solution I can think of is making your own runtime (with puppeteer installation), and using it in Appwrite. Noone did that yet, so if you do, please let us know if there are any problems down the road.

**Comment by Maxbrt18** [comment] 2022-06-14 13:28
Have you found any solution to run Puppeteer with Appwrite ? I am facing the same problem right now.

**Comment by stnguyen90** [comment] 2022-08-15 22:13
@voodee, the problem looks to be the need for OS-level dependencies, which looks like a duplicate of #1037. I'm going to close this issue as duplicate, but please feel free to upvote #1037

**Closed by stnguyen90** 2022-08-15 22:13 UTC
Labels: bug
