### ISSUE TITLE
🐛 Bug Report: MariaDB - Return value must be of type int, float returned

### ISSUE THREAD

**Issue by Mister-Muffin** [appwrite/appwrite#3272] opened 2022-05-22 12:50 UTC
### 👟 Reproduction steps

1. Go to the Database tab on the left side.
2. Create a new collection.
3. Open the collection, click on Attributes and create a new String Attribute.
4. Fill in Attribute ID (12341234).
5. Fill in size (256).
6. Set Required (true).
7. Click create.

### 👍 Expected behavior

It should say "available" as it does when creating a Boolean Attribute.

### 👎 Actual Behavior

It actually says "failed" as it also does with Integer Attribute
![grafik](https://user-images.githubusercontent.com/45641704/169695720-8f10e1d7-bf8e-4572-b84f-8ead1eb73c1a.png)

Error in MariaDB Docker:
`appwrite-worker-database | Utopia\Database\Adapter\MariaDB::getStringLimit(): Return value must be of type int, float returned`

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use Docker on a Raspberry Pi 4B 8 GB RAM
To get it to work on the 32bit System (with 64bit Kernel), I modified the docker-compose.yml as follows:

```
...
mariadb:
    image: linuxserver/mariadb:10.5.16 # fix issues when upgrading using: mysql_upgrade -u root -p
    container_name: appwrite-mariadb
    restart: unless-stopped
    networks:
      - appwrite
    volumes:
      - appwrite-mariadb:/var/lib/mysql:rw
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${_APP_DB_ROOT_PASS}
      - MYSQL_DATABASE=${_APP_DB_SCHEMA}
      - MYSQL_USER=${_APP_DB_USER}
      - MYSQL_PASSWORD=${_APP_DB_PASS}
#    command: 'mysqld --innodb-flush-method=fsync'
...
```
image changed because MariaDB is not directly available as armv7 (note that linuxserver/mariadb's latest version is 10.5)
command commented out because otherwise the container would fail

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2022-05-22 18:00
Possibly related: https://github.com/appwrite/appwrite/issues/3256

**Comment by Mister-Muffin** [comment] 2022-05-22 19:21
Good idea, but the name of the failed Attribute is "test", so not purely numeric 😕

**Comment by stnguyen90** [comment] 2022-05-22 22:22
> Good idea, but the name of the failed Attribute is "test", so not purely numeric 😕

What do you mean? Your step 4 says "Fill in Attribute ID (12341234)."

**Comment by stnguyen90** [comment] 2023-01-12 13:58
@Mister-Muffin, is this still a problem? I tried to reproduce, but it created fine:

<img width="952" alt="image" src="https://user-images.githubusercontent.com/1477010/212085759-14feb4ba-d3b3-4028-8318-58e656c91b38.png">

**Comment by Mister-Muffin** [comment] 2023-01-14 12:36
On v.0.13 it is still not working on armv7, but tested it on an amd64 machine and it worked there.
Unfortunately, I can't test the latest version of Appwrite on my Raspberry Pi, because it is not available for armv7

**Comment by stnguyen90** [comment] 2023-01-26 22:26
@Mister-Muffin, I'm going to close this one for now since we can't reproduce the problem. We can re-open if needed.

For the armv7 problem, I would suggest creating a new issue with details about what doesn't work so that we could look into getting it working.

**Closed by stnguyen90** 2023-01-26 22:26 UTC
Labels: bug, database
