### ISSUE TITLE
🐛 Bug Report: CLI config for integer fields uses invalid default min and max values

### ISSUE THREAD

**Issue by pingu2k4** [appwrite/appwrite#8073] opened 2024-05-03 22:33 UTC
### 👟 Reproduction steps

- Create a DB
- Create a Collection
- Create an attribute on said collection of type integer. Leave min and max blank
- run `appwrite init collection --all`
- After running `appwrite client` and providing an endpoint and projectId...
- run `appwrite deploy collection --all --yes`
- note the error. 

### 👍 Expected behavior

The values stored in the .json file are `9223372036854776000` and `-9223372036854776000`. These are outside the bounds of integers. I would expect it to use Min and Max values for Integer (2.147 billion or so). 

### 👎 Actual Behavior

![image](https://github.com/appwrite/appwrite/assets/11229848/b3f28780-8ebb-4526-87f0-0216810ea436)

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Tinkering right now with Appwrite on localhost

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2024-05-06 19:05
@pingu2k4, thanks for creating this issue! 🙏🏼 This looks like a duplicate of https://github.com/appwrite/sdk-for-cli/issues/124. As such, please add a 👍🏼 to that issue as I'll be closing this as a duplicate.

**Closed by stnguyen90** 2024-05-06 19:05 UTC
Labels: bug

**Comment by pingu2k4** [comment] 2024-05-06 21:19
Ah I had tried searching, but didn't come across this one. Thanks.
