### ISSUE TITLE
🚀 Feature: Function custom execution url (REST API way)

### ISSUE THREAD

**Issue by mbos2** [appwrite/appwrite#5831] opened 2023-07-17 21:43 UTC
### 🔖 Feature description

Custom URL option for  appwrite cloud functions so they can be consumed by REST API as well, than only by [Create Execution API](https://appwrite.io/docs/server/functions?sdk=nodejs-default#functionsCreateExecution). 

### 🎤 Pitch

As AWS Lambda can be called in a RESTful way in a combination with AWS Gateway services, could the same be done for Appwrite functions?

Let's say we make a appwrite function named **get_collections**. We by default get its ID which we can use to make an execition  via [Create Execution API](https://appwrite.io/docs/server/functions?sdk=nodejs-default#functionsCreateExecution). 

But what if we want to expand how we use this cloud functions? 
We can have function url like `https://DOMAIN/PROJECT_ID/OUR-CUSTOM-PATH`. **OUR-CUSTOM-PATH** is what's important here, and we could set something like `get-collections`, so the full path would be `https://DOMAIN/PROJECT_ID/get-collections`. 

Here's some documentation on AWS gateway, there's probably a lot more in their docs.

[https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway.html](https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway.html)
[https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway-tutorial.html](https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway-tutorial.html)

Of course there's also permissions issue and domain whitelisting for such functions. 

Domain whitelist - either set domains that can use this function or allow any domain with a * character. **(This can be a separate feature as well, as an improvement to cloud functions)**

Permissions:  (**This could also be a separate feature**)

- We could set only specific users/teams to be able to use the function inside appwrite console 
- We could set anyone could use the function if they're logged in
- Potentionally, we could also set that anyone can use the function even without being logged in. **Which means appwrite doesn't even have to be installed in a project that consumes it.** 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by mbos2** [comment] 2023-07-17 21:52
REST API way can be a setting to enable or disable. 
If enabled, URL can be set. If disabled, if there's URL in there already, either keep it or clear it, doesn't matter. 

Permissions and domain whitelisting can also go in settings

**Comment by mbos2** [comment] 2023-07-17 22:19
Possibly related to this
https://github.com/appwrite/appwrite/issues/3069

**Comment by stnguyen90** [comment] 2023-07-17 23:00
Can this be closed since it's a duplicate of #3069? 

Also, this is planned for the next version of Appwrite. See FYI, this is planned for the next version of Appwrite. See https://github.com/appwrite/appwrite/discussions/5016.

**Comment by mbos2** [comment] 2023-07-17 23:24
> Can this be closed since it's a duplicate of #3069?
> 
> Also, this is planned for the next version of Appwrite. See FYI, this is planned for the next version of Appwrite. See #5016.

Sure, but this could be mentioned in a comment inside #3069.

**Closed** 2023-07-18 00:14 UTC
Labels: functions
