### ISSUE TITLE
🐛 Bug Report: Storage Permissions

### ISSUE THREAD

**Issue by Vegeta-7** [appwrite/appwrite#7929] opened 2024-04-07 06:18 UTC
### 👟 Reproduction steps

Not able to provide permissions in bucket in a free account.

### 👍 Expected behavior

It should allow me to provide permissions in the bucket as i have only created 1 bucket and 0 files right now.

### 👎 Actual Behavior

Provides a toast speaking maximum file size exceeded for the free account.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment] 2024-04-07 06:45
This is probably due to the default maximum limit set on the Starter plan for File Uploads which is **5GB** however the plan allows **50MB**.

Until this gets fixed, you can scroll down the settings page, change the **Maximum file size** to **50MB** & Update, then change your Bucket Permissions and click Update. That should work for the time being.

**Comment by stnguyen90** [comment] 2024-04-11 22:16
Closing as a duplicate of https://github.com/appwrite/appwrite/issues/7682

**Closed by stnguyen90** 2024-04-11 22:16 UTC
Labels: bug
