### ISSUE TITLE
🚀 Feature: Check multiple attributes at once in DB query

### ISSUE THREAD

**Issue by burakmartin** [appwrite/appwrite#5399] opened 2023-04-18 16:23 UTC
### 🔖 Feature description

When querying documents, allow to check multiple attributes at once with `OR` logic.

### 🎤 Pitch

I often find myself with documents where I would like to check if an value exists in either one or another attribute. Imagine a "Friends" collection like `Friends(user1, user2)`. Finding all friends of a user with the id "userId" would mean having to do two lookups:

```dart
database.listDocuments(
  databaseId: "...",
  collectionId: "...",
  queries: [
      Query.equal("user1", [userId]),
  ]
)

database.listDocuments(
  databaseId: "...",
  collectionId: "...",
  queries: [
      Query.equal("user2", [userId]),
  ]
)
```
What I would prefer is something like:

```dart
database.listDocuments(
  databaseId: "...",
  collectionId: "...",
  queries: [
      Query.equal(["user1", "user2"], [value]),
  ]
)
```
Which would make it more concise and more efficient if implemented correctly

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-04-18 18:27
@burakmartin thanks for creating this issue! 🙏🏼 This actually looks like a duplicate of https://github.com/appwrite/appwrite/issues/2740. As such, would you please 👍🏼 that issue? For now, I'll close this issue.

**Closed by stnguyen90** 2023-04-18 18:27 UTC
