### ISSUE TITLE
🐛 Bug Report: The dashboard breaks if you add a long string attribute

### ISSUE THREAD

**Issue by voodee** [appwrite/appwrite#3162] opened 2022-04-28 14:34 UTC
### 👟 Reproduction steps

I create a colleaction. 
And I add the string attribute with length `1024`.
I deleted this attribute.
And I add the string attribute with length `102400`.

### 👍 Expected behavior

The string attribute will be added.

### 👎 Actual Behavior

First, the attribute was not added. The status was "processing" all the time.

Then documents in the collection stopped loading.

Then the dashboard stopped loading 😢

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment] 2022-04-29 08:57
Hey 👋  Sadly I cannot reproduce the problem. Could you share your full `docker-compose logs appwrite-worker-database` with me?

**Comment by voodee** [comment] 2022-04-30 08:02
> Hey wave Sadly I cannot reproduce the problem. Could you share your full `docker-compose logs appwrite-worker-database` with me?

I forgot read all logs before restart. Now it is hard to do it. I think this situation will happen soon. Next time I will copy logs.

**Comment by stnguyen90** [comment] 2023-02-27 19:53
Closing as we're unable to reproduce. Feel free to comment with logs if you're able to reproduce.

**Closed by stnguyen90** 2023-02-27 19:53 UTC
Labels: bug
