### ISSUE TITLE
Issues while executing Login with Github OAuth2 flow

### ISSUE THREAD

**Issue by DiegoBM** [appwrite/appwrite#1192] opened 2021-05-25 20:07 UTC
## 🐛 Bug Report

While implementing Login with Github, most of the authentication happens smoothly, but by the last redirection (the one to /v1/account/sessions/oauth2/github/redirect...) the server returns a 500 error with the following message:

`[Error] Method: GET
[Error] URL: /v1/account/sessions/oauth2/:provider/redirect
[Error] Type: TypeError
[Error] Message: Cannot access offset of type string on string
[Error] File: /usr/src/code/src/Appwrite/Auth/OAuth2/Github.php
[Error] Line: 98`

## Have you spent some time to check if this issue has been raised before?

I have, to no avail.

## To Reproduce

1.- Execute standard Oauth flow.
2.- Introduce your github login details
3.- Approve the request for the app trying to get access
It seems to go well until here, then the last redirection will display a 500 error

## Expected behavior

The user should have been created and authenticated

## Actual Behavior

Server returned a 500 error prior to executing the last redirection to the passed success url

## Your Environment

Client: React Native using Web SDK 3.0.3, running on the Android simulator
Server: Ubuntu linux server x64 running Appwrite v0.8.0

**Comment by DiegoBM** [comment] 2021-05-26 00:04
It seems like I was not giving Github app configuration enough permissions to provide emails. So it was an issue on my side.

Arguably Appwrite server should fail differently to the issue, since line 98 is trying to process email regardless of Github giving them away or not due to permissions, therefore the 500 error, but I'll leave that to the contributors to decide.

**Comment by eldadfux** [comment] 2021-05-26 05:44
Yes, I think we should submit a better error. Can you share what was the exact error you got from the Github API after debugging?

**Comment by DiegoBM** [comment] 2021-05-26 06:42
Of course, this was the value of $emails:

```Array
(
    [message] => Resource not accessible by integration
    [documentation_url] => https://docs.github.com/rest/reference/users#list-email-addresses-for-the-authenticated-user
)

**Comment by christyjacob4** [comment] 2021-06-02 07:31
This will need some more discussion @eldadfux  because missing scopes could arise with any of the 20+ providers we have and IIRC not all of them return messages that clearly state that "scope x is missing"

**Comment by stnguyen90** [comment] 2022-08-14 08:06
possibly related: https://github.com/appwrite/appwrite/issues/3680

**Comment by stnguyen90** [comment] 2023-07-28 00:04
@DiegoBM, I tried to reproduce this recently, but I wasn't able to figure out how to not share my email address:

<img width="711" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/38914f6f-405e-4515-9ef5-d9a7376ba2e0">

How did you do this?

**Comment by christyjacob4** [comment] 2023-07-28 07:53
@stnguyen90 you can head to your [email settings on GitHub](https://github.com/settings/emails) and check the following box

![Screenshot 2023-07-28 at 11 53 23 AM](https://github.com/appwrite/appwrite/assets/20852629/b8a881f5-c3ad-44db-a6f8-0ab388e0931c)

**Comment by stnguyen90** [comment] 2023-08-02 23:50
> @stnguyen90 you can head to your [email settings on GitHub](https://github.com/settings/emails) and check the following box
> 
> ![Screenshot 2023-07-28 at 11 53 23 AM](https://user-images.githubusercontent.com/20852629/256760061-b8a881f5-c3ad-44db-a6f8-0ab388e0931c.png)

@christyjacob4. I checked that, but I was still able to log in and appwrite was still able to get my email 🧐

**Comment by stnguyen90** [comment] 2024-04-25 19:18
Closing as we're unable to reproduce.

**Closed by stnguyen90** 2024-04-25 19:18 UTC
Labels: enhancement, product / auth
