### ISSUE TITLE
🐛 Bug Report: Using a cursor with `$id`, `$createdAt` or `$updatedAt` as orderAttributes, throws error.

### ISSUE THREAD

**Issue by p4-k4** [appwrite/appwrite#3578] opened 2022-07-21 05:10 UTC
### 👟 Reproduction steps

Specify a cursor in combination with any of the following inside of an `orderAttributes` array:
- `$id`
- `$createdAt`
- `$updatedAt`

### 👍 Expected behavior

Expected to have results sorted by either `$id`, `$createdAt` or `$updatedAt` **from** the cursor position provided.

### 👎 Actual Behavior

Appwrite throws an error.
`AppwriteException: general_unknown, Server Error (500)`
`[Error] Message: Order attribute '_createdAt' is empty.`

### 🎲 Appwrite version

Version 0.15.2.402

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2022-07-21 19:29
I believe this is a duplicate of https://github.com/appwrite/appwrite/issues/3403 and is pending release. Please feel free to upvote the other issue and comment on it if it's still a problem after released.

**Closed by stnguyen90** 2022-07-21 19:29 UTC
Labels: bug
