### ISSUE TITLE
🐛 Bug Report: Error 'Document with the requested ID already exists' when tries to upload video

### ISSUE THREAD

**Issue by joec05** [appwrite/appwrite#5686] opened 2023-06-11 01:41 UTC
### 👟 Reproduction steps

```
InputFile fileToInputFile(String uri, String path) {
    final inputFile = InputFile.fromPath(path: uri, filename: path);
    return inputFile;
  }

  Future<String> uploadMediaToAppWrite(String bucketID, String uri, String path) async{
    String loadedUri = '';
    final appWriteStorage = Storage(updateAppWriteClient());
    String uniqueID = Uuid().v4();
    print('$uniqueID is uniqueid');
    await appWriteStorage.createFile(
      bucketId: bucketID,
      fileId: uniqueID,
      file: fileToInputFile(uri, path)
    ).then((response) async{
      loadedUri = 'https://cloud.appwrite.io/v1/storage/buckets/$bucketID/files/$uniqueID/view?project=$appWriteUserID&mode=admin';
    })
    .catchError((error) {
      print('error');
        print(error.response);
    });
    return loadedUri;
  }
```

i used this function for uploading both images and videos. with images it succeeded but not with videos.

### 👍 Expected behavior

I believe just like when uploading image, uploading videos should have been successful because in the client i'm using the same function as the one i used to upload images.

### 👎 Actual Behavior

but it didnt. it returned an error with the message: '{message: Document with the requested ID already exists., code: 409, type: document_already_exists, version: 0.10.30}'. the only difference between the images and videos in the storage was that i used a separate bucket, and i had double checked the bucket ids. even i tried uploading the video to the image's bucket, but still to no avail.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

i am using the 9.0.0. i tried downgrading to 8.1.0 but still everything doesnt change.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by professorabhay** [comment] 2023-06-16 09:42
Hey @joec05, Have you make sure that the bucket ID and file ID you are using for the video are correct. Double-check that they match the actual IDs of the bucket and file you want to upload the video to.

**Comment by joec05** [comment] 2023-06-20 09:51
well, yes. i even used tried changing the bucket id to the bucket id of the image bucket's. it still returned the same error.

**Comment by Batoe** [comment] 2023-07-27 02:57
Hi, I have the same problem. When I uploaded a video larger than 30MB, the same error was returned.

**Comment by joec05** [comment] 2023-07-27 06:49
> Hi, what is the size of the video? I ask you this because I have already encountered this problem with large files (greater than 5MB). I had the same error message... I use the appwrite sdk flutter and you? Have you solved your problem?

well to be honest i didn't really pay attention to that, but maybe i'll actually try with a smaller sized video.

**Comment by marvinIsSacul** [comment] 2023-09-14 16:10
Hi,

It appears as thought files larger than 5MB really do cause this issue.

Any fixes yet?

**Comment by orelvis15** [comment] 2023-10-18 21:54
Hello, Same problem here with the Kotlin/Android SDK

```Code: 409 type: null response: {"message":"A storage file with the requested ID already exists.","code":409,"type":"storage_file_already_exists","version":"0.11.12"}```

**Comment by fvdf** [comment] 2023-10-19 09:01
Hello, 👋

if the problem is solved with a file of less than 5 MB, the problem comes from cutting and receiving the file. I think that the server after receiving the first party blocks the rest of the file for no real reason. 

In my case I started by testing with the appwrite cloud server and the most no problem, so I understood that it came from my server. I reinstalled my server and no more problems. 

If you have a self-host server you should try this solution.😉

Have good day !

**Comment by stnguyen90** [comment] 2024-05-21 05:05
Closing as a duplicate of https://github.com/appwrite/appwrite/issues/5563

**Closed by stnguyen90** 2024-05-21 05:05 UTC
Labels: bug, product / storage
