### ISSUE TITLE
🚀 Feature: Create multiple relationships between two collections in Appwrite database.

### ISSUE THREAD

**Issue by rsbichkar** [appwrite/appwrite#7288] opened 2023-12-14 19:25 UTC
### 🔖 Feature description

A request to add a feature in Appwrite database to permit creation of multiple relationships (one-to-one or in general any relationships) between two collections.

### 🎤 Pitch

I am creating a Flutter application containing the following data: Contact (of a person) containing mobile, email, permanent address, local address, communication address, etc.

I have created two collections namely, contact and address. The contact has the following fields: mobile, email, permAddr (permanent address), localAddr (local address), and commAddr (communication address), etc. Each of the address fields are expected to have one-to-one relation to the address collection. However, it is not possible to create three one-to-one relations between contact and  address collections. I get 'failed' error in the console when I create second and third one-to-one relations. 

I raised this question on [discord (in Support Section)](https://discord.com/channels/564160730845151244/1184565488127315998) and came to know that Appwrite database relationships are at the collection level rather than at the attribute level. Hence, it is not possible to create such relationship and handle such situations. On discord, it was suggested to raise this feature request.  

It is, however, possible to create one-to-many relationship. But, probably it will require 'address' relation field to be an array, which is not an elegant solution in such situations and will complicate the other associated code. I wish to keep these three fields separate as mentioned above.

There are many such situations in my app (and in general in several apps). For example, a class containing information about a large number persons (students) and one or more persons (teachers).

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2024-02-01 22:29
@rsbichkar, thanks for creating this issue! As mentioned on Discord, it looks like your request is a duplicate of https://github.com/appwrite/appwrite/issues/6281. As such, I'd recommend adding a 👍🏼 on that issue.

**Closed by stnguyen90** 2024-02-01 22:29 UTC
Labels: databases, relationships
