### ISSUE TITLE
🐛 Bug Report: [Apple SDK] XPC Connection Interrupted causes App to Freeze

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#6206] opened 2023-09-09 18:26 UTC
### 👟 Reproduction steps

There's a use of `DispatchGroup` in `Account.swift` which most of the time causes the app to freeze when the app opens the Safari App for `OAuth`.

Flow:
1. I used this: `let status = try account.createOAuth2Session(provider: "google")`
2. App opens `Safari` browser & goes into background
3. Sign In with your Account, the generic `Missing Redirect` page shows up which triggers app open via deep-link
4. App freezes with above error after deep link open.

I manually commented out the `DispatchGroup` implementation in the `Account.swift` and it seems to work smooth!

---

**Note:**
As I have multiple deep-links I cannot directly use `registerOAuthHandler()` on a `View`.
So, I manually check the `URLComponents` received if valid, I use `WebAuthComponent.handleIncomingCookie(from: url)`

### 👍 Expected behavior

App should not freeze.

### 👎 Actual Behavior

App freezes, sometimes even before opening.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment] 2023-09-10 06:36
Another thing is:
`WebAuthComponent.swift` has below :
```swift
#if canImport(SwiftUI)
    openURL(url)
#endif
```

This will throw a warning: `Accessing Environment<OpenURLAction>'s value outside of being installed on a View. This will always read the default value and will not update.`

Alternative could be to use the `UIApplication.shared.open(url, options: [:], completionHandler: nil)`.

**Comment by abnegate** [comment] 2023-09-11 23:45
Thanks @ItzNotABug for the report! A fix is in progress, I'll update again when it's released.

**Comment by ItzNotABug** [comment] 2023-09-12 06:45
Thanks for the update @abnegate.
Would the fix be targeted against appwrite `1.4x`? If so, this wouldn't be backwards compatible I guess...

**Comment by abnegate** [comment] 2023-09-12 18:09
> Thanks for the update @abnegate. Would the fix be targeted against appwrite `1.4x`? If so, this wouldn't be backwards compatible I guess...

@ItzNotABug Yep it will target 1.4.x, but we can backport it to the 1.3.x SDK since the issue is present there too. Once the fix PR is merged, I'll follow up on that.

**Comment by abnegate** [comment] 2023-09-14 19:28
Closing as resolved in versions 4.0.1 (1.4.x) and 2.0.1 (1.3.x)

cc @ItzNotABug

**Closed by abnegate** 2023-09-14 19:28 UTC
Labels: bug
