### ISSUE TITLE
🐛 Bug Report: Error Creating API Key

### ISSUE THREAD

**Issue by meepeek** [appwrite/appwrite#4966] opened 2023-01-07 16:33 UTC
### 👟 Reproduction steps

** github code of conduct link point to 404 **

1. clean install with docker-compose script and default .env
2. create first admin
3. login
4. go to create api key as soon as you can
5. try to create one

### 👍 Expected behavior

It should create the key, but if it requires user to create project or database beforehand, it should not let user get to the screen.

### 👎 Actual Behavior

even if you input a name, the ui will report error for not giving one.

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

run with recommended docker-compose.yml and .env on portainer stack

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-01-09 18:12
@meepeek thanks for creating this issue! 🙏🏼 Question for you...how are you able to try to create an API key after creating the admin account? I'm presented with this to create the project:

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/1477010/211377974-04c31c4b-38f7-4f08-92c3-55ea1671d9b3.png">

**Comment by meepeek** [comment] 2023-01-10 01:45
@stnguyen90 
I create a project and try to create the key right away at that time but I cannot seems to reproduce it now, even if I clear appwrite volumes.

However, I ran into another issue that if I created an organization then create a project with fixed ID, let say, test. After that I delete the organization. I can no longer use 'test' as project ID ever again, even in another organization. The questions are:
1. Is there any way to delete the ghost project that hog the ID ?
2. Is it by design that project id must be unique among organization ?

![Screen Shot 2566-01-10 at 08 39 48](https://user-images.githubusercontent.com/2456033/211442872-2996cffa-90a9-48a2-b7c4-e6ceb41530ee.png)

PS. I'm sorry that I didn't capture screen and freeze the state of the original issue, I will let you know if I ran into that again.

**Comment by stnguyen90** [comment] 2023-01-10 18:32
> I create a project and try to create the key right away at that time but I cannot seems to reproduce it now, even if I clear appwrite volumes.

Since you can't reproduce the original problem, I'm going to close this issue. Please create a new issue for the new problem you're having. You should be able to easily create the issue from the comment.

**Closed by stnguyen90** 2023-01-10 18:32 UTC
Labels: bug, ui/ux

**Comment by stnguyen90** [comment] 2023-01-13 00:12
@meepeek, have you had a chance to create the new issue?

**Comment by stnguyen90** [comment] 2023-01-13 21:57
@meepeek, never mind, I've created issue https://github.com/appwrite/appwrite/issues/5006
