### ISSUE TITLE
🐛 Bug Report: Resending invitations to projects doesn't work

### ISSUE THREAD

**Issue by Megamannen** [appwrite/appwrite#6251] opened 2023-09-15 12:08 UTC
### 👟 Reproduction steps

Press the Resend button in the invite console

### 👍 Expected behavior

Not throw an error and resend the invite instead

### 👎 Actual Behavior

![image](https://github.com/appwrite/appwrite/assets/19424456/e7f7a99a-60ab-404a-83e1-55b0e824d102)

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

1.4.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment] 2023-09-19 15:51
Thanks @Megamannen for bringing this issue up. Will take it to the team!

**Comment by zach28attack** [comment] 2023-10-09 15:20
@Haimantika Could I please be assigned to this issue? I'm looking to contribute to open-source. Thank you!

**Comment by stnguyen90** [comment] 2024-02-05 00:28
Closing as a duplicate of https://github.com/appwrite/appwrite/issues/5901

**Closed by stnguyen90** 2024-02-05 00:28 UTC
Labels: bug, console
