### ISSUE TITLE
🐛 Bug Report: Failed to create connection in appwrite-worker-mails container

### ISSUE THREAD

**Issue by mbackonja** [appwrite/appwrite#8001] opened 2024-04-22 09:38 UTC
### 👟 Reproduction steps

1. Start a 1.5.4 version of Appwrite
2. Invite user to the team
3. Look at the docker logs of the `appwrite-worker-mails` container

### 👍 Expected behavior

No errors and the invite email is sent

### 👎 Actual Behavior

Email is not sent and `appwrite-worker-mails`  contains the following errors:

```
[Job] Received Job (6625633897d6c1.21568090).
[Job] (6625633897d6c1.21568090) failed to run.
[Job] (6625633897d6c1.21568090) Error sending mail: SMTP Error: data not accepted.

Fatal error: Uncaught Exception: Failed to create connection: SQLSTATE[HY000] [1045] Access denied for user ''@'172.28.0.13' (using password: NO) in /usr/src/code/vendor/utopia-php/pools/src/Pools/Pool.php:193
Stack trace:
#0 /usr/src/code/app/worker.php(48): Utopia\Pools\Pool->pop()
#1 /usr/src/code/vendor/utopia-php/queue/src/Queue/Server.php(99): {closure}(Object(Utopia\Cache\Cache), Object(Utopia\Registry\Registry))
#2 /usr/src/code/vendor/utopia-php/queue/src/Queue/Server.php(119): Utopia\Queue\Server->getResource('dbForConsole')
#3 /usr/src/code/vendor/utopia-php/queue/src/Queue/Server.php(99): Utopia\Queue\Server->getResources(Array)
#4 /usr/src/code/vendor/utopia-php/queue/src/Queue/Server.php(388): Utopia\Queue\Server->getResource('project')
#5 /usr/src/code/vendor/utopia-php/queue/src/Queue/Server.php(295): Utopia\Queue\Server->getArguments(Object(Utopia\Hook))
#6 [internal function]: Utopia\Queue\Server->Utopia\Queue\{closure}('0')
#7 /usr/src/code/vendor/utopia-php/queue/src/Queue/Adapter/Swoole.php(37): call_user_func(Object(Closure), '0')
#8 [internal function]: Utopia\Queue\Adapter\Swoole->Utopia\Queue\Adapter\{closure}(Object(Swoole\Process\Pool), '0')
#9 {main}
  thrown in /usr/src/code/vendor/utopia-php/pools/src/Pools/Pool.php on line 193

Fatal error: Uncaught Swoole\Error: API must be called in the coroutine in /usr/src/code/vendor/phpmailer/phpmailer/src/SMTP.php:1269
Stack trace:
#0 /usr/src/code/vendor/phpmailer/phpmailer/src/SMTP.php(1269): stream_select(Array, NULL, NULL, 300)
#1 /usr/src/code/vendor/phpmailer/phpmailer/src/SMTP.php(1041): PHPMailer\PHPMailer\SMTP->get_lines()
#2 /usr/src/code/vendor/phpmailer/phpmailer/src/SMTP.php(936): PHPMailer\PHPMailer\SMTP->sendCommand('QUIT', 'QUIT', 221)
#3 /usr/src/code/vendor/phpmailer/phpmailer/src/PHPMailer.php(2298): PHPMailer\PHPMailer\SMTP->quit()
#4 /usr/src/code/vendor/phpmailer/phpmailer/src/PHPMailer.php(848): PHPMailer\PHPMailer\PHPMailer->smtpClose()
#5 [internal function]: PHPMailer\PHPMailer\PHPMailer->__destruct()
#6 {main}
  thrown in /usr/src/code/vendor/phpmailer/phpmailer/src/SMTP.php on line 1269
```

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2024-04-22 21:25
@mbackonja, thanks for raising this issue and PR! 🙏🏼 

This won't fix your

> Error sending mail: SMTP Error: data not accepted.

error. That is probably caused by an incorrect email set in the [environment variable](https://appwrite.io/docs/advanced/self-hosting/email#environment-variables).

**Closed** 2024-04-22 21:35 UTC
Labels: bug, community

**Comment by mbackonja** [comment] 2024-04-23 07:58
Yes, you are right! After fixing the database connection with PR #8002, the connection error is gone but this SMTP error stayed, so my SMTP settings were wrong... But this database error was "larger" and at the same time so I thought emails were not sent because of it. Anyway, I believe that the connection issue should be fixed and I see you already merged it, so, thank you!
