### ISSUE TITLE
📚 Documentation: Replace `GlobalScope` with `lifecycleScope` in Android-Kotlin examples

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#6002] opened 2023-08-17 08:01 UTC
### 💭 Description

I've noticed that all the examples in the Android-Kotlin SDK documentation use `GlobalScope.launch { ... }` to perform required tasks in the background.

However, `GlobalScope.launch` isn't recommended & **AndroidStudio** would throw a warning like - 
```
This is a delicate API and its use requires care. Make sure you fully read and understand documentation of the declaration that is marked as a delicate API.
```

It would be more appropriate to use an activity-scoped coroutine, such as `lifecycleScope`.

Note: Existing issue https://github.com/appwrite/appwrite/issues/2655 also mentioned this and was recently marked as fixed, but it isn't.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by aryangupta701** [comment] 2023-08-17 10:34
HI please assign this issue to me @Haimantika

**Comment by Haimantika** [comment] 2023-08-22 07:53
Thanks @ItzNotABug for opening this issue. @gewenyu99 can you please look into this?

**Comment by Kgkunal** [comment] 2023-09-18 14:54
Is this issue still open ?

**Comment by gewenyu99** [comment] 2023-09-19 15:48
> Is this issue still open ?

Yes, until Cloud goes on 1.4.x, this is still open. The issue is fixed, just... waiting for Cloud deployment ;)

**Comment by gewenyu99** [comment] 2024-02-20 14:58
I believe this is fixed already

**Closed by gewenyu99** 2024-02-20 14:58 UTC
Labels: waiting for release, product / docs
