### ISSUE TITLE
🚀 Feature: Need a Object attribute in collection. (struct/map)

### ISSUE THREAD

**Issue by Panth977** [appwrite/appwrite#5023] opened 2023-01-19 21:48 UTC
### 🔖 Feature description

we can see basic use cases like

```
User/{userDocID} = {
    name: string; 
    address?: {line1: string; line2: string; line3?: string} // is struct
}
Order/{orderDocID} = {
    success: bool;
    customer: { // is struct
        uid: string; 
        name: string; 
        address?: {line1: string; line2: string; line3?: string} // is struct
        phone?: string;
        email?: string;
    };
    order: { [product_id]: int } // is map
    vendor: {
        venderID: string;
        name: string;
    }
}
```
and converting this into something like
```
User/{userDocID} = {
    name: string; 
    addressLine1?: string;
    addressLine2?: string;
    addressLine3?: string;
}
```
would be a bit buggy, because it is possible to have addressLine1 be null & addressLine2 be string. which don't look very good.

### We can simply have a Object attribute 

Once dev select Object attribute, then it is simple matter of validation check. like
```
// init sdk, stuff


// User/{userDocID} add "address" attribute
databases.createObjectAttribute(
    '[Database]', 
    'User', 
    'address', 
    -1, 
    false,
 // last parameter is "structure", a simple language to explain structure
    "isStruct({ line1: isString, line2: isString, line3: isNullOr(isString) })"
)
// Order/{orderDocID} add "customer" attribute 
databases.createObjectAttribute(
    '[Database]', 
    'Order', 
    'customer', 
    -1, 
    true,
    `isStruct({
        uid: isUid, // check if is valid uid & exists in project auth pool 
        name: isString, 
        address: isNullOr(isStruct({ line1: isString, line2: isString, line3: isNullOr(isString) })) // structs can have inner structs
        phone: isNullOr(isPhone) // check if is valid phone-number
        email: isNullOr(isEmail) // check if is valid email
// or we can also do
        contact: isEither(isPhone, isEmail, isUid) // isEither will check one by one if given data is valid
})`
)

// Order/{orderDocID} add "order" attribute
databases.createObjectAttribute(
    '[Database]', 
    'Order', 
    'order', 
    -1, 
    true,
   "isMap(isInt)"
)
// you get the point
```
[for validation syntax](https://github.com/Panth977/sanitize-json)

basically once object attribute is selected all you have to do is validate if incoming object is correct or not based upon presented structure (syntax of structure can have more complex validator, such as `isUid`, `isEmail`, etc.,. this validator are side-view/optional).
mainly have following validator to make it useable

**minimum Require validator**

- `isNullOr($nonNull-validator)` // it checks if it is null or validator passed in argument
- `isString` // it checks if it is string
- `isInt` // check is int
- `isNumber` // check is number
- `isBool` // check is bool
- `isStruct({ [field: string]: $validator })` // for each mentioned field a unique validator
- `isMap($validator)` // in key-value pair, all values must pass same validator
- `isList($validator)` // all elements must pass same validator

**Optional validator**

- `isEnum("val1", "val2", ...)` // corresponding field value must be one of arguments passed in isEnum
- `isEmail` // checks if is email
- `isPhone` // checks if is phone
- `isUid` // checks if is uid & validate from project user pool
- `isEither($validator1, $validator2, ...)` // checks one by one if value validates one of the given validator in passed arguments
- `satisfies($validator1, $validator2, ...)` // checks one by one if value validates all of the given validator in passed arguments

### Read, Create, Update, Delete

For Read/Write: this attribute will be stored as `jsonEncode(incoming-object)` & while sending parse by `jsonDecode(outgoing-object)` (of-course choose encode as you prefer, but the point is, it happens behind the seen)

creating specific inner field updates (like firestore) is fairly possible, but i have a much simpler alternative:
if developer wants to update certain field within object then i think they should bring the field out side (i.e., create field's own document attribute, don't put it inside object. OR create object as document in some other collection.)
this way entire object type attribute's value will be created/update/delete (i.e., set operation) no need to update a specific field within object.

### Index
indexing any of the inner fields should be easy, 
if index is brand new, then scan all doc & parse/decode attribute with type object (if needed), get field & create query
then every time any document within this collection is updated, simply update index, as incoming write data will be in decoded formate.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-01-20 18:01
@Panth977, thanks for creating this issue! 🙏🏼 Is this a duplicate of https://github.com/appwrite/appwrite/issues/2735? If so, it would be great if you could 👍🏼 that issue and close this as a duplicate.

**Comment by Panth977** [comment] 2023-01-21 04:45
@stnguyen90 that issue didn't talk about what can be done in detail. so i fell like this deserve its own separate instance.
Any way u can close this issue if u want, i will just add a comment in #2735 .
🙏🏻

**Closed** 2023-01-21 04:47 UTC
Labels: database
