### ISSUE TITLE
Bucket limitation

### ISSUE THREAD

**Issue by fZakoumi** [appwrite/appwrite#7325] opened 2023-12-24 13:35 UTC
### 👟 Reproduction steps

hello, i'm not able to upload more than 225 file in bucket, i taught that the limitation by totale size of files note by number

### 👍 Expected behavior

i don't know

### 👎 Actual Behavior

i cand add file even when i delete old files

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

Cloud version

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-12-27 16:41
Closing as a duplicate of https://github.com/appwrite/appwrite/issues/7338

**Closed by stnguyen90** 2023-12-27 16:41 UTC
Labels: bug
