### ISSUE TITLE
One-click Deploy to Heroku

### ISSUE THREAD

**Issue by TJMusiitwa** [appwrite/appwrite#461] opened 2020-06-28 17:23 UTC
Hey there, while the install and deploy with Docker is great. I have been having issues with the Docker installation on my computer so if there was support for a 1-click deploy to Heroku that would be a great developer experience.
Or maybe I am just asking something that is a bit-far fetched.
Thanks

**Comment by eldadfux** [comment] 2020-06-28 17:27
Actually we were just talking about working on something like this. @PedroCisnerosSantana do you have any updates on this or any estimated time table?

**Comment by PedroCisnerosSantana** [comment] 2020-06-29 12:32
Hey @eldadfux I started working on this some days ago and had some problems, still trying to solve them, will keep you up to date in Discord

**Comment by eldadfux** [comment] 2020-06-29 12:41
@PedroCisnerosSantana great, let me know if I can help.

**Comment by PedroCisnerosSantana** [comment] 2020-06-29 12:51
@eldadfux sure, I will contact you if not today, tomorrow :D

**Comment by BananaEgg** [comment] 2020-06-30 13:43
I'm also trying to deploy to Heroku,
I need to know what container is the front end so I can set the process type to web.

**Comment by eldadfux** [comment] 2020-06-30 13:50
@BananaEgg We use Traefik as the entrypoint on a "normal" setup: https://appwrite.io/docker-compose.yml

You can also try and use the Appwrite container on port 80 and 443. Traefik is mainly there for the auto-ssl certificates.

**Comment by BananaEgg** [comment] 2020-06-30 20:27
Iv'e deployed it following this: https://devcenter.heroku.com/articles/container-registry-and-runtime
meaning that i cloned Appwrite locally and created an app with it.
Now i'm getting this error " Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch"

I understand that the issue is because there's no option to bind with the environment variable port.
I found the format in their documentation: https://help.heroku.com/PPBPA231/how-do-i-use-the-port-environment-variable-in-container-based-apps

I'm quite new to dockers and I'm not sure how to implement it without braking anything else.
This is the current format " 
command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.file.directory=/storage/config
      - --providers.file.watch=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --accesslog=true
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
" 
This is what they are expecting - For example, instead of this:

PORT=8080
EXPOSE $PORT
CMD gunicorn --bind 0.0.0.0:$PORT wsgi

We ask that you do something like this:

CMD gunicorn --bind 0.0.0.0:$PORT wsg

**Comment by gkathir15** [comment] 2020-07-02 16:12
@BananaEgg has a different storage specification. ie files won't be retained after some time, it could also be the issue
refer https://devcenter.heroku.com/articles/active-storage-on-heroku,
not to sound negative, but if Apwrite can be deployed with features except storage working.

**Comment by TJMusiitwa** [comment] 2020-07-03 15:39
I am wondering and the thought has just come to me, if this by any chance is a little complex, is it instead possible to say use a Github Action that can be able to pull the docker image, build it then deploy it to the a service of one's choice?
This comes after all the research shows that there are already a number of actions that support docker and pushing images to say Heroku's image container registry.

I am fairly comfortable with Github Actions and will be willing to give this a shot

**Comment by PedroCisnerosSantana** [comment] 2020-07-03 16:18
> I am wondering and the thought has just come to me, if this by any chance is a little complex, is it instead possible to say use a Github Action that can be able to pull the docker image, build it then deploy it to the a service of one's choice?
> This comes after all the research shows that there are already a number of actions that support docker and pushing images to say Heroku's image container registry.
> 
> I am fairly comfortable with Github Actions and will be willing to give this a shot

It was the first thing I did, but the problem is the docker, that action will only get the dockerfile and do the stuff

**Comment by eldadfux** [comment] 2020-07-03 16:23
> I am wondering and the thought has just come to me, if this by any chance is a little complex, is it instead possible to say use a Github Action that can be able to pull the docker image, build it then deploy it to the a service of one's choice?
> This comes after all the research shows that there are already a number of actions that support docker and pushing images to say Heroku's image container registry.
> 
> I am fairly comfortable with Github Actions and will be willing to give this a shot

Can you please share some references to this GitHub actions?

**Comment by TJMusiitwa** [comment] 2020-07-03 16:34
So this action will deploy a docker image to [Heroku](https://github.com/marketplace/actions/deploy-docker-image-to-heroku-app)
Then among the various Github actions this is the one officially provided by the Docker [team ](https://github.com/marketplace/actions/build-and-push-docker-images)to build and push images,

This one sets up the[ Docker CLI](https://github.com/marketplace/actions/the-docker-cli) though I think it won't be needed since I [read ](https://www.docker.com/blog/first-docker-github-action-is-here/)that Github Actions already have some sort of Docker already installed on the backend as quoted below:

> GitHub Actions already leverages Docker in a lot of its workflows. From having Docker pre-installed and configured on the cloud runners to having first class support for containerized actions allows developers to easily use the same Docker workflows they use locally to configure their repo’s CI/CD. Combined with multi-stage builds and you have a powerful environment to work with. 



> 
> 
> > I am wondering and the thought has just come to me, if this by any chance is a little complex, is it instead possible to say use a Github Action that can be able to pull the docker image, build it then deploy it to the a service of one's choice?
> > This comes after all the research shows that there are already a number of actions that support docker and pushing images to say Heroku's image container registry.
> > I am fairly comfortable with Github Actions and will be willing to give this a shot
> 
> Can you please share some references to this GitHub actions?

**Comment by TJMusiitwa** [comment] 2020-07-03 16:37
@PedroCisnerosSantana 
> It was the first thing I did, but the problem is the docker, that action will only get the dockerfile and do the stuff

What do you mean it will only get the dockerfile maybe you didn't include the option to push the image or is there something I am missing out?

**Comment by TJMusiitwa** [comment] 2020-07-03 17:31
Which of the two is better, Using docker to pull the image from hub docker then running the actions to build then push to Heroku, or forking the repo and deploying using the Dockerfile and then just using an action to keep the fork up-to-date with the upstream?

**Comment by eldadfux** [comment] 2020-07-03 17:33
@TJMusiitwa, pulling from Docker Hub would probably be the better solution.

**Comment by TJMusiitwa** [comment] 2020-07-03 17:53
Well the problem now is how to pipe inputs for the config sections or auto accept the defaults in the cli?

**Comment by AugustasV** [comment] 2020-10-17 10:17
I would like to try to sort it out how to do this!

**Comment by orestesgaolin** [comment] 2020-12-15 20:50
Also waiting for the ability to deploy to heroku :)

**Comment by me-abhishekpal** [comment] 2021-02-16 15:14
Waiting for this to happen for a long time, Appreciate the hard work of the developers. Cheers!

**Comment by doricci** [comment] 2021-05-13 13:24
Also waiting for this feature, any idea of the remaning work to have this feature ready?  

Thank you very much for all the people working on this feature and on appwrite! :)

**Comment by doricci** [comment] 2021-09-23 13:38
@eldadfux any news on this?
If it's dead, I can try to have a look when I'll have some time.

**Comment by Brendan-H** [comment] 2021-12-05 01:04
@eldadfux any updates on this?

**Comment by MooseSaeed** [comment] 2022-04-13 14:35
Would be great if we could deploy on Heroku. Thanks for all the hard work!

**Comment by saswatmoo** [comment] 2022-06-09 09:28
everyone is waiting for this

**Comment by VittorioParagallo** [comment] 2022-07-09 16:27
today i tryed deploying on heroku with the following commands:

$ git clone https://github.com/appwrite/lite
$ cd lite
$ sudo heroku container:login
$ sudo heroku create
$ heroku container:push web
$ heroku container:release web
$ heroku open

the the browser opens and heroku tells "An error occurred in the application and your page could not be served."
so i checked the logs:
$ heroku logs --tail
2022-07-09T16:16:03.743932+00:00 app[api]: Release v1 created by user 
2022-07-09T16:16:03.743932+00:00 app[api]: Initial release by 
2022-07-09T16:16:03.897917+00:00 app[api]: Release v2 created by user 
2022-07-09T16:16:03.897917+00:00 app[api]: Enable Logplex by user 
2022-07-09T16:19:21.130563+00:00 app[api]: Release v3 created by user 
2022-07-09T16:19:21.130563+00:00 app[api]: Deployed web (xxxxxxxx) 
2022-07-09T16:19:21.148280+00:00 app[api]: Scaled to web@1:Free by user 
2022-07-09T16:19:27.775542+00:00 heroku[web.1]: Starting process with command `/usr/bin/supervisord -n -c /etc/supervisord.conf`
2022-07-09T16:19:28.792328+00:00 app[web.1]: Error: Can't drop privilege as nonroot user
2022-07-09T16:19:28.792351+00:00 app[web.1]: For help, use /usr/bin/supervisord -h
2022-07-09T16:19:28.973447+00:00 heroku[web.1]: Process exited with status 2
2022-07-09T16:19:29.153900+00:00 heroku[web.1]: State changed from starting to crashed
2022-07-09T16:19:29.157513+00:00 heroku[web.1]: State changed from crashed to starting
2022-07-09T16:19:36.496017+00:00 heroku[web.1]: Starting process with command `/usr/bin/supervisord -n -c /etc/supervisord.conf`
2022-07-09T16:19:38.049592+00:00 app[web.1]: Error: Can't drop privilege as nonroot user
2022-07-09T16:19:38.049600+00:00 app[web.1]: For help, use /usr/bin/supervisord -h
2022-07-09T16:19:38.196599+00:00 heroku[web.1]: Process exited with status 2
2022-07-09T16:19:38.266366+00:00 heroku[web.1]: State changed from starting to crashed
2022-07-09T16:19:46.287683+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=hidden-wildwood-xyz.herokuapp.com request_id=xxxxxx fwd="yyyyyy" dyno= connect= service= status=503 bytes= protocol=https
2022-07-09T16:19:46.675376+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=hidden-wildwood-aaasss.herokuapp.com request_id=axxxyyyzz fwd="casferwerv" dyno= connect= service= status=503 bytes= protocol=https

What does it mean? does anyone knows what to do?

**Comment by stnguyen90** [comment] 2022-07-09 16:36
> $ git clone https://github.com/appwrite/lite

@VittorioParagallo, unfortunately, Appwrite lite is quite out of date and may not work at it's current state. In addition, Appwrite does not work on heroku due to data persistence and access to the docker socket.

**Comment by himanshu-khare** [comment] 2022-07-09 18:50
> > $ git clone https://github.com/appwrite/lite
> 
> @VittorioParagallo, unfortunately, Appwrite lite is quite out of date and may not work at it's current state. In addition, Appwrite does not work on heroku due to data persistence and access to the docker socket.

Any other alternative to Droplet for appwrite?

**Comment by stnguyen90** [comment] 2022-07-09 19:20
> Any other alternative to Droplet for appwrite?

@himanshu-khare you can use any VPS provider including AWS EC2, Azure VMs, Google Compute Engine, and Oracle Cloud Compute VMs.

**Comment by neiljaywarner** [comment] 2022-10-11 17:25
@himanshu-khare  what is the downside to droplet?  it has $4/month droplet and $200 credit, but the billing structure does seem confusing. obviously a free-for-experimenting via heroku or something "really" free would be great.

**Comment by stnguyen90** [comment] 2022-10-11 19:00
@neiljaywarner, if you're looking for something to experiment on, I would suggest our [integration with gitpod](https://github.com/appwrite/integration-for-gitpod).

**Comment by stnguyen90** [comment] 2023-09-22 16:43
@W4nn4Die, are you still working on this? FYI, I'll need to unassign you soon due to inactivity.

**Comment by W4nn4Die** [comment] 2023-09-22 22:47
Hello,Sorry for the delay, I’m no longer working on this, you can reassign this.Regards.PedroEnviado desde mi iPhoneEl 22 sept 2023, a las 18:43, Steven Nguyen ***@***.***> escribió:﻿
@W4nn4Die, are you still working on this? FYI, I'll need to unassign you soon due to inactivity.

**Comment by daohoangson** [comment] 2023-10-07 03:15
Can you assign this to me @stnguyen90?

**Comment by opiredev** [comment] 2024-05-02 16:32
@nabby27 created a $50.00 reward using [Opire](https://opire.dev) 
 <details><summary>How to earn this reward?</summary>

Since this project does not have Opire bot installed yet 😞 you need to go to [Opire](https://app.opire.dev) and claim the rewards through your programmer's dashboard once you have your PR ready 💪</details>

**Comment by eldadfux** [comment] 2024-10-25 19:19
Due to the fact Heroku shutdown their free tier and since there is some limited edition contributed by @daohoangson I am closing this issue as this is not a priority anymore.

More free options for self-hosting Appwrite are available at https://appwrite.io/docs/advanced/self-hosting#one-click-setups

**Closed by eldadfux** 2024-10-25 19:19 UTC
Labels: enhancement, help wanted
