### ISSUE TITLE
🐛 Bug Report: Appwrite freezes randomly on function execution

### ISSUE THREAD

**Issue by netapy** [appwrite/appwrite#4626] opened 2022-11-02 16:55 UTC
### 👟 Reproduction steps

I have an Appwrite server on decent hardware (2 core CPU and 4 gigs of RAM).
There are many collections in my database and I use functions to retrieve and edit data before sending it to the client — functions are called very often.

I still haven’t figured out why/when exactly but at some point the server doesn’t serve functions, I can requests accumulating on the functions logs : 
(this get_feed function only queries data, compacts it and send it back to the client)
![IMG_0416](https://user-images.githubusercontent.com/39877685/199547997-0a6997ce-cd16-446e-9313-73fd0f4a3ae3.jpeg)

At first the backend interface is still responsive but at some point other functions freeze and i’m unable to load pages or query anything.

The appwrite doctor doesn’t show any issues : 
![IMG_0417](https://user-images.githubusercontent.com/39877685/199550015-bbd251db-1646-4bff-8532-bea55543c59c.jpeg)

Thanks 

### 👍 Expected behavior

It should not crash as the functions don’t require a lot of memory, and runs without any issues during my stress tests. 

### 👎 Actual Behavior

Appwrite freezes for a while and then comes back after 15-20 minutes.

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Only pure Appwrite is running on the server.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2022-11-02 16:57
@netapy thanks for raising this issue! 🙏🏼 Would you please provide the executor logs and check `docker ps -a` to see if the runtime container is still running? If it is, the logs from the runtime container can be helpful too.

**Comment by netapy** [comment] 2022-11-02 17:01
Sure, as of writing this message the issue is ongoing and this is the log : 
```
TAINER ID   IMAGE                        COMMAND                  CREATED          STATUS                  PORTS                                                                      NAMES
c7140174e711   openruntimes/python:v2-3.9   "/usr/local/src/star…"   17 minutes ago   Up 17 minutes           3000/tcp                                                                   62e0fcfca3b3c5124f16-633d37fa36cb75b79045
af36e0d71f8e   openruntimes/python:v2-3.9   "/usr/local/src/star…"   39 minutes ago   Up 39 minutes           3000/tcp                                                                   62e0fcfca3b3c5124f16-634d2fe7204a7c470294
8150a559904b   openruntimes/python:v2-3.9   "/usr/local/src/star…"   4 hours ago      Up 4 hours              3000/tcp                                                                   62e0fcfca3b3c5124f16-6347cbfd4d6a53ef838e
f513055af40d   appwrite/appwrite:1.0.3      "worker-functions"       4 hours ago      Up 4 hours              80/tcp                                                                     appwrite-worker-functions
1a3d67b1302a   traefik:2.7                  "/entrypoint.sh --pr…"   4 hours ago      Up 4 hours              0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   appwrite-traefik
49db3fb1a079   appwrite/appwrite:1.0.3      "executor"               4 hours ago      Up 4 hours              80/tcp                                                                     appwrite-executor
ada529598a25   appwrite/appwrite:1.0.3      "realtime"               4 hours ago      Up 4 hours              80/tcp                                                                     appwrite-realtime
cf3ba23161dc   appwrite/appwrite:1.0.3      "maintenance"            4 hours ago      Up 4 hours              80/tcp                                                                     appwrite-maintenance
f2efb28da48b   appwrite/appwrite:1.0.3      "worker-webhooks"        4 hours ago      Up 4 hours              80/tcp                                                                     appwrite-worker-webhooks
1a5f0181a33a   appwrite/appwrite:1.0.3      "worker-databases"       4 hours ago      Up 4 hours              80/tcp                                                                     appwrite-worker-databases
d2ec773125d8   appwrite/appwrite:1.0.3      "worker-mails"           4 hours ago      Up 4 hours              80/tcp                                                                     appwrite-worker-mails
2f219a79b78b   appwrite/appwrite:1.0.3      "worker-builds"          4 hours ago      Up 4 hours              80/tcp                                                                     appwrite-worker-builds
c1c41ef43feb   appwrite/appwrite:1.0.3      "schedule"               4 hours ago      Up 4 hours              80/tcp                                                                     appwrite-schedule
bdd9ea078789   appwrite/appwrite:1.0.3      "worker-certificates"    4 hours ago      Up 4 hours              80/tcp                                                                     appwrite-worker-certificates
7629d292ce88   appwrite/appwrite:1.0.3      "worker-deletes"         4 hours ago      Up 4 hours              80/tcp                                                                     appwrite-worker-deletes
b1e21b3fa110   appwrite/appwrite:1.0.3      "worker-audits"          4 hours ago      Up 4 hours              80/tcp                                                                     appwrite-worker-audits
b2c5a6652e70   appwrite/appwrite:1.0.3      "usage --type=timese…"   4 hours ago      Up 4 hours              80/tcp                                                                     appwrite-usage-timeseries
254e19f06e4b   appwrite/appwrite:1.0.3      "usage --type=databa…"   4 hours ago      Up 4 hours              80/tcp                                                                     appwrite-usage-database
43dbf896b882   appwrite/appwrite:1.0.3      "docker-php-entrypoi…"   4 hours ago      Up 4 hours              80/tcp                                                                     appwrite
a8709093f11a   appwrite/appwrite:1.0.3      "worker-messaging"       4 hours ago      Up 4 hours              80/tcp                                                                     appwrite-worker-messaging
5e8a0ec85c12   redis:7.0.4-alpine           "docker-entrypoint.s…"   4 hours ago      Up 4 hours              6379/tcp                                                                   appwrite-redis
c1ff63fd3336   mariadb:10.7                 "docker-entrypoint.s…"   4 hours ago      Up 4 hours              3306/tcp                                                                   appwrite-mariadb
16bb528d243a   appwrite/influxdb:1.5.0      "/entrypoint.sh infl…"   4 hours ago      Up 4 hours              8086/tcp                                                                   appwrite-influxdb
96701ceb4b35   appwrite/telegraf:1.4.0      "/entrypoint.sh tele…"   4 hours ago      Up 4 hours              8092/udp, 8125/udp, 8094/tcp                                               appwrite-telegraf
dc8df12ede3b   hello-world                  "/hello"                 5 days ago       Exited (0) 5 days ago                                                                              cranky_kepler

```

**Comment by netapy** [comment] 2022-11-02 17:04
And this is the executor log : 
```
Function executed in 0.11850380897522 seconds, status: completed
Executing Runtime: 62e0fcfca3b3c5124f16-6347cbfd4d6a53ef838e
Function executed in 0.044380903244019 seconds, status: completed
Executing Runtime: 62e0fcfca3b3c5124f16-6347cbfd4d6a53ef838e
Function executed in 0.11296200752258 seconds, status: completed
Executing Runtime: 62e0fcfca3b3c5124f16-6347cbfd4d6a53ef838e
Function executed in 0.035964012145996 seconds, status: completed
[Error] Type: Exception
[Error] Message: Runtime not found. Please create the runtime.
[Error] File: /usr/src/code/app/executor.php
[Error] Line: 469
Building container : 62e0fcfca3b3c5124f16-633d37fa36cb75b79045
Build Stage completed in 1 seconds
Executing Runtime: 62e0fcfca3b3c5124f16-633d37fa36cb75b79045
[Error] Type: Exception
[Error] Message: An internal curl error has occurred within the executor! Error Msg: Connection refused
[Error] File: /usr/src/code/app/executor.php
[Error] Line: 541
Executing Runtime: 62e0fcfca3b3c5124f16-633d37fa36cb75b79045
Executing Runtime: 62e0fcfca3b3c5124f16-6347cbfd4d6a53ef838e
Function executed in 0.12101793289185 seconds, status: completed
Executing Runtime: 62e0fcfca3b3c5124f16-6347cbfd4d6a53ef838e
Function executed in 0.04660701751709 seconds, status: completed
Executing Runtime: 62e0fcfca3b3c5124f16-6347cbfd4d6a53ef838e
Function executed in 0.11787605285645 seconds, status: completed
Executing Runtime: 62e0fcfca3b3c5124f16-6347cbfd4d6a53ef838e
Function executed in 0.040542840957642 seconds, status: completed
[Error] Type: Exception
[Error] Message: An internal curl error has occurred within the executor! Error Msg: Operation timed out
[Error] File: /usr/src/code/app/executor.php
[Error] Line: 544
Executing Runtime: 62e0fcfca3b3c5124f16-6347cbfd4d6a53ef838e
Executing Runtime: 62e0fcfca3b3c5124f16-6347cbfd4d6a53ef838e
Function executed in 0.18129801750183 seconds, status: completed
Executing Runtime: 62e0fcfca3b3c5124f16-6347cbfd4d6a53ef838e
Executing Runtime: 62e0fcfca3b3c5124f16-6347cbfd4d6a53ef838e
Function executed in 0.22170782089233 seconds, status: completed
Executing Runtime: 62e0fcfca3b3c5124f16-6347cbfd4d6a53ef838e
Function executed in 0.088666915893555 seconds, status: completed
Function executed in 0.26568603515625 seconds, status: completed
Executing Runtime: 62e0fcfca3b3c5124f16-6347cbfd4d6a53ef838e
Function executed in 0.18561196327209 seconds, status: complet
```

**Comment by stnguyen90** [comment] 2022-11-02 17:15
@netapy, `docker logs <container name or id>`. The container should be named `<project id>-<deployment id>`. Are these for when the function was frozen? What was the deployment ID for the frozen function?

**Comment by netapy** [comment] 2022-11-02 17:27
Yes these logs were taken when the function was frozen.

It’s weird my containers are able to display logs, except for the two python openruntimes containers.
![IMG_0422](https://user-images.githubusercontent.com/39877685/199559174-d8c24189-8c2a-4693-9df2-d387f5ac8e01.jpeg)

**Comment by stnguyen90** [comment] 2022-11-02 17:55
@netapy, which deployment ID is the frozen one?

**Comment by netapy** [comment] 2022-11-02 18:00
> @netapy, which deployment ID is the frozen one?

Usually the one ending with 838e freezes first, but then the freeze generalizes to the whole appwrite application. 
Also it recovers by itself after 15-20 minutes.

**Comment by stnguyen90** [comment] 2022-11-02 18:13
@netapy is this `get_feed` function being executing asynchronously or synchronously?

**Comment by netapy** [comment] 2022-11-02 18:37
> @netapy is this `get_feed` function being executing asynchronously or synchronously?

“get_feed” is launched synchronously, as are all my functions.

**Comment by Shiba-Kar** [comment] 2022-11-03 12:12
`Message: An internal curl error has occurred within the executor! Error Msg: Operation timed out`
check your `variables` for the function `APPWRITE_FUNCTION_ENDPOINT`  ``http://<domain>.com/v1``  you must have forgotten `v1`

**Comment by netapy** [comment] 2022-11-03 14:12
> `Message: An internal curl error has occurred within the executor! Error Msg: Operation timed out`
> check your `variables` for the function `APPWRITE_FUNCTION_ENDPOINT` `http://<domain>.com/v1` you must have forgotten `v1`

Thanks for your answer. Unfortunately I re-checked my code and it includes the right variables — my functions run correctly until some point in time (which I haven’t determined yet).


Not sure if this helps but when I `docker compose down` it seems that my `appwrite_runtimes` container has trouble shutting down. Logs below :

```
$ sudo docker compose down 
[+] Running 23/24
 ⠿ Container appwrite-worker-certificates  Removed                                                                                                           11.8s
 ⠿ Container appwrite-worker-deletes       Removed                                                                                                           11.7s
 ⠿ Container appwrite-usage-timeseries     Removed                                                                                                           11.1s
 ⠿ Container appwrite-realtime             Removed                                                                                                           11.2s
 ⠿ Container appwrite-worker-builds        Removed                                                                                                           11.7s
 ⠿ Container appwrite-maintenance          Removed                                                                                                           11.7s
 ⠿ Container appwrite-worker-mails         Removed                                                                                                           11.8s
 ⠿ Container appwrite-schedule             Removed                                                                                                           10.5s
 ⠿ Container appwrite-worker-audits        Removed                                                                                                           11.5s
 ⠿ Container appwrite-worker-messaging     Removed                                                                                                           11.2s
 ⠿ Container appwrite-usage-database       Removed                                                                                                           11.8s
 ⠿ Container appwrite-worker-databases     Removed                                                                                                           11.2s
 ⠿ Container appwrite-traefik              Removed                                                                                                            0.7s
 ⠿ Container appwrite-worker-webhooks      Removed                                                                                                           11.4s
 ⠿ Container appwrite-telegraf             Removed                                                                                                            0.4s
 ⠿ Container appwrite-worker-functions     Removed                                                                                                           11.8s
 ⠿ Container appwrite-executor             Removed                                                                                                           10.3s
 ⠿ Container appwrite                      Removed                                                                                                            0.2s
 ⠿ Container appwrite-mariadb              Removed                                                                                                            0.5s
 ⠿ Container appwrite-redis                Removed                                                                                                            1.1s
 ⠿ Container appwrite-influxdb             Removed                                                                                                            0.2s
 ⠿ Network appwrite_appwrite               Removed                                                                                                            0.1s
 ⠿ Network appwrite_gateway                Removed                                                                                                            0.2s
 ⠿ Network appwrite_runtimes               Error                                                                                                              0.0s
failed to remove network appwrite_runtimes: Error response from daemon: error while removing network: network appwrite_runtimes id a066910e107af1054e6f805b6397f09791183321b302fda52005b78b3d22b565 has active endpoints
```

**Comment by Shiba-Kar** [comment] 2022-11-03 15:54
`docker kill appwrite_runtimes`

**Comment by Shiba-Kar** [comment] 2022-11-03 16:00
> > `Message: An internal curl error has occurred within the executor! Error Msg: Operation timed out`
> > check your `variables` for the function `APPWRITE_FUNCTION_ENDPOINT` `http://<domain>.com/v1` you must have forgotten `v1`
> 
> Thanks for your answer. Unfortunately I re-checked my code and it includes the right variables — my functions run correctly until some point in time (which I haven’t determined yet).
> 
> Not sure if this helps but when I `docker compose down` it seems that my `appwrite_runtimes` container has trouble shutting down. Logs below :
> 
> ```
> $ sudo docker compose down 
> [+] Running 23/24
>  ⠿ Container appwrite-worker-certificates  Removed                                                                                                           11.8s
>  ⠿ Container appwrite-worker-deletes       Removed                                                                                                           11.7s
>  ⠿ Container appwrite-usage-timeseries     Removed                                                                                                           11.1s
>  ⠿ Container appwrite-realtime             Removed                                                                                                           11.2s
>  ⠿ Container appwrite-worker-builds        Removed                                                                                                           11.7s
>  ⠿ Container appwrite-maintenance          Removed                                                                                                           11.7s
>  ⠿ Container appwrite-worker-mails         Removed                                                                                                           11.8s
>  ⠿ Container appwrite-schedule             Removed                                                                                                           10.5s
>  ⠿ Container appwrite-worker-audits        Removed                                                                                                           11.5s
>  ⠿ Container appwrite-worker-messaging     Removed                                                                                                           11.2s
>  ⠿ Container appwrite-usage-database       Removed                                                                                                           11.8s
>  ⠿ Container appwrite-worker-databases     Removed                                                                                                           11.2s
>  ⠿ Container appwrite-traefik              Removed                                                                                                            0.7s
>  ⠿ Container appwrite-worker-webhooks      Removed                                                                                                           11.4s
>  ⠿ Container appwrite-telegraf             Removed                                                                                                            0.4s
>  ⠿ Container appwrite-worker-functions     Removed                                                                                                           11.8s
>  ⠿ Container appwrite-executor             Removed                                                                                                           10.3s
>  ⠿ Container appwrite                      Removed                                                                                                            0.2s
>  ⠿ Container appwrite-mariadb              Removed                                                                                                            0.5s
>  ⠿ Container appwrite-redis                Removed                                                                                                            1.1s
>  ⠿ Container appwrite-influxdb             Removed                                                                                                            0.2s
>  ⠿ Network appwrite_appwrite               Removed                                                                                                            0.1s
>  ⠿ Network appwrite_gateway                Removed                                                                                                            0.2s
>  ⠿ Network appwrite_runtimes               Error                                                                                                              0.0s
> failed to remove network appwrite_runtimes: Error response from daemon: error while removing network: network appwrite_runtimes id a066910e107af1054e6f805b6397f09791183321b302fda52005b78b3d22b565 has active endpoints
> ```

![image](https://user-images.githubusercontent.com/24454722/199771549-a33102f8-b4e8-4c77-9e5d-c542c04a96b0.png)

**Comment by stnguyen90** [comment] 2022-11-03 16:22
@netapy, can you check the stats (`docker stats`) to see if the runtime container is still doing anything? The Open Runtime server itself is a pretty [simple flask app](https://github.com/open-runtimes/open-runtimes/blob/main/runtimes/python-3.10/server.py). I don't see how/why it would become unresponsive...

**Comment by netapy** [comment] 2022-11-05 10:02
**Update :** 
I can't reproduce this bug anymore and I have a theory on how I fixed it.
The issue started occurring about a week after I migrated my Appwrite app on a new VPS, using [this method](https://gist.github.com/Evgentret/5a04f59c99371b63c1fc5dfd74920a4f).

I started the backup right after using `docker compose down` and removing the appwrite folder.

As I mentioned previously : 
> Not sure if this helps but when I `docker compose down` it seems that my `appwrite_runtimes` container has trouble shutting down. Logs below :
> ```
> [...]
> failed to remove network appwrite_runtimes: Error response from daemon: error while removing network: network appwrite_runtimes id a066910e107af1054e6f805b6397f09791183321b302fda52005b78b3d22b565 has active endpoints
> ```
So _appwrite_runtimes_ was still running when I backed the server up.

So I re-did a backup of my Appwrite app and made sure that no containers were running.
I restored it, and now I can't reproduce the error.

I'm not really sure though,  maybe it will happen after a week or so as it did before. I'll keep you updated.

**Comment by netapy** [comment] 2022-11-10 17:08
**Update 2 :** 
Sorry about that, but the problem occurred again. Not sure if the functions are at fault, it just stopped for 5 minutes and then went back up.
Could it be just a matter of specs ? Is 2 core CPU and 4 gigs of RAM barely enough ?
For now it's just me and someone else on the server so it should be able to handle our little activity.

Also I noticed everytime it crashes, a mail is sent to demo@example.com (through my gmail smtp) :
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/39877685/201160054-82bbc88a-8873-4eeb-9150-8d96889f36bb.png">

**Comment by stnguyen90** [comment] 2022-11-10 17:46
@netapy,

While it's down, it would be helpful to check `docker stats` to see if any containers are running harder than it should. Looking at logs for anomalies could be helpful too.

> Could it be just a matter of specs ? Is 2 core CPU and 4 gigs of RAM barely enough ?

That should be enough for a couple of people with a little activity.

> Also I noticed everytime it crashes, a mail is sent to [demo@example.com](mailto:demo@example.com) (through my gmail smtp) :

The only place I see that is in the doctor:

https://github.com/appwrite/appwrite/blob/02a432102df047d2ea96faed65d77a862239d487/app/tasks/doctor.php#L139

Are you running the doctor command? Can you check the mail worker logs to see what that email actually is? Do you have that email defined anywhere?

**Comment by netapy** [comment] 2022-11-11 17:05
Thank you for your answer and patience @stnguyen90.
So today the problem occurred again when launching a function (4 runtimes open at the same time).

Here is the  `docker stats`, nothing seems overwhelmed : 
![IMG_0462](https://user-images.githubusercontent.com/39877685/201391794-99e9f354-b3fb-4989-95d8-b65001883b6b.jpeg)

Now it’s been 10 minutes and the server isn’t up yet.

My functions containers still don’t have any logs, except one for which I used « set_self_signed(True) », which I just fixed (not sure if it will make a difference in the future).

**Comment by netapy** [comment] 2022-11-11 17:47
Okay I think I know what precise steps before a crash (doesn’t always work but most of the time).
1. I log in to the app with Google Auto
2. I go on my user profile (it calls a function that grabs data made by the user on multiple tables and compacts them in a json)
3. I go back to the main feed (which also calls a function that queries the content database and returns some documents)
That second function (point 3) sometimes never gets an answer and then everything is just frozen (even the appwrite console)

**Comment by stnguyen90** [comment] 2022-11-11 21:01
@netapy could there be an infinite loop somewhere in your function code?

**Comment by netapy** [comment] 2022-11-12 08:21
> @netapy could there be an infinite loop somewhere in your function code ?

No, it really is just queries to the database with ~4 attributes lookup per queries. No `while` or `for` loops.

**Comment by netapy** [comment] 2022-11-12 11:38
Okay @stnguyen90 I think I've got something interesting.
Tried backing up the data and making a full reinstall but the problem occured 30 minutes after.

And as I inspected the logs of my running 3 python containers : 
- 2 of them didn't have any logs
- the third one had this : 
<img width="709" alt="image" src="https://user-images.githubusercontent.com/39877685/201472063-cb9dcb7a-2fd8-4c49-a437-55f9c41ebc97.png">

And as soon as I stopped that container, the appwrite console started working back again-- except for the functions which showed at each call `An internal curl error has occurred within the executor! Error Msg: Could not resolve host: 62e0fcfca3b3c5124f16-636f7fadce5adc8e4aba` (because of the fact that the container was killed I believe)

**Comment by stnguyen90** [comment] 2022-11-12 15:53
@netapy what's on line 23 of that function?

**Comment by netapy** [comment] 2022-11-13 10:38
> @netapy what's on line 23 of that function?

<img width="764" alt="image" src="https://user-images.githubusercontent.com/39877685/201517355-2e7e0f16-aa49-4883-855d-e85cee64aaf1.png">

I parse the payload (there always is a payload following the same format).

Also on the next line I read the user_id that called the function.
The function may be called by anyone, which makes this value an empty string in my experience.

**Comment by stnguyen90** [comment] 2022-11-13 15:37
@netapy 

> I parse the payload (there always is a payload following the same format).

just in case, make sure to add try/except so you catch all exceptions and call `res.json` or `res.send` at least once before the function exits.

> The function may be called by anyone, which makes this value an empty string in my experience.

That's weird...it shouldn't be blank if it's executed by a user...

**Comment by netapy** [comment] 2022-11-13 15:50
@stnguyen90 
> just in case, make sure to add try/except so you catch all exceptions and call res.json or res.send at least once before the function exits.

Alright I will do that.

> That's weird...it shouldn't be blank if it's executed by a user...

I'm sorry I meant that it's an empty string when an unregistered user calls the function, someone unknown by the system (which makes perfect sense).

**Comment by redarflap** [comment] 2022-11-18 11:46
I just wanted to ditch in to say, that I am having exactly the same kinds of issues.
I'm using the Dart-2.17 runtime, Appwrite 1.0.3

Some things that i noticed:
- Even a very simple function with just a few static queries on the DB, that worked 100 times could fail from time to time, however it mostly happens when executing a bit more complex functions with some queries nested in loops.
- After that, it is likely that the function fails again multiple times, taking some time to recover, maybe until the openruntime container is destroyed, not sure about that.
- The log of the affected openruntime container is always empty
- The only thing i get is the feared "Operation timed out" exception. All my functions are wrapped in try/catch where i return a generic error message, but that doesn't help at all. The functions still time out, and i never get to see my error message.
- I'm only developing yet, so the server has no load at all.

I am currently in the process of setting up appwrite on my development machine, in the hope that having more than one CPU core would fix those problems.

**Comment by redarflap** [comment] 2022-12-04 01:57
@netapy 
Are you by any chance running a docker version installed through snapd on Ubuntu?

After lots of testing, i noticed, that the functions are far less likely to get stuck on my Docker Desktop Windows environment.
So I tested different things and finally I replaced the snapd version with the version from the official Docker repo, while copying all my volumes over and it seems much more stable now.
When spamming a simple function 10.000 times (10 parallel), it still fails between 0-50 times. But it seems that now at least it takes much more effort to pull down the whole system.


I'm running Ubuntu 22.04 LTS in a VM with 4 cores/4Gb.
Before: Docker installed via OS installer (20.10.17)
Now: Docker installed using Docker repo (20.10.21)


Some other interesting things that i noticed.. 
I got two functions
- testFunction, that creates one simple document in the DB  (called 10.000 times)
- monitoring function which gets health data and collection info every 30 seconds

1.) When spamming the testFunction too hard (like 20 in parallel), often it is the monitoring function that gets completely stuck, and fails to recover indefinitely, while the testFunction is still able to create Documents.
Only after starting the test-procedure again (or occasionally even after refreshing the web console) the monitoring function suddenly starts working again.

2.) Functions that don't access the appwrite API don't seem to be affected by those problems at all.

So to me it seems like the problem (at least in my case) lies somewhere between the runtime container and the appwrite API, which causes it to randomly get stuck if stressed too much. And it recovers most of the time, but not always. Also it can still work for one function, but not for another one.

**Comment by redarflap** [comment] 2022-12-04 15:49
Another thing i noticed just now:
Increasing _APP_WORKER_PER_CORE also seems to help quite a lot to get rid of this.

**Comment by netapy** [comment] 2022-12-05 12:01
@redarflap thanks for your input.
Yes I am running my server on Ubuntu 22.04LTS, but my Docker always was from the official repository..

I have found that when I decreased the `function timeout` somewhere between 5-10 seconds, my server would not crash anymore, only the function(s).

I tried out the solution with the `_APP_WORKER_PER_CORE ` but it doesn't seem to fix it, I still get random functions that don't launch, rendering the following error :  `An internal curl error has occurred within the executor! Error Msg: Operation timed out` 

On the logs of the executor container, I get the following : 
```
Executing Runtime: 62e0fcfca3b3c5124f16-638dd2d795d639e0cacd
[Error] Type: Exception
[Error] Message: An internal curl error has occurred within the executor! Error Msg: Operation timed out
[Error] File: /usr/src/code/app/executor.php
[Error] Line: 544
```
Are your error logs on the Appwrite executor the same as mine ? 

I also noticed that only the functions that work with the Appwrite API get this kind of error/freeze.
I tried rewriting my functions in Node JS (previously Python) but that doesn't change a thing.

A similar issue is opened I believe : #2940

**Comment by TheDarkX** [comment] 2023-01-03 15:52
![image](https://user-images.githubusercontent.com/7087449/210386110-5c99d2b6-4add-4355-9d89-6566ca32c08d.png)

Intermittent.
Appwrite version: v:0.15.2.402
No logs from runtime container

docker compose logs appwrite-executor
![image](https://user-images.githubusercontent.com/7087449/210386899-4e412448-76e2-427d-b978-85e154c9af34.png)

Based on users above commented, looks like this is still occurring on latest version.
Upgrading my Appwrite version to latest might have minor chances being fixed.
but I'll try.

This is a function that aggregate and generate an end day report which have dozen of loops.

![image](https://user-images.githubusercontent.com/7087449/210391431-7a9384ca-4896-4f68-b705-e78e8406db14.png)

Noticed that after continuous 4-5 execution in a row, the function failed to perform and resulted Operation Timed Out error.
Also checked the x-ratelimit-limit  = 60 & x-ratelimit-remaining = 54, nothing seems related to rate limit.

@eldadfux apologize for the ping.

Appwrite Cloud Function is a crucial feature. 
Hope someone look into this seriously.
I will deep dig the mentioned .php line error when leisure.

**Comment by stnguyen90** [comment] 2023-01-06 21:32
@TheDarkX, I tried creating dozens of executions of:

```javascript
const sdk = require("node-appwrite");

function sleep(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

module.exports = async function (req, res) {
  const client = new sdk.Client();

  if (
    !req.variables['APPWRITE_FUNCTION_ENDPOINT'] ||
    !req.variables['APPWRITE_FUNCTION_API_KEY']
  ) {
    console.warn("Environment variables are not set. Function cannot use Appwrite SDK.");
  } else {
    client
      .setEndpoint(req.variables['APPWRITE_FUNCTION_ENDPOINT'])
      .setProject(req.variables['APPWRITE_FUNCTION_PROJECT_ID'])
      .setKey(req.variables['APPWRITE_FUNCTION_API_KEY'])
      .setSelfSigned(true);
  }

  await sleep(200);

  res.json({
    areDevelopersAwesome: true,
  });
};
```

but they all executed fine:

![image](https://user-images.githubusercontent.com/1477010/211103063-11c260f8-454a-4eeb-aaff-e3f0b94bdb1f.png)

Is there some promise in your code that isn't resolving? Perhaps you could try adding `console.stdlog()` (yes, `stdlog`) and check the runtime container logs?

**Comment by garvitomer** [comment] 2023-02-02 15:32
Hi,

I am facing the same issue in production now. Is there any temporary work around for this?

**Comment by stnguyen90** [comment] 2023-05-12 14:50
> > just in case, make sure to add try/except so you catch all exceptions and call res.json or res.send at least once before the function exits.
> 
> Alright I will do that.

@netapy, are you still experiencing the problem after adding the try/except?

**Comment by netapy** [comment] 2023-05-15 10:29
> @netapy, are you still experiencing the problem after adding the try/except?

@stnguyen90 
Should have came back to share it but it seems that I kind of solved my problem by setting the `_APP_FUNCTIONS_INACTIVE_THRESHOLD` appwrite env variable to a month or so.

The constant restart of the function apparently caused the crashes.
Not sure about it though but it seems more stable since then.

**Comment by pomarec** [comment] 2023-05-24 08:12
It does not look like an issue you should close to me. Is there a fix I missed ?

FYI, we had to completely switch to a docker based node backend to satisfy our client as the cloud functions were not reliable.
Tweaking _APP_FUNCTIONS_INACTIVE_THRESHOLD might be a workaround but it also has its reason to exist and to be used.

**Comment by byawitz** [comment] 2023-05-31 14:58
Hey @ stnguyen90, I found a way to reproduce and I think maybe there is a solution to overcome it. 
Is there any option to reopen the issue and get it reassigned? 

Thanks

**Comment by dokind** [comment] 2023-11-02 10:29
_APP_FUNCTIONS_INACTIVE_THRESHOLD  to how much ?

**Comment by stnguyen90** [comment] 2024-08-21 16:40
Will use https://github.com/appwrite/appwrite/issues/4626 to track this.

**Closed by stnguyen90** 2024-08-21 16:40 UTC
Labels: bug, product / functions
