### ISSUE TITLE
📚 Documentation: Version selection and indicator

### ISSUE THREAD

**Issue by renzos42** [appwrite/appwrite#8713] opened 2024-09-23 08:14 UTC
### 💭 Description

I would greatly appreciate a version selection dropdown in the docs page. With breaking releases like 1.6.0, not everyone can jump ship directly. Not being able to 'trust' the docs now is a pretty big inconvenience.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by renzos42** [comment] 2024-09-23 14:00
Exactly! But this but the docs itself,  not for the API reference. The API reference does not 100% overlap with the information given in the documentation.

**Comment by stnguyen90** [comment] 2024-09-23 23:59
@renzos42, thanks for creating this issue! 🙏🏼 I'm going to close this as a duplicate of https://github.com/appwrite/website/issues/730. I suggest you add a 👍🏼 on that issue.

**Closed by stnguyen90** 2024-09-23 23:59 UTC
