### ISSUE TITLE
🚀 Enhancement: Allow data only push notification on Appwrite Massaging 

### ISSUE THREAD

**Issue by leonelamatos** [appwrite/appwrite#8665] opened 2024-09-14 18:21 UTC
### 🔖 Enhancement description

 An data only option to allow the notification received by the app to handle the notification by a 3rd party notification package. 

### 🎤 Pitch

Allowing data only push notification will allow for using a 3rd party notification package to handle the notification and not the default FCM push notification e.g. Notifee, react-native-notification

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by balachandarlinks** [comment] 2024-09-28 21:09
Duplicate of https://github.com/appwrite/appwrite/issues/8307

**Closed** 2024-10-25 19:26 UTC
Labels: duplicate, enhancement
