### ISSUE TITLE
📚 Documentation: Events documentation

### ISSUE THREAD

**Issue by seanhanck** [appwrite/appwrite#5226] opened 2023-03-14 19:30 UTC
### 💭 Description

For the event strings that are related to document level events, there is a missing '\*'. Current on https://appwrite.io/docs/events it has examples of:

databases.\*.collections.\*.documents.create
databases.\*.collections.\*.documents.update
databases.\*.collections.\*.documents.delete

using those values in appwrite.json and deploying results in functions not being triggered. When building the event criteria via the ui, an \* is added between "documents" and the event name, looks like the correct strings should be:

databases.\*.collections.\*.documents.\*.create
databases.\*.collections.\*.documents.\*.update
databases.\*.collections.\*.documents.\*.delete

Also....

The link in the "I have the Code of Conduct" checkbox leads to a 404 page, the one in the bubble to the right leads to the appropriate page

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-03-15 20:45
@seanhanck, thanks for creating this issue, but it looks like it's a duplicate of https://github.com/appwrite/appwrite/issues/3928. 

Ideally, issues should be focused rather than about multiple topics so feel free to create a separate issue for the code of conduct.

**Closed by stnguyen90** 2023-03-15 20:45 UTC
Labels: docs
