### ISSUE TITLE
🐛 Bug Report: Storage image preview incorrectly rotates image taken by camera

### ISSUE THREAD

**Issue by outrelouxhe** [appwrite/appwrite#2696] opened 2022-01-26 09:38 UTC
### 👟 Reproduction steps

When I take a picture with my phone (iPhone) and upload it to the storage, either with the console, either with the sdk method, the image returned by the PREVIEW link is incorrectly rotated. The image shown in the console under "File preview" is incorrectly rotate as well. On the other hand, the image returned by the VIEW or the DOWNLOAD link are correctly positioned. 

Note that this problem do not appear if upload an image found randomly on the internet.

### 👍 Expected behavior

The preview image should be rotated correctly as the view image is.

### 👎 Actual Behavior

The preview image is incorrectly rotated on images taken by a phone camera.

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 🧱 Your Environment

No

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment] 2022-01-26 09:50
Hey there 👋

In theory, we might be ignoring some meta-data, but it's hard for me to reproduce since my images are rotated correctly. Could you share a specific photo with us that causes trouble with you please? To prevent any data manipulation, it would be best if you shared the image with me directly through email. My email address is `matej@appwrite.io`.

**Comment by outrelouxhe** [comment] 2022-01-26 09:56
Hey Matej. I have sent you a picture by email.

**Comment by Meldiron** [comment] 2022-01-26 10:09
I received the file and am able to reproduce the problem. Looks like this is related to `EXIF Orientation` metadata. Looks like iPhone adds this rotation metadata instead of using CPU to actually rotate the image.

I will look into the Appwrite storage system and see how we could use this metadata for base rotation when generating the preview.

**Comment by Meldiron** [comment] 2022-01-26 10:38
I have implemented a fix to this issue in the Utopia Image library - a library maintained by the Appwrite team, and used by Appwrite: https://github.com/utopia-php/image/pull/19

Once the PR is merged, Appwrite should have the fix automatically ready.

**Comment by TorstenDittmann** [comment] 2022-03-03 13:14
We just released 0.13 and this should be fixed 👍🏻 

You can find the announcement [here](https://dev.to/appwrite/announcing-appwrite-013-with-major-upgrades-to-storage-and-functions-3hpf).

Thank you a lot for reporting this 🙏🏻

**Closed by TorstenDittmann** 2022-03-03 13:14 UTC
Labels: bug, waiting for release
