### ISSUE TITLE
🐛 Bug Report: Web SDK fails to disconnect when the unsubscribe function is returned

### ISSUE THREAD

**Issue by collinmyers** [appwrite/appwrite#7584] opened 2024-02-13 19:36 UTC
### 👟 Reproduction steps

![subscribe](https://github.com/appwrite/appwrite/assets/51715099/415d628a-7f34-4324-bdd6-21f679858a0a)

![useFocusEffect](https://github.com/appwrite/appwrite/assets/51715099/bc2ec11e-8dab-45d6-9570-83e45d193eee)
This occurs with both the useEffect and useFocusEffect hooks. Upon subscribing to the real-time event from the database, you receive a function within the logic to eventually unsubscribe. When navigating away from the page, the components in the return statement of the useEffect or useFocusEffect should execute. The function returned from the subscribe operation should disconnect the real-time connection.

### 👍 Expected behavior

Upon unmounting the component, the unsubscribe function should terminate the real-time connection.

### 👎 Actual Behavior

The real-time connection remains active even after the component has been unmounted.

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Windows

### 🧱 Your Environment

I'm utilizing Appwrite v1.4.13, along with SDK version 13.0.1, in a self-hosted environment. This setup is integrated within a React Native application.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2024-02-13 20:07
@collinmyers, thanks for raising this issue! 🙏🏼 This definitely looks like a bug in the SDK. It doesn't look the the SDK is closing the websocket because of this code: https://github.com/appwrite/sdk-for-web/blob/ca8cb1d9f2c0393ec99c7d5cb50f3be543987918/src/client.ts#L211

Related Discord thread: https://discord.com/channels/564160730845151244/1201047679338295429

**Comment by behics** [comment] 2024-03-08 13:07
Waiting for update about this issue, it was really headache for my chat app 🚀

**Comment by xuelink** [comment] 2024-03-28 17:18
Any updates here ?

**Comment by ZachHandley** [comment] 2024-04-16 03:05
@xuelink https://github.com/ZachHandley/AppwriteReactRealtimeTest can you fork this and give me a reproducible example perchance

**Comment by xuelink** [comment] 2024-04-16 11:18
> @xuelink https://github.com/ZachHandley/AppwriteReactRealtimeTest can you fork this and give me a reproducible example perchance -- this is 1.5, but I imported the built SDK right in and I don't think the Realtime changed in between, but I can test it on 1.4 if there's an issue
> 
> Can't seem to get it to break myself though that's a really simple example

@ZachHandley Thank you for your interest here but im not comfortable with react well, so maybe @collinmyers can do it for reproduction for you  to understand easily.

This closed issue is the same issue as with reproduced with angular: https://github.com/appwrite/sdk-for-web/issues/91

I just bypassed this issue by forking sdk and commenting this related line temporarily. [ref](https://github.com/langxapp/langx/blob/5378a460aaf68091c6e558546198510006569500/src/app/extras/sdk/src/client.ts#L227)

**Comment by stnguyen90** [comment] 2024-04-17 19:10
Fixed in https://github.com/appwrite/sdk-for-web/pull/93

**Closed by stnguyen90** 2024-04-17 19:10 UTC
Labels: bug, api / realtime
