### ISSUE TITLE
🐛 Bug Report: ui bug - the left-arrow icon in switch does not seems to be in centre

### ISSUE THREAD

**Issue by tewarig** [appwrite/appwrite#5752] opened 2023-06-26 16:47 UTC
### 👟 Reproduction steps

https://github.com/appwrite/appwrite/assets/54894783/77775033-d2ec-43d2-9af2-43d797a8b643

### 👍 Expected behavior

this is a minor bug ... the switch in the whole console is broken ... the arrow-left should be in the center of the button.

### 👎 Actual Behavior

<img width="1173" alt="Screenshot 2023-06-26 at 10 16 22 PM" src="https://github.com/appwrite/appwrite/assets/54894783/4719d09b-8d79-4c7e-95e7-cac90db2b39c">
<img width="1105" alt="Screenshot 2023-06-26 at 10 16 40 PM" src="https://github.com/appwrite/appwrite/assets/54894783/76d024f1-9a6b-4dda-9813-89bed797b353">

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 🧱 Your Environment

[Version 1.1.2](https://github.com/appwrite/appwrite/blob/master/CHANGES.md)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment] 2023-06-27 12:55
Hi
Thank you for opening this and showing your interest in contributing to Appwrite.
This is a duplicate of #5482 - which indicates that this is updated and newer versions and once Cloud is updated, this will go away. I would recommend closing this issue as of now. 

For contributions, you can take a look at our other issues and select the ones which are up for grabs and not being worked on by any one else,  https://github.com/appwrite/appwrite/issues

Happy contributing!

**Closed** 2023-06-27 12:57 UTC
Labels: bug
