### ISSUE TITLE
🐛 Bug Report: Migrating from 14.2 to 15.1 drops attributes for some collections

### ISSUE THREAD

**Issue by pspierce** [appwrite/appwrite#3482] opened 2022-07-01 17:34 UTC
### 👟 Reproduction steps

When I run through the process of installing 15.1 and then migrating as described in the documentation.

### 👍 Expected behavior

All collections are migrated with all attributes intact from 14.2

### 👎 Actual Behavior

At least one collection is migrating with the result of only 1/3 the original attributes are contained within the migrated collection.
List of attributes after migration:
```
  key            │ type    │ status    │ required │ array │ format │ default │ size │ min                  │ max                  
 ────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  ip_address     │ string  │ available │ true     │ false │ ip     │ -       │ -    │ -                    │ -                    
 ────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  location       │ string  │ available │ false    │ false │ -      │ -       │ 400  │ -                    │ -                    
 ────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  name           │ string  │ available │ false    │ false │ -      │ -       │ 255  │ -                    │ -                    
 ────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  serial_number  │ string  │ available │ false    │ false │ -      │ -       │ 255  │ -                    │ -                    
 ────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  classification │ string  │ available │ false    │ false │ -      │ -       │ 255  │ -                    │ -                    
 ────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  vlan           │ string  │ available │ false    │ false │ -      │ -       │ 255  │ -                    │ -                    
 ────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  site           │ string  │ available │ false    │ false │ -      │ -       │ 3    │ -                    │ -                    
 ────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  last_update    │ integer │ available │ false    │ false │ -      │ -       │ -    │ -9223372036854776000 │ 9223372036854776000  
 ────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  manual         │ string  │ available │ false    │ true  │ -      │ -       │ 255  │ -                    │ -                    
 
```
List of original attributes:
```

  key                       │ type    │ status    │ required │ array │ format │ default │ size │ min                  │ max                  
 ───────────────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  ip_address                │ string  │ available │ true     │ false │ ip     │ -       │ -    │ -                    │ -                    
 ───────────────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  location                  │ string  │ available │ false    │ false │ -      │ -       │ 400  │ -                    │ -                    
 ───────────────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  name                      │ string  │ available │ false    │ false │ -      │ -       │ 255  │ -                    │ -                    
 ───────────────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  serial_number             │ string  │ available │ false    │ false │ -      │ -       │ 255  │ -                    │ -                    
 ───────────────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  classification            │ string  │ available │ false    │ false │ -      │ -       │ 255  │ -                    │ -                    
 ───────────────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  vlan                      │ string  │ available │ false    │ false │ -      │ -       │ 255  │ -                    │ -                    
 ───────────────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  site                      │ string  │ available │ false    │ false │ -      │ -       │ 3    │ -                    │ -                    
 ───────────────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  last_update               │ integer │ available │ false    │ false │ -      │ -       │ -    │ -9223372036854776000 │ 9223372036854776000  
 ───────────────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  manual                    │ string  │ available │ false    │ true  │ -      │ -       │ 255  │ -                    │ -                    
 ───────────────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  comments                  │ string  │ available │ false    │ false │ -      │ -       │ 2550 │ -                    │ -                    
 ───────────────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  purpose                   │ string  │ available │ false    │ false │ -      │ -       │ 255  │ -                    │ -                    
 ───────────────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  motherboard_serial_number │ string  │ available │ false    │ false │ -      │ -       │ 255  │ -                    │ -                    
 ───────────────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  powersupply_serial_number │ string  │ available │ false    │ false │ -      │ -       │ 255  │ -                    │ -                    
 ───────────────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  firmware                  │ string  │ available │ false    │ false │ -      │ -       │ 255  │ -                    │ -                    
 ───────────────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  notes                     │ string  │ available │ false    │ true  │ -      │ -       │ 255  │ -                    │ -                    
 ───────────────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  driver                    │ string  │ available │ false    │ false │ -      │ -       │ 255  │ -                    │ -                    
 ───────────────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  model                     │ string  │ available │ false    │ false │ -      │ -       │ 255  │ -                    │ -                    
 ───────────────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  vendor_id                 │ string  │ available │ false    │ false │ -      │ -       │ 255  │ -                    │ -                    
 ───────────────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  port                      │ string  │ available │ false    │ false │ -      │ -       │ 255  │ -                    │ -                    
 ───────────────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  mac                       │ string  │ available │ false    │ false │ -      │ -       │ 20   │ -                    │ -                    
 ───────────────────────────┼─────────┼───────────┼──────────┼───────┼────────┼─────────┼──────┼──────────────────────┼───────────────────── 
  asset_tag                 │ string  │ available │ false    │ false │ -      │ -       │ 50   │ -                    │ -                    
                                                                                                                                             
```

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Docker on localhost.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by brianmutiso** [comment] 2022-07-02 17:26
Same here, Infact in my case it drops all attributes in my collection, but the index still remains, i cannot add data to the table but i can read data using flutter sdk, i cannot query using indexes as the attributes are missing, it seems there is a problem with the migration tool, some of my collections are okay while others are not, I repeated the process with same results over and over,

I migrated from version 14.2 to version 15.1

**Comment by pspierce** [comment] 2022-07-03 22:34
@brianmutiso I noted from the attribute tables I shared in this bug report that "comment" listed above has a high size.  I don't know if that has anything to do with it, but curious if the high size breaks the migration as the attributes above that one all come over in the migration.  I upgraded/migrated three different times each with the same, consistent results, all attributes starting at comment are dropped in the migration.  Do you have any of a large size similar to what I show?

**Comment by brianmutiso** [comment] 2022-07-03 23:16
Same case to me, all attributes after attributes with a lot of characters
fails,

**Comment by brianmutiso** [comment] 2022-07-03 23:18
Yes i have large sizes, some upto 1000 characters

**Comment by pspierce** [comment] 2022-07-07 21:40
I didn't save it, just worked around it, but there is a bug when attempting to create an index with a field too large.  This particular table had an index with two fields: product_name and product_version, which threw an error recorded in appwrite-database-worker of: Syntax error or access violation: 1071 Specified key was too long; ....

**Comment by pspierce** [comment] 2022-07-13 18:18
JSON of 14.2 collection in case that makes it easier to reproduce.  I noticed a lot of index errors when you have a string with a large size, especially indexes with multiple attributes; however, I was preoccupied with this bug to go down that rabbit hole.

{
    "$id": "ip_addresses",
    "$read": [
        "role:all"
    ],
    "$write": [
        "role:all"
    ],
    "name": "IP Addresses",
    "enabled": true,
    "permission": "collection",
    "attributes": [
        {
            "key": "ip_address",
            "type": "string",
            "status": "available",
            "required": true,
            "array": false,
            "format": "ip",
            "default": null
        },
        {
            "key": "location",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 400,
            "default": null
        },
        {
            "key": "name",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 255,
            "default": null
        },
        {
            "key": "serial_number",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 255,
            "default": null
        },
        {
            "key": "classification",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 255,
            "default": null
        },
        {
            "key": "vlan",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 255,
            "default": null
        },
        {
            "key": "site",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 3,
            "default": null
        },
        {
            "key": "last_update",
            "type": "integer",
            "status": "available",
            "required": false,
            "array": false,
            "min": -9223372036854776000,
            "max": 9223372036854776000,
            "default": null
        },
        {
            "key": "manual",
            "type": "string",
            "status": "available",
            "required": false,
            "array": true,
            "size": 255,
            "default": null
        },
        {
            "key": "comments",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 2550,
            "default": null
        },
        {
            "key": "purpose",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 255,
            "default": null
        },
        {
            "key": "motherboard_serial_number",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 255,
            "default": null
        },
        {
            "key": "powersupply_serial_number",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 255,
            "default": null
        },
        {
            "key": "firmware",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 255,
            "default": null
        },
        {
            "key": "notes",
            "type": "string",
            "status": "available",
            "required": false,
            "array": true,
            "size": 255,
            "default": null
        },
        {
            "key": "driver",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 255,
            "default": null
        },
        {
            "key": "model",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 255,
            "default": null
        },
        {
            "key": "vendor_id",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 255,
            "default": null
        },
        {
            "key": "port",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 255,
            "default": null
        },
        {
            "key": "mac",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 20,
            "default": null
        },
        {
            "key": "asset_tag",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
        },
        {
            "key": "active",
            "type": "boolean",
            "status": "available",
            "required": false,
            "array": false,
            "default": true
        }
    ],
    "indexes": [
        {
            "key": "idx_ip_address",
            "type": "key",
            "status": "available",
            "attributes": [
                "ip_address"
            ],
            "orders": [
                "ASC"
            ]
        },
        {
            "key": "idx_name",
            "type": "key",
            "status": "available",
            "attributes": [
                "name"
            ],
            "orders": [
                "ASC"
            ]
        }
    ]
}

**Comment by brianmutiso** [comment] 2022-07-13 19:15
If this bug can be fixed it will be pretty helpful, as it stands I cannot
upgrade to the next AppWrite version due to this issue, most indexes aren't
resolved, migrating from 13 to 14.2 had no issue in my case, 14.2 to 15.1
failed

**Comment by stnguyen90** [comment] 2022-07-13 19:34
Thank you for raising this issue! 🙏 We’ll dig into this and get back to you as soon as we can. 😊

**Comment by badmark** [comment] 2022-07-14 18:42
Same here. Posting before and after migration JSON of collection.
[after_15_migration.json.txt](https://github.com/appwrite/appwrite/files/9114483/after_15_migration.json.txt)
[before_15_migration.json.txt](https://github.com/appwrite/appwrite/files/9114484/before_15_migration.json.txt)

**Comment by stnguyen90** [comment] 2022-07-18 22:40
@TorstenDittmann, @wess, I was able to reproduce by doing the following:

1. Spin up a 0.14.2 instance
2. Create a project with id `missingattrs`
3. Deploy collections in the appwrite.json file below using the Appwrite CLI
    <details>
    <summary>appwrite.json</summary>

    ```json
    {
    "projectId": "missingattrs",
    "projectName": "Missing Attrs",
    "databaseId": "Default",
    "collections": [
        {
        "$id": "c1",
        "$read": ["role:all"],
        "$write": ["role:all"],
        "name": "C1",
        "enabled": true,
        "permission": "collection",
        "attributes": [
            {
            "key": "a1",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a2",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a3",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a4",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a5",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a6",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a7",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a8",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a9",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a10",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a11",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a12",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a13",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a14",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a15",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a16",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a17",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a18",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a19",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a20",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a21",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a22",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a23",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a24",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a25",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a26",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a27",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a28",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a29",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a30",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            }
        ],
        "indexes": []
        },
        {
        "$id": "c2",
        "$read": ["role:all"],
        "$write": ["role:all"],
        "name": "C2",
        "enabled": true,
        "permission": "collection",
        "attributes": [
            {
            "key": "a31",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a32",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a33",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a34",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a35",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a36",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a37",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a38",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a39",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a40",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a41",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a42",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a43",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a44",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a45",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a46",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a47",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a48",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a49",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a50",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a51",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a52",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a53",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a54",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a55",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a56",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a57",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a58",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a59",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a60",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            }
        ],
        "indexes": []
        },
        {
        "$id": "c3",
        "$read": ["role:all"],
        "$write": ["role:all"],
        "name": "C3",
        "enabled": true,
        "permission": "collection",
        "attributes": [
            {
            "key": "a61",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a62",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a63",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a64",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a65",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a66",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a67",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a68",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a69",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a70",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a71",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a72",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a73",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a74",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a75",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a76",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a77",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a78",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a79",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a80",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a81",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a82",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a83",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a84",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a85",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a86",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a87",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a88",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a89",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a90",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            }
        ],
        "indexes": []
        },
        {
        "$id": "c4",
        "$read": ["role:all"],
        "$write": ["role:all"],
        "name": "C4",
        "enabled": true,
        "permission": "collection",
        "attributes": [
            {
            "key": "a91",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a92",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a93",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a94",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a95",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a96",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a97",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a98",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a99",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a100",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            },
            {
            "key": "a101",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 50,
            "default": null
            }
        ],
        "indexes": []
        }
    ]
    }
    ```

    </details>
4. Upgrade to 0.15.2
5. Migrate

After migrating, you should be able to find an attribute named `a101` in collection `c4`, but it doesn't look like it migrated.

If you look at the migrate logs, you'll see:

```
Migrating Collection attributes:
100 / 101
100 / 101
```

which seems to indicate the attribute(s) after the first 100 aren't migrated.

<details>
<summary>My full migrate logs:</summary>

```
$ docker compose exec appwrite migrate
Starting Data Migration to version 0.15.2
[PDO] MySQL connection restarted
Migrating project: Appwrite (console)
Migrating Collections
- _metadata
- audit
- abuse
- databases
- collections
- attributes
- indexes
- projects
- platforms
- domains
- keys
- webhooks
- users
- tokens
- sessions
- teams
- memberships
- functions
- deployments
- builds
- executions
- certificates
- buckets
- stats
- realtime
- files
Create Default Database Layer
Migrating Documents
Migrating Collection _metadata:
25 / 25
Migrating Collection audit:
4 / 4
Migrating Collection abuse:
14 / 14
Migrating Collection databases:
0 / 0
Migrating Collection attributes:
0 / 0
Migrating Collection indexes:
0 / 0
Migrating Collection projects:
1 / 1
Migrating Collection platforms:
0 / 0
Migrating Collection domains:
1 / 1
Migrating Collection keys:
0 / 0
Migrating Collection webhooks:
0 / 0
Migrating Collection users:
1 / 1
Migrating Collection tokens:
0 / 0
Migrating Collection sessions:
2 / 2
Migrating Collection teams:
1 / 1
Migrating Collection memberships:
1 / 1
Migrating Collection functions:
0 / 0
Migrating Collection deployments:
0 / 0
Migrating Collection builds:
0 / 0
Migrating Collection executions:
0 / 0
Migrating Collection certificates:
1 / 1
Migrating Collection buckets:
1 / 1
Migrating Collection stats:
0 / 0
Migrating Collection realtime:
2 / 2
Migrated 1/2 projects...
Migrating project: missingattrs (missingattrs)
Migrating Collections
- _metadata
- audit
- abuse
- databases
- collections
- attributes
- indexes
- projects
- platforms
- domains
- keys
- webhooks
- users
- tokens
- sessions
- teams
- memberships
- functions
- deployments
- builds
- executions
- certificates
- buckets
- stats
- realtime
- files
Create Default Database Layer
Migrating Database Collections
- c1 (C1)
- c2 (C2)
- c3 (C3)
- c4 (C4)
Migrating Documents
Migrating Collection _metadata:
28 / 28
Migrating Collection audit:
100 / 105
105 / 105
Migrating Collection abuse:
0 / 0
Migrating Collection databases:
1 / 1
Migrating Collection attributes:
100 / 101
100 / 101
Migrating Collection indexes:
0 / 0
Migrating Collection projects:
0 / 0
Migrating Collection platforms:
0 / 0
Migrating Collection domains:
0 / 0
Migrating Collection keys:
0 / 0
Migrating Collection webhooks:
0 / 0
Migrating Collection users:
0 / 0
Migrating Collection tokens:
0 / 0
Migrating Collection sessions:
0 / 0
Migrating Collection teams:
0 / 0
Migrating Collection memberships:
0 / 0
Migrating Collection functions:
0 / 0
Migrating Collection deployments:
0 / 0
Migrating Collection builds:
0 / 0
Migrating Collection executions:
0 / 0
Migrating Collection certificates:
0 / 0
Migrating Collection buckets:
0 / 0
Migrating Collection stats:
12 / 12
Migrating Collection realtime:
0 / 0
Migrated 2/2 projects...
Data Migration Completed
```
</details>

**Comment by TorstenDittmann** [comment] 2022-07-26 10:05
This should be fixed now with `0.15.3` 🙏🏻 

Thanks for the patience!

**Comment by stnguyen90** [comment] 2022-09-27 13:41
@pspierce, have you had a chance to migrate to 0.15.3?

**Comment by abnegate** [comment] 2023-01-11 03:05
Closing as resolved

**Closed by abnegate** 2023-01-11 03:05 UTC
Labels: bug, database
