### ISSUE TITLE
🐛 Bug Report:  Console label not found

### ISSUE THREAD

**Issue by TakeSomeSteps** [appwrite/appwrite#7977] opened 2024-04-16 14:43 UTC
### 👟 Reproduction steps

1. When adding permissions for lables/ teams and hovering, it's not showing properly.
2. When hovering on a label - it shows "Not found"

![image](https://github.com/appwrite/appwrite/assets/156800479/c831450d-5967-416d-b348-3eb2a65fe9b3)
![image](https://github.com/appwrite/appwrite/assets/156800479/5b19b11b-518f-426c-a165-51ad08711ca1)

### 👍 Expected behavior

1. the tooltip should have a background
2. the labels hovering should be found, or generate it?

### 👎 Actual Behavior

1. the tooltop doesn't have a background
2. label not found

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

I use Firefox, but it's also in chrome.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by avezqureshi14** [comment] 2024-04-16 17:23
I would like to work, on this. Please assign me this issue.

**Comment by stnguyen90** [comment] 2024-04-16 21:46
Closing as a duplicate of https://github.com/appwrite/appwrite/issues/5912

**Closed by stnguyen90** 2024-04-16 21:46 UTC
Labels: bug
