### ISSUE TITLE
🐛 Bug Report: Adding Roles for Bucket Permission fails with unrelated error

### ISSUE THREAD

**Issue by KaleabKindu** [appwrite/appwrite#7746] opened 2024-03-07 14:41 UTC
### 👟 Reproduction steps

1. I first created a bucket on the appwrite console
2. click on settings 
3. go to the Permission section and add a role for any user
4. failed with error saying maximum file size limit

### 👍 Expected behavior

the permission for the bucket should have been updated

### 👎 Actual Behavior

adding role fails with an error Maximum file size limit

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by EVDOG4LIFE** [comment] 2024-03-07 16:55
Thanks for reporting this @KaleabKindu - we're aware and actively working on a fix. Please see #7682, closing this as a duplicate.

**Comment by EVDOG4LIFE** [comment] 2024-03-07 16:58
Closing as duplicate of #7682

**Closed by EVDOG4LIFE** 2024-03-07 16:58 UTC
Labels: bug
