### ISSUE TITLE
🚀 Feature: Ability to Sort Collection's Attributes

### ISSUE THREAD

**Issue by aboidrees90** [appwrite/appwrite#5038] opened 2023-01-25 06:23 UTC
### 🔖 Feature description

Ability to Sort collection's attributes 

### 🎤 Pitch

Sorting attributes will make it possible to put related attributes (fields) for easy review and debugging.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-01-26 00:22
@aboidrees90 thanks for creating this issue! 🙏🏼

**Comment by pratik-codes** [comment] 2023-01-27 19:28
I would like to pick this up @stnguyen90 If given a little more background on the feature request and some guidance on how to go about doing this feature

**Comment by stnguyen90** [comment] 2023-01-31 00:17
@aboidrees90 is this a duplicate of https://github.com/appwrite/appwrite/issues/2787? If so, would you 👍 that issue and close this issue?

**Comment by aboidrees90** [comment] 2023-02-02 13:03
@stnguyen90 Yes it's the same

**Closed** 2023-02-02 13:04 UTC
Labels: database, feature
