### ISSUE TITLE
🐛 Bug Report: error `Invalid document structure: Unknown attribute "count"` trying to create a document

### ISSUE THREAD

**Issue by gepd** [appwrite/appwrite#5052] opened 2023-01-26 19:59 UTC
### 👟 Reproduction steps

1. Create collection

<img width="308" alt="image" src="https://user-images.githubusercontent.com/7091609/214932247-b6cfe956-db30-4f2e-9e14-301c7168b4e7.png">

2. create one or more attributes (I have added two string attributes of size 255)

<img width="310" alt="image" src="https://user-images.githubusercontent.com/7091609/214932575-da664173-9ba0-4c4a-b35d-b5c05084157f.png">

3. set the data to create a document

<img width="382" alt="image" src="https://user-images.githubusercontent.com/7091609/214935219-c458f0dc-2bec-4cd8-97be-021bdbf1f5de.png">

I didn't change anything in the permission settings

4. Hit the create button and you will get `Invalid document structure: Unknown attribute "count"`

<img width="215" alt="image" src="https://user-images.githubusercontent.com/7091609/214935380-16179591-0300-401e-a7b1-bd0640adf80b.png">
__

### 👍 Expected behavior

Create a document without any error

### 👎 Actual Behavior

We get the error: `Invalid document structure: Unknown attribute "count"`

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-01-26 21:30
@gepd thanks for creating this issue! 🙏🏼 Is this a duplicate of [this](https://github.com/appwrite/appwrite/issues/4993) issue? If so, it would be good to 👍🏼 that issue and close this one.

**Comment by gepd** [comment] 2023-01-26 21:45
@stnguyen90 it seems to be similar, I'm not sure if it's the same because in that issue he talked about two collections, and here I I'm testing with just one. For me is like it's the same

**Closed** 2023-01-26 21:46 UTC
Labels: bug
