### ISSUE TITLE
🚀 Feature: One click structure export/import

### ISSUE THREAD

**Issue by kunduarnab** [appwrite/appwrite#4945] opened 2023-01-03 10:29 UTC
### 🔖 Feature description

After developing our application locally, we want to export the whole structure of the appwrite instance, so that we can transfer the same structure to our production environment. e.g. All database, collection structure without data, bucket configurations etc.

### 🎤 Pitch

An one click structure export/import functionality will help us to move application from development to production hassle-free.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-01-05 18:22
Closing as this is a duplicate of https://github.com/appwrite/appwrite/issues/3449.

**Closed by stnguyen90** 2023-01-05 18:22 UTC
