### ISSUE TITLE
🐛 Bug Report:File Upload to bucket  doesn't work

### ISSUE THREAD

**Issue by scshiv29-dev** [appwrite/appwrite#4510] opened 2022-10-16 09:11 UTC
### 👟 Reproduction steps

1.Create a new appwrite instance through coolify .
2.Open app create new project and a new bucket
3. try uploading a new file
4. see it fail

![image](https://user-images.githubusercontent.com/68141773/196027535-be68a9d7-5c17-4949-ac08-1bc7281fd96b.png)

### 👍 Expected behavior

Expected the file to upload

### 👎 Actual Behavior

File not uploaded.

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use cloudfare for dns and coolify to create an appwrite instance.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2022-10-17 18:18
Related issue in Coolify repo: https://github.com/coollabsio/coolify/issues/685

**Comment by stnguyen90** [comment] 2022-11-21 17:59
Since the coolify issue has been resolved, I'm going to close this one since it's a duplicate of https://github.com/appwrite/appwrite/issues/3311

**Closed by stnguyen90** 2022-11-21 17:59 UTC
Labels: bug
