### ISSUE TITLE
🐛 Bug Report: WEBP image has twice file size than original JPEG 

### ISSUE THREAD

**Issue by step135** [appwrite/appwrite#7527] opened 2024-01-31 16:05 UTC
### 👟 Reproduction steps

Add argument `output=webp` in the URL and the transformed JPEG image of same dimensions will take twice memory.

### 👍 Expected behavior

It should be smaller size.

### 👎 Actual Behavior

File size too big.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment] 2024-02-11 16:45
Do you use the quality parameter on the jpeg? If yes it might be related to this bug that has a pending fix: https://github.com/appwrite/appwrite/issues/7213

**Comment by stnguyen90** [comment] 2024-04-24 16:03
Closing as a duplicate of https://github.com/appwrite/appwrite/issues/7213

**Closed by stnguyen90** 2024-04-24 16:03 UTC
Labels: bug, work in progress, product / storage
