### ISSUE TITLE
🐛 Bug Report:  The Console UI is broken on a few pages and modals

### ISSUE THREAD

**Issue by Aarush-Acharya** [appwrite/appwrite#8024] opened 2024-04-25 09:35 UTC
### 👟 Reproduction steps

When I got to Console -> Database -> Collection -> Attributes -> Create New Attribute -> choose String attribute 

after this if i enter the size of the string to be >= 100 the enter string text field expands and overflows on the isRequired checkbox
![Screenshot 2024-04-25 at 3 01 10 PM](https://github.com/appwrite/appwrite/assets/92685647/7f5c365a-65d9-4939-b343-d93c93bdfedb)

This happens again while manually creating a document in the collection the string attributes having size >=100 overflow their input textfield to the attributes below them 

![Screenshot 2024-04-25 at 2 04 19 PM](https://github.com/appwrite/appwrite/assets/92685647/2a055902-23cc-41a6-861b-4d69caade928)

On the Collections page the side bar shows up half covered and it does not give user the option to expand it further

![Screenshot 2024-04-25 at 6 52 38 PM](https://github.com/appwrite/appwrite/assets/92685647/8b7b8a0f-ead7-4645-bbf3-07fce373ff84)

### 👍 Expected behavior

The attributes below the expanded text field should move down more once or if the text field above is expanded 

The side bar should give user the option to minimise or maximise it and should show the full contents when set on max width

## 👎 Actual Behavior

The text field above expands or is expanded yet the attributes below them maintain their position and get overflown 

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

The currently deployed version of Appwrite Console UI on web

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Aarush-Acharya** [comment] 2024-04-25 09:40
Hey, I would like to work on it if it is alright, and the issue is genuine.

**Comment by stnguyen90** [comment] 2024-04-26 03:38
@Aarush-Acharya thanks for raising this issue! 🙏 This looks like a duplicate of https://github.com/orgs/appwrite/projects/8/views/1?sliceBy%5Bvalue%5D=x.x.5&filterQuery=Cover&pane=issue&itemId=60635380 which was fixed in Appwrite 1.5.5 and will be coming to Cloud soon

**Closed by stnguyen90** 2024-04-26 03:37 UTC
Labels: bug
