### ISSUE TITLE
🚀 Feature: Support for middleware authentication

### ISSUE THREAD

**Issue by vlohar08** [appwrite/appwrite#5067] opened 2023-02-01 02:58 UTC
### 🔖 Feature description

Hi,
I was previously using Next auth with nextjs for user authentication. Next auth with middleware can redirect the user to the login page before loading content if the user is trying to access restricted pages.

And I can redirect users before loading content if they try to access the admin dashboard with an account that doesn't have enough permissions.

I miss this flexibility and feature in appwrite. You can't really use middleware to verify the user before the content is displayed.

### 🎤 Pitch

--This feature is really important for restricting access to admin dashboards or other pages.
--We can do it with currently available options. But any code will be executed after the page has finished loading.
--There is no method available in appwrite that can verify the user in between the request and redirect it if it's not authenticated.
--These results in the flashing of content and in slow internet connections it can take a long time to execute the code related to page restrictions.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-02-01 18:18
@vlohar08, thanks for creating this issue! 🙏🏼 Is this a duplicate of https://github.com/appwrite/appwrite/issues/2358? If so, it would be good if you close this issue and 👍🏼 the other issue.

**Closed** 2023-02-02 02:35 UTC
