### ISSUE TITLE
🐛 Bug Report: Package name isn't saved when adding a new platform

### ISSUE THREAD

**Issue by fjolne** [appwrite/appwrite#4796] opened 2022-11-26 15:58 UTC
### 👟 Reproduction steps

Add a new Flutter Android platform via web console and enter correct package name.

### 👍 Expected behavior

`Package Name` should be displayed in `Update Package Name` block and API requests from given Android origin should authenticate.

### 👎 Actual Behavior

On just created platform page, the package name field in `Update Package Name` block is empty, but the correct package name is displayed in `Delete Platform` block. All API requests from the proper Android origin return:
```
AppwriteException: general_unknown_origin, Invalid Origin. Register your new client (com.fake.app) as a new Android platform on your project console dashboard (403)
```

After updating `Package Name` on platform page the API gets authenticated correctly.

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Docker: appwrite 1.1.2
Flutter: appwrite 8.1.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2022-11-26 16:17
@fjolne is this a duplicate of https://github.com/appwrite/appwrite/issues/4787? If so can this be closed and you can 👍 the other issue?

**Comment by fjolne** [comment] 2022-11-26 17:28
@stnguyen90 right, sorry for missing that issue!

**Closed** 2022-11-26 17:28 UTC
Labels: bug
