### ISSUE TITLE
🐛 Bug Report: Changing _APP_FUNCTIONS_TIMEOUT from 900 breaks console side validation

### ISSUE THREAD

**Issue by johnschatner** [appwrite/appwrite#7924] opened 2024-04-05 15:26 UTC
### 👟 Reproduction steps

1. Change _APP_FUNCTIONS_TIMEOUT to a value greater than 900 in .env
2. Restart appwrite containers
3. Go to appwrite console in browser
4. Try to change the value to anything greater than 900

### 👍 Expected behavior

The console side validation to update and reflect the new value. 

### 👎 Actual Behavior

The console side validation seems hardcoded to 900, which doesn't allow me to update the function to have a timeout greater than 900.

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2024-06-05 20:42
Closing as a duplicate of https://github.com/appwrite/console/issues/385. Feel free to add a 👍🏼 to the related issue.

**Closed by stnguyen90** 2024-06-05 20:42 UTC
Labels: bug
