### ISSUE TITLE
🐛 Bug Report: Appwrite console bug

### ISSUE THREAD

**Issue by Srinivasan-Akash** [appwrite/appwrite#5975] opened 2023-08-12 11:53 UTC
### 👟 Reproduction steps

When we create a database, collection and have some documents.
& we change some attributes and open any document to add an attribute value it does not even load that document or some times loads but we cannot update the new value.

https://github.com/appwrite/appwrite/assets/108281031/0d597365-cadd-41c4-bf2a-6ca6a8186556

![image (3)](https://github.com/appwrite/appwrite/assets/108281031/90882298-6f1e-44a0-bdad-52691acdeee8)

### 👍 Expected behavior

Expected behaviour is to not produce the above bug and let user add value to the attribute

### 👎 Actual Behavior

It does not even load the document sometimes and if loaded we are not able to update the attribute.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

I am using the web SDK with next.js and below are the libraries
  "dependencies": {
    "@next/font": "13.4.13",
    "appwrite": "^11.0.0",
    "eslint": "8.46.0",
    "eslint-config-next": "13.4.13",
    "next": "13.4.13",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-icons": "^4.10.1",
    "react-toastify": "^9.1.3",
    "uuid": "^9.0.0"
  }

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by safwanyp** [comment] 2023-08-13 08:02
Hey @Srinivasan-Akash 

The issue with not being able to update the value of any attribute in a document was fixed in https://github.com/appwrite/console/pull/495

As for the collection/document not loading properly, it could be that the cloud database was undergoing routine backups when you were trying to perform operations. Could you try to do this again and see if the issue still exists?

**Comment by safwanyp** [comment] 2023-08-13 08:05
Another thing to mention is that version `11.0.0.` of the Web SDK isn't compatible with v1.1.2 of Appwrite (which is what Cloud is running right now). It's better if you use version `10.1.0` which can be found here: https://www.npmjs.com/package/appwrite/v/10.1.0

**Comment by joeyouss** [comment] 2023-08-16 13:18
Hi @Srinivasan-Akash , checking in to see if this still exists for you?

**Comment by stnguyen90** [comment] 2023-10-16 20:31
Do you still have a problem? If so, please provide exact reproducible steps as what's provided isn't detailed enough for us to reproduce the problem.

Please be advised we'll have to close this soon due to inactivity.

**Comment by eldadfux** [comment] 2024-10-24 06:24
Closed due to inactivity.

**Closed by eldadfux** 2024-10-24 06:24 UTC
Labels: bug, product / databases, product / console
