### ISSUE TITLE
🐛 Bug Report: All function files are deleted when the container is stopped

### ISSUE THREAD

**Issue by Asored-D** [appwrite/appwrite#2935] opened 2022-03-10 16:08 UTC
### 👟 Reproduction steps

1. Deploy a cloud function for a project (Just a simple Hello World output)
2. Run `docker-compose down`
3. Run `docker-compose up -d`
4. Try to execute the function. There will be an error with the string: `File Not Found`
5. Deploy the same function again
6. Now executions are working 

### 👍 Expected behavior

I would expect that after rebooting the containers, you don't have to redeploy all the functions every time. For large projects, that could be a lot. 

### 👎 Actual Behavior

Currently, you have to redeploy the functions after each container restart. Otherwise they do not work and return "File not found". The programming language of the function does not seem to matter. I tested it with DART and PHP functions.

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

No special customizations.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2022-03-11 03:29
My theory is the code is mounted into a volume, but the volume is in the appwrite-executor container. When the container is removed, the volume is also removed.

Source: https://github.com/appwrite/appwrite/blob/406f914585f74bef574f1bcf6cda36c39eb8696b/app/executor.php#L229

**Comment by Meldiron** [comment] 2022-03-14 20:28
> My theory is the code is mounted into a volume, but the volume is in the appwrite-executor container. When the container is removed, the volume is also removed.
> 
> Source:
> 
> https://github.com/appwrite/appwrite/blob/406f914585f74bef574f1bcf6cda36c39eb8696b/app/executor.php#L214-L229

This sounds very correct, great feedback!

**Comment by s3ppo** [comment] 2022-03-14 20:51
> My theory is the code is mounted into a volume, but the volume is in the appwrite-executor container. When the container is removed, the volume is also removed.
> 
> Source:
> 
> https://github.com/appwrite/appwrite/blob/406f914585f74bef574f1bcf6cda36c39eb8696b/app/executor.php#L214-L229

i think you are 100% right
i testet it and redeployed the executor docker.. after that all my functions where red with the error ```File not found```

**Comment by Meldiron** [comment] 2022-03-15 09:03
I am not able to reproduce the problem 😬

**Comment by Meldiron** [comment] 2022-03-15 09:13
Never mind, the problem is there on 0.13.2, but not on master branch. With next release, the bug will most likely be fixed.

**Comment by stnguyen90** [comment] 2022-03-15 13:44
> Never mind, the problem is there on 0.13.2, but not on master branch. With next release, the bug will most likely be fixed.

Any idea what the fix was?

**Comment by s3ppo** [comment] 2022-03-15 19:30
i just tested 0.13.3 but it seems its not yet fixed

**Comment by Meldiron** [comment] 2022-03-16 08:27
I can confirm this occurs with 0.13.3 when using Docker images. If started from source code (same version), it works fine. Whoof, this one will be interesting... 🤔

**Comment by Meldiron** [comment] 2022-03-16 09:26
Found it 🥳 We will need to sync our development and production docker-compose, as there are some mismatches around volumes, environment variables, and versions.

The solution to this problem can be seen in this gist: https://gist.github.com/Meldiron/1ac493328141210da950e40d9c3cb568/revisions

Check out the latest revision and apply these changes to your `docker-compose.yml`. Then, restart appwrite with `docker-compose down && docker-compose up -d`. After Appwrite starts, make sure to redeploy your functions, and from now on, your functions should not lose deployments if you restart Appwrite 😍

![CleanShot 2022-03-16 at 10 24 02](https://user-images.githubusercontent.com/19310830/158558620-a62fac96-9585-4f76-a644-cfec480a467b.png)

**Comment by s3ppo** [comment] 2022-03-16 11:40
i can confirm, everything is fine now! ;-)

**Comment by Asored-D** [comment] 2022-03-16 14:57
Good work! :)

**Comment by SUDDSDUDDS** [comment] 2022-03-16 15:54
mount

**Comment by Meldiron** [comment] 2022-03-21 07:39
The issue should be fixed with 0.13.3 release. Please upgrade to latest version and let me know if we can close this issue 😇

**Comment by s3ppo** [comment] 2022-03-21 07:41
> The issue should be fixed with 0.13.3 release. Please upgrade to latest version and let me know if we can close this issue 😇

I think its not fixed in 0.13.3 because of the needed manual docker-compose file changes 😉

**Comment by Meldiron** [comment] 2022-03-21 09:15
Oh, it's not merged yet, not released.
 Thankfully, after release, when you upgrade, all changes to `.env` and `docker-compose.yml` are done automatically.

**Comment by gepd** [comment] 2022-03-27 16:27
Not available in 0.13.4?

**Comment by eldadfux** [comment] 2022-05-18 12:35
This feature is now released and available as part of Appwrite 0.14. More on the new release here: https://github.com/appwrite/appwrite/discussions/3240

**Closed by eldadfux** 2022-05-18 12:35 UTC
Labels: bug, waiting for release, functions
