### ISSUE TITLE
🐛 Bug Report: Console 2.0 Param "url" is not optional

### ISSUE THREAD

**Issue by shengfa** [appwrite/appwrite#4701] opened 2022-11-17 03:26 UTC
### 👟 Reproduction steps

Password Recovery shows error `Param "name" is not optional` after upgrade to appwrite:1.1.0
![image](https://user-images.githubusercontent.com/15109645/202347318-8ec46957-265b-4bb0-a95f-102e46353dfd.png)

### 👍 Expected behavior

It should send a mail to me.

### 👎 Actual Behavior

it shows the error message

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

appwrite:1.1.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by shengfa** [comment] 2022-11-17 03:28
logs with `docker logs appwrite` shows:
```
[Error] Timestamp: 2022-11-17T03:10:15+00:00
[Error] Method: POST
[Error] URL: /v1/account/recovery
[Error] Type: Utopia\Exception
[Error] Message: Param "url" is not optional.
[Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
[Error] Line: 804
```

**Comment by stnguyen90** [comment] 2022-11-17 04:14
Closing as a duplicate of https://github.com/appwrite/console/issues/159. Please make sure to 👍🏼 that issue.

**Closed by stnguyen90** 2022-11-17 04:14 UTC
Labels: bug
