### ISSUE TITLE
🚀 Feature: Allow to get random documents.

### ISSUE THREAD

**Issue by SMARTMICROWORLD** [appwrite/appwrite#7094] opened 2023-11-08 07:54 UTC
### 🔖 Feature description

I am creating social app but unable to fetch posts randomly. Only getting posts in order asc or desc. Kindly add feature to get random documents from collection.

### 🎤 Pitch

If someone wishes to develop an application similar to Facebook, Instagram, YouTube, or other social platforms and desires to incorporate a random document fetching feature, this functionality can significantly enhance their app's user experience.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-11-09 06:25
@SMARTMICROWORLD, thanks for creating this issue. For now, I'm going to close this as a duplicate of https://github.com/appwrite/appwrite/issues/5205. Please make sure to 👍🏼 the other issue.

**Closed by stnguyen90** 2023-11-09 06:25 UTC
