### ISSUE TITLE
🐛 Bug Report:  Functions Connect to Github goes to 404 Page

### ISSUE THREAD

**Issue by sunjianan9900** [appwrite/appwrite#6086] opened 2023-08-31 08:06 UTC
### 👟 Reproduction steps

Create A Function with templates "python - Prompt ChatGPT"

Connect to Github

Whichever one you choose will go to a 404 page:
![image](https://github.com/appwrite/appwrite/assets/10936316/bf876d8e-2cd5-4d1b-a0cd-9ea795ec59a2)

it jump to

https://github.com/apps//installations/new?state=%7B%22projectId%22%3A%2264f0462f890e0693f561%22%2C%22success%22%3A%22https%3A%5C%2F%5C%2Fapi.mydomain.top%5C%2Fconsole%5C%2Fproject-64f0462f890e0693f561%5C%2Ffunctions%5C%2Ftemplates%3Ffrom%3Dgithub%26to%3Dtemplate%26step%3D4%26template%3Dprompt-chatgpt%26templateConfig%3D%257B%2522%2524id%2522%253Anull%252C%2522runtime%2522%253A%2522python-3.9%2522%252C%2522name%2522%253A%2522Prompt%2BChatGPT%2522%252C%2522variables%2522%253A%257B%2522OPENAI_API_KEY%2522%253A%2522sb-33e885d5320d95bd99de3496ff7346d1%2522%252C%2522OPENAI_MAX_TOKENS%2522%253A%2522512%2522%257D%252C%2522repositoryBehaviour%2522%253A%2522new%2522%252C%2522repositoryName%2522%253A%2522prompt-chatgpt%2522%252C%2522repositoryPrivate%2522%253Atrue%252C%2522repositoryId%2522%253Anull%257D%22%2C%22failure%22%3A%22https%3A%5C%2F%5C%2Fapi.mydomain.top%5C%2Fconsole%5C%2Fproject-64f0462f890e0693f561%5C%2Ffunctions%5C%2Ftemplates%3Ffrom%3Dgithub%26to%3Dtemplate%26step%3D4%26template%3Dprompt-chatgpt%26templateConfig%3D%257B%2522%2524id%2522%253Anull%252C%2522runtime%2522%253A%2522python-3.9%2522%252C%2522name%2522%253A%2522Prompt%2BChatGPT%2522%252C%2522variables%2522%253A%257B%2522OPENAI_API_KEY%2522%253A%2522sb-33e885d5320d95bd99de3496ff7346d1%2522%252C%2522OPENAI_MAX_TOKENS%2522%253A%2522512%2522%257D%252C%2522repositoryBehaviour%2522%253A%2522new%2522%252C%2522repositoryName%2522%253A%2522prompt-chatgpt%2522%252C%2522repositoryPrivate%2522%253Atrue%252C%2522repositoryId%2522%253Anull%257D%22%7D&redirect_uri=https%3A%2F%2Fapi.mydomain.top%2Fv1%2Fvcs%2Fgithub%2Fcallback

![image](https://github.com/appwrite/appwrite/assets/10936316/3514c199-b7e2-4ac4-b5e4-990ac042d11c)

### 👍 Expected behavior

create a github project

### 👎 Actual Behavior

open a 404 page

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by istornz** [comment] 2023-08-31 12:19
I can confirm the issue on my server too...

- Migrated from 1.3.8 to 1.4.0, migration without problem.
- Migrated from 1.4.0 to 1.4.1, migration with a lot of warnings (don't know if is it ok or not ?).

**Comment by safwanyp** [comment] 2023-08-31 19:11
Can confirm this issue exists on a fresh install as well.

- Setup on localhost
- Installed 1.4.0
- Upgraded to 1.4.1 and performed migration
- Followed steps in the original post, landed on the 404

**Comment by TorstenDittmann** [comment] 2023-08-31 19:16
Can you check if all environment variables are set?

ref: https://appwrite.io/docs/environment-variables#vcs_(version_control_system)

**Comment by TorstenDittmann** [comment] 2023-08-31 19:26
Checked really quick, it looks like `_APP_VCS_GITHUB_APP_NAME` is missing for you 👍🏻 

https://github.com/appwrite/appwrite/blob/caf53bb7839a087404d1a19c936f891f191790ec/app/controllers/api/vcs.php#L250-L251

**Comment by safwanyp** [comment] 2023-08-31 19:28
@TorstenDittmann I've got a few questions.

`_APP_VCS_GITHUB_APP_NAME` is supposed to be the name of the github app, which quite frankly i don't know about 😅 

What exactly am I looking for?

**Comment by sunjianan9900** [comment] 2023-09-01 01:52
> Checked really quick, it looks like `_APP_VCS_GITHUB_APP_NAME` is missing for you 👍🏻
> 
> https://github.com/appwrite/appwrite/blob/caf53bb7839a087404d1a19c936f891f191790ec/app/controllers/api/vcs.php#L250-L251

After I add _APP_VCS_GITHUB_APP_NAME , it not goes to 404
But what I'm very confused about is that he'll jump straight to the github page and never come back.
My function doesn't create anything either

New Project and Select Existing both jump to this page and nothing more!

![image](https://github.com/appwrite/appwrite/assets/10936316/ac7ebccf-9b12-45e6-bce0-4449a9844a2b)

**Comment by safwanyp** [comment] 2023-09-01 12:13
> After I add _APP_VCS_GITHUB_APP_NAME , it not goes to 404 But what I'm very confused about is that he'll jump straight to the github page and never come back. My function doesn't create anything either
> 
> New Project and Select Existing both jump to this page and nothing more!

Can confirm this. It goes to the app installation page, and does nothing. Going back to the console shows no new function. Nothing in my github profile as well.

**Comment by stnguyen90** [comment] 2023-09-01 17:07
@sunjianan9900, would you please try to uninstall the github app from your [github account](https://github.com/settings/installations) and then try connecting from appwrite again?

**Comment by acidlake** [comment] 2023-09-01 23:31
i'm having the same issue, i think it would be great that this get added to the documentation for the self hosting section, even after an upgrade from 1.3.x to 1.4.x that app never came up, and was a missing env variable, so i think it would be great that this get added to the documentation, what to put on the github app creation etc, after it send me to install appwrite on github, it just stay there, if i go back to create a function, and i choose github ( after is already install on appwrite ) it does the same process as if is going to be installed again

**Comment by stnguyen90** [comment] 2023-09-06 18:51
@sunjianan9900, do you still need help connecting to GitHub? FYI, I'll need to close this due to inactivity soon.

@acidlake, I recommend joining us on [Discord](https://appwrite.io/discord) if you still need help.

**Comment by hinnerkweiler** [comment] 2023-09-07 21:36
I can confirm (after spending the entire evening) reinstalling the app does not solve this.

**Comment by stnguyen90** [comment] 2023-09-12 17:43
Closing due to inactivity. Anyone else having troubles should create a support post on [Discord](https://appwrite.io/discord).

**Closed by stnguyen90** 2023-09-12 17:43 UTC
Labels: bug, functions

**Comment by NeKoFu** [comment] 2023-12-09 22:16
Documentation is unclear. 
The value of **_APP_VCS_GITHUB_APP_NAME** needs to be the application `slug`. 
For example, if your application is named **My Amazing App**, the value of this variable will be:
_APP_VCS_GITHUB_APP_NAME=`my-amazing-app`
