### ISSUE TITLE
🐛 Bug : Appwrite with typescript react app throws error

### ISSUE THREAD

**Issue by learncodingforweb** [appwrite/appwrite#5706] opened 2023-06-14 17:12 UTC
### 👟 Reproduction steps

1. npm create vite@latest, create react app with typescript
2. npm i appwrite 
3. create Appwriteapi.ts file with content
```
import { Client, Account } from "appwrite";

const client = new Client();

const account = new Account(client);

client
    .setEndpoint('http://localhost:8080/v1') // Your API Endpoint
    .setProject('6488a7219429fdf30941') // Your project ID
;

export {
    client,
    account
}
```
getting warning messages, without any typescript autocomplete.

**Could not find a declaration file for module 'appwrite'. 'node_modules/appwrite/dist/esm/sdk.js' implicitly has an 'any' type.
  There are types at 'node_modules/appwrite/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'appwrite' library may need to update its package.json or typings.ts(7016)**

### 👍 Expected behavior

resolve warning messages, so that typescript function can detect function details, like autocomplete

### 👎 Actual Behavior

**Could not find a declaration file for module 'appwrite'. 'node_modules/appwrite/dist/esm/sdk.js' implicitly has an 'any' type.
  There are types at 'node_modules/appwrite/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'appwrite' library may need to update its package.json or typings.ts(7016)**

warning messages, without function autocomplete exist in typescript.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

using appwrite self hosting on ubuntu22.05 LTS
`` Linux notebook 5.19.0-43-generic #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon May 22 13:39:36 UTC 2 x86_64 x86_64 x86_64 GNU/Linux``

docker image
```
docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:1.3.7
```

package.json
```
"dependencies": {
    "appwrite": "^11.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }
```

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by TristonWasik** [comment] 2023-06-18 08:29
I also having this issue with a fresh Vite react project

**Comment by TristonWasik** [comment] 2023-06-19 00:54
I started a PR for this issue in the [sdk repo](https://github.com/appwrite/sdk-for-web/pull/59)

**Comment by joeyouss** [comment] 2023-06-20 10:06
Thank you for the PR @TristonWasik , we will look into it ASAP.

**Comment by joeyouss** [comment] 2023-06-20 10:29
I have left a comment there on the PR @TristonWasik

**Comment by stnguyen90** [comment] 2023-06-28 23:41
Closing as a duplicate of https://github.com/appwrite/sdk-for-web/issues/54

**Closed by stnguyen90** 2023-06-28 23:41 UTC
Labels: bug, work in progress
