### ISSUE TITLE
🐛 Bug Report: Inconsistency of using $id between createDocument and updateDocument

### ISSUE THREAD

**Issue by step135** [appwrite/appwrite#7345] opened 2023-12-27 17:00 UTC
### 👟 Reproduction steps

`db.createDocument( db, collection, id, { "$id": id, "name": "John"} )`
`db.updateDocument( db, collection, id, { "$id": id, "name": "John"} )`

The first call is throwing error whereas the second one is passing. Including $id directly to data can mean simplification of so complicated method regarding many entries. We know that every variable starting `$` is not part of standard fields in collection, so it would be more elegant to pass in directly in JSON data.

### 👍 Expected behavior

I would expect the same behavior.

### 👎 Actual Behavior

The first call is throwing error whereas the second one is passing.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-12-27 17:26
@step135, thanks for raising this issue! 🙏🏼 This looks like a duplicate of https://github.com/appwrite/appwrite/issues/4802. As such, I would suggest you add a 👍🏼 to that issue as I'll be closing this one.

**Closed by stnguyen90** 2023-12-27 17:26 UTC
Labels: bug
