### ISSUE TITLE
🐛 Bug Report: Boolean attribute doesn't store default false value

### ISSUE THREAD

**Issue by gigili** [appwrite/appwrite#4980] opened 2023-01-10 14:18 UTC
### 👟 Reproduction steps

* Create a collection
* Go to attributed tab
* Click on `Create attribute`
* In the dialog select `Type` to be `boolean` and choose `false` as a default value.

### 👍 Expected behavior

When the boolean attribute with the default value of false gets created and a new documented added without a value provided for that (non required) attribute it should set it's value to `false` and not `n/a`

### 👎 Actual Behavior

When creating a Boolean attribute with the default value of `false` that value doesn't get recorded and when you create a new document in the collection and don't manually provide the value for that boolean field it sets it to `n/a` instead of `false`.

When looking at the overview for that attribute the default value is  shown as empty both in the dialog and in the table.

The same is not the case for true, that one works just as expected.

![appwrite-attribute-error-1](https://user-images.githubusercontent.com/2153382/211570224-68402534-c576-4262-aa38-3d7fbfef5bd6.png)

![appwrite-attribute-error-2](https://user-images.githubusercontent.com/2153382/211570260-0b295e04-7ed7-4099-8557-53e6ab2a9c35.png)

![appwrite-attribute-error-3](https://user-images.githubusercontent.com/2153382/211570293-6236213d-459e-444f-a481-2f15dfcb4319.png)

![appwrite-attribute-error-4](https://user-images.githubusercontent.com/2153382/211570542-2d93a015-1f7c-4f35-8528-6127bbc34cac.png)

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

* Docker version 20.10.22, build 3a2c30b
* docker-compose version 1.25.0, build unknown
* Linux 5.4.0-135-generic
* Ubuntu 20.04.5 LTS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by harshmange44** [comment] 2023-01-10 15:24
@gigili @stnguyen90 Hey, I'd like to fix this

**Comment by stnguyen90** [comment] 2023-01-10 17:57
Closing as this looks like a duplicate of https://github.com/appwrite/appwrite/issues/4712 and should be resolved in the next release

**Closed by stnguyen90** 2023-01-10 17:57 UTC
Labels: bug
