### ISSUE TITLE
🚀 Feature: Short Links in Emails

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#6261] opened 2023-09-16 05:41 UTC
### 🔖 Feature description

Add an optional support for Short Links with default or custom domains for verification, password reset, magic login & invite links.
This can be used in conjunction with redirection to actual links.

Currently this isn't possible by any means (afaik) due to no middleware config.

---

This:
https://cloud.xyz.app/auth/verify?userId=24381aa5adefc123bcde&secret=ad12cd934567ef8910ab23c4de56fa78b90123c456ef7890bcd123ef45gh67i89j012k345lmno678pqr90a12b34cd5678ef9012gh34ij56kl78mn90op12qr34st56uv78wx90yz12ab34cd56&expire=2045-12-34+10%3A23%3A45.678

could be:
https://xyz.app/auth/8jKwZtQ4
https://auth.xyz.app/8jKwZtQ4

### 🎤 Pitch

Example usecase:
`1.4x` allows email customisation where we can hide the long links under a button or a view.

However the standard usecase is also providing the complete link at the end, usually with a placeholder text like: "If the above doesn't work, copy and paste this url in your browser".

Here the long link doesn't really look good and a short version would really look good.

A `{{ short_link }}` short code can be added in the SMTP Settings.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by behicsakar** [comment] 2023-09-17 09:23
I totally agree with that. It is going to be very useful feature.

**Comment by Haimantika** [comment] 2023-09-18 10:47
Thanks @ItzNotABug for raising this issue. This is a good suggestion :)
Will discuss this internally with the team and be back with more updates

**Comment by stnguyen90** [comment] 2023-09-22 16:30
@ItzNotABug, this seems like a duplicate of https://github.com/appwrite/appwrite/issues/4311. Can this closed in favor of the other one?

**Comment by ItzNotABug** [comment] 2023-09-22 16:37
@stnguyen90 The linked issue doesn't really look like a duplicate.
That issue describes the layout issue which "could be solved" by using short links but doesn't mention a pitch or any other info. for the same.

Maybe lets keep this one open? 😅

**Comment by stnguyen90** [comment] 2023-09-26 00:45
@ItzNotABug, both issues raise the problem of long URLs in emails so it would be best to consolidate into 1 issue so that upvotes are tracked in 1 issue. I do think it would be best if you 👍🏼 the other issue and comment with your use case/requirement of needing to also provide the full link to users, but you don't want it to be too long.

**Comment by ItzNotABug** [comment] 2023-09-26 05:16
Added more context & use-case to #4311, Closing this one.

**Closed** 2023-10-05 00:37 UTC
