### ISSUE TITLE
🐛 Bug Report:  Query Select has issue when selecting only attributes it seems that Document.fromMap model has limitation on handling internal attributes

### ISSUE THREAD

**Issue by moshOntong-IT** [appwrite/appwrite#7235] opened 2023-12-03 13:28 UTC
### 👟 Reproduction steps

``` dart
 final consultationList =
        await ref.read(consultationRepoProvider).getConsultationList(
      queries: [
        Query.select([
          r'$id',
          'orgRef',
          'clinicRef',
          'startDate',
          'endDate',
          'startTime',
          'endTime'
        ])
      ],
    );
 ```
    
These are the attributes I want to get. However there is an unhandled exception called  Null is not a subtype of type List<dynamic>. When I debugging my flutter, it actually fetch the data:
    
    
<img width="296" alt="image" src="https://github.com/appwrite/appwrite/assets/57244338/ce7d6f3f-eaa7-4c93-808a-3e50f9393c28">

>Below is the information of error:

<img width="543" alt="image" src="https://github.com/appwrite/appwrite/assets/57244338/96dfb000-42f5-4715-b973-e5e2e8683c69">

>Below is the screen recorded

https://github.com/appwrite/appwrite/assets/57244338/7450ec10-7e63-4efa-abde-b1a86344cdde

### 👍 Expected behavior

The Document.fromMap must handle the result of using Query.select

### 👎 Actual Behavior

Throwing an error I think it is relates on internal attributes

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by moshOntong-IT** [comment] 2023-12-03 13:31
I fix the problem to add all the internal attributes. I thought that the QUery.select must includes internal attributes as default

**Comment by moshOntong-IT** [comment] 2023-12-03 13:31
<img width="152" alt="image" src="https://github.com/appwrite/appwrite/assets/57244338/0f17f20a-968e-41f5-b8de-f74343ea1158">

**Comment by stnguyen90** [comment] 2023-12-11 18:22
@moshOntong-IT, thanks for creating this issue! 🙏🏼 Looks like this is a duplicate of https://github.com/appwrite/appwrite/issues/6158 so I'm going to close this.

> I thought that the QUery.select must includes internal attributes as default

There was a [request](https://github.com/appwrite/appwrite/issues/5376) to not return system attributes.

**Closed as not planned by stnguyen90** 2023-12-11 18:22 UTC
Labels: bug
