### ISSUE TITLE
🐛 Bug Report: [Console] - Can't create function

### ISSUE THREAD

**Issue by vincentnacar02** [appwrite/appwrite#5990] opened 2023-08-15 05:14 UTC
### 👟 Reproduction steps

- Go to the functions tab
- Create a new function
- Populate name and select runtime
- Hit next

### 👍 Expected behavior

Should proceed to next step

### 👎 Actual Behavior

Returns Param "name" is not optional
![image](https://github.com/appwrite/appwrite/assets/11674307/ce9c6c76-4ecb-4274-a8c6-a59c1f0e965d)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by safwanyp** [comment] 2023-08-16 05:38
Works fine for me. Tested on 3 separate devices. 
Keep in mind that Appwrite Cloud undergoes backups every day, so if you face a _weird_ issue, it's probably because of that. Trying again in 30-40 mins should work :D

**Comment by stnguyen90** [comment] 2023-08-18 00:56
@vincentnacar02, thanks for raising this issue! 🙏🏼 This looks like a duplicate of https://github.com/appwrite/appwrite/issues/4847 so I'm going to close this for now. You can raise a new issue after 1.4.0 if the problem still happens.

**Closed by stnguyen90** 2023-08-18 00:56 UTC
Labels: bug, ui/ux
