### ISSUE TITLE
🐛 Bug Report: functions deployment -- Signing key cannot be empty

### ISSUE THREAD

**Issue by RoeyZada-airis** [appwrite/appwrite#8861] opened 2024-10-25 18:18 UTC
### 👟 Reproduction steps

- On self-hosting appwrite.
- create an environment 
- create new function 
- deploy function

an error you be shown 
![Image](https://github.com/user-attachments/assets/0283a953-9081-4bdb-a96f-683a3b7afebc)

### 👍 Expected behavior

this should be deployed and working 

### 👎 Actual Behavior

when deploying function, I always getting this error "Signing key cannot be empty" - also when using manual upload 

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite 6.0.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by DH-555** [comment] 2024-10-25 18:43
@RoeyZada-airis What's the runtime you're running? How do you have installed appwrite? Do you can provide the logs for the openruntimes-executor container? You can get it by running ```docker compose logs openruntimes-executor```

**Comment by RoeyZada-airis** [comment] 2024-10-27 09:28
@DH-555 thank you david! 

We didn’t configured OpenSSL key is it mandatory for on-prem?

regarding logs: 
```
openruntimes-executor  | Pulling v4 images...
openruntimes-executor  | Warming up Node.js 16.0 environment...
openruntimes-executor  | Warming up PHP 8.0 environment...
openruntimes-executor  | Warming up Ruby 3.0 environment...
openruntimes-executor  | Warming up Python 3.9 environment...
openruntimes-executor  | Successfully Warmed up PHP 8.0!
openruntimes-executor  | Successfully Warmed up Node.js 16.0!
openruntimes-executor  | Successfully Warmed up Python 3.9!
openruntimes-executor  | Successfully Warmed up Ruby 3.0!
openruntimes-executor  | Image pulling finished.
openruntimes-executor  | Starting maintenance interval...
openruntimes-executor  | Maintenance interval started.
openruntimes-executor  | Starting stats interval...
openruntimes-executor  | Stats interval started.
openruntimes-executor  | Executor is ready.
```

**Comment by DH-555** [comment] 2024-10-28 16:52
I'm closing this since you confirmed through discord that the solution was setting the OpenSSL key env variable.

Context for future users: https://discord.com/channels/564160730845151244/1298190925666979850

**Closed by DH-555** 2024-10-28 16:52 UTC
Labels: bug, question, product / functions
