### ISSUE TITLE
🐛 Bug Report: Error when installing node modules with appwrite functions.

### ISSUE THREAD

**Issue by Maxbrt18** [appwrite/appwrite#3303] opened 2022-05-29 10:16 UTC
### 👟 Reproduction steps

I have created a function to scrape data (with **puppeteer**) from a site and I want to run my function every day with appwrite functions. During the build of my function I have an error (see below) which is due to the installation of node js modules.

### 👍 Expected behavior

This should install puppeteer module for nodejs.

### 👎 Actual Behavior

Instead I have an error in the build:

```
Docker Error: npm notice 
npm notice New major version of npm available! .0 -> .0
npm notice Changelog: 
npm notice Run `npm install -g npm@8.11.0` to update!
npm notice 
npm ERR! code 
npm ERR! path /usr/builds/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! The chromium binary is not available for arm64.
npm ERR! If you are on Ubuntu, you can install with: 
npm ERR! 
npm ERR!  sudo apt install chromium
npm ERR! 
npm ERR! 
npm ERR!  sudo apt install chromium-browser
npm ERR! 
npm ERR! /usr/builds/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:123
npm ERR!                     throw new Error();
npm ERR!                     ^
npm ERR! 
npm ERR! Error
npm ERR!     at /usr/builds/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:123:27
npm ERR!     at FSReqCallback.oncomplete (node:fs:194:21)

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-29T10_06_29_683Z-debug.log
```

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I am using an Oracle Cloud machine running on the latest version of Ubuntu. It is an ARM machine on which I can manually run the function usually.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2022-05-30 03:19
The core team may have plans to introduce lifecycle hooks that allow you to run things before building. If/when that happens, you can run `apt install chromium` before the appwrite build occurs.

For now, you may be able to update your package.json to add a [preinstall script](https://docs.npmjs.com/cli/v8/using-npm/scripts#pre--post-scripts) to run `apt install chromium`.

**Comment by Maxbrt18** [comment] 2022-05-30 18:40
Thanks for your answer. I tried to add a preinstall script in my package.json but it doesn't seem to work.

**Comment by stnguyen90** [comment] 2022-05-30 19:35
> Thanks for your answer. I tried to add a preinstall script in my package.json but it doesn't seem to work.

What went wrong?

**Comment by Maxbrt18** [comment] 2022-05-31 08:00
I added a precompress script in package.json : (I tried with only `apt install chromium` and like below but none works).
```
"scripts": {
    "precompress": "apt install chromium && apt install chromium-browser",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```

But I still get the error in Appwrite :
```
Docker Error: npm notice 
npm notice New major version of npm available! .0 -> .0
npm notice Changelog: 
npm notice Run `npm install -g npm@8.11.0` to update!
npm notice 
npm ERR! code EJSONPARSE
npm ERR! path /usr/builds/package.json
npm ERR! JSON.parse Unexpected token "}" (0x7D) in JSON at position  while parsing near "...{\n    \"puppeteer\"\n  },\n  \"keywords\": [],..."
npm ERR! JSON.parse Failed to parse JSON data.
npm ERR! JSON.parse Note: package.json must be actual JSON, not just JavaScript.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-31T07_56_21_069Z-debug.log
```

**Comment by stnguyen90** [comment] 2022-06-01 03:24
Womp. It didn't work for me either. I got a timeout error for some reason. I was able to run it if I ran `npm i` manually in the container but it just doesn't work  during the build. The more I think about it, though, this won't work long term because once the runtime container is removed due to inactivity, chromium will no longer be installed.

**Comment by stnguyen90** [comment] 2022-06-03 20:31
Related discussion: https://github.com/appwrite/appwrite/discussions/2985

**Comment by Maxbrt18** [comment] 2022-06-04 20:38
Thanks for your help

**Comment by stnguyen90** [comment] 2022-08-15 22:13
@Maxbrt18, the problem looks to be the need for OS-level dependencies, which looks like a duplicate of #1037. I'm going to close this issue as duplicate, but please feel free to upvote #1037.

**Closed by stnguyen90** 2022-08-15 22:13 UTC
Labels: bug
