### ISSUE TITLE
🐛 Bug Report: User identity attached to user even though account with matching email exists

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#7190] opened 2023-11-22 01:42 UTC
### 👟 Reproduction steps

1. Create an account like person1@gmail.com
2. Create an account like person2@gmail.com
3. Create an email session with person1@gmail.com
4. Create an OAuth2 session with person2@gmail.com to create an identity for person1@gmail.com

### 👍 Expected behavior

Error occurs because an account with matching email already exists

### 👎 Actual Behavior

The identity is created successfully.

This check:

https://github.com/appwrite/appwrite/blob/5a715ff68cba4171bf3473eabc83b84a4ae5876c/app/controllers/api/account.php#L550-L560

should probably also check the users collection.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Vedsaga** [comment] 2023-11-23 05:14
Sure, here is the corrected grammar for the text:

`Case 1:`

If an account was created using email and password, the email is marked as unverified. (This is correct.)

`Case 2:`

If a user logs in via OAuth services and there is no existing account with the same email, the email is marked as verified. (This is correct.)

`Case 3:`

If a user logs in again using any OAuth service (Google, Facebook, Apple) and the email address matches the one associated with the OAuth provider, the email should be marked as verified. (This was the expected behavior.) However, in some cases, the email is not marked as verified when the user logs in via OAuth and an account already exists with the given email address. This could be due to a bug in the system or an error in the OAuth provider's data.

**Closed** 2023-12-28 00:59 UTC
Labels: bug, auth
