### ISSUE TITLE
🐛 Bug Report: docker-compose set wrong config file path

### ISSUE THREAD

**Issue by yuvalbl** [appwrite/appwrite#5289] opened 2023-03-28 13:30 UTC
### 👟 Reproduction steps

I've installed appwrite using the recommended step for UNIX:
```
docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:1.2.1
```

Note that the second line specify path `/usr/src/code/appwrite`, however when I tried to stop the docker-compose, I've seen there is no `docker-compose.yml` file in that location, so I couldn't pause or shut it down

```
➜ ~ docker compose ls
NAME                STATUS              CONFIG FILES
appwrite            running(20)         /usr/src/code/appwrite/docker-compose.yml

➜ ~ docker compose stop
no configuration file provided: not found
```

After some search I've found the yml file in a different location - `/Users/MY_USER/appwrite/docker-compose.yml`,
and I was able to use that to shut down docker compose

Notes:
1. I've seen this issue here on the docker repo, also triggered by appwrite- https://github.com/docker/for-win/issues/12155 
2. I use MacOS, and I assume the issue here is about Apple's [System Integrity Protection](https://support.apple.com/en-us/HT204899) which prevent writing to `/usr/` (even with root privileges). Note that 3rd party can still write to `/usr/local
`, which might be a possible solution for this issue

I use MacOS Venture version 13.0.1

### 👍 Expected behavior

Appwrite Docker compose should be allowed to stop  without specifying yml location

### 👎 Actual Behavior

Appwrite Docker compose cannot be stopped without finding and specifying yml location

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-03-29 00:48
@yuvalbl thanks for raising this isssue! 🙏🏼 

So, this is happening because, during the installation process, the installation container has the docker compose files in `/usr/src/code/appwrite` and starts the containers from in there. Because of this, docker thinks the `docker-compose.yml` file is in `/usr/src/code/appwrite/`, but that path is actually mounted in from the host machine.

> After some search I've found the yml file in a different location - /Users/MY_USER/appwrite/docker-compose.yml

You were in `/Users/MY_USER` when you ran the install command which creates the `appwrite` folder and the compose files inside it.

Anyways, I think this is actually a duplicate of https://github.com/appwrite/appwrite/issues/4700. Would it be okay to close this and you can 👍🏼 the original issue?

**Closed** 2023-04-30 19:41 UTC
Labels: bug
