### ISSUE TITLE
🐛 Bug Report: Bucket created with permissions Bucket Level/rw to role:guest refuses access to role:guest 

### ISSUE THREAD

**Issue by superseby2** [appwrite/appwrite#3639] opened 2022-08-03 17:49 UTC
### 👟 Reproduction steps

- create a new bucket
- set permissions to bucket level
- set read permissions to role:guest
- set write permissions to role:guest

### 👍 Expected behavior

Not-authenticated user should be able to upload to bucket

### 👎 Actual Behavior

I've got 401 code
AppwriteException: User (role: guest) missing scope (files.write)
    at Appwrite.<anonymous> (http://localhost:3000/node_modules/.vite/deps/appwrite.js?v=ef65426d:1973:17)
    at Generator.next (<anonymous>)
    at fulfilled (http://localhost:3000/node_modules/.vite/deps/appwrite.js?v=ef65426d:488:24)

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by superseby2** [comment] 2022-08-03 17:52
Everything works as expected if I create first an anonymous session.

**Comment by stnguyen90** [comment] 2022-08-04 00:34
Hi @superseby2 ! Thanks for opening this issue! 🙏 This is actually expected behavior. A session is required for all write operations like creating a document, uploading a file, or executing a function. This is to help with rate limiting.

As you have discovered, the best approach to not requiring a user to input a username and password is to create an anonymous session first.

**Comment by superseby2** [comment] 2022-08-04 04:23
Oh .. I see ! Thanks for your reply ! It might be intesting to add this in the permissions section of the documentation as I  don't seem to find anything about this behaviour. 

Thx again!

**Comment by stnguyen90** [comment] 2022-08-04 04:32
@superseby2, did you see the notice at the end of [this](https://appwrite.io/docs/storage#permission) section? If so, what do you think we can do to make it clearer?

**Comment by stnguyen90** [comment] 2022-08-06 04:01
@superseby2, do you have any other feedback? Can this issue be closed?

**Comment by superseby2** [comment] 2022-08-09 04:40
Hello @stnguyen90 , 

The notice is so obvious that I missed it ;)
I would put it on the top though just to avoid people like me stop at "As buckets are very similar to collections we have in the database, we have a similar permission model."

Also, it might be interested to have a warning in the console reminding, when permissions are set to role:all or role:guest, that anonymous session will be needed as well or even better when the 401 is returned (aka : "you might need to create an anonymous session" )

Thanks

**Comment by stnguyen90** [comment] 2022-08-09 06:29
@gewenyu99, what do you think about moving the permission notice up above file level permission?

**Comment by gewenyu99** [comment] 2022-09-27 21:04
@stnguyen90 Can users now write as a guest with the correct permissions? Idk if this issue is still relevant.

**Comment by stnguyen90** [comment] 2022-09-28 03:06
@gewenyu99, yes, guests should be able to create files now if granted the permissions.

**Comment by gewenyu99** [comment] 2022-10-07 20:31
Okay closing this because this shouldn't be relevant anymore because guests can write. I just confirmed this, too, when I was reviewing hacktoberfest PRs

**Closed by gewenyu99** 2022-10-07 20:31 UTC
Labels: bug
