### ISSUE TITLE
🐛 Bug Report: Queries doesn't work on non-ascii characters 

### ISSUE THREAD

**Issue by neolizee** [appwrite/appwrite#8064] opened 2024-05-02 13:58 UTC
### 👟 Reproduction steps

The search for documents with such parameters returns an empty result if the keyword is in Cyrillic:

`const response = await databases.listDocuments('<DATABASE_ID>', '<COLLECTION_ID>', [Query.or( [ Query.search("titleString", "keyword"), Query.contains("altArrayTitleString", "Кириллица") ] )])`

### 👍 Expected behavior

It works if the characters are in ASCII, but does not work with Cyrillic. The documents found should be returned in all cases.

### 👎 Actual Behavior

Returns an empty list of documents.

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2024-05-02 16:37
@neolizee, thanks for creating this issue! 🙏🏼 This seems like a duplicate of https://github.com/appwrite/appwrite/issues/7232. It would be best to add a 👍🏼 on the issue as this one will be closed as a duplicate.

**Closed by stnguyen90** 2024-05-02 16:37 UTC
Labels: bug
