### ISSUE TITLE
🐛 Bug Report: System malfunction and 500 Server error when ecceding the string length of an attribute

### ISSUE THREAD

**Issue by drmilde** [appwrite/appwrite#2998] opened 2022-03-23 15:42 UTC
### 👟 Reproduction steps

When I add an document to the database, that exceeds the max number of characters of a string attribute
(default is 255, if the string value is longer than 255), I receive a 

500 Server error

### 👍 Expected behavior

It should just give a warning and clip the string to the maximum size. 

### 👎 Actual Behavior

The system is broken ... no new Documents can be created and attributes remain in status processing.
Once I restart appwrite, the system is back to normal function.

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment] 2022-04-01 11:16
We probably can't implement automatic string trimming, as we can't expect all users to have this functionality. If you want to achieve this, you can put `createDocument` in a try/catch, and depending on the error, trim it on the client-side.

With that said, the error should be 400 instead of 500, and should not break the whole Appwrite.

After investigation, it looks to be related to this issue: https://github.com/appwrite/appwrite/issues/2703
(same problem, but with array string attribute)

A PR has been created and merged already: https://github.com/utopia-php/database/pull/112
Resolving the missing check for string length, because it was set to `0` previously, meaning any length is allowed: https://github.com/utopia-php/database/pull/112/files#diff-f825608327bc9f65523cfade0df2d65631df23c89b91a59bcc5f802aac630a3eR238-R239

Once a new database version is released and Appwrite upgrades to a new version, the issue should be resolved automatically. I'll keep an issue open for now.

**Comment by stnguyen90** [comment] 2022-05-20 16:05
Duplicate of https://github.com/appwrite/appwrite/issues/2681 and should be fixed now.

**Closed** 2022-07-22 23:32 UTC
Labels: bug
