### ISSUE TITLE
🚀 Feature: Support for  JSON  and Datetime as attribute and visualizer for creating  relations in the database !!

### ISSUE THREAD

**Issue by arunavabasucom** [appwrite/appwrite#3018] opened 2022-03-26 17:44 UTC
### 🔖 Feature description

👉In the admin panel, there is an option to select the DateTime value or when we last update the data in the document or create the document and also there is no option to add a JSON as an attribute. 😄 
👉it is very handy if there is a visualizer to create relations between objects in the console.

### 🎤 Pitch

If these features are implemented that's very easy for users to create the APIs and used that.

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment] 2022-03-28 07:52
Regarding date time, we have been recently discussing such an attribute type, alongside `updatedAt` and `createdAt` attributes.

I will see what we can do about JSON. What would be the difference between a JSON attribute and a `string` one? You can do a method like `JSON.stringify()` on the client-side and store it in string attribute. Parsing afterwards would be as simple as `JSON.parse()`.

Interesting idea about visualizing relations. We currently don't support native relations, but you can store IDs in string attributes. We do have a plan to add relations in the figure, but no ETA yet. Adding visualizer into Console is a cool idea tho, might be a great iteration.

**Comment by TorstenDittmann** [comment] 2022-09-15 13:05
The DateTime Attribute got implemented and released with Appwrite 1.0.0 🥳 

Thank you for your contribution 🙏🏻  You can read more [here](https://appwrite.io/1.0).

**Comment by johannesschobel** [comment] 2022-11-04 10:43
Dear @TorstenDittmann ,
i guess, this issue / feature request is not completed. I think, some kind of `object` (`JSON`) type would be very handy! Can you please consider adding this feature as well?

**Comment by fliitor** [comment] 2023-01-27 10:20
+1

**Comment by tremendus** [comment] 2023-02-20 14:31
Not storing JSON is a huge omission, IMHO. Yes you can stringify as save, as @Meldiron mentioned, but since you have to set a max string length in your collection design and objects/arrays are flexible structures, knowing how long that string might be is very difficult.

**Comment by nimit2801** [comment] 2023-05-09 14:09
> Not storing JSON is a huge omission, IMHO. Yes you can stringify as save, as @Meldiron mentioned, but since you have to set a max string length in your collection design and objects/arrays are flexible structures, knowing how long that string might be is very difficult.

Exactly what I thought when I wanted to store maps coordinates for an event. I think JSON feature is really needed!

**Comment by been-there-done-that** [comment] 2023-07-27 12:36
+1

**Comment by nimit2801** [comment] 2023-07-27 14:04
please re-open this, we should discuss more on this.

**Comment by step135** [comment] 2024-01-08 14:54
Looks like they ignore it.

**Comment by TorstenDittmann** [comment] 2024-01-11 09:53
> Not storing JSON is a huge omission, IMHO. Yes you can stringify as save, as @Meldiron mentioned, but since you have to set a max string length in your collection design and objects/arrays are flexible structures, knowing how long that string might be is very difficult.

I would set the max length of string attributes, but I see why this could be problematic especially displaying such data in UI.

**Comment by KevinHaendel** [comment] 2024-06-11 11:09
The problem is not only that stringified JSONs are limited in character length, but a built-in type could also allow for searching/filtering within JSON properties in the collection. MariaDB also natively [supports JSON data types](https://mariadb.com/kb/en/json-data-type/), as well as setting constraints to [validate against JSON Schemas](https://mariadb.com/kb/en/json_schema_valid/) if needed.

I know that all of this could be accomplished by creating a new collection with the corresponding relations, but sometimes unstructured but still queryable data comes in very handy, especially for very dynamic data.

**Comment by johnstack01** [comment] 2024-08-01 21:32
This is very handy indeed. It reduces reads and overall complexity significantly. It'd be very nice to have object type so we don't have to stringify or parse JSON strings.

It would basically be subcollections in firestore terms, and seeing as you aim to be the alternative I don't see why this would be omitted.

I for one would love this feature!

**Comment by stnguyen90** [comment] 2024-08-20 03:50
Closing as this issue's scope is too wide.

**Closed by stnguyen90** 2024-08-20 03:50 UTC
Labels: enhancement
