### ISSUE TITLE
🚀 Feature: Require CAPTCHA mechanism in account creation API 

### ISSUE THREAD

**Issue by SanthoshS20** [appwrite/appwrite#6311] opened 2023-09-23 05:21 UTC
### 🔖 Feature description

𝑫𝒆𝒔𝒄𝒓𝒊𝒑𝒕𝒊𝒐𝒏: There is no CAPTCHA mechanism implemented in the account creation API.

**It results in the following categories,**
1. Automated bot attacks - Automated bots can easily generate a large number of fake accounts. Automated bot attacks can also strain your server. 
2. Resource Consumption - Resource consumption will increase in a short period of time.
3. Increase cost to the company - Creation of multiple accounts will increase the company cost
4. Increase database storage - Database storage will be increased and it doesn't contain valid user profile.

### 🎤 Pitch

This feature helps to block the attackers from automated bot attacks results in resource consumption, server crash, increase the cost to the company and database will contains fake accounts.

𝑺𝒐𝒍𝒖𝒕𝒊𝒐𝒏: Implement CAPTCHA mechanism in the account creation API. It will reduce the creation of fake accounts in appwrite.

𝑷𝒓𝒊𝒐𝒓𝒊𝒕𝒚: High
𝑺𝒆𝒗𝒆𝒓𝒊𝒕𝒚: Medium

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-09-26 00:18
@SanthoshS20, thanks for creating this issue! 🙏🏼 It seems like this is a duplicate of https://github.com/appwrite/appwrite/issues/5384. As such, can we close this and you can 👍🏼 the other issue?

**Comment by SanthoshS20** [comment] 2023-10-01 05:45
Yeah Sure. We can close it

**Closed** 2023-10-10 19:20 UTC
Labels: auth, feature
