### ISSUE TITLE
🚀 Feature: Remote Config

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#5209] opened 2023-03-10 11:56 UTC
### 🔖 Feature description

It would be create if we could add a similar implementation to Firebase's `Remote Config` in Appwrite.
A similar discussion from 2021 exists for this feature [here](https://github.com/appwrite/appwrite/discussions/2389) but there's no update on that.

Generic Idea - 
1. This would require add a new section to the AppWrites dashboard
2. A separate collection / document like screen UI that shows existing configs (if any).
3. A button to create a new config type with available types : `Integer`, `Boolean`, `String`, `JSON`.
We can add a default values OR use the `in-app default` (similar to firebase).
If the user selects `in-app default`, the client sdk must have a default value set in the app.
4. Use built-in caching/local-storage for saving the latest fetched configs.
5. Use similar api like `minimumFetchIntervalInSeconds` via client side to limit frequent network requests.

### 🎤 Pitch

1. Considering Appwrite as an open-source Firebase alternative, it'd make sense to add `RemoteConfig` so that we can change the behavior and appearance of the app without pushing app update.
2. I mean, why not!? 😉 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-03-10 19:34
@ItzNotABug, thanks for creating this issue! 🙏🏼 Is this a duplicate of https://github.com/appwrite/appwrite/issues/323? If so, would you please close this as a duplicate and 👍🏼 the other issue?

**Comment by ItzNotABug** [comment] 2023-03-11 06:51
Hi @stnguyen90,
I'm not 100% sure if that linked issue is the duplicate of what I suggested.

The linked issue seems to be about "managing" configs, probably the backend configs (I'm not sure)?.
Also, it does not seem to be anywhere similar to what I've described or to Firebase's RC.

**Comment by stnguyen90** [comment] 2023-03-11 20:07
@ItzNotABug, in order to have remote configs, you need a way to manage them (create, update, delete them). The configuration API would support A/B testing, which is what feature flag APIs like Firebase's Remote Configs can be used for.

**Comment by ItzNotABug** [comment] 2023-03-12 05:00
I see,
Thanks for the explanation.

But do we have any ETA or any info. for this feature?
Is this on any future release milestones or roadmaps?

**Comment by stnguyen90** [comment] 2023-03-15 23:04
@ItzNotABug, no ETA at the moment. Make sure to 👍🏼 the other issue.

**Closed by stnguyen90** 2023-03-15 23:04 UTC
Labels: feature
