### ISSUE TITLE
🐛 Bug Report: Attribute Error

### ISSUE THREAD

**Issue by indratrisnar** [appwrite/appwrite#5870] opened 2023-07-24 01:43 UTC
### 👟 Reproduction steps

i have collection, and there are attribute "completed" with type boolean. i want to change attribute name and type. so i delete it first then success.
i create attribute "status" with type String the success.
now i want to update status value.
when i click button save, show error unknown attribute "completed", but there is no attribute "completed". i have delete it before.

### 👍 Expected behavior

when update document: success

### 👎 Actual Behavior

Invalid document structure: unknown attribute "completed",

<img width="452" alt="image" src="https://github.com/appwrite/appwrite/assets/65453071/6719437b-74d1-4b94-af09-d4cca36ce817">

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

AppWrite cloud, 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment] 2023-07-24 14:01
Hi @indratrisnar thanks for bringing this issue up, I just tried it on my end, and everything seems to work as expected. Can you refresh and try again?

**Comment by stnguyen90** [comment] 2023-08-18 02:09
@indratrisnar, thanks for creating this issue! 🙏🏼 This sounds like the same problem as https://github.com/appwrite/appwrite/issues/4847 which was caused by some leftover state in the wizard. This should be fixed in the next version so I'm going to close this, but feel free to create a new issue if the problem persists in 1.4.

**Closed by stnguyen90** 2023-08-18 02:09 UTC
Labels: bug, database, ui/ux
