### ISSUE TITLE
🐛 Bug Report: Document not shown in usage

### ISSUE THREAD

**Issue by kevkoch** [appwrite/appwrite#2730] opened 2022-01-31 15:32 UTC
### 👟 Reproduction steps

When deleting a document through the Dashboard, after 15 minutes it's not shown in "Usage".

All other stats are shown correctly.

### 👍 Expected behavior

Should be shown in usage

### 👎 Actual Behavior

Not shown in usage

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 🧱 Your Environment

-

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment] 2022-01-31 23:38
The usage will show the active number of documents at a specific period of time. In the main dashboard it will just show the latest figure. Data is aggregated every 15 minutes.

**Comment by stnguyen90** [comment] 2022-02-09 08:10
Sounds like a duplicate of https://github.com/appwrite/appwrite/issues/2321

**Closed** 2022-03-20 04:27 UTC
Labels: bug
