### ISSUE TITLE
🐛 Bug Report: no activity despite there being activity

### ISSUE THREAD

**Issue by AidenY69** [appwrite/appwrite#7174] opened 2023-11-19 15:31 UTC
### 👟 Reproduction steps

Create an account, use the platform, check 'Activity' for that user, it will show nothing

### 👍 Expected behavior

It should show the activity

### 👎 Actual Behavior

This has happened since day one of using Appwrite, and across all users ever on the site. Despite them using the site, and even my test accounts, the activity window looks like this:

![image](https://github.com/appwrite/appwrite/assets/120392135/99252cbc-75cc-4406-bb1e-a16437663cb3)

Did I miss some specific implementation in the codebase that would put actions done into this activity window? I can't really see any of that mention in the Docs. I'm just looking to get basic activity of the user.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-11-20 04:15
@AidenY69, thanks for creating this issue! 🙏🏼. This looks like a duplicate of https://github.com/appwrite/appwrite/issues/7109. As such, would you please close this and 👍🏼 the other issue?

**Closed** 2023-11-20 04:23 UTC
Labels: bug

**Comment by AidenY69** [comment] 2023-11-20 04:25
@stnguyen90 

I closed it in case that one gets fixed maybe it will solve this, but I don't think the issue is the same one. I am running 1.3 and this issue exists, and that one is for 1.4. Also, it seems like some activity shows for others, while I see nothing, and have never seen anything in the activity tab.
