### ISSUE TITLE
🐛 Bug Report: ListDocuments queries on String attribute do not find some values containing special chars

### ISSUE THREAD

**Issue by BenMemescape** [appwrite/appwrite#3585] opened 2022-07-21 20:30 UTC
### 👟 Reproduction steps

1. Create a String attribute in a Collection, and add an Index for it.
2. Create documents where this attribute is set to a variety of different strings containing characters like " ' { (maybe more but these are the ones I've tried)
3. Use the below code (adjusting collectionId and attrName as applicable) read the values, then search for those same values using Query.equal 

```
  String collectionId = '62d97e8e98f77fba02b4';
  String attrName = 'TestAttr';
  DocumentList allDocs = await database.listDocuments(collectionId: collectionId);
  for (Document doc in allDocs.documents) {
    String testSearch = doc.data[attrName];
    DocumentList searchResult = await database.listDocuments(
      collectionId: collectionId,
      queries: [
        Query.equal(attrName, testSearch),
      ],
    );
    if (searchResult.total > 0) {
      print('$testSearch found');
    } else {
      print('$testSearch NOT FOUND');
    }
  }
```

### 👍 Expected behavior

Every string should be found.

### 👎 Actual Behavior

```
NormalString found
{"type":"json","somekey":"someval"} NOT FOUND
{NormalStringInBraces} found
"NormalStringInDoubleQuotes" NOT FOUND
{"NormalStringInDoubleQuotesAndBraces"} found
'NormalStringInSingleQuotes' NOT FOUND
{'NormalStringInSingleQuotesAndBraces'} found
SingleQuote'InMiddle found
DoubleQuote"InMiddle found
Slash/InMiddle found
Backslash\InMiddle NOT FOUND
Colon:InMiddle found
"quoted":"colon" NOT FOUND
```

I can't deduce any rhyme or reason to this. Why, for example, does 'NormalStringInSingleQuotes' fail while both SingleQuote'InMiddle and {'NormalStringInSingleQuotesAndBraces'} succeed? Makes no sense to me. Regardless, a string index should be able to match any string that exists in the database.

I have tried using all 3 possible index types (key, unique, fulltext), they all produce the same result. 

I've also tried using the PHP SDK in case this was specific to Dart, but again, the same result.

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2022-07-21 21:50
Thank you for raising this issue! 🙏. These edge cases are super helpful!

> {"type":"json","somekey":"someval"}

This is due to the comma. See https://github.com/appwrite/appwrite/issues/3089.

> "NormalStringInDoubleQuotes"

This looks to be due to [trim()](https://github.com/utopia-php/database/blob/ad6e15144b082b3d7b9029143b2564d17652c085/src/Database/Query.php#L239) trimming too many double quotes such that the value becomes `NormalStringInDoubleQuotes` rather than `"NormalStringInDoubleQuotes"`.

> 'NormalStringInSingleQuotes'

Save as above. `"'NormalStringInSingleQuotes'"` becomes `NormalStringInDoubleQuotes`.

> Backslash\InMiddle

In this case, I think the backslash is being stripped out before it even gets to Appwrite. Either that, or [stripslashes()](https://github.com/utopia-php/database/blob/ad6e15144b082b3d7b9029143b2564d17652c085/src/Database/Query.php#L237) may be stripping the slash.

> "quoted":"colon"

This seems to be also caused by the same problem as `"NormalStringInDoubleQuotes"`

**Comment by christyjacob4** [comment] 2022-08-20 09:29
These should be fixed now 👍

**Closed** 2022-08-20 09:33 UTC
Labels: bug, database
