### ISSUE TITLE
Automatically activate first tag

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1265] opened 2021-06-08 18:02 UTC
## 🚀 Feature

When you deploy a code (let's say using CLI), it created a new function tag. Now you need to enter administration and mark this tag as an active.

Sure, this system is awesome for updating, but if I upload the first tag for a newly created function, I think we can agree to be sure I actually want to deploy this one.

## Have you spent some time to check if this issue has been raised before?

Discord discussion lead me to believe this is not part of the Appwrite. It should be possible using events, but I believe most of the appwrite function users (80+%) mark their first tag as active.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes, I believe this does not go against any rules.

## Pitch

As explained above, I believe most of the users do this already but as an additional step to click "Activate". 

Example:
I code locally, test functions offline.. I make a script to build everything (from typescript to javascript), separate it and make new tags for it in Appwrite. Out of my 50 functions, 20 didnt change, 1 has a bug fixed and 29 are new functions. I believe you can mark these 29 as active automatically.

**Comment by kodumbeats** [comment] 2021-06-09 18:35
Duplicate of #1264, so I'll close this one.

**Closed by kodumbeats** 2021-06-09 18:35 UTC

**Comment by Meldiron** [comment] 2021-06-09 18:37
My bad, no idea how that happened.
