### ISSUE TITLE
🐛 Bug Report: GraphQL stopped working completely after upgrading from 1.5.11 to 1.6.0

### ISSUE THREAD

**Issue by tawfeks** [appwrite/appwrite#8690] opened 2024-09-19 11:50 UTC
### 👟 Reproduction steps

When I perform any graphql call, it produces an error always.
The same graphql call was working fine in previous release: 1.5.11.

### 👍 Expected behavior

Works as it was in 1.5.11

### 👎 Actual Behavior

This error raised:

```Traceback (most recent call last):
  File "/usr/local/server/src/function/runtime-env/lib/python3.12/site-packages/appwrite/client.py", line 117, in call
    response.raise_for_status()
  File "/usr/local/server/src/function/runtime-env/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://mydomain.com/v1/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/server/src/server.py", line 121, in action
    output = await asyncio.wait_for(execute(context), timeout=safeTimeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/server/src/server.py", line 114, in execute
    output = userModule.main(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/server/src/function/src/main.py", line 332, in main
    db_context_result = graphql.query(query)
                        ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/server/src/function/runtime-env/lib/python3.12/site-packages/appwrite/services/graphql.py", line 19, in query
    return self.client.call('post', api_path, {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/server/src/function/runtime-env/lib/python3.12/site-packages/appwrite/client.py", line 140, in call
    raise AppwriteException(response.json()['message'], response.status_code, response.json().get('type'), response.json())
appwrite.exception.AppwriteException: Server Error
```

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

I'm on self-host version 1.6.0

My Python SDK versions that I tried:
6.1.0, 7.0.0-rc1, 5.0.3

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by neehhaa06** [comment] 2024-09-19 12:21
Hello @tawfeks :)

fix: #8690

``
To resolve the GraphQL bug after upgrading to version 1.6.0, first review the release notes for any breaking changes in the API. Then, manually test the GraphQL endpoint using tools like Postman to confirm if the issue is with the server or the client code. Check server logs for detailed error messages, and verify that your queries and configurations (e.g., headers, authentication) are correctly set for the new version. If the issue persists, try reverting to version 1.5.11 to isolate the cause. Lastly, update your code to align with any new requirements in version 1.6.0.
``

**Comment by tawfeks** [comment] 2024-09-19 12:49
In the browser,

On 1.5.11, i tried this url as a test: https://old.mydomain.com/v1/graphql?query=s
Result:
```{
  "errors": [
    {
      "message": "Syntax Error: Unexpected Name \"s\"",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 1,
          "column": 1
        }
      ]
    }
  ]
}```

And when the syntax is correct, it works.

On 1.6.0, i tried this url as a test: https://mydomain.com/v1/graphql?query=s
Result:
```{
  "message": "Server Error",
  "code": 500,
  "type": "general_unknown",
  "version": "1.6.0"
}```
And when the syntax is correct, same error message.
It seems the endpoint is not working at all.

**Comment by tawfeks** [comment] 2024-09-19 12:53
Server logs
```
appwrite  | [Error] Timestamp: 2024-09-19T12:52:56+00:00
appwrite  | [Error] Method: GET
appwrite  | [Error] URL: /v1/graphql
appwrite  | [Error] Type: TypeError
appwrite  | [Error] Message: Appwrite\Functions\Validator\RuntimeSpecification::__construct(): Argument #3 ($maxCpus) must be of type float, string given, called in /usr/src/code/app/controllers/api/functions.php on line 171
appwrite  | [Error] File: /usr/src/code/src/Appwrite/Functions/Validator/RuntimeSpecification.php
appwrite  | [Error] Line: 17
appwrite  | [Error] Timestamp: 2024-09-19T12:53:01+00:00
appwrite  | [Error] Method: GET
appwrite  | [Error] URL: /v1/graphql
appwrite  | [Error] Type: TypeError
appwrite  | [Error] Message: Appwrite\Functions\Validator\RuntimeSpecification::__construct(): Argument #3 ($maxCpus) must be of type float, string given, called in /usr/src/code/app/controllers/api/functions.php on line 171
appwrite  | [Error] File: /usr/src/code/src/Appwrite/Functions/Validator/RuntimeSpecification.php
appwrite  | [Error] Line: 17
appwrite  | [Error] Timestamp: 2024-09-19T12:53:02+00:00
appwrite  | [Error] Method: GET
appwrite  | [Error] URL: /v1/graphql
appwrite  | [Error] Type: TypeError
appwrite  | [Error] Message: Appwrite\Functions\Validator\RuntimeSpecification::__construct(): Argument #3 ($maxCpus) must be of type float, string given, called in /usr/src/code/app/controllers/api/functions.php on line 171
appwrite  | [Error] File: /usr/src/code/src/Appwrite/Functions/Validator/RuntimeSpecification.php
appwrite  | [Error] Line: 17
appwrite  | [Error] Timestamp: 2024-09-19T12:53:04+00:00
appwrite  | [Error] Method: GET
appwrite  | [Error] URL: /v1/graphql
appwrite  | [Error] Type: TypeError
appwrite  | [Error] Message: Appwrite\Functions\Validator\RuntimeSpecification::__construct(): Argument #3 ($maxCpus) must be of type float, string given, called in /usr/src/code/app/controllers/api/functions.php on line 171
appwrite  | [Error] File: /usr/src/code/src/Appwrite/Functions/Validator/RuntimeSpecification.php
appwrite  | [Error] Line: 17
```

**Comment by stnguyen90** [comment] 2024-09-19 21:55
@tawfeks, thanks for raising this issue! 🙏🏼 Looks like there's some unexpected behavior here:

https://github.com/appwrite/appwrite/blob/e406dead9a9cbca78ce79ecab2f112006708624e/app/controllers/api/functions.php#L171-L176

if the `_APP_FUNCTIONS_CPUS` or `_APP_FUNCTIONS_MEMORY` env vars are not set.

As a workaround, I suggest setting those env vars.

**Comment by tawfeks** [comment] 2024-09-19 22:03
Thank you so much for your help, Steven! I would never know this was the problem in env vars.

The workaround worked! I needed to set up both to make it work for now.

I will remove the set up once a fix is released.

**Comment by stnguyen90** [comment] 2024-09-19 22:40
This should be fixed in the next version of Appwrite as the updated code uses `System::getEnv()` which handles the empty string fine:

https://github.com/appwrite/appwrite/blob/778edf1ac28ef24c350240d13ecffeec0a6462d3/app/controllers/api/functions.php#L173-L178

**Closed** 2024-11-21 20:05 UTC
Labels: bug, waiting for release, api / graphql
