### ISSUE TITLE
🐛Bug Report: 500 Internal Error on Appwrite Cloud

### ISSUE THREAD

**Issue by kid0733** [appwrite/appwrite#7716] opened 2024-03-03 05:51 UTC
### 👟 Reproduction steps

Enter into a project, and try to go databases or auth dashboard.

### 👍 Expected behavior

Go to dashboards and see the database collections and able to post and retrieve data.

### 👎 Actual Behavior

500 Internal Server Error.
![Screenshot 2024-03-03 164957](https://github.com/appwrite/appwrite/assets/125928491/72b2c583-6717-475f-87a1-e9b1fa0d5acf)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

Google Chrome.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment] 2024-03-03 06:39
There's an open incident, will be fixed - https://status.appwrite.online/incident/334938

**Comment by ItzNotABug** [comment] 2024-03-03 07:00
Update: The incident is marked resolved. Console should work just fine!

**Comment by anurag1802** [comment] 2024-03-03 16:14
> Update: The incident is marked resolved. Console should work just fine!

No, the problem is still the same.

**Comment by ItzNotABug** [comment] 2024-03-03 16:16
> > Update: The incident is marked resolved. Console should work just fine!
> 
> 
> 
> No, the problem is still the same.

I replied to your thread, mentioning another open incident.

**Comment by kunalcharde** [comment] 2024-03-03 16:55
i am facing the same issue in mac

**Comment by docimin** [comment] 2024-03-03 21:42
Hey @kunalcharde @kid0733 

Please check again, the issue popped up again but should be resolved.

**Comment by BlaqueC88** [comment] 2024-03-04 12:48
Yeah I'm having the same problem.

**Comment by VaidyaHarshal** [comment] 2024-03-04 15:30
Not able to access anything except for Overview since yesterday

**Comment by stnguyen90** [comment] 2024-03-04 19:56
@kid0733, thanks for raising this issue! 🙏🏼 As mentioned, there was an incident that probably affected you. If you created the project during that time, it wouldn't have created successfully, but you should be able to create a project now. We'll probably have to do a sweep of Appwrite Cloud to delete all of the broken projects.

If you still need help, feel free to create a [support](https://discord.com/channels/564160730845151244/1072905050399191082) post on our [Discord](https://appwrite.io/discord).

**Closed by stnguyen90** 2024-03-04 19:56 UTC
Labels: bug

**Comment by VaidyaHarshal** [comment] 2024-03-04 20:02
Thank you for your response.. I created my project 2-3 days ago and didnt face any issue to create it at that time. Now, I am able to access other options but the bucket which I had created, whenever I try to access the bucket it is showing me the same Internal 500 Server Error.
