### ISSUE TITLE
🚀 Feature: SMTP settings per project

### ISSUE THREAD

**Issue by XeroxDev** [appwrite/appwrite#3066] opened 2022-04-07 16:23 UTC
### 🔖 Feature description

Hello Appwrite team!

I've already searched for this feature, but haven't found a request for it. If I missed it, I'm really sorry.

TL;DR: In my opinion it should be possible to store one sender email / SMTP data per project.

More in "Pitch".

### 🎤 Pitch

It can be very strange if you have for example 4 different / separate projects with different domains, but the project uses the same email address. This could also come across as unprofessional or dodgy to our users.

You probably already had this in mind or are even working on it, I just wanted to make sure it was addressed.

The SMTP configuration in the `.env` file could be the default or Appwrite specific and every project itself is getting in the settings tab few new input fields for the project specific SMTP settings.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment] 2022-04-11 10:18
Hey :)

Your idea makes sense! We'll look into on how we can support this properly 👍🏻

**Comment by stnguyen90** [comment] 2022-08-15 01:38
Closing as a duplicate of https://github.com/appwrite/appwrite/issues/3147. Feel free to upvote the other issue.

**Closed by stnguyen90** 2022-08-15 01:38 UTC
Labels: feature

**Comment by XeroxDev** [comment] 2022-08-15 08:05
> Closing as a duplicate of https://github.com/appwrite/appwrite/issues/3147. Feel free to upvote the other issue.

Isn't #3147 technically a duplicate of this ticket?

**Comment by stnguyen90** [comment] 2022-08-15 14:25
@XeroxDev, yes, but that one has more upvotes 😬
