### ISSUE TITLE
🚀 Feature: Show the ID for Collection, File, etc... versus only allowing to copy it

### ISSUE THREAD

**Issue by pspierce** [appwrite/appwrite#4942] opened 2023-01-02 14:42 UTC
### 🔖 Feature description

Show the ID versus having to copy/paste to get the actual ID.

![image](https://user-images.githubusercontent.com/456876/210245899-abc10827-5718-42bc-9f7c-9d07615aae97.png)

### 🎤 Pitch

As of 1/2/2023, the name of an ID is shown in the dashboard with the ability to click on it to copy the actual ID.  I often have simple IDs with a more expressive name.  If I am flipping around the dashboard, having to click, copy, then paste the ID, is more burdensome than typing "post."  Often, I have to copy/paste into an arbitrary text input because I don't want to paste the value; I am only confirming what it is.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-01-05 18:19
@pspierce is this a duplicate of https://github.com/appwrite/appwrite/issues/4723? If so, it would be good if you 👍🏼 that issue, add your comment on that issue, and close this issue.

**Comment by pspierce** [comment] 2023-01-07 14:08
Duplicate #4723

**Closed** 2023-01-07 14:07 UTC
Labels: ui/ux
