### ISSUE TITLE
PHP SDK fail with custom port

### ISSUE THREAD

**Issue by thesmartrenovation** [appwrite/appwrite#904] opened 2021-02-12 19:19 UTC
When i change the AppWrite port in traefik the PHP SDK fail.

with this data the PHP SDK works fine:
$client
    ->setEndpoint('{URL}/v1') // Your API Endpoint
    ->setProject('{PROJECT}') // Your project ID
    ->setKey('{KEY}'); // Your secret API key;

But, if i change the port here:

$client
    ->setEndpoint('{URL}:8080/v1') // Your API Endpoint
    ->setProject('{PROJECT}') // Your project ID
    ->setKey('{KEY}'); // Your secret API key;

the sdk fail: Fatal error: Uncaught Exception: Failed to connect to {MYDOMAIN} port 8080: Connection refused with status
code 0

traefik conf:

services:
  traefik:
    image: traefik:2.3
    container_name: appwrite-traefik
    command:
      - --providers.file.directory=/storage/config
      - --providers.file.watch=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.constraints=Label(`traefik.constraint-label-stack`,`appwrite`)
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    restart: unless-stopped
    ports:
      - 8080:80
      - 7443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - appwrite-config:/storage/config:ro
      - appwrite-certificates:/storage/certificates:ro
    depends_on:
      - appwrite
    networks:
      - gateway
      - appwrite

**Comment by eldadfux** [comment] 2021-02-13 07:51
Seems like a problem with the way we handle CURL custom ports on the HTTP client -> we'll work on a fix.

**Comment by lohanidamodar** [comment] 2021-02-14 05:44
@thesmartrenovation Can you confirm that when you visit {URL}:8080 you can access the Appwrite console.We tried to reproduce the problem, but couldn't with latest SDK (2.0.0)

**Comment by thesmartrenovation** [comment] 2021-02-15 03:14
> @thesmartrenovation Can you confirm that when you visit {URL}:8080 you can access the Appwrite console.We tried to reproduce the problem, but couldn't with latest SDK (2.0.0)

Yes, everything works when I change the port, except the PHP SDK. Always response: Connection refused with status
code 0

**Comment by lohanidamodar** [comment] 2021-02-15 07:48
@thesmartrenovation 
As we were unable to reproduce the error ourself, please provide more details, share screenshots of running web console and your code using PHP SDK, it will help us create the exact scenario, also share PHP SDK version you are using. The more information you can share the better.

**Comment by lohanidamodar** [comment] 2021-03-01 06:21
We are closing this issue as there were no new responses. If you again run into this issue or if it's still unresolved for you, feel free to reopen the issue any time. Thank you.

**Closed by lohanidamodar** 2021-03-01 06:21 UTC
Labels: bug
