### ISSUE TITLE
🐛 Bug Report: Can't create Relational Attribute (failed)

### ISSUE THREAD

**Issue by MatthewMartino** [appwrite/appwrite#7740] opened 2024-03-07 07:11 UTC
### 👟 Reproduction steps

![CleanShot 2024-03-06 at 23 02 15@2x](https://github.com/appwrite/appwrite/assets/15672637/9ce7caf1-59fa-4e26-ac68-722e9ba6d13f)

1. (on Appwrite Cloud) Create a new Relational Attribute with any related collection, attribute key, relation, and deleting behavior.
2. Click Create
3. Observe that (nearly every time) you are unable to create a new attribute, as the attribute lists "failed", but without any sort of error message or explanation. After trying repeatedly for a while I was able to get a relation through using the exact same parameters as many times before, so this feels like a bug.

I did notice [this PR](https://github.com/appwrite/appwrite/issues/6281) was merged a couple days ago, but not sure if it's related.

### 👍 Expected behavior

Create the new relational attribute as specified.

### 👎 Actual Behavior

Unable to create any kind of relational attributes.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 🧱 Your Environment

Appwrite Cloud (1.4.x i think?)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2024-03-08 21:33
@MatthewMartino, thanks for creating this issue! 🙏🏼 Your problem is probably related to the issue you linked. The issue is resolved for Appwrite 1.5, but Cloud is currently on 1.4.13 (you can see the version at the bottom right of the Console).

Since this issue is the same as the linked issue, I'm going to close this as a duplicate.

**Closed by stnguyen90** 2024-03-08 21:33 UTC
Labels: bug
