### ISSUE TITLE
🐛 Bug Report: Vanishing Upload File Layout and Unresponsive Create File Button when Uploading Duplicate Files.

### ISSUE THREAD

**Issue by roubalsehgal** [appwrite/appwrite#5775] opened 2023-07-06 09:51 UTC
### 👟 Reproduction steps

Description:
When attempting to upload two identical files consecutively by dragging and dropping them into the upload area, a bug occurs where the Upload File layout disappears, and the Create File button becomes unresponsive.

Steps to Reproduce:

1) Access the file upload feature within the application.
2) Drag a file and drop it into the designated upload area.
3) Observe that the file upload starts, and the Upload File layout is displayed.
4) Without any delay, drag and drop the same file again into the upload area.
5) Verify that the Upload File layout disappears immediately after dropping the second file.
6) Attempt to interact with the Create File button or any other elements in the upload area.
7) Confirm that the Create File button remains unresponsive, and no action is triggered.

<img width="750" alt="image" src="https://github.com/appwrite/appwrite/assets/44202409/0c43ecc1-e729-4db2-b7bc-0c0b3375db63">

### 👍 Expected behavior

It should prevent the user from uploading identical files or should show a error message or popup. Also, after the layout is disappeared, the Create file button should be actionable. Currently, it's inactionable.

### 👎 Actual Behavior

The Upload file modal is getting vanished and Create file button is getting unresponsive and inactionable.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by heyCarla** [comment] 2023-07-26 01:30
Hi there, I'm unable to reproduce this bug using the steps you've listed. Can you share any more information about your environment (Appwrite version, browser & version, MacOS version, the file types you attempted to upload, any applicable console logs you may have seen, etc.) that could help us diagnose? Cheers!

**Comment by priyankuhazarika** [comment] 2023-07-26 12:13
I too cannot reproduce the bug, more information awaited!

**Comment by roubalsehgal** [comment] 2023-07-27 07:22
**MacOS - 12.2
Browser - Chrome (Version 114.0.5735.248)**

Sharing the Compressed Video for reference.

https://github.com/appwrite/appwrite/assets/44202409/f6a89ce3-06c5-42e9-8504-822c7750ac58

**Comment by priyankuhazarika** [comment] 2023-07-27 07:31
@roubalsehgal can you please update your appwrite version, I think this issue is fixed in the latest version. I am using the latest version, could not find the issue. You are using version 1.1.2 and the latest version is 1.3.8

**Comment by roubalsehgal** [comment] 2023-07-27 07:50
@priyankuhazarika - How can i change the version of the [cloud.appwrite ](https://cloud.appwrite.io/) ?

**Comment by priyankuhazarika** [comment] 2023-07-27 08:27
@roubalsehgal probably go through https://appwrite.io/docs/upgrade

**Comment by priyankuhazarika** [comment] 2023-07-27 08:38
Even I checked appwrite cloud version 1.1.2 still not able to reproduce the bug. Here is a video 

https://github.com/appwrite/appwrite/assets/35552170/6a0b3d4d-7771-4839-95f9-62a184d314c2

**Comment by abnegate** [comment] 2023-09-16 07:38
Closing as unable to reproduce

**Closed by abnegate** 2023-09-16 07:38 UTC
Labels: bug, storage, console
