### ISSUE TITLE
🚀 Feature: Update database attribute

### ISSUE THREAD

**Issue by sampatsharma143** [appwrite/appwrite#3328] opened 2022-06-02 18:43 UTC
### 👟 Reproduction steps

When we put wrong attribute in database section

### 👍 Expected behavior

we should be able to edit the attributes of a database collection.

### 👎 Actual Behavior

 their is only delete button

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by niels-hubs** [comment] 2022-07-29 08:02
For us this would not matter even if the database/API would be in maintenance mode during the duration of the update.

It seems weird for example a category, we now use an enum type for this (because of lack of relations). But now we can't add categories after we initially created them. So this kinda sucks.

**Comment by barracus84** [comment] 2022-09-29 21:23
For anyone on hold with this, waiting for a solution from appwrite team, I am scripting attribute update in this way (using Python SDK).

It lacks any control about data integrity, data type (eg: should check if old attr is the same type of new attr)...and results check.

If any one interested, I am writing update for also enum type.

```
from appwrite.client import Client
from appwrite.services.databases import Databases

def setup_client() -> Client:
  client = Client()

  (client
    .set_self_signed()
    .set_endpoint('https://localhost/v1') # Your API Endpoint
    .set_project('633...b44') # Your project ID
    .set_key('d78...28a') # Your secret API key
  )

  return client

def main():

  DATABASE_ID = '633...e37'
  COLLECTION_ID = '633...edd'
  OLD_ATTRIBUTE_KEY = 'name1'
  NEW_ATTRIBUTE_KEY = 'barbapapa'

  # setup client
  client = setup_client()

  databases = Databases(client)

  # list documents
  documents = databases.list_documents(DATABASE_ID, COLLECTION_ID)

  # scroll documents, update document new attribute value with old attribute value
  for doc in documents['documents']:
    document_id = doc['$id']
    old_attribute_value = doc[OLD_ATTRIBUTE_KEY]
    # preapre new object
    obj_update = {
      NEW_ATTRIBUTE_KEY: old_attribute_value
    }
    # update docs
    databases.update_document(DATABASE_ID, COLLECTION_ID, document_id, obj_update)

  # delete attribute
  databases.delete_attribute(DATABASE_ID, COLLECTION_ID, OLD_ATTRIBUTE_KEY)

if __name__ == "__main__":
    main()
```

**Comment by JustinBack** [comment] 2022-12-07 14:33
+1 Any update on this issue? Seems to be a deal breaker in prod

**Comment by suleimanas** [comment] 2023-02-23 16:52
any news on this feature

**Comment by stnguyen90** [comment] 2023-02-25 16:03
> +1 Any update on this issue? Seems to be a deal breaker in prod

What's your use case? Changing an attribute in prod might be problematic if you have users using an older version of your app.

**Comment by eldadfux** [comment] 2023-03-05 21:26
I can confirm this feature is in work and should be available for the next Appwrite release.

**Comment by TorstenDittmann** [comment] 2023-04-12 10:47
I am happy to announce that [1.3.0](https://github.com/appwrite/appwrite/releases/tag/1.3.0) is now released with the ability to update attributes 👏🏻 

You can find more informations in [this blog post](https://dev.to/appwrite/join-celebrations-appwrite-13-ships-relationships-57fc) and [our docs](https://appwrite.io/docs/databases-relationships).

**Closed by TorstenDittmann** 2023-04-12 10:47 UTC
Labels: database, feature

**Comment by sonicviz** [comment] 2024-06-07 09:11
But you still can't update name or size? If you need to modify these you have to delete and recreate the attribute still?

**Comment by bizrockman** [comment] 2024-09-09 17:16
The same. When I can not change (at least increase) an attribute, the best way would be set all string attributes to a high value? 

Is there a quick hack, like changing it manually in the database?

**Comment by sonicviz** [comment] 2024-09-17 13:34
This looks to have been fixed now, as I can edit both name and size. 
Thanks!
