### ISSUE TITLE
🐛 Bug Report: Database Relationship payload in realtime event

### ISSUE THREAD

**Issue by moshOntong-IT** [appwrite/appwrite#5385] opened 2023-04-16 01:56 UTC
### 👟 Reproduction steps

_This particular bug is hard to find but I need to be a tricky to detect this bug_

Currently I am using the new feature of **Appwrite**, specifically the Database Relationship. Please look at my availables collection to discuss and acknowledge:

![image](https://user-images.githubusercontent.com/57244338/232261817-45d0129c-d6f8-49ff-bcbf-d7b966e1aa38.png)
 

This steps can find the bugs:
1. Update the vocabulary document
2. Realtime triggers because of the update event and it returns me the payload and this payload includes the language documents
3. Add audio
4. Delete some audio
5. Update the vocabulary document
6. Realtime trigger again but this time it returns me the payload without the language document.

To understand this issue I will attach a video google drive link:
[Video](https://drive.google.com/file/d/1B9Ox2zy8kqhhr-bbryDfPL0pCa7ukM3Q/view?usp=sharing)

### 👍 Expected behavior

In my code side, I have this realtime to subscribe any changes of vocabulary collection such as the create, delete, and update event. And it is so expected that whenever the realtime event, it gives us the return payload object.

In instance:

```
{
 ...
 payload: {
  word: ... ,
  english: ... ,
  language: {
  ... ->>>> This object is from language collection since the vocabulary collection have its relation in the language collection
  }
 }
}
```
### 👎 Actual Behavior

Sometimes it does not include the language document in payload from realtime 

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-04-19 19:36
@moshOntong-IT, thanks for creating this issue! 🙏🏼 I definitely think some improvements are necessary for relationships and our event system. I've let the team know about this, but this is probably not going to be a quick fix.

**Comment by abnegate** [comment] 2023-09-08 02:29
Hi @moshOntong-IT, are you able to confirm if this bug is still an issue for you in the latest version 1.4.2?

**Comment by moshOntong-IT** [comment] 2023-09-10 07:48
cant test this anymore I already deleted my self hosted in digital ocean😅

**Comment by abnegate** [comment] 2023-09-12 02:09
@moshOntong-IT No worries, I'll dig into this further :grin:

**Comment by abnegate** [comment] 2023-09-14 01:43
Closing as unable to reproduce in 1.4.2, please re-open if you're able to provide reproduction steps

**Closed by abnegate** 2023-09-14 01:43 UTC
Labels: bug, databases, realtime, relationships
