### ISSUE TITLE
🐛 Bug Report: Project ID cannot contain underscores

### ISSUE THREAD

**Issue by TobyKLight** [appwrite/appwrite#8341] opened 2024-06-30 13:08 UTC
### 👟 Reproduction steps

When I create a new project then I have a chance to enter a custom project ID, the help text says "Allowed characters: alphanumeric, non-leading hyphen, underscore, period"

But if you use an underscore you get an error that provides a different list of allowed characters, notably without underscore 
<img width="328" alt="image" src="https://github.com/appwrite/appwrite/assets/4467208/924a5fd2-8592-4046-bd06-2474761e246d">

### 👍 Expected behavior

Correct list of allowed characters on the help text. 

Even better UX would be error feedback on the field when a disallowed character is used and which character. 

### 👎 Actual Behavior

After advancing to the final step in the flow (after pick server region) you get the error saying you used an incorrect character in the project ID field back at the first step, and with a different list of allowed characters than the original help text

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Something else

### 🧱 Your Environment

Appwrite Cloud

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2024-07-06 19:17
@TobyKLight, thanks for raising this issue! 🙏🏼 This looks like a duplicate of https://github.com/appwrite/console/issues/1015 so I'm going to close it. It would be best if you added a 👍🏼 to the related issue.

**Closed by stnguyen90** 2024-07-06 19:17 UTC
Labels: bug
