### ISSUE TITLE
🐛 Bug Report: Can't update document after deleting array element

### ISSUE THREAD

**Issue by ochatzi** [appwrite/appwrite#5476] opened 2023-05-01 16:47 UTC
### 👟 Reproduction steps

I have a Database with a collection and with a attribute of String | array and a length of 350. I have added a value. After create a new entry i can update the document. After updating i'm going to delete the item. But when i'm going to delete it. There is no ability to save or update the Document.

### 👍 Expected behavior

I can add and remove attributes entries.

![Bildschirm­foto 2023-05-01 um 18 43 56](https://user-images.githubusercontent.com/107322650/235490415-ebbdfd22-74ef-4401-92f1-ebd8b4a93b9c.png)

![Bildschirm­foto 2023-05-01 um 18 44 35](https://user-images.githubusercontent.com/107322650/235490453-5d15f1cd-c50c-46e1-817b-91c1d43d3c75.png)

### 👎 Actual Behavior

It's only possible to add. Not to delete.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite is running in over docker compose.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment] 2023-05-09 10:40
Thank you for opening this. The feedback has been passed to concerned team and it will be improved.

**Comment by sahilsuman933** [comment] 2023-07-19 00:18
@stnguyen90, can I work on this issue?

**Comment by joeyouss** [comment] 2023-08-08 18:09
Hi @ochatzi this issue is open for contributions now BTW in case anyone from our community wants to work on this.

**Comment by safwanyp** [comment] 2023-08-08 18:13
Can I be assigned to this?

**Comment by joeyouss** [comment] 2023-08-08 18:14
Assigned

**Comment by sahilsuman933** [comment] 2023-08-08 18:37
If I am not wrong, this issue has already been fixed @joeyouss because I couldn't reproduce it.

**Comment by safwanyp** [comment] 2023-08-08 18:50
> If I am not wrong, this issue has already been fixed @/joeyouss because I couldn't reproduce it.

@sahilsuman933 I just pulled all changes made to the console, and it seems like this issue still exists. I can add an entry and update, but can't update on removal.

**Comment by sahilsuman933** [comment] 2023-08-08 18:53
Okay, @safwanyp.

**Closed** 2023-08-11 13:05 UTC
Labels: bug, help wanted, good first issue, database, ui/ux
