### ISSUE TITLE
[BUG] Failed newsletter email verification on appwrite.io with "plus" pattern

### ISSUE THREAD

**Issue by mxgnr** [appwrite/appwrite#539] opened 2020-09-17 14:55 UTC
Hi,

As previously described on the discord server, i've encountered an issue with the verification of my email address with a "plus" pattern (eg. `my.email+appwrite@gmail.com`). 

After clicking on the verification email link, the email param of the POST request `https://appwrite.io/newsletter/verify` seems to replace the "+" character with a space (eg. `my.email appwrite@gmail.com`) and eventually fail with a 400 Bad Request. The key param seems to be OK.

**Comment by hack3r-0m** [comment] 2020-10-31 12:41
can I be assigned to this issue? it seems this is because of base64 to URL encoding conversion somewhere. it would be good if someone can help with files to check.

**Comment by Glide7** [comment] 2020-12-10 09:46
Hey @hack3r-0m ,  did you end up taking this issue?

**Comment by hack3r-0m** [comment] 2021-01-04 14:43
@Glide7 I want to take this issue but need help regarding which files/folders to check for finding out that error

**Comment by Glide7** [comment] 2021-01-05 07:25
@hack3r-0m sure I assigned you.
@mxgnr can you please help and tell us which files/folders to check for finding out this error?

**Comment by eldadfux** [comment] 2021-01-05 07:34
This is the email validation we use: https://github.com/utopia-php/framework/blob/master/src/Validator/Email.php sound to me like it is something related to URI encoding. @hack3r-0m If thats the case, the source code for appwrite.io is not open-sourced yet :/

**Comment by hack3r-0m** [comment] 2021-01-06 10:03
@eldadfux if I am not wrong "newsletter" has been replaced with "Get Updates" in appwrite.io recently and I can confirm "+" is not causing issue while subscribing for "Get Updates"

**Closed** 2021-04-06 14:29 UTC
Labels: bug
