### ISSUE TITLE
🐛 Bug Report: Can't add Rule for single embedded Document (without Array option) via UI on FIREFOX

### ISSUE THREAD

**Issue by Gustl22** [appwrite/appwrite#1881] opened 2021-10-04 17:52 UTC
### 👟 Reproduction steps

- Open Firefox (here 94.0) and go to appwrite app.
- Add two different Collections (e.g. A and B) via UI
- Add Rule to Collection A with Rule Type "Document"
- Select one Collection under "Allowed Collections" WITHOUT checking the "Array" checkbox.
- Click on Update

<img src="https://user-images.githubusercontent.com/18537755/135899955-8d8b4746-47e4-401a-8387-b55d57689055.png" width="300">

### 👍 Expected behavior

Should allow adding Rule for single embedded document (one collection).

### 👎 Actual Behavior

Nothing happens. Cannot add Rule for single embedded document (one collection).

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Used `localhost` and port 5683 for http and port 5684 for https.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

### Notes
What also is confusing is that the "Array" option seems to fulfill two different purposes:
- Adding different types of collections
- Adding multiple documents of the same or more collections.

Usually the checkbox should only be responsible for the second case. For the first case, the selection is implicit, as selecting only one type would mean you can only add documents of the selected type. This means, that the selection of collection type in the UI should always be checkboxes and never radio buttons, independently from the `Array` checkbox.

**Comment by stnguyen90** [comment] 2021-11-04 23:57
I agree with @EduardoWeber. I can't reproduce the problem on v:0.11.0.170. 

![image](https://user-images.githubusercontent.com/1477010/140435652-81eb5236-aeb2-43a4-abeb-db92f97819d6.png)

**Comment by Gustl22** [comment] 2021-11-06 12:50
I deleted all images, containers, deleted the appwrite folder, installed apprite again, forced a rebuild on docker-compose up. Still not working. I look into the discord to get some help. Thx for now.

**Comment by stnguyen90** [comment] 2021-11-08 19:59
After additional troubleshooting, it appears as the problem occurs in Firefox and not Chrome.

In addition, I do agree with @Gustl22 that the Array toggle shouldn't affect the Allowed Collection.

**Comment by eldadfux** [comment] 2021-12-13 06:25
This will be fixed with the new database updates as part of Appwrite 0.12

**Comment by eldadfux** [comment] 2022-01-05 11:42
This fix is now available as part of Appwrite 0.12 which is now officially released. You can learn more at: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b

**Closed by eldadfux** 2022-01-05 11:42 UTC
Labels: bug, waiting for release
