### ISSUE TITLE
🐛 Bug Report: Python Server SDK Query.equal Not Working 

### ISSUE THREAD

**Issue by Infinil** [appwrite/appwrite#3089] opened 2022-04-13 05:00 UTC
### 👟 Reproduction steps

First I created a collection (json for reference) :- 
 
`{
    "$id": "feed",
    "$read": [
        "role:all"
    ],
    "$write": [],
    "name": "feed",
    "enabled": true,
    "permission": "collection",
    "attributes": [
        {
            "key": "title",
            "type": "string",
            "status": "available",
            "required": true,
            "array": false,
            "size": 255,
            "default": null
        }
    ],
    "indexes": [
        {
            "key": "title_index",
            "type": "key",
            "status": "available",
            "attributes": [
                "title"
            ],
            "orders": [
                "ASC"
            ]
        },
    ]
}`

Then I created document (json for reference) :- 
`{
    "title": "Microsoft Store Spring Sale: Hot Deals on Xbox Games, Gaming PCs, and More",
    "$read": [],
    "$write": [],
    "$id": "62563d9d4b5227768340",
    "$collection": "feed"
}`

Then I used this python code to show the result :- 
`isFound = database.list_documents('feed', [
  Query.equal('title', 'Microsoft Store Spring Sale: Hot Deals on Xbox Games, Gaming PCs, and More')
])
print(isFound)`

### 👍 Expected behavior

The query should have found the exact title and the document should have been shown.

### 👎 Actual Behavior

It does not find the exact title even though the document for it exists. 

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2022-04-13 05:04
It looks like the problem is due to how the query expression is parsed. Because there are commas, it becomes a list of values due to this: https://github.com/utopia-php/database/blob/6507b58ef3e22703b9df68d3dbd5e822d5bb023f/src/Database/Query.php#L210. As such, when the query is sent to the database, the where includes `table_main.title = 'Microsoft Store Spring Sale: Hot Deals on Xbox Games' OR table_main.title = 'Gaming PCs' OR table_main.title = 'and More'`.

**Comment by stnguyen90** [comment] 2022-04-13 05:17
Perhaps str_getcsv() would be a better alternative to explode() for parsing the query values.

**Comment by Infinil** [comment] 2022-04-13 05:18
> It looks like the problem is due to how the query expression is parsed. Because there are commas, it becomes a list of values due to this: https://github.com/utopia-php/database/blob/6507b58ef3e22703b9df68d3dbd5e822d5bb023f/src/Database/Query.php#L210. As such, when the query is sent to the database, the where includes `table_main.title = 'Microsoft Store Spring Sale: Hot Deals on Xbox Games' OR table_main.title = 'Gaming PCs' OR table_main.title = 'and More'`.

I see.. so will I have to use a workaround for this and close the issue , now? this is my first bug report so I am not sure when to close it 😅

**Comment by stnguyen90** [comment] 2022-04-13 05:35
> I see.. so will I have to use a workaround for this and close the issue , now? this is my first bug report so I am not sure when to close it sweat_smile

Workaround for now until a proper fix is deployed. Leave this issue open to track the bug.

**Comment by Infinil** [comment] 2022-04-13 05:43
> > I see.. so will I have to use a workaround for this and close the issue , now? this is my first bug report so I am not sure when to close it sweat_smile
> 
> Workaround for now until a proper fix is deployed. Leave this issue open to track the bug.

Okay ! Thanks for the help.

**Comment by stnguyen90** [comment] 2022-04-14 06:58
Looks like `str_getcsv()` doesn't work on:

1. `actors.notContains( " Johnny Depp ",  " Brad Pitt" , "Al Pacino")` because the 2nd value is parsed as ` Brad Pitt `
2. `director.notEqual("null")` because the value becomes `null` and we can't distinguish between null string or actual null

**Comment by lohanidamodar** [comment] 2022-04-15 00:49
Thank you @stnguyen90  always for your hard work. Our database expert @TorstenDittmann will go through the PR.

**Comment by christyjacob4** [comment] 2022-08-20 09:29
This should be fixed now 👍

**Comment by TorstenDittmann** [comment] 2022-09-15 12:49
This got implemented and released with Appwrite 1.0.0 🥳 

Thank you for your contribution 🙏🏻  You can read more [here](https://appwrite.io/1.0).

**Closed by TorstenDittmann** 2022-09-15 12:49 UTC
Labels: bug, database
