### ISSUE TITLE
Document relation like Product and Categories🚀 Feature: 

### ISSUE THREAD

**Issue by miami12** [appwrite/appwrite#4601] opened 2022-10-28 13:18 UTC
### 🔖 Feature description

document relationship like many to many or many to one 

### 🎤 Pitch

it will help

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2022-10-28 15:05
@miami12, thanks for raising this issue! 🙏🏼 Is this a duplicate of https://github.com/appwrite/appwrite/issues/2735? If so, would you please 👍🏼 that issue and close this issue?

Btw, for now, you can manually handle relationships like how [this](https://levelup.gitconnected.com/building-a-location-based-app-with-appwrite-48a2e2b6d4c2#a658) article shows.

**Comment by stnguyen90** [comment] 2022-11-17 05:02
Closing due to inactivity and it seems like a duplicate.

**Closed by stnguyen90** 2022-11-17 05:02 UTC
Labels: feature

**Comment by lucasctd** [comment] 2023-03-03 13:37
@stnguyen90 Hi Steven, I've a question. Is it possible to ensure that a parent document will not be deleted if it has a relationship with a child one? 

From your article, how can I ensure that an user will not be deleted if it has a comment?
