### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by AnatoleLucet** [appwrite/appwrite#373] opened 2020-06-02 16:00 UTC
So first of all; in my opinion the ui feels nice (it's the main reason why I've decided to learn Appwrite instead of Parse, Kuzzle, and more... (yes, uis makes a big diff for me 🙃)), it always feels like the product is finely tuned when the user experience a good ui. But I believe some improvement can be made.

Watch-out the animations feel a bit slower on the gif then it really is.

## Modals animations
- [ ] Done
### Before:
![](https://i.gyazo.com/03c9c6b78f0a1f84a89d17d2df2cd595.gif)
### After:
![](https://i.gyazo.com/42c2920e518e10e697ce56be8c90c2fd.gif)

## Buttons animations
- [ ] Done
### Before:
![](https://i.gyazo.com/ede6a93074995e41d1eff0f32c8d240b.gif)
### After:
Unfortunately we can't really see this one on the gif. 😕
But it's clearly smoother.
![](https://i.gyazo.com/b6a3b7d3394244b9ee71ddba9b5376e2.gif)

## Go-back link animations
- [x] Done  (#392)
### Before:
![](https://i.gyazo.com/db5c8274faf228c3eccff4276649d764.gif)
### After:
![](https://i.gyazo.com/902accadcf02f1a130da7dac751a03f3.gif)

## Nav links animations
- [x] Done (#397)
### Before:
![](https://i.gyazo.com/e2e8b546e1fa4e54b5067d418c29fddb.gif)
### After:
Same here, we can't really see the diff, but I simply removed the weight change and added a transition.
![](https://i.gyazo.com/fd0bf189da72d6b9fde72e4ed4f4b3a0.gif)

## Links animations
- [x] Done (#392)
### Before:
![](https://i.gyazo.com/49f7c4c6107e00898840a5249157fa74.gif)
### After:
![](https://i.gyazo.com/97c13c3d4287fff7d4198e75d0f5dff8.gif)

## Toggle between light and dark theme transition
- [ ] Done

I haven't tried anything yet, but it could be nice to have a transition when switching theme.

## Fix the scroll when menu is open
- [ ] Done

For now when the menu is open, you can still scroll the page in the background (see the scroll bar on the right). I don't think this is wanted.

![](https://i.gyazo.com/46c5d96d1b540f4bc538b9cae8e8ae0f.gif)

## The icon in the `add` button isn't PERFECTLY centered
- [x] Done (#396)
![](https://i.gyazo.com/feb9fee7bde740c70c33ce6fb3144815.png)

## Changing the `add` button position
- [ ] Done

Maybe it's just me, but the `add` button for collections in database, storage and users are hard to find (I speak about the little red button with a `+` in the bottom left of the page). I think it would be better to do the same as (for example) on the tasks page with the `Add Task` button.

---

Anyway, maybe some more could be made like having a bigger color gap for the dark theme, animating drop downs, etc...
If the maintainers are ok with these changes I may open a PR. But I'm waiting to see what you think. 🙂

**Comment by eldadfux** [comment] 2020-06-03 03:13
UI is a huge part of everything we try to do in Appwrite. I really like your suggestions and it will be great if you'll help by submitting PR's.

**Comment by eldadfux** [comment] 2020-06-03 03:14
It would be easier if you could submit a PR per feature, so we could carefully validate every change across the entire console.

**Comment by eldadfux** [comment] 2020-06-14 18:46
@AnatoleLucet I've changed the links animations to be off by default and turned them on manually. Because appwrite.io extends the stylesheets in this repo there were some unexpected behaviours with links inside long articles, and some bugs with mobile only elements that had display: none. This commit should fix it: https://github.com/appwrite/appwrite/commit/56c3f3a94630b90cca5aae13758782db086dd28a

Note that the class `link-animation-disabled` is now `link-animation-enabled`

**Comment by eldadfux** [comment] 2020-07-25 13:08
Hey @AnatoleLucet, any updated on the next improvements in line? Do you think we can push a few more for 0.7?

**Comment by AnatoleLucet** [comment] 2020-07-25 18:10
Hey 👋 I've started working on button animations a few weeks ago but never came back to it. I'll try to find some time tomorrow to  finish the button animations and maybe do the modal transition.

**Comment by eldadfux** [comment] 2020-09-15 14:02
@AnatoleLucet do you think you'll have time to continue working on this?

**Comment by AnatoleLucet** [comment] 2020-09-15 14:24
@eldadfux oops, forgot about that.

> do you think you'll have time to continue working on this?

Unfortunately no, I don't think I'll.

**Comment by eldadfux** [comment] 2020-09-15 14:31
OK, I'll close this for now. Thanks for all the help @AnatoleLucet !

**Closed by eldadfux** 2020-09-15 14:31 UTC
Labels: enhancement, work in progress
