### ISSUE TITLE
🐛 Bug Report: Drop down overflows parent container

### ISSUE THREAD

**Issue by DevJobalia** [appwrite/appwrite#7404] opened 2024-01-07 10:02 UTC
### 👟 Reproduction steps

![image](https://github.com/appwrite/appwrite/assets/109411169/288e9ae5-f7b1-491f-9041-141b35f5977e)

Database > Collection > Attributes > Relationship >  Related Collection
When creating a attribute, 

### 👍 Expected behavior

The related collection drop down should be contained within relationship modal

### 👎 Actual Behavior

![image](https://github.com/appwrite/appwrite/assets/109411169/8d4bd13b-8149-4e02-bce1-c9d5ade2d97b)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kanugurajesh** [comment] 2024-01-07 10:06
.take

**Comment by kanugurajesh** [comment] 2024-01-07 10:07
I would like to work on this issue.

**Comment by stnguyen90** [comment] 2024-01-08 04:03
Thanks for raising this issue! 🙏 We should have a fix somewhere for this already.

**Comment by kailashsur** [comment] 2024-01-08 06:00
Thanks for taking action

**Comment by stnguyen90** [comment] 2024-01-08 18:36
Closing as a duplicate of https://github.com/appwrite/appwrite/issues/7334

**Closed by stnguyen90** 2024-01-08 18:36 UTC
Labels: bug, console, cloud
