### ISSUE TITLE
🐛 Bug Report: Default value not working for attributes

### ISSUE THREAD

**Issue by akago-dev** [appwrite/appwrite#4526] opened 2022-10-18 10:29 UTC
### 👟 Reproduction steps

Add a String or a bool with default value, then check existing documents, the returned value for those attributes is null.

### 👍 Expected behavior

Should update previous documents with default value.

### 👎 Actual Behavior

Return null value instead of default value

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

local env and dev env on google cloud server

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2022-11-15 21:01
Closing as this looks like a duplicate of https://github.com/appwrite/appwrite/issues/2768

**Closed by stnguyen90** 2022-11-15 21:01 UTC
Labels: bug
