### ISSUE TITLE
File not found error 

### ISSUE THREAD

**Issue by jithinlal** [appwrite/appwrite#2691] opened 2022-01-25 18:22 UTC
I am using storage to view a file that is stored using storage. It has a user:userID read access to it.

The file is getting displayed during testing, but the same file is not getting viewed during live deployment.

I am using the js SDK method to get the URL for file view. 
I am getting an error of "file not found" with code 404

**Comment by stnguyen90** [comment] 2022-01-25 19:51
Would you please share more of the code? And maybe the HTTP request that returned 404?

One thing that could be the problem is the session cookie is not being included in the network request. To have the cookie set properly, you may need to create a custom domain for your appwrite instance that has the same base domain as your app.

**Comment by jithinlal** [comment] 2022-01-26 05:51
All i am doing is calling the SDK function to fetch the view URL

`appwrite.storage.getFileView(file.$id)`

My react front end is on domain, say, `storage.test.com`

And what i am doing for my appwrite at the moment. And my appwrite is running on my local machine and i am tunneling it at a domain called, say,  `sample.tunnel.com`

When i give the read permission to be role:all the image view is working perfect. But when i give it like user:{userId} the file is not getting viewed even by the person who has permission to read it

**Comment by eldadfux** [comment] 2022-01-26 05:55
This does sound like a cookie issue. Try to set a custom domain that has the same top-level domain for both your app and Appwrite. For example: `myapp.com` and `appwrite.myapp.com`

**Comment by jithinlal** [comment] 2022-01-26 06:17
So what you mean, is i want to host appwrite under the host name right?

**Comment by stnguyen90** [comment] 2022-01-26 06:28
You can set up a custom domain for your project: https://appwrite.io/docs/custom-domains

**Comment by jithinlal** [comment] 2022-01-26 07:21
will it work if i am running appwrite in a tunneled state?

**Comment by stnguyen90** [comment] 2022-01-26 07:41
I believe so as long as you can set up the DNS entry.

**Comment by jithinlalpr** [comment] 2022-01-26 08:40
Is it necessary that my app is in
example.com and appwrite is in app.example.com?

Can my app be in myapp.example.com and appwrite in app.example.com??

**Comment by jithinlal** [comment] 2022-01-26 09:03
Is it necessary that my app is in
example.com and appwrite is in app.example.com?

Can my app be in myapp.example.com and appwrite in app.example.com??

**Comment by stnguyen90** [comment] 2022-01-26 14:15
myapp.example.com and app.example.com should be fine because they both have example.com.

**Comment by eldadfux** [comment] 2022-01-30 22:56
Closing this issue, will re-open if evidence to another problem pops up.

**Closed by eldadfux** 2022-01-30 22:56 UTC
