### ISSUE TITLE
🐛 Bug Report: Docs navbar overflow

### ISSUE THREAD

**Issue by AditiSingh2003** [appwrite/appwrite#6856] opened 2023-10-09 06:00 UTC
### 👟 Reproduction steps

When I clicked on the Docs button, the screen that opens have the Go To Console button crossing out of the screen
![image](https://github.com/appwrite/appwrite/assets/97729662/d7381cf5-f5b5-4d25-8c73-32c22703e7b6)

### 👍 Expected behavior

The button will lie completely inside the screen.

### 👎 Actual Behavior

The button is crossing out of the screen.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by DhairyaMajmudar** [comment] 2023-10-09 06:51
@stnguyen90 @AditiSingh2003 I would like to work on this. Can you assign it to me? 🙏

**Comment by Haimantika** [comment] 2023-10-09 07:11
Hi @AditiSingh2003 which browser are you using? It looks perfectly fine to me
<img width="1512" alt="Screenshot 2023-10-09 at 12 41 24 PM" src="https://github.com/appwrite/appwrite/assets/32809211/7306e58f-e049-4f71-a495-6c32f770a5df">

**Comment by DhairyaMajmudar** [comment] 2023-10-09 07:26
> Hi @AditiSingh2003 which browser are you using? It looks perfectly fine to me <img alt="Screenshot 2023-10-09 at 12 41 24 PM" width="1512" src="https://user-images.githubusercontent.com/32809211/273516771-7306e58f-e049-4f71-a495-6c32f770a5df.png">

ma'am It might be because of the screen zoom

**Comment by DhairyaMajmudar** [comment] 2023-10-09 07:29
![image](https://github.com/appwrite/appwrite/assets/124715224/fd0e9b22-7ee9-4f92-bf5d-a6b2b31fbb06)

In Firefox 90% zoom out facing a similar kind of bug but on further zooming out the bug is resolved

**Comment by TGlide** [comment] 2023-10-09 11:11
Hi @AditiSingh2003, thank you for raising this issue! I managed to reproduce it on certain breakpoints. We'll be fixing this ASAP 🚀

**Comment by DhairyaMajmudar** [comment] 2023-10-09 11:42
> Hi @AditiSingh2003, thank you for raising this issue! I managed to reproduce it on certain breakpoints. We'll be fixing this ASAP 🚀

Can you pls. assign this issue to me.

**Comment by TGlide** [comment] 2023-10-10 09:48
> > Hi @AditiSingh2003, thank you for raising this issue! I managed to reproduce it on certain breakpoints. We'll be fixing this ASAP 🚀
> 
> @Haimantika @TGlide pls. assign this issue to me. I have gone through the code can found out where to fix the bug.

Thanks, but this issue is part of a bigger problem, which I have already created a PR for 🙂

**Closed** 2023-10-10 11:12 UTC
Labels: bug
