### ISSUE TITLE
🐛 Bug Report: Appwrite 1.6.0 functions.createExecution() not executing function

### ISSUE THREAD

**Issue by hej2010** [appwrite/appwrite#8700] opened 2024-09-20 14:47 UTC
### 👟 Reproduction steps

Upgraded from 1.5.10 to 1.6 and now nothing happens when a function executes another function (using https://appwrite.io/docs/references/1.6.x/server-nodejs/functions#createExecution).

```js
const client = new Client()
    .setEndpoint(process.env.APPWRITE_FUNCTION_API_ENDPOINT)
    .setProject(process.env.APPWRITE_FUNCTION_PROJECT_ID)
    .setKey(req.headers['x-appwrite-key']);
const functions = new Functions(client);
const result = await functions.createExecution(
    "my-function",
    JSON.stringify({
      data: here
    }),
    false, // async (optional)
    '/', // path (optional)
    "POST", // method (optional)
  );
log(JSON.stringify(result));
```

For some functions it tries to execute the response from that call is `{"total":0,"executions":[]}` and for others it's 
```json
{
  "total": 2,
  "executions": [
    {
      "$id": "66ed7f8e5f45edfb48b6",
      "$createdAt": "2024-09-20T13:58:38.390+00:00",
      "$updatedAt": "2024-09-20T13:58:42.864+00:00",
      "$permissions": [
        "read(\"user:66bc77ca001acb789ada\")"
      ],
      "functionId": "my-function",
      "trigger": "http",
      "status": "completed",
      "requestMethod": "GET",
      "requestPath": "/",
      "requestHeaders": [],
      "responseStatusCode": 400,
      "responseBody": "",
      "responseHeaders": [
        {
          "name": "content-type",
          "value": "text/plain; charset=utf-8"
        },
        {
          "name": "content-length",
          "value": "18"
        }
      ],
      "logs": "",
      "errors": "",
      "duration": 3.5980348587036,
      "scheduledAt": null
    },
    {
      "$id": "66ed7fb101a11dc0fdd8",
      "$createdAt": "2024-09-20T13:59:13.007+00:00",
      "$updatedAt": "2024-09-20T13:59:13.096+00:00",
      "$permissions": [
        "read(\"user:66bc77ca001acb789ada\")"
      ],
      "functionId": "my-function",
      "trigger": "http",
      "status": "failed",
      "requestMethod": "POST",
      "requestPath": "/",
      "requestHeaders": [],
      "responseStatusCode": 500,
      "responseBody": "",
      "responseHeaders": [
        {
          "name": "content-type",
          "value": "text/plain; charset=utf-8"
        },
        {
          "name": "content-length",
          "value": "0"
        }
      ],
      "logs": "\n",
      "errors": "SyntaxError: Unexpected end of JSON input\n    at JSON.parse (<anonymous>)\n    at get bodyJson [as bodyJson] (/usr/local/server/src/server.js:113:21)\n    at Module.default (file:///usr/local/server/src/function/src/main.js:13:20)\n    at execute (/usr/local/server/src/server.js:208:42)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async action (/usr/local/server/src/server.js:225:7)\n    at async /usr/local/server/src/server.js:14:5\n",
      "duration": 0.042665958404541,
      "scheduledAt": null
    }
  ]
}
```

No Execution is visible in the Appwrite console for the function it tries to execute.

### 👍 Expected behavior

The function should execute.

### 👎 Actual Behavior

Nothing is executed.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

Self-hosted 1.6.0 using the default docker-compose setup and Nginx in front.
node-appwrite 14.1.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ZachHandley** [comment] 2024-09-20 16:24
Did you try syncing your configuration with the new CLI?

**Comment by hej2010** [comment] 2024-09-21 08:46
> Did you try syncing your configuration with the new CLI?

Yes, also tried different node runtimes and node-appwrite 13.0.0 but it's the same issue. Same with #8701

**Comment by hej2010** [comment] 2024-09-21 10:17
Found the issue in https://github.com/appwrite/appwrite/issues/8701#issuecomment-2365132249

**Comment by stnguyen90** [comment] 2024-09-24 00:35
I'm going to close this as a duplicate of https://github.com/appwrite/appwrite/issues/8701

**Closed by stnguyen90** 2024-09-24 00:35 UTC
Labels: bug, product / self-hosted
