### ISSUE TITLE
Support for ARM platform

### ISSUE THREAD

**Issue by AlimFreight** [appwrite/appwrite#465] opened 2020-07-02 22:17 UTC
Hi there,
I was wondering is there any possibility to install AppWrite on arm platform? I tried to find that info but I only  can find that it's  support x86/64 only.

**Comment by eldadfux** [comment] 2020-07-03 06:32
Hey @AlimFreight, currently almost all the containers in the Appwrite stack can support ARM (Traefik, Redis, MariaDB, and InfluxDB). We still need to build the Appwrite container itself and ClamAV to support it as well and test them out. 

Would be great if you could help me with some test, if so you can reach me out on our Discord server: https://appwrite.io/discord

**Comment by eldadfux** [comment] 2020-07-03 15:47
@AlimFreight, @doricci, @reigelgallarde I have some good news. I have been able to test around `docker buildx` and after serval failed attempts was able to push a very experimentally version of Appwrite to Docker Hub that **should support ARM**. This is a great POC, but we still need to push production images for appwrite/appwrite, appwrite/clamav and appwrite/mariadb

**Comment by eldadfux** [comment] 2020-07-03 15:48
And you can check the image on this link: https://hub.docker.com/layers/appwrite/beta/multi/images/sha256-7e486ffb4fa20e38f8013cd8ab0d9057139e0ed89ff14931d230d269c689ecc6?context=repo

**Comment by AlimFreight** [comment] 2020-07-03 15:51
Thank you I will do that right now :)

**Comment by eldadfux** [comment] 2020-07-03 16:10
This are the architectures that are supported by Docker Buildx:
* linux/amd64
* linux/arm64
* linux/ppc64le
* linux/s390x
* linux/386
* linux/arm/v7
* linux/arm/v6

Should we allow support to all of them, or are there any redundant ones on this list?

**Comment by AlimFreight** [comment] 2020-07-03 16:26
I think linux/ppc64le and linux/s390x is quite obsolete.

**Comment by AlimFreight** [comment] 2020-07-04 05:11
I was able to start every container with this  Docker-compose file, but still have some issues with mariadb, and connections between telegraf and influxdb

version: '3'
services:
  traefik:
    image: 'traefik:v2.1.4'
    command:
      - '--providers.file.directory=/storage/config'
      - '--providers.file.watch=true'
      - '--providers.docker=true'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
    restart: unless-stopped
    ports:
      - '88:80'
      - '4455:443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'appwrite-config:/storage/config:ro'
      - 'appwrite-certificates:/storage/certificates:ro'
    depends_on:
      - appwrite
    networks:
      - gateway
      - appwrite
  appwrite:
    image: 'appwrite/beta:multi'
    restart: unless-stopped
    networks:
      - appwrite
    labels:
      - traefik.http.routers.appwrite.rule=PathPrefix(`/`)
      - traefik.http.routers.appwrite-secure.rule=PathPrefix(`/`)
      - traefik.http.routers.appwrite-secure.tls=true
    volumes:
      - 'appwrite-uploads:/storage/uploads:rw'
      - 'appwrite-cache:/storage/cache:rw'
      - 'appwrite-config:/storage/config:rw'
      - 'appwrite-certificates:/storage/certificates:rw'
    depends_on:
      - mariadb
      - redis
      - smtp
      - clamav
      - influxdb
      - telegraf
    environment:
      - _APP_ENV=production
      - _APP_OPENSSL_KEY_V1=your-secret-key
      - _APP_DOMAIN=localhost
      - _APP_DOMAIN_TARGET=localhost
      - _APP_REDIS_HOST=redis
      - _APP_REDIS_PORT=6379
      - _APP_DB_HOST=mariadb
      - _APP_DB_PORT=3306
      - _APP_DB_SCHEMA=appwrite
      - _APP_DB_USER=user
      - _APP_DB_PASS=password
      - _APP_INFLUXDB_HOST=influxdb
      - _APP_INFLUXDB_PORT=8086
      - _APP_STATSD_HOST=telegraf
      - _APP_STATSD_PORT=8125
      - _APP_SMTP_HOST=smtp
      - _APP_SMTP_PORT=25
  mariadb:
    image: 'linuxserver/mariadb:latest'
    restart: unless-stopped
    networks:
      - appwrite
    volumes:
      - 'appwrite-mariadb:/var/lib/mysql:rw'
    environment:
      - MYSQL_ROOT_PASSWORD=rootsecretpassword
      - MYSQL_DATABASE=appwrite
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    command: mysqld --innodb-flush-method=fsync
  smtp:
    image: 'ixdotai/smtp:latest'
    restart: unless-stopped
    networks:
      - appwrite
    environment:
      - MAILNAME=appwrite
      - 'RELAY_NETWORKS=:192.168.0.0/24:10.0.0.0/16'
  redis:
    image: 'redis:5.0'
    restart: unless-stopped
    networks:
      - appwrite
    volumes:
      - 'appwrite-redis:/data:rw'
  clamav:
    image: 'jjoshtech/clamav:arm'
    restart: unless-stopped
    networks:
      - appwrite
    volumes:
      - 'appwrite-uploads:/storage/uploads'
  influxdb:
    image: 'influxdb:latest'
    restart: unless-stopped
    networks:
      - appwrite
    volumes:
      - 'appwrite-influxdb:/var/lib/influxdb:rw'
  telegraf:
    image: 'telegraf:1.14.5'
    restart: unless-stopped
    networks:
      - appwrite
networks:
  gateway: null
  appwrite: null
volumes:
  appwrite-mariadb: null
  appwrite-redis: null
  appwrite-cache: null
  appwrite-uploads: null
  appwrite-certificates: null
  appwrite-influxdb: null
  appwrite-config: null

**Comment by PedroCisnerosSantana** [comment] 2020-09-18 18:31
Hello @AlimFreight could you please give steps to reproduce? Also seems like there's already a mysqld process running, if you are in a fresh install could be Appwrite issue. Telegraf seems to have problems in the port connection, make sure you don't have any kind of strict firewall and make sure that port is not binded by other process.

**Comment by AlimFreight** [comment] 2020-09-18 19:31
> Hello @AlimFreight could you please give steps to reproduce? Also seems like there's already a mysqld process running, if you are in a fresh install could be Appwrite issue. Telegraf seems to have problems in the port connection, make sure you don't have any kind of strict firewall and make sure that port is not binded by other process.

Yes, that was clean installation, and I checked all processes for ports similarity of cause.

**Comment by eldadfux** [comment] 2020-09-27 07:35
Update 27-09-2020:

1. I have opened a new branch for adding ARM support: https://github.com/appwrite/appwrite/tree/feat-465-add-arm-support
2. Added support for multi-CPU architectures as part of our CI process
3. Opened multiple issues to convert all our core docker-images to use Alpine as a base image.

**Comment by eldadfux** [comment] 2020-09-27 08:14
From the first CI run, seems like this are our problematic Docker images:
![image](https://user-images.githubusercontent.com/1297371/94359914-87f39b80-00b2-11eb-91b9-755b39693eb1.png)

**Comment by kodumbeats** [comment] 2021-01-01 21:00
Happy to help with this!

**Comment by eldadfux** [comment] 2021-01-04 09:51
ARM Support Update

Seems like we've managed to solve 99% of all open issues. The only thing still failing right now is the test for executing a Deno cloud function. Seems like the Deno Docker image lacks ARM support: https://github.com/hayd/deno-docker/issues/100

**Comment by g123k** [comment] 2021-03-18 13:59
Any news on this @eldadfux?

**Comment by eldadfux** [comment] 2021-03-20 05:55
@g123k everything is pretty much ready, right now we're just giving it a run to test it is stable with all our latest changes. We also need to make some minor updates to our CI to make sure builds won't take forever. Good chances this will get merged to 0.8.

**Comment by kodumbeats** [comment] 2021-06-09 14:22
It warms my ❤️ to close this as resolved since #726 has been released with Appwrite 0.8.0! 🚀 

Huge thanks to @AlimFreight , @mlucas-NU , @SoftCreatR, and to everyone I've missed who contributed, tested, and gave feedback. This feature was made possible due to the diverse talents and experience of our open-source community 💪🏻

**Closed by kodumbeats** 2021-06-09 14:22 UTC
Labels: enhancement, hacktoberfest, help wanted

**Comment by mlucas-NU** [comment] 2021-06-09 23:17
Totally agree, @eldadfux. Big thanks to everyone involved! I'll miss benchmarking appwrite on my Rockpro64, but I'm always happy to do so for future features. :')
