### ISSUE TITLE
🚀 Feature: Custom cloud-function runtime

### ISSUE THREAD

**Issue by byawitz** [appwrite/appwrite#5547] opened 2023-05-17 15:28 UTC
### 🔖 Feature description

<details><summary>Note</summary>
<p>

> Well, this is actually more [OpenRuntime](https://github.com/open-runtimes/open-runtimes) feature, but, it's related to Appwrite directly. So if it's not the right place I can reopen it.

</p>
</details> 

As of now, Appwrite function has support for all these runtimes:
| C++ | Dart| Deno|
|--------|--------|--------|
| Go | Java| Kotlin|
| Node| PHP| Python|
| Ruby| Swift | | 

And when we want to add a new runtime it has to go through official ways only. That means there is a need of creating an Issue then a matching Pull Request and after a few (necessary) tests the runtime will be added. This is the best solution for most use-case and runtimes.

Also, OpenRuntimes is set to be optimized as such the list of runtimes available in it is only the edge and widely accepted versions. So, In case of someone, for example, have a need for version 5.6 of PHP, this version won't be available from OpenRuntimes.

I think that way to solve all those and to provide higher customization for functions the user can add custom runtimes by adding their docker image version. 

This can be done in a few ways, the first one is just adding it `_APP_FUNCTIONS_RUNTIME` variable. or another variables
```ini
# First way
_APP_FUNCTIONS_RUNTIMES=node-16.0,php-8.0,python-3.9,ruby-3.0,appwrite-custom:php5.6,

# or
_APP_FUNCTIONS_RUNTIMES=node-16.0,php-8.0,python-3.9,ruby-3.0,
_APP_FUNCTIONS_CUSTOM_RUNTIMES=appwrite-custom:php5.6,
```

_The use of PHP 5.6 is just an example._

### 🎤 Pitch

I think that doing so can create a list of unofficial Appwrite-compatible runtimes. And also will make it easy for Runtimes providers to easily create and maintain on their own a solid Appwrite-compatible docker image to be used with Appwrite Cloud functions.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-05-17 16:22
@byawitz, thanks for creating this issue! 🙏🏼 This seems like a duplicate of https://github.com/appwrite/appwrite/issues/1037? Would it be okay to close this and you can 👍🏼 the other issue?

**Comment by byawitz** [comment] 2023-05-17 16:26
Thank you for your time @stnguyen90. 
I've gone over that Issue. it does purpose a similar solution but with a different approach. as that issue targets more the technical aspect of OpenRuntime ready-to-use images.

If you think the end results are the same in both of them then, of course, it will be better to have just the first one.

**Comment by stnguyen90** [comment] 2023-05-19 19:34
@byawitz, it might be good to only focus on 1 issue. If after that issue is closed and we still find the need for custom docker images, you can re-open this one.

**Comment by byawitz** [comment] 2023-05-19 19:36
Make sense 👍

**Closed** 2023-05-19 19:36 UTC
Labels: functions
