### ISSUE TITLE
🐛 Bug Report: LinkedIn Oauth2 Broken

### ISSUE THREAD

**Issue by superseby2** [appwrite/appwrite#4827] opened 2022-12-08 09:59 UTC
### 👟 Reproduction steps

-  create an Oauth2Session like so appwrite.account.createOAuth2Session('linkedin',successPath,errorPath)
- Linkedin prompts for credentials
- On submit, Linkedin displays ""Bummer, something went wrong.
We're having difficulty connecting."

We have opened an issue at LinkedIN here is their reply : 

> We see that in the URI the request has an encoded state parameter and redirectURI parameter. However the state parameter should be a unique string as recommended by [https://www.rfc-editor.org/rfc/rfc6749#section-4.1.1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.rfc-editor.org%2Frfc%2Frfc6749%23section-4.1.1&data=05%7C01%7Crahulgupta%40linkedin.com%7Ce841c17a3f9d4ea1c37d08dad6ded9f4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638058549872596155%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9paiWu44EM5CgAtaT8UEr%2BNITmexpjrI1N39CaiBu7g%3D&reserved=0). Please try double encoding the state parameter. Encoding the redirectURI can also cause issues.
> 
>  
> 
> Please review our documentation here [https://learn.microsoft.com/en-us/linkedin/shared/authentication/authorization-code-flow?tabs=HTTPS](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Flinkedin%2Fshared%2Fauthentication%2Fauthorization-code-flow%3Ftabs%3DHTTPS&data=05%7C01%7Crahulgupta%40linkedin.com%7Ce841c17a3f9d4ea1c37d08dad6ded9f4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638058549872596155%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=T9R%2FwvHz1V%2BXAZttCKxw%2BkOyojhopqJEXJZaimv%2BLLQ%3D&reserved=0)

We dived a little bit our side  and indeed if we urlencode the state parameter the pb goes away. 
from `src/Appwrite/Auth/OAuth2/Linkedin.php`
```
  'https://www.linkedin.com/oauth/v2/authorization?' . \http_build_query([
            'response_type' => 'code',
            'client_id' => $this->appID,
            'redirect_uri' => $this->callback,
            'scope' => \implode(' ', $this->getScopes()),
            'state' => urlencode(\json_encode($this->state)),
        ]);
```

from 'app/controllers/api/account.php` in `App::get('/v1/account/sessions/oauth2/:provider/redirect')` line 363

```
$state = urldecode($state);
```
It seems lile LinkedIN urldecode his side and the state being only  url-encoded once messes up somehow when decoded. (At least that is my understanding). 
It might actually make sense to do this for every OAuth providers as "state" as defined by the RFC should be a String and nothing else.

Could you please have a look ? 

### 👍 Expected behavior

- When the login is successful the redirectURL should be called
- The user should be loggedin

### 👎 Actual Behavior

- Users see the LinkedIn Error Page
- Users are not logged in into our app

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2022-12-08 20:18
Thanks for raising this! 🙏🏼 We'll look into this as soon as we can!

**Comment by SoulPancake** [comment] 2022-12-17 07:20
@stnguyen90 Can I work on this? Seems fairly straightforward as @superseby2 suggested, are there any additional caveats to this?

**Comment by stnguyen90** [comment] 2023-07-27 23:49
So I just tested this on the latest version of Appwrite, but I wasn't able to reproduce the problem as the session created fine for me:

![image](https://github.com/appwrite/appwrite/assets/1477010/a0ee505d-9a41-4707-a572-009e45a09eb5)

@superseby2, are you still experiencing this or may I close this issue?

**Comment by gewenyu99** [comment] 2023-08-03 20:52
@stnguyen90 I'm closing due to inactivity. Feel free to reopen if you found this issue, and have reproduction steps.

**Closed by gewenyu99** 2023-08-03 20:52 UTC
Labels: bug, authentication
