### ISSUE TITLE
🐛 Bug Report: Index not deleted correctly when a linked attribute is deleted before

### ISSUE THREAD

**Issue by xmesky** [appwrite/appwrite#5041] opened 2023-01-25 10:41 UTC
### 👟 Reproduction steps

You have a collection with an attribute "Attribute1" and an index "Index1" with target attribute "Attribute1". If you delete the "Attribute1" attribute before deleting the "Index1" index, this will generate an error when you attempt to recreate the "Index1" index with the same name. Indeed, when you have deleted "Attribute1", Appwrite makes "Index1" disappear from the list of indexes but the latter is not correctly deleted. So if you try to re-create an index with the same name "Index1" there will be an error.

### 👍 Expected behavior

When deleting an attribute being the target of certain indexes, it should completely delete the indexes concerned.

### 👎 Actual Behavior

We have an error when recreating an index with the same name as the old one, previously deleted via attribute deletion. There is an error in the Appwrite logs indicating that the index already exists (normal since the old one with the same name was not correctly deleted).

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite is installed on a Debian 11 VPS with Docker (latest version)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-01-26 00:38
Is this a duplicate of https://github.com/appwrite/appwrite/issues/3274? If so, would you please 👍🏼 that issue and close this?

**Comment by xmesky** [comment] 2023-01-26 23:09
Yes sure

**Comment by stnguyen90** [comment] 2023-01-28 00:11
@xmesky don't forget to 👍 in https://github.com/appwrite/appwrite/issues/3274!

**Closed by stnguyen90** 2023-01-28 00:11 UTC
Labels: bug, database
