### ISSUE TITLE
🐛 Bug Report: Create function permissions covered by page element.

### ISSUE THREAD

**Issue by cetfor** [appwrite/appwrite#8423] opened 2024-07-21 21:29 UTC
### 👟 Reproduction steps

When creating a new Function and selecting permissions, the drop down menu is partially covered by a page element. The path to this issue is `https://cloud.appwrite.io/console/project-<ID_HERE>/functions`.

### 👍 Expected behavior

Show the entire drop down.

### 👎 Actual Behavior

The drop down is covered by a page element.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

Please see the attached image.  I reported this issue in the Maintainers channel on Discord and was asked to submit a ticket so it didn't get lost. Thanks!
![issue](https://github.com/user-attachments/assets/404ee6f3-5ce0-4e6c-b31c-c3ebfec93669)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by RidhamGolakiya** [comment] 2024-07-22 07:19
![Issue screenshot](https://github.com/user-attachments/assets/6c93a5d3-8de5-4660-9849-c67ccf0f7823)

Just need to remove this CSS Z-index

![Issue fixed screenshot](https://github.com/user-attachments/assets/6bc4dd63-33d3-4561-bbd1-7088aab8fb13)

Thanks.

**Comment by stnguyen90** [comment] 2024-07-30 16:57
@cetfor, thanks for raising this. This should be fixed soon. Closing as a duplicate of https://github.com/appwrite/console/issues/1235

**Closed by stnguyen90** 2024-07-30 16:57 UTC
Labels: bug
