### ISSUE TITLE
📚 Documentation: The "Running the Migration" Header Link on the Upgrade Docs is Broken

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#4731] opened 2022-11-19 22:06 UTC
## Reproduction Steps

1. Browse to the [Upgrade docs](https://appwrite.io/docs/upgrade).
2. Scroll to the "Running the Migration" section
3. Click on the header link

## Expected Behavior

The browser jumps to that section similar to if you clicked on [this](https://appwrite.io/docs/installation#installWithDocker).

## Actual Behavior

You're taken to the top of the page

It looks like the header link for both "Installing the Next Version" and "Running the Migration" are incorrect. The links should match the ID

* https://github.com/appwrite/docs/blob/f087e131f531f538747fddd3db134d7f6c79d59e/app/views/docs/upgrade.phtml#L23
* https://github.com/appwrite/docs/blob/f087e131f531f538747fddd3db134d7f6c79d59e/app/views/docs/upgrade.phtml#L69

If a contributor wants to help with this, they can update the files, but won't be able to preview the docs.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by MukulKolpe** [comment] 2022-11-20 07:34
Hey @stnguyen90, can I work on this issue?

**Comment by stnguyen90** [comment] 2022-11-20 15:22
@MukulKolpe assigned! Thanks for your interest!

**Comment by kunalshokeen051** [comment] 2022-12-10 06:03
hi i see the issue is still not resolved can i work on this.

**Comment by fancymithun** [comment] 2023-07-23 18:36
@stnguyen90 Please close this issue.. this issue already merged and solved

**Comment by Haimantika** [comment] 2023-07-29 06:11
> @stnguyen90 Please close this issue.. this issue already merged and solved

Yes! Thanks. Will close this issue now

**Closed by Haimantika** 2023-07-29 06:11 UTC
Labels: good first issue, docs
