### ISSUE TITLE
🐛 Bug Report: Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 1617920 bytes) in /usr/src/code/src/Appwrite/Extend/PDOStatement.php on line 111

### ISSUE THREAD

**Issue by nexmoe** [appwrite/appwrite#5419] opened 2023-04-22 14:28 UTC
### 👟 Reproduction steps

Using 
```
cd appwrite/
docker compose exec appwrite migrate
```

### 👍 Expected behavior

No err

### 👎 Actual Behavior

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 1617920 bytes) in /usr/src/code/src/Appwrite/Extend/PDOStatement.php on line 111

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-04-24 18:53
@nexmoe, thanks for creating this issue! 🙏🏼 Would you be able to provide more of the migrate logs to give us a better idea of where the problem is occurring?

**Comment by nexmoe** [comment] 2023-04-26 06:34
> @nexmoe, thanks for creating this issue! 🙏🏼 Would you be able to provide more of the migrate logs to give us a better idea of where the problem is occurring?

I ran immigration today and didn't show errors when immigrating, but it seems some data didn't immigrate properly.
![image](https://user-images.githubusercontent.com/16796652/234488920-f324a38f-593d-4332-8aa3-5d188cc62bf1.png)
As you can see in the image, it returned that `total` is 8 and `documents` is empty.
When I use 1.2.1, it can return the proper value.

**Comment by nexmoe** [comment] 2023-04-26 06:43
I change back to 1.2.1, it runs all well.
I don't how can I help you locate the question further, if there are other information you need, tell me.
![image](https://user-images.githubusercontent.com/16796652/234490843-bdcd1d3f-8c5f-4058-a23b-866965c3bc3e.png)

**Comment by stnguyen90** [comment] 2023-04-28 23:31
> As you can see in the image, it returned that total is 8 and documents is empty.

There were some bugs in 1.3.1 which should be resolved in 1.3.3. Please try upgrading to that version.

Also, I'm going to close this now since your original issue is no longer a problem. Feel free to join us on [Discord](https://appwrite.io/discord) or open another issue if needed.

**Closed by stnguyen90** 2023-04-28 23:31 UTC
Labels: bug
