### ISSUE TITLE
🐛 Bug Report: Cannot set endpoint with Appwrite CLI

### ISSUE THREAD

**Issue by Clemens05** [appwrite/appwrite#4961] opened 2023-01-06 13:26 UTC
### 👟 Reproduction steps

Hello,

When I want to set the Appwrite client endpoint (`appwrite client --endpoint https://[domain]/v1`), I get the following message: `✗ Error Invalid endpoint or your Appwrite server is not running as expected.`. 

<img width="1125" alt="Bildschirmfoto 2023-01-06 um 14 24 26" src="https://user-images.githubusercontent.com/37633233/211021490-fc74711c-eecb-4683-ab4f-8966fa0d5288.png">

Thanks, Clemens

### 👍 Expected behavior

It should set the API endpoint to ` https://[domain]/v1 `

### 👎 Actual Behavior

I get the following message: `✗ Error Invalid endpoint or your Appwrite server is not running as expected.`.

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use a droplet at DigitalOcean. I created this droplet with the [Marketplace app](https://marketplace.digitalocean.com/apps/appwrite). 

Appwrite version: 1.2.0
OS: Ubuntu 20.04

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-01-06 23:11
@Clemens05 thanks for raising this issue! 🙏🏼 Does your domain have a valid SSL certificate?

**Comment by Clemens05** [comment] 2023-01-07 13:44
Thanks for your reply,

yes it has a valid SSL certificate. When I access the Appwrite dashboard, I always have a HTTPS connection.

**Comment by stnguyen90** [comment] 2023-01-10 19:29
@Clemens05 from where you're running the Appwrite CLI, what's the output of:

```shell
curl https://[domain]/v1/health/version
```

**Comment by Clemens05** [comment] 2023-01-10 21:50
It says:
```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by stnguyen90** [comment] 2023-01-11 01:39
@Clemens05, this seems to indicate you need a valid certificate for the domain. As such, I'm going to close this as a duplicate of https://github.com/appwrite/sdk-for-cli/issues/58#issuecomment-1378130092. Feel free to comment if that's not the case.

**Closed by stnguyen90** 2023-01-11 01:39 UTC
Labels: bug

**Comment by felipeavilis** [comment] 2023-03-15 19:04
Im facing the same isssue. The difference here is that my Appwrite is behind a Nginx doing reverse proxy.

* curl is fine

    curl https://domain.com/v1/health/version
    {"version":"1.2.1"}

* Login with IP address, fine!

    > appwrite login
    ? Enter your email felipe@domain.com
    ? Enter your password *******
    ? Enter the endpoint of your Appwrite server http://0.0.0.0/v1
    ✓ Success

* Login with FQDN, fail... 

    > appwrite login
    ? Enter your email felipe@domain.com
    ? Enter your password *******
    ? Enter the endpoint of your Appwrite server http://domain.com/v1
    ✗ Error Invalid endpoint or your Appwrite server is not running as expected.

Nginx server config `/etc/nginx/sites-enabled/appwrite.conf` :

    server{
           listen 80;
           server_name appwrite-dev.domain.com;
           return 301 https://appwrite-dev.domain.com$request_uri;
    }
    server{
           listen 443 ssl;
           server_name appwrite-dev.domain.com;
           location / {
                   proxy_set_header Upgrade    $http_upgrade;
                   proxy_set_header Connection $http_connection;
                   proxy_http_version 1.1;
                  add_header       X-Served-By        $host;
                   proxy_set_header X-Forwarded-Scheme $scheme;
                   proxy_set_header X-Forwarded-Proto  $scheme;
                   proxy_set_header X-Forwarded-Host   $host;
                   proxy_set_header X-Forwarded-For    $remote_addr;
                   proxy_set_header Host       $host;
                   proxy_set_header X-Real-IP  $remote_addr;
                   proxy_pass http://10.0.0.1;
           }
    }

SSL Settings are in nginx.conf
