### ISSUE TITLE
🐛 Bug Report: Users CreateSession endpoint doesn't create a session for the user

### ISSUE THREAD

**Issue by pingu2k4** [appwrite/appwrite#8788] opened 2024-10-11 01:22 UTC
### 👟 Reproduction steps

- Make a call to the [create session endpoint within the Users API](https://appwrite.io/docs/references/1.6.x/server-rest/users#createSession).
- For the user you specified, note that no session is created by checking their account in the console
- A session object IS returned over the API, but no session is attributed to the user you specified.
- The secret returned cannot be used as authentication for the user either, so the endpoint has no use as it currently stands.

### 👍 Expected behavior

Returned session should be attributed to the requested user, and should be usable

### 👎 Actual Behavior

No session is attached to the user specified, and cannot be used for the user at all.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

Making requests with postman / my in-progress SDK

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jspm2013** [comment] 2024-10-12 06:06
Probably it's the first session which has to be created at all for a user (password or phone), and maybe afterwards the programmatically use of create session will always work as expected...?

**Comment by pingu2k4** [comment] 2024-10-12 06:54
> Probably it's the first session which has to be created at all for a user (password or phone), and maybe afterwards the programmatically use of createSession will always work as expected...?

No, I saw this bug with existing sessions already on a user also. It was identical behaviour when there were no sessions, or pre-existing sessions

**Comment by ComissarLetlev** [comment] 2024-11-18 06:45
Any solutions

**Comment by stnguyen90** [comment] 2024-11-23 05:54
Closing as a duplicate of https://github.com/appwrite/appwrite/issues/8569. Please add a 👍🏼 to the other issue.

**Closed by stnguyen90** 2024-11-23 05:54 UTC
Labels: bug
