### ISSUE TITLE
🚀 Feature: Modify Length of Existing String

### ISSUE THREAD

**Issue by leejustin** [appwrite/appwrite#6905] opened 2023-10-13 22:18 UTC
### 🔖 Feature description

It would be very useful to have a mechanism to update the string length of a field that has already been created.

### 🎤 Pitch

Having a table be put under a pending state is expected when you do a refactor on the length and I don't think it's a deal-breaker.

Having the onus on the user to define the string length means that we should be able to have flexibility in how we want to manage the data structure. Usage of a database column is not always perfectly scoped out and there are transformations for data as our applications grow over time. This is *especially* true when we use the column to store JSON blobs as many Appwrite supporters recommend doing for complex data.

The rigidity works fine for one-off projects but someone will be punished having an application grow over time and investing in Appwrite for larger projects. Instead, I now need to figure out a way to migrate all of the data into another newly-created field which is going to create downtime anyways.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by nishitxmehta** [comment] 2023-10-14 03:31
Hi @leejustin, can you please assign this issue to me?

**Comment by ItzNotABug** [comment] 2023-10-14 12:00
Is this same as https://github.com/appwrite/appwrite/issues/5458?

**Comment by stnguyen90** [comment] 2023-10-16 20:45
> Instead, I now need to figure out a way to migrate all of the data into another newly-created field which is going to create downtime anyways.

Btw, to handle this in production, I would recommend a multi-phased approach to be able to handle apps using an old version of our app. Here are some resources:

* https://thorben-janssen.com/update-database-schema-without-downtime/
* https://teamplify.com/blog/zero-downtime-DB-migrations/#example-3-solution
* https://reflectoring.io/zero-downtime-deployments-with-feature-flags/

For now, I'm going to close this a duplicate of https://github.com/appwrite/appwrite/issues/5458.

**Closed by stnguyen90** 2023-10-16 20:45 UTC
