### ISSUE TITLE
🐛 Bug Report: calling deleteDocument with an empty collection ID deletes the whole database

### ISSUE THREAD

**Issue by t0mm4rx** [appwrite/appwrite#5597] opened 2023-05-29 14:32 UTC
### 👟 Reproduction steps

Hello, this bug is quite severe.

Reference:
- https://ptb.discord.com/channels/564160730845151244/1112736240186437674
- https://ptb.discord.com/channels/564160730845151244/1098833742249857044

Via a SDK or a function, call `deleteDocument` with an empty collection ID.

### 👍 Expected behavior

It should yield an error.

### 👎 Actual Behavior

It actually erases the whole database.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Self-hosted via the official docker-compose file.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-05-29 14:52
@t0mm4rx, thanks for raising this issue! 🙏 This is actually a duplicate of https://github.com/appwrite/appwrite/issues/5310 so I'll close this and you can 👍 that issue.

**Closed by stnguyen90** 2023-05-29 14:52 UTC
Labels: bug
