### ISSUE TITLE
🐛 Bug Report: Wrong Error Returned when Project ID is Not Provided

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#7743] opened 2024-03-07 13:18 UTC
### 👟 Reproduction steps

Assuming there are correct permissions applied to relevant Storage, Databases, etc. Follow this -

1. Build a mis-configured `Client` i.e. without adding the Project ID.
```js
const client = new Client()
    .setEndpoint('https://cloud.appwrite.io/v1')
    .setKey(playgroundKey);
```

2. Do any request like -
```js
const bucketFiles = await storage.listFiles(bucketId);
console.log(JSON.stringify(bucketFiles, null, 2));
```

or

```js
const documents = await databases.listDocuments(databaseID, collectionID);
console.log(JSON.stringify(documents, null, 2));
```

---
There are 2 types of outputs here -
1. If as previously assumed, permissions are in place then this is returned -
```text
AppwriteException [Error]: Storage bucket with the requested ID could not be found.
```

2. If permissions are not correctly set i.e. if the caller doesn't have permission to access the resource, the error is -
```text
AppwriteException [Error]: User (role: guests) missing scope (buckets.read)
```

---
Interestingly, calls to `Databases.listFiles()` return an `Error 500`for case 1 -
```text
AppwriteException [Error]: Server Error
```

---
Tested against Web & Node Appwrite SDKs, its possible that other SDKs might be affected too.

### 👍 Expected behavior

Check `Client` for all required fields like Endpoint, Project ID, Key or JWT and throw a correct error.

### 👎 Actual Behavior

Wrong error are returned.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2024-03-08 21:22
@ItzNotABug, thanks for creating this issue! 🙏🏼 I think this is a duplicate of https://github.com/appwrite/appwrite/issues/6166. As such, please add a 👍🏼 to that issue as I will be closing this one.

**Closed by stnguyen90** 2024-03-08 21:22 UTC
Labels: bug
