### ISSUE TITLE
🐛 Bug Report: Broken README Link

### ISSUE THREAD

**Issue by bharatr21** [appwrite/appwrite#6459] opened 2023-10-03 15:19 UTC
### 👟 Reproduction steps

1. Go to the Readme Page of appwrite repo - [Link](https://github.com/appwrite)
2. Go to the Connect with us Part
3. Apply to Appwrite through the [Appwrite Careers page (We're HIRING!)](https://appwrite.io/company/careers) 🧑‍💻 link

### 👍 Expected behavior

This link should ideally redirect to the correct Appwrite Careers Page [here](https://careers.appwrite.io/)

### 👎 Actual Behavior

Instead redirects to a broken (possibly just outdated) link [here](https://appwrite.io/company/careers) which says it's not found

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

Not applicable, this is on the GitHub README

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Harsh3363** [comment] 2023-10-03 16:07
Hi I would like to work on this bug please assign this to me

**Comment by bharatr21** [comment] 2023-10-03 16:15
A PR has already been opened for this bug, please find some other issue to work on

**Comment by stnguyen90** [comment] 2023-10-04 19:52
Closing as a duplicate of https://github.com/appwrite/appwrite/issues/6451

**Closed by stnguyen90** 2023-10-04 19:52 UTC
Labels: bug
