### ISSUE TITLE
🚀 Feature:  Add Point Attribute type

### ISSUE THREAD

**Issue by moshOntong-IT** [appwrite/appwrite#7022] opened 2023-10-27 06:18 UTC
### 🔖 Feature description

The feature request is to add a new attribute type we can called it `POINT`, it will be like this (x,y). This feature is something similar on POSTGRE or MYSQL POINT datatype, it has  (x,y)

### 🎤 Pitch

In this case it will be helpful, to use this attribute type on Longitude and Latitude address of the particular user. This will also help the appwrite team, if ever they will implement soon to get the nearest between users address.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by adarsh-jha-dev** [comment] 2023-10-27 12:23
Hey @moshOntong-IT , could you please assign me this issue?

**Comment by stnguyen90** [comment] 2023-10-27 21:29
@moshOntong-IT, thanks for creating this issue! 🙏🏼 It sounds like what you're really looking for is geo-based operations. If that's the case, I think this would be a duplicate of https://github.com/appwrite/appwrite/issues/388. As such, can this be closed and you can 👍🏼 the original issue?

FYI, it is possible to do some geo-based operations today. See [this](https://github.com/appwrite/appwrite/issues/388#issuecomment-1490527240) comment.

**Closed** 2023-11-03 22:38 UTC
Labels: databases
