### ISSUE TITLE
🐛 Bug Report: Verification email after signup

### ISSUE THREAD

**Issue by step135** [appwrite/appwrite#7361] opened 2023-12-30 09:01 UTC
### 👟 Reproduction steps

It is not possible to send verification email after creating a new account. The login has to procede it.

### 👍 Expected behavior

User creates account and verification email should be sent immediately. 

Also why don't you do it automatically?

### 👎 Actual Behavior

Email verification can be send only after creating a session.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by sourabpramanik** [comment] 2023-12-30 13:06
@step135  I guess it is more of a feature than a bug. Maybe it changes the auth flow as it works fine but it is not broken. What do you think?

**Comment by step135** [comment] 2023-12-30 13:22
I throws error and it doesn't make sense it it behaves so. Standard workflow is that the verification email is sent before user login for the first time. Without verification the user shouldn't be able to create session.

**Comment by step135** [comment] 2023-12-30 13:23
I throws error and it doesn't make sense it behaves so. Standard workflow is that the verification email is sent before user login for the first time. Without verification the user shouldn't be able to create session.

**Comment by step135** [comment] 2023-12-30 13:23
I throws error and it doesn't make sense that it behaves so. Standard workflow is that the verification email is sent before user login for the first time. Without verification the user shouldn't be able to create session.

**Comment by sourabpramanik** [comment] 2023-12-30 13:33
> I throws error and it doesn't make sense that it behaves so. Standard workflow is that the verification email is sent before user login for the first time. Without verification the user shouldn't be able to create session.

Okay now I got it. I will check once and if I found a fix for it then I may raise a PR. Thanks

**Comment by satnamalhan** [comment] 2023-12-30 15:32
right @step135

**Comment by step135** [comment] 2024-01-01 11:49
I suggest also that only resending verification email can be controlled by developer. The initial one should be automatic.

**Comment by stnguyen90** [comment] 2024-01-04 22:19
@step135, thanks for creating this issue! 🙏🏼 

> It is not possible to send verification email after creating a new account. The login has to procede it.

It is expected to require a session to send the verification email to ensure the right person is requesting the verification email.

> Also why don't you do it automatically?

Appwrite cannot send it automatically because Appwrite doesn't know the URL where you, as the developer, will handle the [confirmation](https://appwrite.io/docs/references/cloud/client-web/account#updateVerification).

Since things are working as designed, I'm going to close this issue.

**Closed by stnguyen90** 2024-01-04 22:19 UTC
Labels: bug, auth
