### ISSUE TITLE
🚀 Feature: Single storage bucket API KEY

### ISSUE THREAD

**Issue by obiwanzenobi** [appwrite/appwrite#6054] opened 2023-08-29 07:07 UTC
### 🔖 Feature description

In console, when selecting `files.read` or `files.write` scope, show additional selector with actual buckets list and option `All buckets`. This API key will have access only to selected buckets (or all of them - selected by default)
Or
In bucket settings in console, there will be new section call API access. This will work similar to API keys tab from projects overview, but this keys will have only `file.read` or/and `file.write` access this particular bucket.

### 🎤 Pitch

When sharing resources saved in appwrite storage with other server side apps there is no option to have fine-grained api key access. 
With server-server communication we don't want to use Account API, but instead go with API keys just like on Google Cloud Storage or S3.

Current options:
- share API key with files.read - client will have access to all of our files
- use account api JWT - create separate user for client backend, but their server side will have to support sessions (maybe appwrite should have "createJWTSession" method instead of two step process of createXSession -> createJWT), this is also nightmare to maintain 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-08-31 23:00
@obiwanzenobi is this maybe a duplicate of https://github.com/appwrite/appwrite/issues/545 or https://github.com/appwrite/appwrite/issues/3398?

**Comment by koch10** [comment] 2023-09-14 07:41
I second this. For security reasons, it would be beneficial to be able to have fine-grained restriction to what resources your functions can access.

**Comment by stnguyen90** [comment] 2024-08-08 19:18
closing as a duplciate of https://github.com/appwrite/appwrite/issues/545

**Closed by stnguyen90** 2024-08-08 19:18 UTC
Labels: enhancement, product / storage, product / console
