### ISSUE TITLE
🚀 Feature: Event before

### ISSUE THREAD

**Issue by bronte2k7** [appwrite/appwrite#5148] opened 2023-02-21 10:21 UTC
### 🔖 Feature description

Need to expand the event system to add new event before, for example, before creating a document.

### 🎤 Pitch

Sometimes it is necessary to change some data before it is created or updated in the document. This will allow pre-processing of the data. For example, data validation...

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-02-23 00:00
@bronte2k7, thanks for raising this issue! 🙏🏼 

You brought up the use case for data validation, but it's impossible to do data validation with a function triggered on events because the update would have already happened.

That said, I think this issue may be a duplicate of https://github.com/appwrite/appwrite/issues/3294. If it is, would you please 👍🏼 the existing issue and close this issue?

**Comment by bronte2k7** [comment] 2023-02-23 06:01
Only part of the idea is described #3294 Need before and after hooks for functions. Through a function on the server side, you want to change some data or delete it before it gets into the document. Or perform some kind of data manipulation after not in the document but after updating it

**Comment by gepd** [comment] 2023-02-23 15:23
I was nedding the same thing for a project but after doing some test, I realize that a function don't perform any change in the database so we can create a basic event on our own

```js
// before event

appwrite.database.create_document(...);

// after event
``` 

You can make a call to have the current data in the dabase before update it and we can even trigger a new function

```js

const newData = APPWRITE_FUNCTION_EVENT_DATA;
const documentId = newData.$id;
const currentData = await appwrite.database.getDocument('database', documentId);

// any logic

appwrite.database.updateDocument(...);

// call other function

appwrite.functions.createExecution('[FUNCTION_ID]');
```

**Comment by stnguyen90** [comment] 2023-02-24 19:00
@bronte2k7 

> Need before and after hooks for functions. 

For this, you might want to 👍🏼 this issue: https://github.com/appwrite/appwrite/issues/2358.

> Through a function on the server side, i am want to change some data or delete it before it gets into the document. 

For this, I'd recommend creating a function for creating the document rather than calling `createDocument()` client side. The function can change whatever data and then call `createDocument()`.

**Comment by bronte2k7** [comment] 2023-02-24 19:15
@stnguyen90
Yes, my idea is the same as #2358
Creating a document from a function is a good idea. But hooks before and after would be more convenient.

**Comment by bronte2k7** [comment] 2023-02-24 19:28
It would be very convenient if before and after hooks could be added on the collection page in the console.

**Comment by stnguyen90** [comment] 2023-02-25 01:27
Closing this as a duplicate of https://github.com/appwrite/appwrite/issues/2358 and https://github.com/appwrite/appwrite/issues/3294

**Comment by stnguyen90** [comment] 2023-02-25 01:28
@bronte2k7 please make sure you 👍🏼 the related PRs so that we can accurately gauge interest.

**Closed by stnguyen90** 2023-02-25 01:27 UTC
Labels: functions
