### ISSUE TITLE
🐛 Bug Report: Local function dart3.3 runtime error: Request body size exceeds the size limit.

### ISSUE THREAD

**Issue by berthou** [appwrite/appwrite#8789] opened 2024-10-11 08:04 UTC
### 👟 Reproduction steps

Get the latest compose (https://appwrite.io/install/compose) and env (https://appwrite.io/install/env)

Replace production with development and add dart-3.3 (latest supported) to the runtimes list

```diff
1c1
< _APP_ENV=production
---
> _APP_ENV=development
85c85
< _APP_FUNCTIONS_RUNTIMES=node-16.0,php-8.0,python-3.9,ruby-3.0
---
> _APP_FUNCTIONS_RUNTIMES=node-16.0,php-8.0,python-3.9,ruby-3.0,dart-3.3
```

```bash
docker-compose up -d
```

visit the console, create account, create org

```bash
appwrite client -e http://localhost/v1 -ss true
appwrite login
appwrite init project #defaults
appwrite init functions #defaults with runtime dart-3.3
```

set function's lib/main.dart to
```dart
import 'dart:async';
import 'dart:io';
import 'package:dart_appwrite/dart_appwrite.dart';

Future<dynamic> main(final context) async {

  return context.res.json({
    'motto': 'Build like a team of hundreds_',
    'learn': 'https://appwrite.io/docs',
    'connect': 'https://appwrite.io/discord',
    'getInspired': 'https://builtwith.appwrite.io',
  });
}
```

run function locally

```bash
appwrite run function #defaults
````

### 👍 Expected behavior

when visiting http://localhost:3000/ we should get a 200 response json with {'motto': 'Build like a team of hundreds_',.....}

If I do exactly the same steps with the python3.9 runtime env it works perfectly

### 👎 Actual Behavior

get 500 response

with server side error :
```bash
Request body size exceeds the size limit.
#0      action (file:///usr/local/server/src/server.dart:33)
#1      main.<anonymous closure> (file:///usr/local/server/src/server.dart:196)
#2      handleRequest (package:shelf/shelf_io.dart:138)
#3      serveRequests.<anonymous closure>.<anonymous closure> (package:shelf/shelf_io.dart:91)
#4      _rootRunUnary (dart:async/zone.dart:1407)
#5      _CustomZone.runUnary (dart:async/zone.dart:1308)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#9      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784)
#10     _StreamController._add (dart:async/stream_controller.dart:658)
#11     _StreamController.add (dart:async/stream_controller.dart:606)
#12     _HttpServer._handleRequest (dart:_http/http_impl.dart:3328)
#13     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:3112)
#14     _rootRunUnary (dart:async/zone.dart:1407)
#15     _CustomZone.runUnary (dart:async/zone.dart:1308)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784)
#20     _StreamController._add (dart:async/stream_controller.dart:658)
#21     _StreamController.add (dart:async/stream_controller.dart:606)
#22     _HttpParser._headersEnd (dart:_http/http_parser.dart:390)
#23     _HttpParser._doParse (dart:_http/http_parser.dart:759)
#24     _HttpParser._parse (dart:_http/http_parser.dart:320)
#25     _HttpParser._onData (dart:_http/http_parser.dart:887)
#26     _rootRunUnary (dart:async/zone.dart:1407)
#27     _CustomZone.runUnary (dart:async/zone.dart:1308)
#28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#31     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784)
#32     _StreamController._add (dart:async/stream_controller.dart:658)
#33     _StreamController.add (dart:async/stream_controller.dart:606)
#34     _Socket._onData (dart:io-patch/socket_patch.dart:2447)
#35     _rootRunUnary (dart:async/zone.dart:1415)
#36     _CustomZone.runUnary (dart:async/zone.dart:1308)
#37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784)
#41     _StreamController._add (dart:async/stream_controller.dart:658)
#42     _StreamController.add (dart:async/stream_controller.dart:606)
#43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1936)
#44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1379)
#45     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
#47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118)
#48     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185)
```

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

MacOS

### 🧱 Your Environment

Appwrite 1.6.0 run locally using docker compose

macOs 15.0.1
docker+compose installed through brew
docker desktop 4.34.2
Engine: 27.2.0
Compose: v2.29.2-desktop.2

I have dart installed locally but not sure this is relevant:
Dart SDK version: 3.5.3 (stable) (Wed Sep 11 16:22:47 2024 +0000) on "macos_arm64"

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by berthou** [comment] 2024-10-11 08:04
Related discord thread:
https://discord.com/channels/564160730845151244/1293518351997337692

**Comment by christyjacob4** [comment] 2024-10-31 16:03
@berthou Thanks for raising this issue. We are looking into it and will get it resolved ASAP

**Comment by Meldiron** [comment] 2024-11-04 13:38
I reproduced the problem, but only with GET requests that don't have a body.

I believe root cause is following line: https://github.com/open-runtimes/open-runtimes/blob/main/runtimes/dart/versions/latest/src/server.dart#L32

Null content-length always results in the exception. This is unexpected behaviour.
Ill be working on a fix, and adding a test to ensure this works properly in all runtimes.

**Comment by Meldiron** [comment] 2024-11-04 13:54
I couldn't reproduce this on production, confirming it's local only. On production there is Appwrite API and Executor in front, and some of them are likely adding `0` content-length to request, preventing this problem.

This PR should be a fix to local issues: https://github.com/open-runtimes/open-runtimes/pull/329

Once released, CLI will automatically pull newest fix to Dart runtime.

**Comment by Meldiron** [comment] 2024-11-04 14:08
Resolved ✅

This issue existed in Dart and Ruby.

New versions were released. This problem should no longer be occurring. CLI update isn't nessessary simply rerunning `appwrite run` should fix the problem.

Before:

![Image](https://github.com/user-attachments/assets/b6f92153-5820-4c4c-b188-4d6793aae352)


After:

![Image](https://github.com/user-attachments/assets/d3072060-63dc-4ec0-b6c3-ba9677d882c5)

**Comment by Meldiron** [comment] 2024-11-04 14:10
@berthou Thanks for reporting the issue, and providing all the details. It means a lot! 🙌
@dhonig-weizmann Huge thanks to you as well for sharing further details.

Ill be closing the issue, but please re-open it if anyone still faces this specific issue.

**Closed by Meldiron** 2024-11-04 14:10 UTC
Labels: bug, product / functions
