### ISSUE TITLE
🐛 Bug Report: Incorrect Logging Variable in Account - Should Use console.log(result) Instead of console.log(response)

### ISSUE THREAD

**Issue by Lavavarshney** [appwrite/appwrite#8590] opened 2024-08-28 10:40 UTC
### 👟 Reproduction steps

1. Review the code or documentation related to Account where logging is demonstrated.
2 .Notice that console.log(response) is used to output the result of a function .
![image](https://github.com/user-attachments/assets/6c9534ad-1d74-4b11-9938-b9e45ca0e037)
 

### 👍 Expected behavior

 Should Use console.log(result) Instead of console.log(response)

### 👎 Actual Behavior

![image](https://github.com/user-attachments/assets/84188bcb-49d5-44b4-bc85-c5bc1c0dade4)

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by prashant235913** [comment] 2024-08-29 00:32
I noticed that the result variable is used in our test cases to capture and verify method outputs, while the response variable in the main code handles API responses and attributes like result, status, and messages.

Could you please clarify if there is a discrepancy or mismatch between how result and response are handled? Specifically:

Consistency Check: Are there cases where the test expectations for result do not align with how response is set up in the main code?
Impact Assessment: Could this discrepancy affect test results or the overall functionality of the application?
Understanding this will help in addressing any potential issues and ensuring alignment between our tests and main code.
Because So far what I understood is that it's correct?Correct me if I am wrong. I am new to Appwrite.
Thank you!

**Comment by stnguyen90** [comment] 2024-08-30 00:25
@Lavavarshney, thanks for creating this issue! 🙏🏼 I'm going to close this as a duplicate of https://github.com/appwrite/appwrite/issues/8328

**Closed by stnguyen90** 2024-08-30 00:25 UTC
Labels: bug
