### ISSUE TITLE
📚 Documentation: The Logo of Digital Ocean, GitPod Logo is not rendering in README.md

### ISSUE THREAD

**Issue by Veer0x1** [appwrite/appwrite#5217] opened 2023-03-13 06:46 UTC
### 💭 Description: The Logo of Digital Ocean, GitPod Logo is not rendering in README.md
<img width="1440" alt="Screenshot 2023-03-13 at 12 12 03 PM" src="https://user-images.githubusercontent.com/96714915/224626468-eab36b37-ccb3-4cce-a0fe-396650860059.png">

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by abhijain2003** [comment] 2023-03-13 07:19
can I work on this?

**Comment by Veer0x1** [comment] 2023-03-13 07:39
actually, I'm about to make the PR

**Comment by x0samnan** [comment] 2023-03-13 08:50
@Veer0x1 How to reproduce the issue?  I can't see it as svgs are properly rendered on my browser.

**Comment by Veer0x1** [comment] 2023-03-13 09:57
just see the readme of this [](https://github.com/appwrite/appwrite) 
I'm on chrome, I checked it on both my Laptop and Phone , its not showing.

**Comment by x0samnan** [comment] 2023-03-13 12:01
![image](https://user-images.githubusercontent.com/92310785/224695901-20dd3750-1b7e-4135-b99b-5ed29392e51f.png)

@Veer0x1 This one, right?

**Comment by Veer0x1** [comment] 2023-03-13 14:21
yes,I guess it is either a problem with my Mac because I'm not able to see these images in both safari and chrome, and not also in my android phone.

**Comment by x0samnan** [comment] 2023-03-13 14:36
Can you once check the logs once to see if the icon is rendered at all or not

**Comment by stnguyen90** [comment] 2023-03-15 22:53
@Veer0x1, thanks for creating this issue! 🙏🏼 Unfortunately, I'm also not able to reproduce the problem. As such, can we close this issue?

**Comment by Veer0x1** [comment] 2023-03-16 05:57
Okay

**Closed** 2023-03-16 14:32 UTC
