### ISSUE TITLE
🐛 Bug Report: Dart Cloud Functions sends 'Error Msg: Operation timed out' instead of my exception message

### ISSUE THREAD

**Issue by okandemirofficial** [appwrite/appwrite#4950] opened 2023-01-04 21:36 UTC
### 👟 Reproduction steps

When I throw exceptions intentionally Appwrite Function gives 'Error Msg: Operation timed out' instead of my error message after a timeout.

Here is a sample:

```
Future<void> start(final req, final res) async {
  throw Exception('test exception');
}
```
output:
```
An internal curl error has occurred within the executor! Error Msg: Operation timed out
```

PS: I know there is a workaround via wrapping try-catch blocks. But I would like to see the status as 'failed' 

### 👍 Expected behavior

It should throw my Exception message

### 👎 Actual Behavior

An internal curl error has occurred within the executor! Error Msg: Operation timed out

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Windows

### 🧱 Your Environment

"runtime": "dart-2.17"

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-01-05 18:23
Closing as a duplicate of https://github.com/appwrite/appwrite/issues/4529. It would be good if you 👍🏼 that issue.

**Closed by stnguyen90** 2023-01-05 18:23 UTC
Labels: bug
