### ISSUE TITLE
🐛 Bug Report: Error template email

### ISSUE THREAD

**Issue by Maxbrt18** [appwrite/appwrite#4880] opened 2022-12-19 09:47 UTC
### 👟 Reproduction steps

When I ask for a password reset, I receive the following email (in French):

> Bonjour Name Surname
> 
> Suivez ce lien pour réinitialiser votre mot de passe pour {{projet}}.
> 
> https://link:port/password/?userId=...........
> 
> Si vous n'avez pas demandé à réinitialiser votre mot de passe, vous pouvez ignorer ce message.
> 
> Merci 
> L'équipe --------

The problem is with the {{projet}} which is not replaced by the project name.

Have I forgotten to edit a .env variable or is it a bug?

### 👍 Expected behavior

It should replace {{project}} with Appwrite project name.

### 👎 Actual Behavior

It actually doesn't, the template it not modified.

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use a Ubuntu server (running latest version) with last version of Appwrite.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2022-12-21 18:28
@Maxbrt18 thanks for raising this issue! 🙏🏼 Is this a duplicate of https://github.com/appwrite/appwrite/issues/4782? If so, would you please 👍🏼 that issue and close this issue?

**Comment by Maxbrt18** [comment] 2022-12-22 16:30
Thanks, I'll do it 👍

**Closed** 2022-12-22 16:30 UTC
Labels: bug
