### ISSUE TITLE
📚 Documentation: Extend Appwrite Storage with Exoscale Adapter #6412

### ISSUE THREAD

**Issue by HARSHALJETHWA19** [appwrite/appwrite#6474] opened 2023-10-04 06:35 UTC
### 💭 Description

To contribute to Hacktoberfest 2023 by completing task #6412, you'll be working on extending Appwrite Storage with an Exoscale Adapter. This involves creating documentation that explains the integration process between Appwrite and Exoscale storage. Your contribution will enhance Appwrite's capabilities, making it compatible with Exoscale cloud storage services. Happy coding! 🚀

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment] 2023-10-04 07:17
Duplicate of https://github.com/appwrite/appwrite/issues/6412

**Closed by Haimantika** 2023-10-04 07:17 UTC
