### ISSUE TITLE
🚀 Feature:  Disable Orgs and Project Creation for Invited Members

### ISSUE THREAD

**Issue by punitdiwan** [appwrite/appwrite#6858] opened 2023-10-09 06:22 UTC
### 🔖 Feature description

As of now, in Appwrite, if I invite a member to a project within an Organization, he can create further projects and organizations, I cannot stop the user from creating further projects and organizations.

Request you to add a feature to disable further project creation and even new organization creation. 

### 🎤 Pitch

This is useful in self-hosted and cloud-based environments where we grant access to our projects and organization to our team members for managing projects.

This configuration will be done using two environment variables, one for disabling the project and the other for disabling the orgs creations so that it is applied to the whole Appwrite Instance.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment] 2023-10-09 16:41
Duplicate of https://github.com/appwrite/appwrite/issues/3756

Hi @punitdiwan thanks for the feature request. Closing this as it a duplicate, feel free to add your comments there.

**Closed by Haimantika** 2023-10-09 16:41 UTC
