### ISSUE TITLE
🐛 Bug Report: Unable to delete a document, if it has a relation

### ISSUE THREAD

**Issue by jdk-21** [appwrite/appwrite#5558] opened 2023-05-19 11:26 UTC
### 👟 Reproduction steps

I have two collections with following attributes:
task:
- title
- project (one way, many to one, On delete set null)
project:
- title

If I now try to delete a document that has a relation to a task, I get a server error
AppwriteException: 500, 'general unknown'

### 👍 Expected behavior

I expected that the document can be deleted and that tasks that referenced this document have now the value null in the project attribute.

### 👎 Actual Behavior

If I try to delete a project that has a relation to a task, I get a server error:
AppwriteException: 500, 'general unknown'

I would have expected to get an error if the relation type was "restrict", but that's not the case.

If this behavior is actually expected, a clearer exception message would be much appreciated.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite-Version: 1.3.1
Flutter SDK: feat-offline-support-refactor

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment] 2023-05-29 12:47
Hi - about a clearer exception message, we hear you and we are working on improving it. About the error, let me dig deeper into it and get back ASAP.

**Comment by joeyouss** [comment] 2023-06-20 11:04
Hi @jdk-21 
Apologies for taking time to get back to you. I have passed the feedback about better error messages to the concerned team and it has been received positively.

About the error, no this should not be happening. I want to confirm once if you are still facing the same error and if yes, can you please cop whatever you get after running `docker compose logs appwrite` command?

Thank you in advance.

**Comment by jdk-21** [comment] 2023-06-25 09:44
Hi @joeyouss,
I did some digging and noticed that I couldn't reproduce the issue on a completely new appwrite installation until I added a third collection (tags) that also has a relation to tasks. The setup looks now like this:
task:
- title
- project (one way, many to one, On delete set null)
- tags (one way, many to many, On delete set null)

project:
- title

tag:
- title

After trying to delete a task with a relation to a project I can reproduce the error. Below are the logs generated by `docker compose logs appwrite`:
```
appwrite  | [32mWorker 1 started successfully[0m
appwrite  | [1;33mDatabase not ready. Retrying connection (1)...[0m
appwrite  | [32mWorker 5 started successfully[0m
appwrite  | [32mWorker 9 started successfully[0m
appwrite  | [32mWorker 10 started successfully[0m
appwrite  | [32mWorker 11 started successfully[0m
appwrite  | [32mWorker 6 started successfully[0m
appwrite  | [32mWorker 12 started successfully[0m
appwrite  | [32mWorker 7 started successfully[0m
appwrite  | [32mWorker 4 started successfully[0m
appwrite  | [32mWorker 8 started successfully[0m
appwrite  | [32mWorker 3 started successfully[0m
appwrite  | [32mWorker 2 started successfully[0m
appwrite  | [32m[Setup] - Server database init started...[0m
appwrite  | [32m[Setup] - Creating database: appwrite...[0m
appwrite  | [32m[Setup] - Creating collection: databases...[0m
appwrite  | [32m[Setup] - Creating collection: attributes...[0m
appwrite  | [32m[Setup] - Creating collection: indexes...[0m
appwrite  | [32m[Setup] - Creating collection: projects...[0m
appwrite  | [32m[Setup] - Creating collection: platforms...[0m
appwrite  | [32m[Setup] - Creating collection: domains...[0m
appwrite  | [32m[Setup] - Creating collection: keys...[0m
appwrite  | [32m[Setup] - Creating collection: webhooks...[0m
appwrite  | [32m[Setup] - Creating collection: users...[0m
appwrite  | [32m[Setup] - Creating collection: tokens...[0m
appwrite  | [32m[Setup] - Creating collection: sessions...[0m
appwrite  | [32m[Setup] - Creating collection: teams...[0m
appwrite  | [32m[Setup] - Creating collection: memberships...[0m
appwrite  | [32m[Setup] - Creating collection: functions...[0m
appwrite  | [32m[Setup] - Creating collection: deployments...[0m
appwrite  | [32m[Setup] - Creating collection: builds...[0m
appwrite  | [32m[Setup] - Creating collection: executions...[0m
appwrite  | [32m[Setup] - Creating collection: certificates...[0m
appwrite  | [32m[Setup] - Creating collection: buckets...[0m
appwrite  | [32m[Setup] - Creating collection: stats...[0m
appwrite  | [32m[Setup] - Creating collection: realtime...[0m
appwrite  | [32m[Setup] - Creating collection: cache...[0m
appwrite  | [32m[Setup] - Creating collection: variables...[0m
appwrite  | [32m[Setup] - Creating default bucket...[0m
appwrite  | [32m[Setup] - Creating files collection for default bucket...[0m
appwrite  | [32m[Setup] - Server database init completed...[0m
appwrite  | [32mServer started successfully (max payload is 6,291,456 bytes)[0m
appwrite  | [34mMaster pid 1, manager pid 8[0m
appwrite  | [1;33mlocalhost is not a publicly accessible domain. Skipping SSL certificate generation.[0m
appwrite  | [31m[Error] Timestamp: 2023-06-25T09:03:22+00:00[0m
appwrite  | [31m[Error] Method: GET[0m
appwrite  | [31m[Error] URL: /v1/account[0m
appwrite  | [31m[Error] Type: Appwrite\Extend\Exception[0m
appwrite  | [31m[Error] Message: User (role: guests) missing scope (account)[0m
appwrite  | [31m[Error] File: /usr/src/code/app/controllers/general.php[0m
appwrite  | [31m[Error] Line: 365[0m
appwrite  | [1;33mlocalhost is not a publicly accessible domain. Skipping SSL certificate generation.[0m
appwrite  | [31m[Error] Timestamp: 2023-06-25T09:03:22+00:00[0m
appwrite  | [31m[Error] Method: GET[0m
appwrite  | [31m[Error] URL: /v1/account[0m
appwrite  | [31m[Error] Type: Appwrite\Extend\Exception[0m
appwrite  | [31m[Error] Message: User (role: guests) missing scope (account)[0m
appwrite  | [31m[Error] File: /usr/src/code/app/controllers/general.php[0m
appwrite  | [31m[Error] Line: 365[0m
appwrite  | [31m[Error] Timestamp: 2023-06-25T09:03:25+00:00[0m
appwrite  | [31m[Error] Method: GET[0m
appwrite  | [31m[Error] URL: /v1/account[0m
appwrite  | [31m[Error] Type: Appwrite\Extend\Exception[0m
appwrite  | [31m[Error] Message: User (role: guests) missing scope (account)[0m
appwrite  | [31m[Error] File: /usr/src/code/app/controllers/general.php[0m
appwrite  | [31m[Error] Line: 365[0m
appwrite  | [31m[Error] Timestamp: 2023-06-25T09:23:22+00:00[0m
appwrite  | [31m[Error] Method: GET[0m
appwrite  | [31m[Error] URL: /v1/projects/:projectId[0m
appwrite  | [31m[Error] Type: Appwrite\Extend\Exception[0m
appwrite  | [31m[Error] Message: Project with the requested ID could not be found. Please check the value of the X-Appwrite-Project header to ensure the correct project ID is being used.[0m
appwrite  | [31m[Error] File: /usr/src/code/app/controllers/api/projects.php[0m
appwrite  | [31m[Error] Line: 240[0m
appwrite  | [1;33mlocalhost is not a publicly accessible domain. Skipping SSL certificate generation.[0m
appwrite  | [31m[Error] Timestamp: 2023-06-25T09:26:01+00:00[0m
appwrite  | [31m[Error] Method: DELETE[0m
appwrite  | [31m[Error] URL: /v1/databases/:databaseId/collections/:collectionId/documents/:documentId[0m
appwrite  | [31m[Error] Type: PDOException[0m
appwrite  | [31m[Error] Message: Unknown column 'tags' in 'field list'[0m
appwrite  | [31m[Error] File: @swoole-src/library/core/Database/PDOStatementProxy.php[0m
appwrite  | [31m[Error] Line: 64[0m
appwrite  | [2023-06-25 09:27:00 #1.2]	INFO	Server is shutdown now
```

I also noticed that I'm not able to add a tag relation to a task in the web interface, as the update button is still greyed out:
<img width="987" alt="Bildschirmfoto 2023-06-25 um 11 35 23" src="https://github.com/appwrite/appwrite/assets/57756132/c185b0c9-245d-44b9-bcb4-41cbee50e5e5">

> Also, can you let me know if the relationship on delete was always set null, or if it was changed

Yes, I only changed the relation type after the error occured.

Thank you for your help.

**Comment by fanatic75** [comment] 2023-07-05 09:05
Hi @jdk-21 ,

We would like to fix this bug now as we have some capacity, I tried replicating the issue directly with the three collections you mentioned, but I could not reproduce the bug. Let me know if I need to do something differently. 


My steps

1. Create a collection of Tags with a title attribute
2. Create a collection Project with a title attribute
3. Create a collection task with a title attribute, relationship attribute to Project (one way, many to one, On delete set null), relationship attribute to Tags  (one way, many to many, On delete set null)
4. Adding a document in the Tags collection. 
5. Adding a document in the Project collection. 
6. Adding a document in the Tasks collection.


After this, I tried multiple things to reproduce this issue, the first one 
Deleting the project document to see the Tasks document shows N/A in Project, which is expected. 

Deleted tasks document successfully as well, which is expected behaviour. 

Can you please try out the bug with a new app write version? Please share your findings. Thanks

**Comment by fogelito** [comment] 2023-07-13 13:13
I could not reproduce the steps to get an error, for me, it is working as expected, I think we fixed this in one of the iterations.
Will close it for now 👍

**Closed by fogelito** 2023-07-13 13:13 UTC
Labels: bug, database
