### ISSUE TITLE
🐛 Bug Report: Console: Cookies are not cleared on logout, and can prevent login later

### ISSUE THREAD

**Issue by BenMemescape** [appwrite/appwrite#3584] opened 2022-07-21 19:13 UTC
### 👟 Reproduction steps

After logging in to the Console UI, some cookies are set. Of particular relevance I think are `_ga` and `_gid` but there may be others.

On logging out, or otherwise being redirected to the login screen, these should be cleared, but they aren't.

I've found that their continued presence can prevent successful login in future, in the case that the Appwrite instance at that URL has been replaced with a fresh one. It seems the login process still consults the old cookies which are no longer valid. Consequently even though I am entering the correct admin username and password that I set up on the new instance, Appwrite thinks I only have 'guest' role and sends me straight back to the login screen. 

### 👍 Expected behavior

Clear all authentication- and privilege-related cookies on logout, whether the user has deliberately logged out, or they've been sent to the login screen because they have no privs. 

### 👎 Actual Behavior

Cookies are not cleared and can interfere with future logins. Clearing the cookies manually enables login to work again.

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2022-07-21 20:25
Thank you for raising this issue! 🙏

I'm trying to reproduce your issue, but it's not happening for me. :monocle_face: These are my steps:

1. Spin up Appwrite instance
2. Create a new Console User account (which signs me in)
3. Log out
4. Run `docker compose down -v` to clear Appwrite instance
5. Run `docker compose up -d` to spin up a fresh Appwrite instance
6. Browse to Appwrite Console

At this point, I'm presented with the sign up page again. I can sign up (which logs me in) fine.

Even without logging out:

1. Spin up Appwrite instance
2. Create a new Console User account (which signs me in)
3. Run `docker compose down -v` to clear Appwrite instance
4. Run `docker compose up -d` to spin up a fresh Appwrite instance
5. Browse to Appwrite Console

I am also presented with the sign up page.

Would you please clarify your steps to reproduce this problem? :pray:

**Comment by BenMemescape** [comment] 2022-07-22 10:47
Hm yes I am having trouble nailing this down now. It's something I've run into incidentally on a couple of occasions and I thought I understood what was happening but perhaps not. 

One thing that does happen is that if I simply reload the current page after recycling the Appwrite instance, it redirects to the login page, when perhaps it should redirect to the signup page if there is no admin user meaning a login would be impossible. That might have been the source of my confusion. 

Regardless, I do think it's good practice to clear cookies on logout or invalid session.

**Comment by stnguyen90** [comment] 2022-08-06 03:59
> One thing that does happen is that if I simply reload the current page after recycling the Appwrite instance, it redirects to the login page

If you're on the login page (/auth/signin) and you just refresh, the login page would show again. However, if you browse to the root (/) on a fresh instance of Appwrite, you'll be redirected to the sign up page, regardless of any cookies. See the source code for the redirect: https://github.com/appwrite/appwrite/blob/master/app/controllers/web/home.php#L39-L66 

> Regardless, I do think it's good practice to clear cookies on logout or invalid session.

It looks like the authentication related cookies are deleted on logout. See source: https://github.com/appwrite/appwrite/blob/master/app/controllers/api/account.php#L1736-L1739.

@BenMemescape, is it okay to close this issue as no further action is required?

**Closed** 2023-07-17 16:47 UTC
Labels: bug, authentication
