### ISSUE TITLE
🐛 Bug Report: Reverse pagination causes error 500

### ISSUE THREAD

**Issue by hey-nicolasklein** [appwrite/appwrite#3356] opened 2022-06-08 14:16 UTC
### 👟 Reproduction steps

I'm managing items based on a starting and ending dateTime. I save the dateTime in the Database as an Iso8601 String. Now I'm trying to implement reverse pagination. The user should see the newest items first, and the oldest items last.

A simple offset pagination is exactly the wrong direction. Therefor, I'm trying to add the attribute `orderAttributes`. I also added a key Index on the starting attribute with DESC. 

My query (in Flutter) looks something like this:

```
var documentList = await _database.listDocuments(
        limit: _perPage,
        offset: _perPage * page,
        collectionId: CollectionNames.mediaItems,
        orderAttributes: ['starting'],
        orderTypes: ['DESC'],
        queries: [Query.equal('session', '2')]);
```

### 👍 Expected behavior

I'm expecting to be able to use a simple offset pagination through the reverse sorted items.
It should return the corresponding documents in reversed order based on the starting attribute.

### 👎 Actual Behavior

The request returns with an appwrite 500 error. In the docker logs the following error is visible:

![image](https://user-images.githubusercontent.com/32168266/172638924-8d5df20a-fda7-4672-b879-f0e848b8cf4c.png)

Probably mariaDB is not able to sort by a string? What other way should I use for reverse pagination by a date attribute.

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

All running local with the default appwrite docker-compose file.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by hey-nicolasklein** [comment] 2022-06-08 15:09
I tried to switch from a String to a integer with Milliseconds Since Epoch instead of a UTC String. Still I'm getting a simillar error. Sorting by a integer should not cause such problems. 

I added a own collection for trying the integer instead of string. And I also applied a fresh index on the starting column with sorting DESC.

Still this query:

```
var documentList = await _database.listDocuments(
        collectionId: CollectionNames.mediaItems,
        queries: [Query.equal('xCollection', '1')],
        orderAttributes: ['starting'],
        orderTypes: ['DESC']);
```

![image](https://user-images.githubusercontent.com/32168266/172652124-c8590a2c-d058-43dd-919f-79e75fd8809a.png)



Results in:

![image](https://user-images.githubusercontent.com/32168266/172651395-dabef442-1bd4-4475-b56b-a78bcd67e170.png)

**Comment by Meldiron** [comment] 2022-06-08 17:07
Hey there 👋 Sorting string and number both should work. Tho, in your case, I would use timestamp number, because string sorting would be alphabetic, not what you really want.

Regarding syntax error, let's investigate 😎 First of all, can you try to rename the attribute to something else than `starting`? Maaaybe this is some kind of reserved word? Let's try `createdAt` or something like that.

Also, can you please export your database schema for me? That will help me reproduce exact same database structure as you have, hopefully getting the same problem. You can go to your collection settings and on the right side export it to `JSON`.

**Comment by stnguyen90** [comment] 2022-06-09 15:22
@hey-nicolasklein, the goal would be to make it transparent to the user so they CAN use the attribute name with no problem. Can this be closed since it's a duplicate of https://github.com/appwrite/appwrite/issues/3250?

**Closed** 2022-06-09 15:39 UTC
Labels: bug
