### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by DanielAlbertSwan** [appwrite/appwrite#3724] opened 2022-08-27 15:54 UTC
### 👟 Reproduction steps

Create a Collection with a string field for example name and create an index on it

Add a Entry with the following value:
 - name: Bla , Bla

now we query the the Collection for this Value
appwrite --databaseId default --collectionId collection --queries="name.equal('Bla , Bla')"

### 👍 Expected behavior

total : 1
documents
...
✓ Success

### 👎 Actual Behavior

total : 0
documents
[]

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2022-08-27 19:17
@DanielAlbertSwan, thanks for opening this issue! 🙏 . I think this is actually a duplicate of https://github.com/appwrite/appwrite/issues/3089 so I'm going to close this. Feel free to 👍 that issue, but it should be fixed in our next version of Appwrite.

**Closed by stnguyen90** 2022-08-27 19:17 UTC
Labels: bug
