### ISSUE TITLE
🐛 Bug Report: Multiple many-to-many relationships fails onCreate

### ISSUE THREAD

**Issue by johnschatner** [appwrite/appwrite#7044] opened 2023-10-30 13:29 UTC
### 👟 Reproduction steps

When I try to add more than one relationship with relation type of many-to-many it fails and in the worst case scenario, where this relationship exists I cannot access the data tab on my documents effectively rendering the backend unusable.

### 👍 Expected behavior

Add multiple relationships, be that of the same relation type or otherwise

### 👎 Actual Behavior

It fails, the other attribute on the related collection usually says "processing". In the best case I can just delete the failed attribute but in the worst case the backend stops working.

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Self hosted instance of Appwrite v1.4.8 running on a one click install DigitalOcean droplet.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-10-31 01:21
Closing as a duplicate of https://github.com/appwrite/appwrite/issues/6887. Please 👍🏼 the original issue.

**Closed by stnguyen90** 2023-10-31 01:21 UTC
Labels: bug
