### ISSUE TITLE
🐛 Bug Report: 500 error

### ISSUE THREAD

**Issue by desyed** [appwrite/appwrite#5881] opened 2023-07-26 04:59 UTC
### 👟 Reproduction steps

1. login to Appwrite
2. select a project
3. click database and create new [no loader showing, after realoading page newly created DB appears]
4. click newly created database
5. create collection [again no loader]
6. click multiple time on click button
7. reload page
8. you will see multiple collection with same name
9. try to access the
10. you will see 500 internal error

### 👍 Expected behavior

- it should have loading state while creating collection.

- it should show collection detail page after clicking it.

### 👎 Actual Behavior

1. After creating collection no loading shown. I can create multiple collection with same name.
2. Cannot access Collection it says **500 error**

![image](https://github.com/appwrite/appwrite/assets/18189873/c20c1c5c-280e-40d5-9bdc-2cc136e2dcfb)
![image](https://github.com/appwrite/appwrite/assets/18189873/55aa597a-0c08-45b9-b21a-a5cb5df70fcb)
![image](https://github.com/appwrite/appwrite/assets/18189873/816371de-f166-4e5e-90bd-6e00509b1bfd)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment] 2023-07-26 11:57
Hi @desyed 
I tried reproducing and it is a possibility this bug no longer exists since for me, Cloud works as intended. Can you please re-try this attempt and let me know?

**Comment by priyankuhazarika** [comment] 2023-07-26 12:07
I too cannot reproduce the bug, it works fine for me!

**Comment by desyed** [comment] 2023-07-29 08:26
Today I tried to reproduce but failed. Maybe this issue no longer exists.

**Comment by joeyouss** [comment] 2023-07-29 20:44
Closing it since it is now resolved. Thanks !

**Closed by joeyouss** 2023-07-29 20:44 UTC
Labels: bug, cloud

**Comment by adrian-myhouseph** [comment] 2023-08-25 07:00
any update on this? it still persist as 500 internal error.
