### ISSUE TITLE
🚀 Feature: Attributes permissions + Validate & sanitize queries

### ISSUE THREAD

**Issue by fliitor** [appwrite/appwrite#4656] opened 2022-11-09 16:34 UTC
### 🔖 Feature description

Allow to define permissions on Attributes & use it on query generator to auto generate columns on SELECT and validate access before UPDATE

### 🎤 Pitch

It will natively allow to moderate data scope and have a user wich can only read col1/2/3, other user with only read/write permission on col3/4/5, etc..

Perhaps use other redis instance to store session access, to avoid database queries each time

Call to [List Documents](https://appwrite.io/docs/client/databases?sdk=web-default#databasesListDocuments) or [Get Document](https://appwrite.io/docs/client/databases?sdk=web-default#databasesGetDocument) transform to

`
SELECT sessionAccessCol1, sessionAccessCol2 FROM ...
`

On UPDATE, if user havn't write right on column, it delete field from data JSON object before query

Other ticket about : [More granular permissions and powerful defaults](https://github.com/appwrite/appwrite/issues/1326)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2022-11-09 16:38
@fliitor thanks for creating this issue! 🙏🏼 One way to achieve something like this right now is to use separate collections. Your example has 3 levels of access:

1. col 1, 2
2. col 3
3. col 4, 5

So you can make 3 collections. User A would have access to collection 1 and 2. User B would have access to collection 2 and 3.

**Comment by stnguyen90** [comment] 2022-11-09 16:53
> User wich have access on 5 columns need 3 Get api calls (and frontend need to know that) to merge response

@fliitor, yes, correct.

**Comment by fliitor** [comment] 2022-11-09 17:18
Is acceptable to replace all database get queries by functions ?

**Comment by stnguyen90** [comment] 2022-11-09 18:15
@fliitor, you can. I have seen a community member create a function that works generically on multiple collections to join data. You can certainly have a function that does a SELECT on attributes before returning the data.

**Comment by stnguyen90** [comment] 2024-04-24 15:48
Closing this as a duplicate of https://github.com/appwrite/appwrite/issues/1326

**Closed by stnguyen90** 2024-04-24 15:48 UTC
Labels: enhancement, product / databases
