### ISSUE TITLE
Feature Request : Asking users to pay for subscription

### ISSUE THREAD

**Issue by Shubhampratapsingh** [appwrite/appwrite#4970] opened 2023-01-08 08:36 UTC
It will be helpful if we can ask users to pay one time or recurring payment to access certain feature from our app.
Something like this: "https://userbase.com/docs/sdk/purchase-subscription/". 
If we can also have client sdk for subscription, it will be helpful.

**Comment by stnguyen90** [comment] 2023-01-09 19:22
@Shubhampratapsingh thanks for raising this issue! 🙏🏼 Is this a duplicate of https://github.com/appwrite/appwrite/issues/4834? If so, I'd recommend 👍🏼 that issue to upvote it.

**Comment by stnguyen90** [comment] 2023-01-11 01:27
@Shubhampratapsingh please make sure you 👍🏼 issue https://github.com/appwrite/appwrite/issues/4834.

**Closed by stnguyen90** 2023-01-11 01:27 UTC
Labels: feature
