### ISSUE TITLE
[0.15.3.402] 🐛 Bug Report: Float attributes round up / precision is limited to 4 values after the point 

### ISSUE THREAD

**Issue by fballan93** [appwrite/appwrite#3730] opened 2022-08-29 12:45 UTC
### 👟 Reproduction steps

I have a flutter front end / nodejs middle-ware 

Flutter front end will create a document in collection X with these attributes 

sender_long: Float 
Sender_lat: Float 
recipient_lat:Float 
recipient_long:Float 

Flutter app create a document with this payload :
`{
       .
        'sender_latitude': 25.27705773818511,
        'sender_longitude': 51.51322256667464,
        'sender_postalcode': '123',
        .
        . 
        .
        'recipient_latitude': 0.0,
        'recipient_longitude': 0.0,
       .
       .
      } `

NoteL some attributes were removed 

Express middle ware update document   
 'recipient_latitude': 0.0,
 'recipient_longitude': 0.0,

### 👍 Expected behavior

document created with this values correctly not touched . however the floats are cut off or rounded 

`{
   
    "sender_latitude": 25.27705773818511,
    "sender_longitude": 51.51322256667464,
    "recipient_longitude": 51.596432357342,
    "recipient_latitude": 25.2322245246345,
  
}`

note : other attributes and fields were removed 

### 👎 Actual Behavior

document created with this values aboce . however the floats are cut off or rounded 

`{
   
    "sender_latitude": 25.2771,
    "sender_longitude": 51.5132,
    "recipient_longitude": 51.596,
    "recipient_latitude": 25.2322,
  
}`

note : other attributes and fields were removed 

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Digital Ocean 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2022-08-29 13:39
I think this is related to this existing issue: https://github.com/appwrite/appwrite/issues/2766. @fballan93, is it okay if we close this one and you can upvote the other one?

**Comment by fballan93** [comment] 2022-08-29 13:45
> I think this is related to this existing issue: #2766. @fballan93, is it okay if we close this one and you can upvote the other one?

hey Steven this issue is different that the mentioned issue.

**Comment by stnguyen90** [comment] 2022-08-29 13:49
@fballan93, it seems the same because the problem is with using float and how they get rounded. What makes you say they're different?

**Comment by abnegate** [comment] 2023-01-11 03:13
Closing as duplicate of https://github.com/appwrite/appwrite/issues/2766

**Closed by abnegate** 2023-01-11 03:13 UTC
Labels: bug, database
