### ISSUE TITLE
🚀 Feature: Simplified Management of Document Relationships

### ISSUE THREAD

**Issue by vlohar08** [appwrite/appwrite#5925] opened 2023-08-01 14:03 UTC
### 🔖 Feature description

Appwrite should add a few separate methods for Managing Relationships.
We should not be forced to send all the previous documents again to add new relationship documents to the database collection.
Example -

`
databases.createRelationship(...parameters)
databases.deleteRelationship(...parameters)
databases.updateRelationship(...parameters)
`

OR

Appwrite can add a way similar to how we set document permissions. We can just add a new function parameter that can handle relationships. 

I won't comment more on how this can be done. You guys know better!

### 🎤 Pitch

If we look at database relationship management now then it is not suitable for high-scaling apps.
I will explain this with the doc example.

```
await databases.updateDocument(
    'marvel',
    'movies',
    'spiderman',
    {
        title: 'Spiderman',
        year: 2002,
        reviews: [
            'review4',
            'review5'
        ]
    }
);
```

Now, in the above example, If I want to add more reviews to the movie Spiderman then the only way is to pass both old and new reviews in the update document function.

This is OK if you have 10-20 reviews.
But Imagine if you have 1000 movie reviews. And if you pass all the 1000 reviews in the reviews array inside the updateDocument function then it will increase the payload size a lot.

Even big issue is first fetching all the old reviews from the server and making another request to update the relationships.

There should be an easy and more optimized way to Create, Update, and Delete Appwrite Database Relationships.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment] 2023-08-01 15:12
Hi @vlohar08 thanks for the feature request! Tagging @gewenyu99 to look into this.

**Comment by stnguyen90** [comment] 2023-08-02 03:26
Closing this as a duplicate of https://github.com/appwrite/appwrite/issues/2531.

**Closed by stnguyen90** 2023-08-02 03:26 UTC
Labels: database
