### ISSUE TITLE
🐛 Bug Report: User cannot sign up again with the same email address after account is deleted

### ISSUE THREAD

**Issue by JaviBonilla** [appwrite/appwrite#2411] opened 2021-11-12 12:32 UTC
### 👟 Reproduction steps

With the `Account API`:

- Create an account
- Delete the account
- Create an account with the same email address

### 👍 Expected behavior

Recreate an account with the same email address.

### 👎 Actual Behavior

The following error messages:

When signing up: `Account already exits`
When loging in: `Invalid credentials. User is blocked`

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Linux

### 🧱 Your Environment

- Appwrite Flutter SDK 2.0.3
- Latest Flutter package: FlAppwrite Account Kit

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment] 2021-11-14 07:17
This looks like the issue is similar to https://github.com/appwrite/appwrite/issues/1104 which was resolved in 0.9. Will look more into it.

**Comment by TorstenDittmann** [comment] 2021-11-15 10:29
I wasn't able to re-create it on `0.11.x`.

The delete method on the account service doesn't actually delete the account - but blocks it. Only the delete method from the Users API removes the account completely 👍🏻

**Comment by lohanidamodar** [comment] 2021-11-15 10:41
@JaviBonilla as @TorstenDittmann mentioned, while deleting account using client SDK (i.e. the Account service) the account is only blocked. As you are using Flutter SDK this is the intended behavior of the API. If you want to permanently delete the user account then you can delete it from Users (server SDK) service or console as well. Closing this issue. If this doesn't help you, feel free to reopen the issue with more information. 
Thank you 🙏🏻

**Closed by lohanidamodar** 2021-11-15 10:41 UTC
Labels: bug

**Comment by JaviBonilla** [comment] 2021-11-15 11:37
@lohanidamodar Ok, I thought that even though the user was blocked, Appwrite was in charge of unblocking the user when the same email address was used to create a new account.

So, to make this secure, I have to make sure that the delete account function only deletes the user account of the `APPWRITE_FUNCTION_USER_ID` env var.

**Comment by lohanidamodar** [comment] 2021-11-30 07:10
> @lohanidamodar Ok, I thought that even though the user was blocked, Appwrite was in charge of unblocking the user when the same email address was used to create a new account.
> 
> So, to make this secure, I have to make sure that the delete account function only deletes the user account of the `APPWRITE_FUNCTION_USER_ID` env var.

Yes, that seems to be the best approach
