### ISSUE TITLE
🐛 Bug Report: Delete confirmation dialogue out of the screen

### ISSUE THREAD

**Issue by step135** [appwrite/appwrite#7300] opened 2023-12-18 10:04 UTC
### 👟 Reproduction steps

Error in CSS on cloud page. When I want to delete something. It shows confirmation frame that is out of the screen.

### 👍 Expected behavior

It should be centered.

### 👎 Actual Behavior

At the bottom of the page, buttons not visible.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by gepd** [comment] 2023-12-18 15:01
Can you take a screenshot and information about your browser?

**Comment by step135** [comment] 2023-12-18 16:34
Mozilla Firefox

**Comment by stnguyen90** [comment] 2023-12-19 00:41
@step135, it looks fine to me using Firefox 120.0.1 on Mac OS 12.6.7 (21G651)

<img width="1490" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/2802e80e-2320-42a8-aeab-5b344e3ef448">

Would you please provide a screenshot and your exact version and OS?

**Comment by iamYashSinha** [comment] 2023-12-23 11:35
Is anyone working on this? Else I'm interested!😊

**Comment by step135** [comment] 2023-12-27 15:44
That dialogue is partly seen from the button of the page and its position is set up by javascript (not responsive) that is very ugly implementation.

**Comment by step135** [comment] 2023-12-27 15:49
I've just check and if I want to delete user, it is completely outside of the viewable area and any resizing doesn't help.

**Comment by step135** [comment] 2023-12-27 15:53
I've just checked and if I want to delete user, it is completely outside of the viewable area and any resizing doesn't help. The position is set up by javascript (not responsive) that is very ugly implementation.

**Comment by stnguyen90** [comment] 2023-12-27 16:24
@step135, would you please provide a screenshot and your exact OS and browser version?

**Comment by step135** [comment] 2024-01-07 19:03
Firefox 102 has this issue and with previous versions the page is broken completely: https://github.com/appwrite/website/issues/496

**Comment by stnguyen90** [comment] 2024-01-08 21:13
@step135, looks like this is a duplicate of https://github.com/appwrite/appwrite/issues/5102. Would you please add a 👍🏼 on that issue since I'm going to be closing this?

**Closed by stnguyen90** 2024-01-08 21:13 UTC
Labels: bug, console
