### ISSUE TITLE
🐛 Bug Report: Unreadable .docx file after writing to storage

### ISSUE THREAD

**Issue by JayF666** [appwrite/appwrite#5086] opened 2023-02-06 15:56 UTC
### 👟 Reproduction steps

I set up a fresh Appwrite environment and created the following JS-function. The function is supposed to convert html to a docx file and save this to the appwrite storage. 

```js
const { Client, ID, InputFile, Permission, Role, Storage } = require('node-appwrite');
const { asBlob } = require('html-docx-js-typescript');

module.exports = async (req, res) => {
  const client = new Client();

  client
    .setEndpoint('http://192.168.178.35:8082/v1')
    .setProject('XXX')
    .setKey(
      'XXX'
    );
  const storage = new Storage(client);

  const html = `<p>test</p>`;
  // returns always Buffer
  const docx = await asBlob(html, {
    orientation: 'landscape',
    margins: { top: 0, right: 400, left: 400, bottom: 0, footer: 0 },
  });

  const file = InputFile.fromBuffer(docx, `output.docx`);

  try {
    const response = await storage.createFile('63dd0075022284e72494', ID.unique(), file, [
      Permission.write(Role.any()),
    ]);
    res.json(response);
  } catch (e) {
    console.error(e);
  }
};

```

### 👍 Expected behavior

It should write a .docx file to the storage that can be downloaded and openend. If I replace 
```js
    const response = await storage.createFile('63dd0075022284e72494', ID.unique(), file, [
      Permission.write(Role.any()),
    ]);
    res.json(response);
```
with just `fs.writeFile('output.docx', docx)` I get a correct .docx file on my filesystem. So the docx generation should be fine.

### 👎 Actual Behavior

It actually writes a file to the storage that, if downloaded, cant be opened by Word. See: 
[output.docx](https://github.com/appwrite/appwrite/files/10664759/output.docx)

Plus, Appwrite detects the Mimetype of this file in the storage as application/zip instead of application/vnd.openxmlformats-officedocument.wordprocessingml.document

Something might be wrong either with InputFile.fromBuffer() or storage.createFile().

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Windows

### 🧱 Your Environment

A fresh appwrite env runs locally on my windows machine with docker desktop. I only set up a function and a bucket.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-02-06 17:39
This looks like a duplicate of https://github.com/appwrite/sdk-for-node/issues/36. For now, please try https://github.com/appwrite/sdk-for-node/issues/36#issuecomment-1249527666

**Closed by stnguyen90** 2023-02-06 17:39 UTC
Labels: bug
