### ISSUE TITLE
🐛 Bug Report: Error Updating One to Many Child

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#5478] opened 2023-05-01 17:18 UTC
### 👟 Reproduction steps

1. Create a collection A
2. Create a collection B with an optional string attribute
3. Create a two-way one to many relationship from A to B
4. Create a document in A
5. Create a document in B
6. Update document B to link to document A
7. Update the string attribute in document B
8. Refresh the page
9. Update the string attribute in document B

### 👍 Expected behavior

String attribute updates

### 👎 Actual Behavior

Error:

> Invalid document structure: Missing collection attribute $collection

<img width="1476" alt="image" src="https://user-images.githubusercontent.com/1477010/235494976-0588cf4f-14d6-4293-be1e-ccd3c08d84d1.png">

<details>
<summary>Stacktrace from API call:</summary>

```json
{
  "message": "Invalid document structure: Missing collection attribute $collection",
  "code": 400,
  "type": "document_invalid_structure",
  "version": "1",
  "file": "/usr/src/code/app/controllers/api/databases.php",
  "line": 3387,
  "trace": [
    {
      "file": "/usr/src/code/vendor/utopia-php/framework/src/App.php",
      "line": 577,
      "function": "{closure}",
      "args": [
        "one-to-many",
        "level2",
        "level2",
        {
          "$permissions": [
            "read(\"user:644c188e597dbee6ee8c\")",
            "update(\"user:644c188e597dbee6ee8c\")",
            "delete(\"user:644c188e597dbee6ee8c\")"
          ],
          "level1": {
            "$id": "level1",
            "$createdAt": "2023-04-28T19:07:31.749+00:00",
            "$updatedAt": "2023-04-28T19:07:31.749+00:00",
            "$permissions": [
              "read(\"user:644c188e597dbee6ee8c\")",
              "update(\"user:644c188e597dbee6ee8c\")",
              "delete(\"user:644c188e597dbee6ee8c\")"
            ],
            "$databaseId": "one-to-many",
            "$collectionId": "level1"
          },
          "level3": [
            "level3"
          ],
          "$collection": "level2",
          "$createdAt": "2023-04-28T19:07:31.750+00:00",
          "$id": "level2"
        },
        [
          "read(\"user:644c188e597dbee6ee8c\")",
          "update(\"user:644c188e597dbee6ee8c\")",
          "delete(\"user:644c188e597dbee6ee8c\")"
        ],
        null,
        {},
        {},
        {},
        "admin"
      ]
    },
    {
      "file": "/usr/src/code/vendor/utopia-php/framework/src/App.php",
      "line": 755,
      "function": "execute",
      "class": "Utopia\\App",
      "type": "->",
      "args": [
        {},
        {}
      ]
    },
    {
      "file": "/usr/src/code/app/http.php",
      "line": 252,
      "function": "run",
      "class": "Utopia\\App",
      "type": "->",
      "args": [
        {},
        {}
      ]
    }
  ]
}
```
</details>

Server logs:

```
appwrite  | [Error] Timestamp: 2023-04-29T16:29:07+00:00
appwrite  | [Error] Method: PATCH
appwrite  | [Error] URL: /v1/databases/:databaseId/collections/:collectionId/documents/:documentId
appwrite  | [Error] Type: Appwrite\Extend\Exception
appwrite  | [Error] Message: Invalid document structure: Missing collection attribute $collection
appwrite  | [Error] File: /usr/src/code/app/controllers/api/databases.php
appwrite  | [Error] Line: 3387
```

The error might be occurring somewhere around here:

https://github.com/utopia-php/database/blob/f6ab65e59a199da5155c114564077b1ab8c4daef/src/Database/Database.php#L3067-L3086

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

This occurs from a clean 1.3.3 install.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by BraveDevelopment** [comment] 2023-05-03 06:27
Would be happy if this gets fixed as soon as possible. It’s extremely annoying when testing and developing (especially debugging real-time stuff).

In addiction the console could be edited so if you press save on a changed record only this record is send to the database. This would also solve this problem and save on computing power 😅

**Comment by hortigado** [comment] 2023-05-08 00:30
This error is delaying my implementation :(

**Comment by hortigado** [comment] 2023-05-08 00:30
This bug is delaying my implementation :(

**Comment by lucifer-Hell** [comment] 2023-05-12 10:39
Hi @stnguyen90  if anyone from the internal dev team is not picking I would be really happy to resolve this bug . Can you please assign it to me ?

**Comment by edwin0401** [comment] 2023-06-24 08:47
The bug still exists in the latest version 1.3.7. Relationships-database is definitely a great new feature, and I understand that it's still in testing. Sorry to push you, but when do you think it can be fixed?

**Comment by stnguyen90** [comment] 2023-07-05 16:19
@BraveDevelopment, @LiamD-Flop, @hortigado, @lucifer-Hell, @edwin0401, are y'all able to reproduce this using 1.3.7 (after clearing the cache)? If so, would you please provide the exact reproduction steps? I tried the reproduction steps in the issue description again, but I wasn't able to reproduce the problem:

https://github.com/appwrite/appwrite/assets/1477010/37c2ac9d-7cba-4811-b4ec-d23c0e388232

**Comment by hortigado** [comment] 2023-07-05 17:17
@stnguyen90  Hi thanks in my case it seems that it was solved.

**Comment by fanatic75** [comment] 2023-07-10 08:06
@stnguyen90, closing this as it looks like this is not reproducible anymore.

**Closed by fanatic75** 2023-07-10 08:06 UTC
Labels: bug, database
