### ISSUE TITLE
🐛 Bug Report: When a collection has more than 5000 documents,  listDocument reports always 5000

### ISSUE THREAD

**Issue by superseby2** [appwrite/appwrite#2835] opened 2022-02-24 20:41 UTC
### 👟 Reproduction steps

- insert more than 5000 documents

### 👍 Expected behavior

- on the console it should display the number of documens
- we should pass the /417 pagination mark
- api should report the proper number of documents in "sum"

### 👎 Actual Behavior

- console shows 5000
- cannot pass /147 in the console
- api reports 5000 always

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by superseby2** [comment] 2022-02-24 20:47
Okay found a APP_LIMIT_COUNT variable ...
I understand it could be handy to restrict pagination on the console. But, to me this should not apply to what the API reports. Otherwise there is no way to know for certain how many documents we have...

**Comment by FirzenYogesh** [comment] 2022-08-11 17:40
@superseby2 I agree, should at-least show the total documents, or it would also make sense to have make it available in the collections get API endpoint.

We also can't also set offset beyond 5000, it throws `Invalid offset: Value must be a valid range between 0 and 5,000`

Note: I am using 0.15.x, my server is on a linux droplet on DigitalOcean.

**Comment by stnguyen90** [comment] 2022-08-11 18:21
@superseby2, @FirzenYogesh, thanks for the comments! 🙏 

We have this limit because using offset and doing counts can be an expensive database operation. 

If you need to track the total count of documents in a collection, I recommend keeping a metadata collection for totals. You can increment/decrement the total using Appwrite Function that triggers on document create/delete.

If you need to paginate past 5k records, you can use [cursor based pagination](https://appwrite.io/docs/pagination#cursor-pagination).

Additional reference can be found:
- https://appwrite.io/docs/pagination
- https://dev.to/appwrite/this-is-why-you-should-use-cursor-pagination-4nh5

**Comment by merabtenei** [comment] 2022-09-27 09:48
> @superseby2, @FirzenYogesh, thanks for the comments! 🙏
> 
> We have this limit because using offset and doing counts can be an expensive database operation.
> 
> If you need to track the total count of documents in a collection, I recommend keeping a metadata collection for totals. You can increment/decrement the total using Appwrite Function that triggers on document create/delete.
> 
> If you need to paginate past 5k records, you can use [cursor based pagination](https://appwrite.io/docs/pagination#cursor-pagination).
>
How do we deal with race condition in that situation (for increment and decrement) ?

**Comment by abnegate** [comment] 2023-01-11 02:22
Closing as expected behavior

**Closed by abnegate** 2023-01-11 02:22 UTC
Labels: bug, database
