### ISSUE TITLE
🐛 Bug Report: Realtime update events not triggering for document attribute with relationship

### ISSUE THREAD

**Issue by pbadr** [appwrite/appwrite#7403] opened 2024-01-07 09:09 UTC
### 👟 Reproduction steps

- Create two collections A and B
- Make relationship attribute X on collection A with one to many relationship with collection B
- Create a document on B, which should automatically add that document on the list of collection A's array

### 👍 Expected behavior

When subscribed to a realtime event on the specific document from collection A
```js
client.subscribe(
  [`databases.${APPWRITE_DATABASE_ID}.collections.${COLLECTION_A}.documents.${DOCUMENT_ID}`],
  (response) => {
    console.log('New document event:', response);
  }
);
```
`COLLECTION_A` should give a response with the new updated document from collection B with the new document added to the list

### 👎 Actual Behavior

The realtime event does not trigger when the document is updated, even though the document from collection A does update it's list with the new document from collection B. When manually adding or removing the document to collection either through the SDK or through the console, the event does get triggered and a response is thrown in the code specified above.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Using Appwrite SDK 13.0.1 with React Native Expo.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by pbadr** [comment] 2024-01-07 09:17
I've also set the permissions to "Any" with all read, write, update and delete checked for both the collections.

**Comment by stnguyen90** [comment] 2024-01-08 04:05
Thanks for creating this issue! 🙏 Looks like this is a duplicate of https://github.com/appwrite/appwrite/issues/6265 so I'm going to close this. You might want to add a 👍 to the original issue.

**Closed by stnguyen90** 2024-01-08 04:05 UTC
Labels: bug, databases, realtime, relationships
