### ISSUE TITLE
🐛 Bug Report: Non-functional 'Back to Top' Button

### ISSUE THREAD

**Issue by Saurav-Pant** [appwrite/appwrite#6910] opened 2023-10-15 03:42 UTC
### 👟 Reproduction steps

In the Quick Start section, when we click on any technology such as Next.js, React, or Flutter, in the explanation of how to set up with these technologies, there is a 'Back to top' button in the right section. However, when clicking on it, it does not scroll to the top

### 👍 Expected behavior

While Clicking on this button it should need to redirect to the top of the page 

### 👎 Actual Behavior

https://github.com/appwrite/appwrite/assets/103263909/4e36fbda-9075-4c77-ada9-5f00ee0911be

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Saurav-Pant** [comment] 2023-10-15 03:44
I want to work on it

**Comment by CharithaCS** [comment] 2023-10-15 04:03
I'd love to work on this issue. Please assign me this.

**Comment by dbarnwal** [comment] 2023-10-15 07:57
Heyyyy.  Can I contribute to this ?

**Comment by 3xp10it3r** [comment] 2023-10-16 11:16
I would like to work on this issue, I have implemented this in many apps.

**Comment by Haimantika** [comment] 2023-10-16 12:31
Hi @Saurav-Pant good catch! Thanks for bringing this up to us. How do you plan to implement it?

**Comment by Saurav-Pant** [comment] 2023-10-16 13:35
![appwrite issue solved](https://github.com/appwrite/appwrite/assets/103263909/c6be2dc1-cee8-476b-8535-408f81ad4480)

Thank you, @Haimantika 
In this image, I have explained how I implemented this, 
In the video, I demonstrated how it is currently working
https://github.com/appwrite/appwrite/assets/103263909/e3442ef5-0747-49f1-9f57-c6d008f34bb3

**Comment by gewenyu99** [comment] 2023-10-16 14:25
> ![appwrite issue solved](https://user-images.githubusercontent.com/103263909/275532187-c6be2dc1-cee8-476b-8535-408f81ad4480.png)
> 
> Thank you, @Haimantika In this image, I have explained how I implemented this, In the video, I demonstrated how it is currently working https://github.com/appwrite/appwrite/assets/103263909/e3442ef5-0747-49f1-9f57-c6d008f34bb3

Hi, thanks for your interest. I'm looking at the code and I don't think this is the approach we want to go for. We have an href for `#top` that should be present in our templates, but isn't for some reason. I think we should fix this isntead.

**Comment by 3xp10it3r** [comment] 2023-10-16 15:21
Assign to me, I will target the `top` to fix it.

**Comment by Saurav-Pant** [comment] 2023-10-16 15:21
Okay, thank you. if you say I will implement the same with CSS.
 Please let me know in which file I should include CSS for `#top`.

**Comment by stnguyen90** [comment] 2023-10-17 20:26
Closing as a duplicate of https://github.com/appwrite/website/issues/169

**Closed by stnguyen90** 2023-10-17 20:26 UTC
Labels: bug
