### ISSUE TITLE
🐛 Bug Report: CORS error when accessing Appwrite from a Flutter Web App

### ISSUE THREAD

**Issue by safwanyp** [appwrite/appwrite#6004] opened 2023-08-17 10:37 UTC
### 👟 Reproduction steps

1. Add a platform for Flutter Web in the Appwrite console with a hostname `example.com`
2. Try to use any Appwrite service through a Flutter Web app from the `example.com` hostname

### 👍 Expected behavior

Appwrite services should respond as expected:
- `listDocuments` should return the documents
- `createEmailSession` should create a session and return it
- etc.

### 👎 Actual Behavior

Appwrite throws a CORS error suggesting that the added hostname `example.com` is not a whitelisted host.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Appwrite 1.3.8

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by safwanyp** [comment] 2023-08-17 10:38
Something to note is that this can be fixed by adding a normal **Web** platform instead of a **Flutter Web** platform.

Would it be easier to simply add a web app instead of a flutter web app in the backend?

**Comment by aryangupta701** [comment] 2023-08-17 12:49
I would like to work on this. please assign this to me

**Comment by stnguyen90** [comment] 2023-08-18 00:46
Weird...the flutter web should work the same as regular web in the backend 🧐

**Comment by safwanyp** [comment] 2023-08-22 17:44
> Weird...the flutter web should work the same as regular web in the backend 🧐
Weird indeed. I assumed that's how it worked tbh

> @safwanyp does it work if you add a regular web platform and not a Flutter Web one?
Yes. In my followup comment to the post, I stated this method as a workaround

**Comment by eldadfux** [comment] 2023-08-24 04:29
I can confirm this is a bug. A workaround would be to use the regular web platform instead. A core member has been assigned to apply a fix.

**Comment by PineappleIOnic** [comment] 2023-08-24 23:07
Hey There 👋 Could you please try and recreate the bug but capture the network requests? I mainly want to checkout the request and reponse headers to see what the CORS Headers looks like

**Comment by safwanyp** [comment] 2023-08-31 06:25
> Hey There 👋 Could you please try and recreate the bug but capture the network requests? I mainly want to checkout the request and reponse headers to see what the CORS Headers looks like

So funny thing, I've been trying to reproduce this issue on a starter flutter web app, but it seems to work just fine now. I'm on 1.3.8 and added a flutter web app as a platform, which is hosted on Netlify. 

Seems to work perfectly fine now lol

**Comment by stnguyen90** [comment] 2023-09-01 01:24
I've also tested again and it works fine 🧐 can we close this now?

**Comment by safwanyp** [comment] 2023-09-01 07:24
> I've also tested again and it works fine 🧐 can we close this now?

Yeah I'd say it's safe to close it for now

**Closed** 2023-10-17 19:40 UTC
Labels: bug, backlog
