### ISSUE TITLE
🐛 Bug Report: Org delete button is not doing anything.

### ISSUE THREAD

**Issue by usamashafiqs** [appwrite/appwrite#8045] opened 2024-04-29 19:12 UTC
### 👟 Reproduction steps

I transferred my project to another organization. Then I go to my old organization to delete it, but the delete button is not doing anything.

Am on v1.5.5

https://github.com/appwrite/appwrite/assets/18592683/b79b4f03-bd09-4cdc-9b0b-8d3978c1f170

### 👍 Expected behavior

It should delete the org.

### 👎 Actual Behavior

The delete button is not doing anything.

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2024-04-29 20:02
@usamashafiqs, thanks for creating this issue! 🙏🏼 Looks like this is a duplicate of https://github.com/appwrite/console/issues/1030. As such, I'm going to close this and you can add a 👍🏼 on the other issue.

**Closed by stnguyen90** 2024-04-29 20:02 UTC
Labels: bug, product / console
