### ISSUE TITLE
🐛 Bug Report: Empty select input when adding a document with relationship

### ISSUE THREAD

**Issue by Emilien-Lambert** [appwrite/appwrite#7075] opened 2023-11-04 11:40 UTC
### 👟 Reproduction steps

Hello, on version, `v1.4.9` when I try to add a relationship to a document, some options are not displayed in the input and others are. 
Example in this screenshot. "pancreas" is displayed and "tne" is not. However, when you click on update, there's no error message and the request appears to be correct in the console. 

I think this outcome is linked to [Issue: #5850](https://github.com/appwrite/appwrite/issues/5850#issuecomment-1793416753) Because I can't delete this document either.

EDIT : I've figured out exactly how to reproduce the problem! 
I have 2 collections "organe" and "cartographies" with a one way link like this:

```
"cartographies can contain one organe
organe can belong to many cartographies"
```

If I have more than 25 "organe" documents, then the 26th is not displayed correctly when I select it when creating a "cartographies".

![image](https://github.com/appwrite/appwrite/assets/52819523/3b08a784-4f79-43ce-b2db-d2934331e9a6)

### 👍 Expected behavior

The "tne" option in the input should be displayed as "pancreas".

### 👎 Actual Behavior

The "tne" option is not displayed after selecting it.

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite `v1.4.9`
Ubuntu server `v23.04`

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Emilien-Lambert** [comment] 2023-11-05 09:54
I'm really stuck in my project because of this, as I have more than 25 documents in several collections that have relationships. Is there a temporary solution, like increasing the limit to more than 25? Please, this is really important for me. I'm using appwrite in a free student project for a hospital in my city for cancer research. [Radium project](https://icl.radium-tech.com/cartography-view/)

**Comment by stnguyen90** [comment] 2023-11-07 18:22
@Emilien-Lambert, thanks for creating this issue! 🙏🏼 This looks like a duplicate of https://github.com/appwrite/appwrite/issues/5541. As such, I will be closing this as a duplicate and I suggest you 👍🏼 that issue.

**Closed by stnguyen90** 2023-11-07 18:22 UTC
Labels: bug, databases, console
