### ISSUE TITLE
🚀 Feature: Signed URLs

### ISSUE THREAD

**Issue by maikeriva** [appwrite/appwrite#3398] opened 2022-06-19 20:38 UTC
### 🔖 Feature description

Signed URLs are short-lived URLs used to make a private resource (such as a file in a bucket but not only) temporarily available to a third-party without requiring him to authenticate.

Signed URLs are provided by other platforms such as AWS S3 and are useful in several common scenarios outlined in the Pitch section below.

Some documentation:
- AWS S3 Signed URLs: https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-presigned-url.html

### 🎤 Pitch

Signed URLs are useful when an entity needs to access a resource but it can't authenticate with Appwrite (such as a 3rd party API, or a user on another device). Today the alternative is to make such resource public, but that has security implications for sensitive data. Some service providers (such as AWS S3) provide this functionality.

Some scenarios:
- As a developer, I want a 3rd party API to access a file in a storage bucket. I have however no control of such API and as such I cannot instruct it to authenticate. The file contains user-provided personal data and as such I'd rather not make the bucket public. Giving the API a signed URL would allow it to access the file with the right security and permissions.
- As a user, I want to give access to one of my files (stored into a bucket) to a friend of mine, similarly to what I do with Google Docs. I want to email him a one-time download link.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment] 2022-06-20 07:53
Sounds like a cool idea to me. I would even take it a step further and implement it for other services such as Database.

There would be a method to create `token` like `appwrite.account.createToken` that would give specific permissions. In the case of server-side, any permission can be given (if the API key has scope for that). In the case of the client-side, only permissions that the user has access to can be given (I cannot share someone else file). When creating the token, a duration can be provided, limited by some reasonable limit (1 year?)

This secret can then be shared with anyone. Just like there is `setJWT` for ServerSDK, we would now have `setToken` for both server and client. Once set, it will be used by Appwrite to see what the client is allowed to see. And of course, this would play nicely even with authenticated users - instead of replacing his permissions, the permissions would stack.

Regarding 3rd party APIs, this token could be set as a query parameter for easy usage.

---

Any feedback? 🤔

**Comment by eldadfux** [comment] 2022-06-20 07:56
I like the idea. I wonder if it should be a dedicated service on the API.

**Comment by maikeriva** [comment] 2022-06-20 12:58
@Meldiron Sounds like a great plan :) I especially like the possibility of applying this to documents and/or collections.

One thought about the query parameter aspect though. Should the signed URL be: 
1. A standard link to the resource with an additional access token parameter? (https://example.org/v1/storage/buckets/BUCKETID/files/FILEID/download?project=PROJECTID&token=SIGNEDTOKEN)
2. A new link (potentially shortened) hiding the implementation details to the user? (https://example.org/s/SOMERANDOMSTRING)
3. Both? (implement 1, then 2 as an internal redirect to 1)

Providing 2 (or 3) would hide implementation details to a 3rd party user (would not even know that appwrite is used as backend) and provide a shorter URL. Likely better for security and sharing, but I assume it'd require some more work.

**Comment by Meldiron** [comment] 2022-06-21 07:20
@maikeriva  To keep it consistent, I would go with 1 only. We had same discussion about executing a function, and we decided to only have 1 endpoint for sick of simplicity, and it is the one that follows REST standards.

If we decide to create new service out of it, the URL will be a bit shorter tho.. To follow-up on that...

@eldadfux I like dedicated service.. Creating token has nothing to do with account, user, nor any other service directly. May his be.. beginning of.. Permissions API? 🤯 (or Invitation API, not sure what we wanted to call it).

```js
// Keep separated because params might change for specific resources
sdk.permissions.createDocumentToken("collectionId", "documented", read:true, write:true, duration:3600);
sdk.permissions.createFileToken("bucketId", "fileId", read:true, write:false);

 // Dont separate to make it simpler
sdk.permissions.listTokens(types:["document","file"]);
sdk.permissions.getToken("tokenId");
sdk.permissions.updateToken("tokenId", read:false, write:true, duration:7000);
sdk.permissions.deleteToken("tokenId");
```

The only concern I have is applying the tokens... That could be on service itself, but only client-side method:
```js
sdk.permissions.applyToken("tokenId");
```
Or directly ok the appwrite class itself:
```js
// Init your Web SDK
const appwrite = new Appwrite();

appwrite
    .setEndpoint('http://localhost/v1')
    .setProject('455x34dfkj');

appwite.setToken("tokenId");
```
Either way, we should support using multiple tokens at the same time, if we are going to do it instance-scoped, and not request-scoped.

( @eldadfux  This PermissionsAPI can later be extended to allow clients to send invitations to permissions to other users, as we discussed a few months ago)

**Comment by stnguyen90** [comment] 2022-12-23 00:24
related issue: https://github.com/appwrite/appwrite/issues/545

**Comment by stnguyen90** [comment] 2024-08-08 19:18
Closing as a duplicate of https://github.com/appwrite/appwrite/issues/545

**Closed by stnguyen90** 2024-08-08 19:18 UTC
Labels: enhancement, product / storage, product / databases
