### ISSUE TITLE
🐛 Bug Report: Can't create an index on string if string size is too big

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#6129] opened 2023-09-03 07:29 UTC
### 👟 Reproduction steps

1. Create a string that is greater than 768
2. Create a index on that string

### 👍 Expected behavior

The index should create

### 👎 Actual Behavior

Index fails to create on Cloud:

<img width="1197" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/3d995a83-de1c-4ec1-9e58-0cdc8ed86b51">

Error in 1.4:

<img width="1093" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/b52d410a-1a18-4f4c-8783-2b6388baab07">

The problem is on previous versions of Appwrite, it was possible to create an index on 1 big string attribute. We should preserve that functionality.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment] 2023-09-04 17:50
Checked in latest version 1.4.1, still cannot create an index with type "key", only possible using Fulltext.

**Comment by fogelito** [comment] 2023-09-05 07:03
@joeyouss 
This behavior is expected.
On fulltext you should be able to create 
We added a validation on 1.4, but as I understand from Steven, it is not yet on the cloud only self-hosted.

**Comment by noob8boi** [comment] 2023-09-10 07:00
Facing similar issue on 1.4.2 Self Hosted Instance.

Size of the string attribute is 128 and same issue for Strings[] array attribute 
[Fulltext Index]

**Comment by fogelito** [comment] 2023-09-10 08:00
@noob8boi Do you get a PDO error?

**Comment by noob8boi** [comment] 2023-09-10 08:38
@fogelito I see this error in `docker logs appwrite` .. or I should be checking smth else?
![image](https://github.com/appwrite/appwrite/assets/91360152/74cd34e6-acc1-4f20-97fc-a139d5d58dac)

**Comment by fogelito** [comment] 2023-09-10 09:00
@noob8boi , Thanks, that's good. 
The attribute you created is an array of String ? what is the length you provided on creatation?
You are trying to create a fulltext text Index for that single attribute?

**Comment by noob8boi** [comment] 2023-09-10 09:10
@fogelito yes an array of string.. tried with both 64 and 128 length. Then I created a fulltext index for that single attribute but failed and same happened for a normal string attribute - 128 length - fulltext index.

**Comment by fogelito** [comment] 2023-09-10 10:09
@noob8boi We do not check length for fulltext indexes, so it feels like between delete and reCreate something is not updated properly, I will try to reproduce..

**Comment by noob8boi** [comment] 2023-09-10 10:29
@fogelito I think it's happening because of the unique url index. As soon I deleted the unique URL index from that collection I was able to create full text index as expected 🤔

**Comment by fogelito** [comment] 2023-09-10 10:36
@noob8boi Let's try to reproduce this case. Can you give me information about that unique index?
what was the length of this string attribute? required? array?

**Comment by noob8boi** [comment] 2023-09-10 10:41
@fogelito we cant actually reproduce because in appwrite 1.4.2 instance I am unable to create a unique index on URL attribute. We will need a pre existing collection with a unique index on URL attribute and then migrate that instance from lets say 1.3.8 to 1.4.2.. After that u wont be able to create any new index whether its key/fulltext in the same collection.

Just my guess tho

**Comment by fogelito** [comment] 2023-09-10 11:01
OOh now I got it, URL field is default set to 2000 length, that's is why you can't create a unique index, there is a limit validation for this.
What you should do is create a regular URL as you did with no index + 
Create a string attribute named "url_md5" length ~32 size and make it a unique index.
When creating a document md5 the URL and You will have a unique index field for URL :)

**Comment by noob8boi** [comment] 2023-09-10 11:08
@fogelito but this is not the best solution right.. What if the url is 128 characters long? Even if we only take the 32 characters in starting then also we can't make sure it will be unique because some urls can be similar in starting even if there is a very less chance 🤔  

Ig we will have to go for a pretty big character limit-

**Comment by abnegate** [comment] 2023-09-16 07:09
Closing as expected behaviour

**Closed by abnegate** 2023-09-16 07:09 UTC
Labels: bug, databases
