### ISSUE TITLE
🐛 Bug Report: Error 500 when searching for user using email

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#2394] opened 2021-11-05 08:56 UTC
### 👟 Reproduction steps

_Make sure you have network tab opened_

1. Visit your appwrite console
2. Open a project
3. Go into "users"
4. Search for user `matej@appwrite.io`
5. Take a look at network tab. Search responses with code 200, but body is "error 500"

![CleanShot 2021-11-05 at 09 55 34@2x](https://user-images.githubusercontent.com/19310830/140484341-94e629e3-228c-4261-9785-6327f9d30de6.png)

<img width="489" alt="CleanShot 2021-11-05 at 09 55 36@2x" src="https://user-images.githubusercontent.com/19310830/140484358-c9ed12ee-8754-4a1d-9f92-ef6d701fdfdf.png">

### 👍 Expected behavior

Symbol `@` should be escaped in the process.

### 👎 Actual Behavior

Symbol `@` in search query throws error 500.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

AW version: 0.11

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment] 2021-11-05 08:58
What is the output log in your main Appwrite container?

**Comment by Meldiron** [comment] 2021-11-05 10:07
```
...

appwrite                        | [Error] Message: Not Found
appwrite                        | [Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
appwrite                        | [Error] Line: 708
appwrite                        | [Error] Timestamp: 2021-11-05T08:20:20+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: Not Found
appwrite                        | [Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
appwrite                        | [Error] Line: 708
appwrite                        | [Error] Type: PDOException
appwrite                        | [Error] Message: syntax error, unexpected '@', expecting $end
appwrite                        | [Error] File: @swoole-src/library/core/Database/PDOStatementProxy.php
appwrite                        | [Error] Line: 70
appwrite                        | [Error] Type: PDOException
appwrite                        | [Error] Message: syntax error, unexpected '@', expecting $end
appwrite                        | [Error] File: @swoole-src/library/core/Database/PDOStatementProxy.php
appwrite                        | [Error] Line: 70
appwrite                        | [Error] Type: PDOException
appwrite                        | [Error] Message: syntax error, unexpected '@', expecting $end
appwrite                        | [Error] File: @swoole-src/library/core/Database/PDOStatementProxy.php
appwrite                        | [Error] Line: 70
appwrite                        | [Error] Type: PDOException
appwrite                        | [Error] Message: syntax error, unexpected '@', expecting $end
appwrite                        | [Error] File: @swoole-src/library/core/Database/PDOStatementProxy.php
appwrite                        | [Error] Line: 70
appwrite                        | [Error] Timestamp: 2021-11-05T08:54:35+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: Not Found
appwrite                        | [Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
appwrite                        | [Error] Line: 708
appwrite                        | [Error] Timestamp: 2021-11-05T08:54:35+00:00
appwrite                        | [Error] Type: Utopia\Exception

...
```

**Comment by kodumbeats** [comment] 2021-11-05 13:57
Checked this in the database refactor branch, and it doesn't appear to be an issue. (I checked the raw request URL, and the `@` symbol is properly escaped as `%40`)
![09_44_42-05_11](https://user-images.githubusercontent.com/9708641/140521276-181e2e96-8e56-4cc9-9b52-60c10cdc4cb1.png)

**Comment by stnguyen90** [comment] 2021-11-06 15:54
Fyi, the current workaround for version 0.11.X is to wrap the search term that includes the @ with double quotes. So search for `"matej@appwrite.io"` instead.

**Comment by eldadfux** [comment] 2022-01-05 11:40
This fix is now available as part of Appwrite 0.12 which is now officially released. You can learn more at: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b

**Comment by stnguyen90** [comment] 2022-01-10 00:50
This no longer throws a 500 error, but it doesn't seem like user search is working as no results get returned.

**Comment by eldadfux** [comment] 2022-01-18 05:25
@stnguyen90 just had a chance to double check and using the console to search users seems to work for me on 0.12.0, can you please share more info on how I might be able to reproduce the issue?

**Comment by stnguyen90** [comment] 2022-01-18 05:40
I'm on 0.12.1 and searching by name or email (exact or partial) don't return any results.

**Comment by stnguyen90** [comment] 2022-01-18 05:45
Hmm... Seems like it's only broken for pre 0.12 projects..

**Comment by kekavc24** [comment] 2022-01-18 08:19
> Hmm... Seems like it's only broken for pre 0.12 projects..

Yeap. It seems so. I had my project since 0.10.

**Comment by kekavc24** [comment] 2022-01-18 08:21
And the funny thing is the user I am searching is first on the list of users 😅

**Comment by eldadfux** [comment] 2022-01-18 08:55
@kodumbeats can you reproduce this issue? I use both 0.12.0 and 0.12.1 and I seem to get result for both exact and partial matches.

**Comment by kodumbeats** [comment] 2022-01-19 13:01
I've investigated this issue and found the root cause: the migration to `0.12.x` does not populate the `search` field in the database, so searching will never return a result. Will open a separate issue to have a focused discussion on solutions. :)

**Comment by kodumbeats** [comment] 2022-01-21 21:14
https://github.com/appwrite/appwrite/pull/2637

**Comment by TorstenDittmann** [comment] 2022-03-09 14:10
This got resolved with the new Database service 👏🏻

**Comment by stnguyen90** [comment] 2022-03-09 19:12
@TorstenDittmann, this seems to be back. GET `/v1/users?search=1029-0dji012jr9if03fjie%40yahoo.com` resulted in:

```json
{
  "message":"Error: Server Error",
  "code":500,"version":"0.13.2"
}
```

appwrite logs:

```
appwrite  | [Error] Type: PDOException
appwrite  | [Error] Message: syntax error, unexpected '@', expecting $end
appwrite  | [Error] File: @swoole-src/library/core/Database/PDOStatementProxy.php
appwrite  | [Error] Line: 64
```

I have to wrap the search term with 2 double quotes (`/v1/users?search=%22%221029-0dji012jr9if03fjie%40yahoo.com`) to get it to work.

Related issue https://github.com/appwrite/appwrite/issues/2834.

**Comment by badmark** [comment] 2022-03-15 00:58
I am also experiencing this issue with previously working code when searching for a user by email prior to registration.

`
[Error] Type: PDOException
[Error] Message: syntax error, unexpected '@', expecting $end
[Error] File: @swoole-src/library/core/Database/PDOStatementProxy.php
[Error] Line: 64
`

**Comment by TorstenDittmann** [comment] 2022-03-15 10:32
Found the culprit again:

> InnoDB full-text search does not support the use of the @ symbol in boolean full-text searches. The @ symbol is reserved for use by the @distance proximity search operator.

https://dev.mysql.com/doc/refman/5.6/en/fulltext-boolean.html

This should be fixed by replacing it with a space 🤔

**Comment by TorstenDittmann** [comment] 2022-03-15 11:29
Anyway, looks like there is an edge case:
Lets say I have 2 users with following emails:
- `torsten@appwrite.io`
- `eldad@appwrite.io`

The Fulltext index creates following structure internally:
- `torsten appwrite io`
- `eldad appwrite io`

So if I replace the `@` sign with ``during the search, searching for `torsten@appwrite.io` will actually give me both results.

Except when I put it in `"` quotes, then it will recognize them as coherent conditions.

**Comment by badmark** [comment] 2022-03-15 12:49
Wait, so that I am clear. When searching for a user by email we have to exclude the ampersand now?

**Comment by TorstenDittmann** [comment] 2022-03-15 13:44
> So much for launching this week... We were ready to launch then the DB changes happened, We've adjusted, now we can't search for an email with an '@'?
> 
> How long before the next release? I have much code to touch if this is the case.

As it looks like now, we are going to release `0.13.3` today 🤞🏻

**Closed** 2022-03-15 19:03 UTC
Labels: bug, database
