### ISSUE TITLE
🚀 Feature: Make membership secret available

### ISSUE THREAD

**Issue by Bendix20** [appwrite/appwrite#4441] opened 2022-10-13 06:34 UTC
### 🔖 Feature description

The secret of the membership should be available. Either after creating a new membership with the `Teams` class or as part of the `Membership` model (but only accessible from the own user or the Team owners).

### 🎤 Pitch

For now it's not possible to send the team invitation again. If the secret is available, it would be possible to send and resend a custom invitation email to the users. 
Also it would be possible to join the team in other ways. There could be a function inside the application to display open invitations with a possibility to directly join these teams.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2022-11-16 16:47
@Bendix20 , @Meldiron is this a duplicate of https://github.com/appwrite/appwrite/issues/3115?

**Comment by rafagazani** [comment] 2023-04-04 04:11
@stnguyen90 can we close this issue?

**Closed** 2023-05-11 08:30 UTC
Labels: authentication, feature
